import type { LearningState } from "@/types/learning";
import { buildWeeklyPlan } from "@/core/coach/weekly-plan";
import { eligibleReviewCards } from "@/core/srs/review-queue";

export const STUDY_EXPORT_POLICY = "local-study-exports-v1" as const;
export const ANKI_EXPORT_COLUMNS = ["Front","Back","Hint","Tags","CardId"] as const;
export type WeeklyReportSections={plan:boolean;evidence:boolean;profileName:boolean};

function dateStamp(date:Date){return date.toISOString().slice(0,10)}
function compactUtc(date:Date){return date.toISOString().replace(/[-:]/g,"").replace(/\.\d{3}Z$/,"Z")}
function compactLocal(date:string,hour:number,minute:number){return `${date.replaceAll("-","")}T${String(hour).padStart(2,"0")}${String(minute).padStart(2,"0")}00`}
function addLocalMinutes(hour:number,minute:number,amount:number){const total=hour*60+minute+amount;return{hour:Math.floor(total/60)%24,minute:total%60}}
function icsEscape(value:string){return value.replaceAll("\\","\\\\").replaceAll("\n","\\n").replaceAll(",","\\,").replaceAll(";","\\;")}
function validTimeZone(timeZone:string){try{new Intl.DateTimeFormat("en-US",{timeZone}).format(new Date());return timeZone}catch{return"UTC"}}

export function buildStudyExportSnapshot(state:LearningState,now=new Date()){
 const plan=buildWeeklyPlan(state,now);const history=state.studyHistory.filter(item=>item.date>=plan.weekStart&&item.date<=plan.weekEnd);const cards=eligibleReviewCards(state).sort((a,b)=>a.id.localeCompare(b.id));
 return{policyVersion:STUDY_EXPORT_POLICY,generatedAt:now.toISOString(),ready:Boolean(state.profile),profileName:state.profile?.name??"",level:state.profile?.currentLevel??"A1",targetExam:state.profile?.targetExam??"goethe-b2",plan,actualMinutes:history.reduce((sum,item)=>sum+item.minutes,0),evidenceCount:history.reduce((sum,item)=>sum+item.evidenceCount,0),completedLessons:state.completedLessonIds.length,activeErrors:state.errors.filter(error=>!error.resolved).length,confirmedErrorCards:cards.filter(card=>card.tags.includes("personal-error")).length,cardCount:cards.length,cards};
}

export function buildWeeklyPlanIcs(state:LearningState,now=new Date(),requestedTimeZone="UTC"){
 const snapshot=buildStudyExportSnapshot(state,now);if(!snapshot.ready)throw new Error("أكمل التهيئة قبل تصدير خطة التقويم.");const timeZone=validTimeZone(requestedTimeZone);const lines=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Der Weg nach Berlin//Local Study Plan//AR","CALSCALE:GREGORIAN","METHOD:PUBLISH",`X-WR-CALNAME:${icsEscape("الطريق إلى برلين — خطة الدراسة")}`,`X-DWNB-POLICY:${STUDY_EXPORT_POLICY}`,`X-WR-TIMEZONE:${timeZone}`];
 for(const day of snapshot.plan.days){let cursor={hour:18,minute:0};for(const slot of day.slots){const end=addLocalMinutes(cursor.hour,cursor.minute,slot.minutes);lines.push("BEGIN:VEVENT",`UID:dwnb-${day.date}-${slot.id}@local`,`DTSTAMP:${compactUtc(now)}`,`DTSTART;TZID=${timeZone}:${compactLocal(day.date,cursor.hour,cursor.minute)}`,`DTEND;TZID=${timeZone}:${compactLocal(day.date,end.hour,end.minute)}`,`SUMMARY:${icsEscape(slot.titleAr)}`,`DESCRIPTION:${icsEscape(`${slot.minutes} دقيقة · ${day.weekdayAr} · خطة محلية غير متزامنة`)}`,`CATEGORIES:DWNB,${slot.kind}`,"END:VEVENT");cursor=end}}
 lines.push("END:VCALENDAR");return{content:`${lines.join("\r\n")}\r\n`,mime:"text/calendar;charset=utf-8",filename:`dwnb-plan-${snapshot.plan.weekStart}.ics`,eventCount:snapshot.plan.days.reduce((sum,day)=>sum+day.slots.length,0),timeZone};
}

function safeSpreadsheetCell(value:string){const compact=value.replace(/\r?\n/g,"<br>").replaceAll("\t"," ").trim();return/^[=+\-@]/.test(compact)?`'${compact}`:compact}
export function buildAnkiTsv(state:LearningState,now=new Date()){
 const snapshot=buildStudyExportSnapshot(state,now);if(!snapshot.cards.length)throw new Error("لا توجد بطاقات درس مؤهلة أو أخطاء مؤكدة لتصديرها.");const rows=[ANKI_EXPORT_COLUMNS.join("\t"),...snapshot.cards.map(card=>[card.front,card.back,card.hint,card.tags.join(" "),card.id].map(safeSpreadsheetCell).join("\t"))];return{content:`\uFEFF${rows.join("\r\n")}\r\n`,mime:"text/tab-separated-values;charset=utf-8",filename:`dwnb-anki-${dateStamp(now)}.tsv`,rowCount:snapshot.cards.length,columns:ANKI_EXPORT_COLUMNS};
}

export function weeklyReportModel(state:LearningState,sections:WeeklyReportSections,now=new Date()){
 const snapshot=buildStudyExportSnapshot(state,now);if(!snapshot.ready)throw new Error("أكمل التهيئة قبل إنشاء التقرير الأسبوعي.");if(!sections.plan&&!sections.evidence)throw new Error("اختر قسم الخطة أو الأدلة على الأقل.");return{...snapshot,sections,displayName:sections.profileName?snapshot.profileName:"غير مضمّن",privacyBoundary:"لا تسجيلات، لا مفاتيح API، لا نصوص كتابة/محادثة حرة. DWNB وحده نسخة استعادة كاملة."};
}

function bytes(value:string){return new TextEncoder().encode(value)}
function concat(parts:Uint8Array<ArrayBufferLike>[]){const length=parts.reduce((sum,part)=>sum+part.length,0);const result=new Uint8Array(length);let offset=0;for(const part of parts){result.set(part,offset);offset+=part.length}return result}
export function buildJpegPdf(jpeg:Uint8Array<ArrayBuffer>,width:number,height:number){if(!jpeg.length||width<1||height<1)throw new Error("صورة التقرير غير صالحة لإنشاء PDF.");const content=`q\n595 0 0 842 0 0 cm\n/Im0 Do\nQ\n`;const objects:[number,Uint8Array[]][]=[[1,[bytes("<< /Type /Catalog /Pages 2 0 R >>")]],[2,[bytes("<< /Type /Pages /Kids [3 0 R] /Count 1 >>")]],[3,[bytes("<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>")]],[4,[bytes(`<< /Type /XObject /Subtype /Image /Width ${width} /Height ${height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpeg.length} >>\nstream\n`),jpeg,bytes("\nendstream")]],[5,[bytes(`<< /Length ${bytes(content).length} >>\nstream\n${content}endstream`)]]];const parts:Uint8Array<ArrayBufferLike>[]=[bytes("%PDF-1.4\n%local\n")];const offsets=[0];for(const[number,body]of objects){offsets[number]=parts.reduce((sum,part)=>sum+part.length,0);parts.push(bytes(`${number} 0 obj\n`),...body,bytes("\nendobj\n"))}const xrefOffset=parts.reduce((sum,part)=>sum+part.length,0);let xref="xref\n0 6\n0000000000 65535 f \n";for(let i=1;i<=5;i+=1)xref+=`${String(offsets[i]).padStart(10,"0")} 00000 n \n`;xref+=`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;parts.push(bytes(xref));return concat(parts)}

function drawText(ctx:CanvasRenderingContext2D,text:string,x:number,y:number,maxWidth:number,lineHeight:number){const words=text.split(/\s+/);let line="";const lines:string[]=[];for(const word of words){const candidate=line?`${line} ${word}`:word;if(ctx.measureText(candidate).width>maxWidth&&line){lines.push(line);line=word}else line=candidate}if(line)lines.push(line);for(const value of lines){ctx.fillText(value,x,y);y+=lineHeight}return y}
export async function buildWeeklyReportPdf(state:LearningState,sections:WeeklyReportSections,now=new Date()){
 const report=weeklyReportModel(state,sections,now);if(typeof document==="undefined")throw new Error("إنشاء PDF يحتاج متصفحًا محليًا.");const canvas=document.createElement("canvas");canvas.width=1240;canvas.height=1754;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Canvas غير متاح لإنشاء التقرير.");ctx.fillStyle="#fffdf8";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.direction="rtl";ctx.textAlign="right";ctx.fillStyle="#163a36";ctx.font="bold 48px Tahoma, Arial";ctx.fillText("الطريق إلى برلين — التقرير الأسبوعي",1160,80);ctx.font="24px Tahoma, Arial";ctx.fillStyle="#51645d";ctx.fillText(`${report.plan.weekStart} — ${report.plan.weekEnd} · ${report.displayName}`,1160,125);let y=190;if(sections.evidence){ctx.fillStyle="#163a36";ctx.font="bold 32px Tahoma, Arial";ctx.fillText("ملخص الأدلة",1160,y);y+=48;ctx.font="24px Tahoma, Arial";ctx.fillStyle="#354f47";for(const line of [`المخطط: ${report.plan.plannedMinutes} دقيقة · الفعلي: ${report.actualMinutes} دقيقة`,`أدلة الأسبوع: ${report.evidenceCount} · الدروس المكتملة: ${report.completedLessons}/84`,`بطاقات مؤهلة: ${report.cardCount} · منها علاج أخطاء: ${report.confirmedErrorCards} · أخطاء نشطة: ${report.activeErrors}`]){ctx.fillText(line,1160,y);y+=38}y+=20}if(sections.plan){ctx.font="bold 32px Tahoma, Arial";ctx.fillStyle="#163a36";ctx.fillText("خطة الاثنين إلى الأحد",1160,y);y+=48;for(const day of report.plan.days){ctx.fillStyle="#eef5f1";ctx.fillRect(70,y-28,1100,Math.max(74,day.slots.length*30+36));ctx.fillStyle="#163a36";ctx.font="bold 24px Tahoma, Arial";ctx.fillText(`${day.weekdayAr} · ${day.date} · ${day.budgetMinutes} دقيقة`,1140,y);y+=34;ctx.font="20px Tahoma, Arial";ctx.fillStyle="#425b53";if(!day.slots.length){ctx.fillText("راحة مخططة",1110,y);y+=30}else for(const slot of day.slots){ctx.fillText(`• ${slot.titleAr} — ${slot.minutes} دقيقة`,1110,y);y+=30}y+=24}}ctx.font="18px Tahoma, Arial";ctx.fillStyle="#5c6c66";drawText(ctx,report.privacyBoundary,1160,1660,1080,28);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/jpeg",0.88));if(!blob)throw new Error("تعذر رسم التقرير المحلي.");const pdf=buildJpegPdf(new Uint8Array(await blob.arrayBuffer()),canvas.width,canvas.height);return{bytes:pdf,mime:"application/pdf",filename:`dwnb-week-${report.plan.weekStart}.pdf`,pageCount:1,model:report};
}
