import type{LearningState,SessionAdaptationReason}from"@/types/learning";import{planningPresetMinutes}from"./intensity-presets";
export const PLAN_CHANGE_TIMELINE_POLICY="explainable-plan-change-timeline-v1"as const;export const PLAN_CHANGE_TIMELINE_BOUNDARY="derived-planning-history-no-answer-reflection-text-mastery-or-penalty"as const;
export type PlanChangeKind="check-in-adjustment"|"session-adaptation"|"mission-alternative"|"load-offer-decision"|"next-focus"|"learning-contract-revision"|"intensity-preset";
export type PlanChangeEntry={id:string;policyVersion:typeof PLAN_CHANGE_TIMELINE_POLICY;kind:PlanChangeKind;date:string;createdAt:string;titleAr:string;reasonAr:string;beforeMinutes?:number;afterMinutes?:number;evidenceBoundary:typeof PLAN_CHANGE_TIMELINE_BOUNDARY};
const adaptationReason:Record<SessionAdaptationReason,string>={"less-time":"سجلت أن وقتك المتاح أصبح أقل، فأعيد تركيب بقية الجلسة ضمن مدة صحيحة.","too-easy":"سجلت أن الحمل سهل، فنُقل وقت محدود من التدريب الموجّه إلى إنتاج أبعد عن المثال.","too-hard":"سجلت أن الحمل صعب، فخُفّضت بقية الجلسة مع إبقاء ما أُنجز.","load-suggestion":"قبلت اقتراح تخفيف ظهر بعد أخطاء متتالية أو تجاوز وقت النشاط."};
function nextFocusReason(value:string){return value==="review"?"اخترت أن تبدأ الجلسة التالية بالمراجعة.":value==="lighter"?"اخترت حملًا أخف للجلسة التالية.":value==="production"?"اخترت إعطاء الإنتاج أولوية في الجلسة التالية.":"اخترت مواصلة المسار الحالي."}
export function buildPlanChangeTimeline(state:LearningState){const entries:PlanChangeEntry[]=[];const profileMinutes=state.profile?.dailyMinutes??45;
 for(const session of Object.values(state.dailySessions)){
  if(session.availableMinutes!==profileMinutes||session.energyBefore<=2)entries.push({id:`plan-change:check-in:${session.date}`,policyVersion:PLAN_CHANGE_TIMELINE_POLICY,kind:"check-in-adjustment",date:session.date,createdAt:session.checkedInAt,titleAr:"تعديل بعد تهيئة اليوم",reasonAr:session.energyBefore<=2?`طاقتك المسجلة ${session.energyBefore}/5؛ حُدّ الحمل اليومي لحماية التركيز.`:`الوقت المتاح ${session.availableMinutes} دقيقة بدل الإعداد المعتاد ${profileMinutes} دقيقة.`,beforeMinutes:profileMinutes,afterMinutes:session.energyBefore<=2?Math.min(20,session.availableMinutes):session.availableMinutes,evidenceBoundary:PLAN_CHANGE_TIMELINE_BOUNDARY});
  for(const adaptation of session.adaptations??[])entries.push({id:`plan-change:adaptation:${adaptation.id}`,policyVersion:PLAN_CHANGE_TIMELINE_POLICY,kind:"session-adaptation",date:session.date,createdAt:adaptation.createdAt,titleAr:"تغيير بقية الجلسة",reasonAr:adaptationReason[adaptation.reason],beforeMinutes:adaptation.beforeMinutes,afterMinutes:adaptation.afterMinutes,evidenceBoundary:PLAN_CHANGE_TIMELINE_BOUNDARY});
  for(const alternative of session.missionAlternatives??[])entries.push({id:`plan-change:alternative:${alternative.id}`,policyVersion:PLAN_CHANGE_TIMELINE_POLICY,kind:"mission-alternative",date:session.date,createdAt:alternative.createdAt,titleAr:"اختيار مهمة بديلة",reasonAr:`رفضت المهمة الأصلية الآن؛ اختير بديل يحافظ على الهدف ونوع الدليل و${alternative.minutes} دقيقة، ولم يكتمل الأصل.`,beforeMinutes:alternative.minutes,afterMinutes:alternative.minutes,evidenceBoundary:PLAN_CHANGE_TIMELINE_BOUNDARY});
  if(session.loadReductionOffer?.status&&session.loadReductionOffer.status!=="pending")entries.push({id:`plan-change:load:${session.loadReductionOffer.id}`,policyVersion:PLAN_CHANGE_TIMELINE_POLICY,kind:"load-offer-decision",date:session.date,createdAt:session.loadReductionOffer.decidedAt??session.loadReductionOffer.offeredAt,titleAr:session.loadReductionOffer.status==="accepted"?"قُبل اقتراح التخفيف":"أُبقي الحمل الحالي",reasonAr:session.loadReductionOffer.status==="accepted"?"اخترت التخفيف بنفسك؛ لم تُحذف أدلة ولم يعاقب الخطأ.":"اخترت إبقاء الخطة؛ لن يتكرر الاقتراح في الجلسة نفسها.",beforeMinutes:Math.round(session.loadReductionOffer.plannedSeconds/60),afterMinutes:session.availableMinutes,evidenceBoundary:PLAN_CHANGE_TIMELINE_BOUNDARY});
  if(session.reflectedAt&&session.nextFocus)entries.push({id:`plan-change:focus:${session.date}:${session.nextFocus}`,policyVersion:PLAN_CHANGE_TIMELINE_POLICY,kind:"next-focus",date:session.date,createdAt:session.reflectedAt,titleAr:"قرار الجلسة التالية",reasonAr:nextFocusReason(session.nextFocus),evidenceBoundary:PLAN_CHANGE_TIMELINE_BOUNDARY});
 }
 for(const contract of state.learningContracts.filter((item)=>item.revision>1))entries.push({id:`plan-change:contract:${contract.id}`,policyVersion:PLAN_CHANGE_TIMELINE_POLICY,kind:"learning-contract-revision",date:contract.startsOn,createdAt:contract.createdAt,titleAr:`مراجعة عقد التعلم ${contract.revision}`,reasonAr:`تغير الالتزام إلى ${contract.dailyMinutes} دقيقة في ${contract.studyWeekdays.length} أيام أسبوعية؛ بقيت الأدلة السابقة كما هي.`,afterMinutes:contract.dailyMinutes,evidenceBoundary:PLAN_CHANGE_TIMELINE_BOUNDARY});
 if(state.planningIntensity.selectedAt){const plan=planningPresetMinutes(state);const label=plan.preset==="light"?"الخفيفة":plan.preset==="intensive"?"المكثفة":"المتوازنة";entries.push({id:`plan-change:intensity:${state.planningIntensity.selectedAt}`,policyVersion:PLAN_CHANGE_TIMELINE_POLICY,kind:"intensity-preset",date:state.planningIntensity.selectedAt.slice(0,10),createdAt:state.planningIntensity.selectedAt,titleAr:"اختيار شدة الخطة",reasonAr:`اخترت الخطة ${label}: ${plan.minutes} دقيقة افتراضيًا من أساس ${plan.base} دقيقة. لم تتغير الأدلة أو الإتقان.`,beforeMinutes:plan.base,afterMinutes:plan.minutes,evidenceBoundary:PLAN_CHANGE_TIMELINE_BOUNDARY})}
 return{policyVersion:PLAN_CHANGE_TIMELINE_POLICY,entries:entries.sort((left,right)=>Date.parse(right.createdAt)-Date.parse(left.createdAt)||right.id.localeCompare(left.id)),evidenceBoundary:PLAN_CHANGE_TIMELINE_BOUNDARY};}
