export type CoachDecisionImpact="mission-selection"|"session-load"|"next-focus"|"target-date-plan"|"offline-readiness"|"learner-data-control"|"none";
export type FeatureProposal={id:string;title:string;decisionImpact:CoachDecisionImpact;decisionBefore:string;decisionAfter:string;automatedEvidence:string[];addedPersistentFields:number;addedNetworkOrigins:number;maintenanceOwner:string};
export const featureProposalRegistry:FeatureProposal[]=[
{id:"learning-integrity-v2",title:"Independent knowledge, productive provenance and phased study",decisionImpact:"mission-selection",decisionBefore:"Legacy caches and four receptive conditions could advance a learner",decisionAfter:"Fresh parallel checks, seven activity conditions and separate quality/retention guide the next task",automatedEvidence:["tests/unit/learning-integrity-repairs.test.ts"],addedPersistentFields:0,addedNetworkOrigins:0,maintenanceOwner:"learning-architecture-owner"},
{id:"weekly-reflection",title:"Independent weekly reflection",decisionImpact:"next-focus",decisionBefore:"Daily reflection only",decisionAfter:"One learner-selected weekly adjustment is reviewable",automatedEvidence:["tests/unit/weekly-reflection-target-planning.test.ts"],addedPersistentFields:1,addedNetworkOrigins:0,maintenanceOwner:"learning-architecture-owner"},
{id:"target-workload",title:"Target-date workload and risk",decisionImpact:"target-date-plan",decisionBefore:"Date stored without load",decisionAfter:"Keep, increase, or move date using a bounded estimate",automatedEvidence:["tests/unit/weekly-reflection-target-planning.test.ts"],addedPersistentFields:0,addedNetworkOrigins:0,maintenanceOwner:"learning-architecture-owner"},
{id:"raw-export",title:"Raw local store export",decisionImpact:"learner-data-control",decisionBefore:"DWNB and partial exports only",decisionAfter:"Learner can inspect all five local stores",automatedEvidence:["tests/unit/raw-store-export-privacy.test.ts"],addedPersistentFields:0,addedNetworkOrigins:0,maintenanceOwner:"portability-owner"},
{id:"p2-355-local-test-generator",title:"Local practice tests from published mini-test templates",decisionImpact:"next-focus",decisionBefore:"The learner must reopen a lesson to take its fixed mini-test",decisionAfter:"The learner can choose a level and build a new 5/10/15-item sample from distinct published lessons",automatedEvidence:["tests/unit/local-test-generator.test.ts","tests/e2e/critical-flows.spec.ts"],addedPersistentFields:0,addedNetworkOrigins:0,maintenanceOwner:"learning-architecture-owner"},
{id:"p2-276-illustrative-pathways",title:"Hypothetical practical guidance without success claims",decisionImpact:"next-focus",decisionBefore:"No authored path examples connect common learner situations to existing tools",decisionAfter:"The learner can follow optional, clearly hypothetical steps linked to existing offline-capable routes",automatedEvidence:["tests/unit/illustrative-pathways.test.ts","tests/e2e/critical-flows.spec.ts"],addedPersistentFields:0,addedNetworkOrigins:0,maintenanceOwner:"learning-architecture-owner"},
];
export function evaluateFeatureProposal(proposal:FeatureProposal){const reasons:string[]=[];if(proposal.decisionImpact==="none")reasons.push("No coach or learner-control decision changes.");if(!proposal.decisionBefore.trim()||!proposal.decisionAfter.trim()||proposal.decisionBefore===proposal.decisionAfter)reasons.push("Decision before/after is missing or unchanged.");if(!proposal.automatedEvidence.length)reasons.push("No automated acceptance evidence.");if(proposal.addedNetworkOrigins>0)reasons.push("New network origin requires separate CSP, privacy, zero-cost, and consent review.");if(!proposal.maintenanceOwner.trim())reasons.push("No maintenance owner.");return{policyVersion:"coach-decision-feature-proposal-gate-v1"as const,accepted:reasons.length===0,reasons,complexity:{addedPersistentFields:proposal.addedPersistentFields,addedNetworkOrigins:proposal.addedNetworkOrigins},boundary:"gate-rejects-complexity-without-decision-impact-not-a-user-outcome-or-quality-score"as const}}
