import { academicLessonList } from "@/data/academic-lessons";
import { z } from "zod";
import { academicLessons } from "@/data/academic-lessons";
import { grammarProgressionNodes, GRAMMAR_PROGRESSION_VERSION } from "@/data/grammar-progression-registry";
import { questionTaxonomyRecords, QUESTION_TAXONOMY_VERSION, type ComprehensionQuestionCategory } from "@/core/comprehension/question-taxonomy";
import type { CEFRLevel } from "@/types/learning";

const levelSchema=z.enum(["A1","A2","B1","B2"]);
export const grammarProgressionNodeSchema=z.object({id:z.string().regex(/^[a-z0-9-]+$/),policyVersion:z.literal(GRAMMAR_PROGRESSION_VERSION),level:levelSchema,order:z.number().int().nonnegative(),titleDe:z.string().min(3).max(120),titleAr:z.string().min(3).max(160),lessonId:z.string(),theoryId:z.string(),prerequisiteIds:z.array(z.string()).max(3),controlledExerciseIds:z.array(z.string()).min(2).max(4),production:z.object({stage:z.enum(["writing","speaking","mediation"]),ref:z.string(),promptDe:z.string().min(4).max(1200),promptAr:z.string().min(4).max(1200)}).strict(),progression:z.object({introducedAr:z.string().min(20).max(500),commonLimitAr:z.string().min(20).max(500),deferredAr:z.string().min(20).max(500)}).strict(),boundariesAr:z.array(z.string().min(15).max(500)).min(2).max(4),exceptionsAr:z.array(z.string().min(15).max(500)).min(1).max(3),semanticAlignmentAr:z.string().min(25).max(500),evidenceBoundary:z.literal("curriculum-navigation-and-alignment-no-automatic-mastery-or-cefr")}).strict();
export const questionTaxonomyRecordSchema=z.object({id:z.string(),policyVersion:z.literal(QUESTION_TAXONOMY_VERSION),lessonId:z.string(),level:levelSchema,surface:z.enum(["reading","listening"]),questionId:z.string(),category:z.enum(["gist","detail","stance","inference","structure"]),labelDe:z.string(),labelAr:z.string(),classificationBasis:z.enum(["listening-sequence-gist-contract","item-text-semantic-signal","specific-detail-default"]),matchedSignal:z.string(),evidenceBoundary:z.literal("question-function-label-no-score-mastery-or-cefr")}).strict();
const levels:CEFRLevel[]=["A1","A2","B1","B2"];const categories:ComprehensionQuestionCategory[]=["gist","detail","stance","inference","structure"];

function cycleIssues(){const issues:string[]=[];const byId=Object.fromEntries(grammarProgressionNodes.map((item)=>[item.id,item]));const visiting=new Set<string>();const visited=new Set<string>();function visit(id:string,path:string[]){if(visiting.has(id)){issues.push(`grammar graph cycle: ${[...path,id].join(" -> ")}`);return}if(visited.has(id))return;visiting.add(id);for(const parent of byId[id]?.prerequisiteIds??[])visit(parent,[...path,id]);visiting.delete(id);visited.add(id)}for(const node of grammarProgressionNodes)visit(node.id,[]);return issues;}

export function buildLearningArchitectureAudit(){
  const issues:string[]=[];const grammarIds=new Set(grammarProgressionNodes.map((item)=>item.id));
  if(grammarIds.size!==grammarProgressionNodes.length)issues.push("grammar map: duplicate node ids");
  grammarProgressionNodes.forEach((node,index)=>{const parsed=grammarProgressionNodeSchema.safeParse(node);if(!parsed.success)parsed.error.issues.forEach((issue)=>issues.push(`grammar[${index}].${issue.path.join(".")}: ${issue.message}`));const lesson=academicLessons[node.lessonId];if(!lesson){issues.push(`grammar.${node.id}: unknown lesson`);return}if(lesson.level!==node.level)issues.push(`grammar.${node.id}: lesson level mismatch`);if(!lesson.theory.some((item)=>item.id===node.theoryId))issues.push(`grammar.${node.id}: theory ref missing`);if(node.controlledExerciseIds.some((id)=>!lesson.exercises.some((item)=>item.id===id)))issues.push(`grammar.${node.id}: controlled ref missing`);if(node.production.ref!==`${node.lessonId}:${node.production.stage}`)issues.push(`grammar.${node.id}: production ref mismatch`);let expectedDe:string;let expectedAr:string;if(node.production.stage==="mediation"){expectedDe=lesson.mediation.sourceDe;expectedAr=lesson.mediation.taskAr}else if(node.production.stage==="writing"){expectedDe=lesson.writing.promptDe;expectedAr=lesson.writing.promptAr}else{expectedDe=lesson.speaking.promptDe;expectedAr=lesson.speaking.promptAr}if(node.production.promptDe!==expectedDe||node.production.promptAr!==expectedAr)issues.push(`grammar.${node.id}: productive prompt is not the lesson-owned task`);for(const prerequisite of node.prerequisiteIds){if(!grammarIds.has(prerequisite))issues.push(`grammar.${node.id}: unknown prerequisite ${prerequisite}`);else{const parent=grammarProgressionNodes.find((item)=>item.id===prerequisite)!;if(parent.order>=node.order)issues.push(`grammar.${node.id}: prerequisite must precede node`);}}});
  issues.push(...cycleIssues());
  for(const level of levels)if(grammarProgressionNodes.filter((item)=>item.level===level).length!==6)issues.push(`${level}: expected six canonical grammar nodes`);

  const originalQuestions=Object.values(academicLessons).flatMap((lesson)=>[...lesson.reading.questions.map((question)=>({lesson,surface:"reading" as const,question})),...lesson.listening.questions.map((question)=>({lesson,surface:"listening" as const,question}))]);const originalIds=new Set(originalQuestions.map((item)=>item.question.id));
  if(questionTaxonomyRecords.length!==originalQuestions.length||originalIds.size!==originalQuestions.length)issues.push("question taxonomy: original question ids are not unique/complete");if(new Set(questionTaxonomyRecords.map((item)=>item.questionId)).size!==questionTaxonomyRecords.length)issues.push("question taxonomy: duplicate question ids");
  questionTaxonomyRecords.forEach((record,index)=>{const parsed=questionTaxonomyRecordSchema.safeParse(record);if(!parsed.success)parsed.error.issues.forEach((issue)=>issues.push(`questionTaxonomy[${index}].${issue.path.join(".")}: ${issue.message}`));const source=originalQuestions.find((item)=>item.question.id===record.questionId);if(!source)issues.push(`questionTaxonomy.${record.questionId}: source missing`);else if(source.lesson.id!==record.lessonId||source.lesson.level!==record.level||source.surface!==record.surface)issues.push(`questionTaxonomy.${record.questionId}: source provenance mismatch`);});
  const byLevel=Object.fromEntries(levels.map((level)=>{const rows=questionTaxonomyRecords.filter((item)=>item.level===level);const counts=Object.fromEntries(categories.map((category)=>[category,rows.filter((item)=>item.category===category).length])) as Record<ComprehensionQuestionCategory,number>;if(categories.some((category)=>counts[category]<1))issues.push(`${level}: all five comprehension categories must be represented`);if(counts.detail/rows.length>.72)issues.push(`${level}: detail share exceeds 72%`);if(counts.gist/rows.length<.12||counts.gist/rows.length>.3)issues.push(`${level}: gist share outside 12–30%`);return[level,{total:rows.length,counts,detailPercent:Math.round(counts.detail/rows.length*100),gistPercent:Math.round(counts.gist/rows.length*100)}]}));
  const listeningGist=questionTaxonomyRecords.filter((item)=>item.surface==="listening"&&item.classificationBasis==="listening-sequence-gist-contract");if(listeningGist.length!==academicLessonList.length||listeningGist.some((item)=>item.category!=="gist"))issues.push("listening taxonomy: first-question gist contract must cover 84 lessons");
  return{format:"dwnb-learning-architecture-audit",version:"learning-architecture-audit-v1",generatedAt:"2026-09-08",ok:issues.length===0,policyVersions:{grammar:GRAMMAR_PROGRESSION_VERSION,questions:QUESTION_TAXONOMY_VERSION},counts:{grammarNodes:grammarProgressionNodes.length,grammarEdges:grammarProgressionNodes.reduce((sum,item)=>sum+item.prerequisiteIds.length,0),controlledMappings:grammarProgressionNodes.filter((item)=>item.controlledExerciseIds.length>=2).length,productiveMappings:grammarProgressionNodes.filter((item)=>item.production.ref).length,questionTaxonomyRows:questionTaxonomyRecords.length,readingQuestions:questionTaxonomyRecords.filter((item)=>item.surface==="reading").length,listeningQuestions:questionTaxonomyRecords.filter((item)=>item.surface==="listening").length},grammarByLevel:Object.fromEntries(levels.map((level)=>[level,grammarProgressionNodes.filter((item)=>item.level===level).length])),questionByLevel:byLevel,questionCategoryCounts:Object.fromEntries(categories.map((category)=>[category,questionTaxonomyRecords.filter((item)=>item.category===category).length])),classificationBasisCounts:Object.fromEntries(["listening-sequence-gist-contract","item-text-semantic-signal","specific-detail-default"].map((basis)=>[basis,questionTaxonomyRecords.filter((item)=>item.classificationBasis===basis).length])),boundaries:{grammar:"canonical-rule-map-and-semantic-controlled-to-production-links-no-automatic-mastery-or-cefr",questions:"deterministic-item-function-taxonomy-not-independent-human-semantic-review-or-score"},issues,grammarRows:grammarProgressionNodes,questionRows:questionTaxonomyRecords};
}
