import { z } from "zod";
import { academicLessons } from "@/data/academic-lessons";
import { arabicLearnerConfusions, registerExamples, wordFamilies, LEXICAL_STRATEGY_VERSION } from "@/data/lexical-strategy-registry";
import { buildModuleReviewQuestionPlan, expectedRecycledPercent, lessonIsBeforeModule, moduleRecyclingSummaries, MODULE_RECYCLING_BOUNDARY, MODULE_RECYCLING_VERSION } from "@/core/lexical-strategy/recycling";
import type { CEFRLevel } from "@/types/learning";

const levelSchema=z.enum(["A1","A2","B1","B2"]);
const wordMemberSchema=z.object({formDe:z.string().min(1).max(80),wordClass:z.enum(["verb","noun","adjective","compound","other"]),relation:z.enum(["base","derivation","compound","semantic-relative"]),meaningAr:z.string().min(2).max(180),exampleDe:z.string().min(4).max(240)}).strict();
export const wordFamilySchema=z.object({id:z.string().regex(/^family-[a-z0-9-]+$/),policyVersion:z.literal(LEXICAL_STRATEGY_VERSION),level:levelSchema,sourceLessonIds:z.array(z.string()).min(1).max(4),anchorDe:z.string().min(2).max(80),titleAr:z.string().min(2).max(120),relationNoteAr:z.string().min(12).max(400),cautionAr:z.string().min(12).max(400),members:z.array(wordMemberSchema).min(4).max(6)}).strict();
export const registerExampleSchema=z.object({id:z.string().regex(/^reg-[a-z0-9-]+$/),policyVersion:z.literal(LEXICAL_STRATEGY_VERSION),level:levelSchema,sourceLessonId:z.string(),register:z.enum(["formal","neutral","colloquial","professional"]),function:z.enum(["greeting","request","opinion","disagreement","problem","planning","workplace","closing"]),expressionDe:z.string().min(3).max(240),meaningAr:z.string().min(2).max(240),contextAr:z.string().min(5).max(300),avoidAr:z.string().min(5).max(300),regionalBoundaryAr:z.string().min(12).max(300).optional(),transferPromptDe:z.string().min(3).max(240),transferPromptAr:z.string().min(3).max(240)}).strict().superRefine((item,context)=>{if(item.register==="colloquial"&&!item.regionalBoundaryAr)context.addIssue({code:"custom",message:"Colloquial examples require an explicit regional/relationship boundary."});if(item.register!=="colloquial"&&item.regionalBoundaryAr)context.addIssue({code:"custom",message:"Only colloquial examples carry the regional boundary field."});});
export const arabicLearnerConfusionSchema=z.object({id:z.string().regex(/^conf-[a-z0-9-]+$/),policyVersion:z.literal(LEXICAL_STRATEGY_VERSION),level:levelSchema,sourceLessonId:z.string(),targetDe:z.string().min(2).max(100),falseAssociationAr:z.string().min(8).max(300),correctMeaningAr:z.string().min(5).max(300),contrastDe:z.string().min(8).max(400),contrastAr:z.string().min(8).max(300),source:z.enum(["arabic-transfer","english-mediation","french-mediation","near-german-form"]),riskAr:z.string().min(8).max(300),strategyAr:z.string().min(8).max(300),notUniversal:z.literal(true)}).strict();

const levels:CEFRLevel[]=["A1","A2","B1","B2"];
const arabicPattern=/[\u0600-\u06ff]/;
const germanPattern=/[A-Za-zÄÖÜäöüß]/;
const learnerVisibleFields=(value:unknown):string[]=>typeof value==="string"?[value]:Array.isArray(value)?value.flatMap(learnerVisibleFields):value&&typeof value==="object"?Object.entries(value).filter(([key])=>!key.endsWith("Id")&&!key.endsWith("Ids")&&key!=="id").flatMap(([,entry])=>learnerVisibleFields(entry)):[];

function countByLevel<T extends {level:CEFRLevel}>(items:T[]){return Object.fromEntries(levels.map((level)=>[level,items.filter((item)=>item.level===level).length])) as Record<CEFRLevel,number>;}
function checkIds(label:string,items:Array<{id:string}>,issues:string[]){const ids=items.map((item)=>item.id);if(new Set(ids).size!==ids.length)issues.push(`${label}: duplicate ids`);}
function checkLesson(level:CEFRLevel,lessonId:string,path:string,issues:string[]){const lesson=academicLessons[lessonId];if(!lesson)issues.push(`${path}: unknown source lesson`);else if(lesson.level!==level)issues.push(`${path}: source lesson level mismatch`);}

export function buildLexicalStrategyAudit(){
  const issues:string[]=[];
  wordFamilies.forEach((item,index)=>{const result=wordFamilySchema.safeParse(item);if(!result.success)result.error.issues.forEach((issue)=>issues.push(`wordFamilies[${index}].${issue.path.join(".")}: ${issue.message}`));item.sourceLessonIds.forEach((lessonId)=>checkLesson(item.level,lessonId,`wordFamilies.${item.id}`,issues));if(item.members.filter((member)=>member.relation==="base").length!==1)issues.push(`wordFamilies.${item.id}: expected exactly one base member`);if(new Set(item.members.map((member)=>member.formDe.toLocaleLowerCase("de-DE"))).size!==item.members.length)issues.push(`wordFamilies.${item.id}: duplicate member form`);if(new Set(item.members.map((member)=>member.wordClass)).size<2)issues.push(`wordFamilies.${item.id}: fewer than two word classes`);});
  registerExamples.forEach((item,index)=>{const result=registerExampleSchema.safeParse(item);if(!result.success)result.error.issues.forEach((issue)=>issues.push(`registerExamples[${index}].${issue.path.join(".")}: ${issue.message}`));checkLesson(item.level,item.sourceLessonId,`registerExamples.${item.id}`,issues);});
  arabicLearnerConfusions.forEach((item,index)=>{const result=arabicLearnerConfusionSchema.safeParse(item);if(!result.success)result.error.issues.forEach((issue)=>issues.push(`arabicLearnerConfusions[${index}].${issue.path.join(".")}: ${issue.message}`));checkLesson(item.level,item.sourceLessonId,`arabicLearnerConfusions.${item.id}`,issues);});
  checkIds("wordFamilies",wordFamilies,issues);checkIds("registerExamples",registerExamples,issues);checkIds("arabicLearnerConfusions",arabicLearnerConfusions,issues);
  for(const level of levels){
    if(wordFamilies.filter((item)=>item.level===level).length!==8)issues.push(`${level}: expected 8 word families`);
    const registerRows=registerExamples.filter((item)=>item.level===level);for(const register of ["formal","neutral","colloquial","professional"] as const)if(registerRows.filter((item)=>item.register===register).length!==2)issues.push(`${level}: expected two ${register} examples`);
    if(arabicLearnerConfusions.filter((item)=>item.level===level).length!==6)issues.push(`${level}: expected 6 Arabic-learner confusions`);
  }
  if(!arabicLearnerConfusions.some((item)=>item.source==="arabic-transfer")||!arabicLearnerConfusions.some((item)=>item.source==="english-mediation")||!arabicLearnerConfusions.some((item)=>item.source==="french-mediation"))issues.push("confusions: mediation/transfer source coverage incomplete");
  for(const value of learnerVisibleFields({wordFamilies,registerExamples,arabicLearnerConfusions}))if(/\b[ab][12]-\d{2}\b/i.test(value))issues.push(`learner-visible registry text leaks internal lesson id: ${value.slice(0,80)}`);
  for(const item of wordFamilies)if(!germanPattern.test(item.anchorDe)||!arabicPattern.test(`${item.titleAr} ${item.relationNoteAr}`))issues.push(`wordFamilies.${item.id}: missing German/Arabic boundary content`);
  for(const item of registerExamples)if(!germanPattern.test(item.expressionDe)||!arabicPattern.test(item.meaningAr))issues.push(`registerExamples.${item.id}: missing German/Arabic content`);
  for(const item of arabicLearnerConfusions)if(!germanPattern.test(item.targetDe)||!arabicPattern.test(item.correctMeaningAr))issues.push(`arabicLearnerConfusions.${item.id}: missing German/Arabic content`);

  const recyclingRows=moduleRecyclingSummaries.map((summary)=>{const plan=buildModuleReviewQuestionPlan(summary.moduleId);const recycled=plan.filter((item)=>item.scope==="recycled");const current=plan.filter((item)=>item.scope==="current");if(plan.length!==10||new Set(plan.map((item)=>item.question.id)).size!==10)issues.push(`${summary.moduleId}: review plan must have 10 unique questions`);if(summary.recycledPercent!==expectedRecycledPercent(summary.level,summary.module)||summary.recycledPercent!==recycled.length*10)issues.push(`${summary.moduleId}: recycling ratio drifted`);if(recycled.some((item)=>!lessonIsBeforeModule(item.sourceLessonId,summary.moduleId)))issues.push(`${summary.moduleId}: recycled source is not from an earlier module`);if(recycled.length>=2&&!recycled.some((item)=>item.contentKind==="vocabulary-retrieval"))issues.push(`${summary.moduleId}: missing recycled vocabulary`);if(recycled.length>=2&&!recycled.some((item)=>item.contentKind==="grammar-retrieval"))issues.push(`${summary.moduleId}: missing recycled grammar`);if(current.length!==summary.currentCount)issues.push(`${summary.moduleId}: current count drifted`);return{...summary,questionIds:plan.map((item)=>item.question.id),recycledKinds:[...new Set(recycled.map((item)=>item.contentKind))]};});
  if(recyclingRows.length!==30)issues.push(`recycling: expected 30 module rows, received ${recyclingRows.length}`);

  return{format:"dwnb-lexical-strategy-audit",version:"lexical-strategy-audit-v1",generatedAt:"2026-09-08",ok:issues.length===0,policyVersions:{registry:LEXICAL_STRATEGY_VERSION,recycling:MODULE_RECYCLING_VERSION},registryRows:{wordFamilies,registerExamples,arabicLearnerConfusions},counts:{wordFamilies:wordFamilies.length,wordFamilyMembers:wordFamilies.reduce((sum,item)=>sum+item.members.length,0),registerExamples:registerExamples.length,arabicLearnerConfusions:arabicLearnerConfusions.length,moduleRecyclingPlans:recyclingRows.length},byLevel:{wordFamilies:countByLevel(wordFamilies),registerExamples:countByLevel(registerExamples),arabicLearnerConfusions:countByLevel(arabicLearnerConfusions)},registerCounts:Object.fromEntries(["formal","neutral","colloquial","professional"].map((register)=>[register,registerExamples.filter((item)=>item.register===register).length])),confusionSourceCounts:Object.fromEntries(["arabic-transfer","english-mediation","french-mediation","near-german-form"].map((source)=>[source,arabicLearnerConfusions.filter((item)=>item.source===source).length])),recyclingBoundary:MODULE_RECYCLING_BOUNDARY,registryBoundary:"authored-navigation-support-no-automatic-derivation-register-rule-or-arabic-speaker-diagnosis",issues,recyclingRows};
}
