/* Generated by scripts/generate-local-test-templates.ts; do not edit. */
import type { LocalTestTemplateLesson } from "@/core/training/local-test-generator";

export const localTestTemplateBankA1 = [
  {
    "id": "a1-01",
    "level": "A1",
    "module": 1,
    "titleDe": "Hallo Berlin!",
    "titleAr": "مرحبًا برلين!",
    "questions": [
      {
        "id": "a1-01-m1",
        "promptDe": "___ heißt du?",
        "promptAr": "اختر أداة السؤال:",
        "options": [
          "Was",
          "Wo",
          "Wie",
          "Wer"
        ],
        "correctIndex": 2,
        "explanationAr": "السؤال عن الاسم هو Wie heißt du?: أداة الاستفهام Wie ثم الفعل heißt ثم الفاعل du. لا يُسأل عن الاسم بـWas أو Wo، لأن Was للسؤال عن شيء وWo للمكان."
      },
      {
        "id": "a1-01-m2",
        "promptDe": "Ich ___ Leila.",
        "promptAr": "أكمل:",
        "options": [
          "heißt",
          "heißen",
          "heißt du",
          "heiße"
        ],
        "correctIndex": 3,
        "explanationAr": "مع ich: heiße. وheißen يدل على الاسم الذي يعرّف به الشخص نفسه: Ich heiße …"
      },
      {
        "id": "a1-01-m3",
        "promptDe": "Formelle Frage",
        "promptAr": "اختر السؤال الرسمي:",
        "options": [
          "Wie heißen Sie?",
          "Wie heißt du?",
          "Wie heiße ich?",
          "Wie heißt er?"
        ],
        "correctIndex": 0,
        "explanationAr": "Sie الرسمية مع heißen. ومعنى heißen أن يكون لك اسم تُنادى به."
      },
      {
        "id": "a1-01-m4",
        "promptDe": "Guten Abend!",
        "promptAr": "أي ردّ طبيعي على تحية المساء؟",
        "options": [
          "Guten Morgen!",
          "Gute Nacht!",
          "Guten Abend!",
          "Auf Wiedersehen!"
        ],
        "correctIndex": 2,
        "explanationAr": "يمكن الرد بالتحية نفسها: Guten Abend! تُقال مساءً ويُجاب عنها بـGuten Abend! أو Guten Abend, wie geht es Ihnen?. أما Guten Morgen! فتحية صباحية، وGute Nacht! وAuf Wiedersehen! تقالان عند الوداع والنوم."
      },
      {
        "id": "a1-01-m5",
        "promptDe": "Richtige Wortstellung",
        "promptAr": "اختر الترتيب الصحيح:",
        "options": [
          "Wie du heißt?",
          "Du wie heißt?",
          "Heißt wie du?",
          "Wie heißt du?"
        ],
        "correctIndex": 3,
        "explanationAr": "Wie + فعل + فاعل. والفعل heißen خاص بالأسماء: Wie heißt du? — Ich heiße Karim."
      }
    ]
  },
  {
    "id": "a1-02",
    "level": "A1",
    "module": 1,
    "titleDe": "Woher kommst du?",
    "titleAr": "من أين أتيت؟",
    "questions": [
      {
        "id": "a1-02-m1",
        "promptDe": "___ kommst du?",
        "promptAr": "اختر:",
        "options": [
          "Wo",
          "Woher",
          "Wie",
          "Welche"
        ],
        "correctIndex": 1,
        "explanationAr": "السؤال عن الأصل Woher. والسؤال Woher عن الأصل، والجواب يبدأ بـaus: Ich komme aus Sfax."
      },
      {
        "id": "a1-02-m2",
        "promptDe": "Ich wohne ___ Tunis.",
        "promptAr": "اختر حرف الجر:",
        "options": [
          "aus",
          "von",
          "zu",
          "in"
        ],
        "correctIndex": 3,
        "explanationAr": "مكان السكن مع المدينة: in. لو كان السؤال Woher؟ لكان الجواب aus، وهنا السؤال Wo؟ فيكون in."
      },
      {
        "id": "a1-02-m3",
        "promptDe": "Er ___ Deutsch.",
        "promptAr": "اختر التصريف:",
        "options": [
          "spreche",
          "sprichst",
          "sprechen",
          "spricht"
        ],
        "correctIndex": 3,
        "explanationAr": "مع er تأتي الصيغة spricht: Er spricht Deutsch. er فاعل مفرد غائب ولذلك يحمل الفعل نهاية t، بخلاف ich spreche وdu sprichst وwir sprechen."
      },
      {
        "id": "a1-02-m4",
        "promptDe": "Du ___ aus Sfax.",
        "promptAr": "اختر:",
        "options": [
          "komme",
          "kommt",
          "kommst",
          "kommen"
        ],
        "correctIndex": 2,
        "explanationAr": "مع du: kommst. وللأصل نستعمل aus: Woher kommen Sie? — Aus Tunesien."
      },
      {
        "id": "a1-02-m5",
        "promptDe": "Frage nach Sprachen",
        "promptAr": "اختر السؤال عن اللغات:",
        "options": [
          "Wo wohnst du?",
          "Wie alt bist du?",
          "Woher kommst du?",
          "Welche Sprachen sprichst du?"
        ],
        "correctIndex": 3,
        "explanationAr": "Welche Sprachen يسأل عن اللغات. الفعل الألماني يتغير مع الفاعل."
      }
    ]
  },
  {
    "id": "a1-03",
    "level": "A1",
    "module": 1,
    "titleDe": "Buchstaben und Zahlen",
    "titleAr": "الحروف والأرقام",
    "questions": [
      {
        "id": "a1-03-m1",
        "promptDe": "21",
        "promptAr": "اختر الكلمة:",
        "options": [
          "zwanzigeins",
          "einszwanzig",
          "einundzwanzig",
          "zwanzigundeins"
        ],
        "correctIndex": 2,
        "explanationAr": "الوحدة ثم und ثم العشرة. من 13 إلى 19 نضيف غالبًا zehn بعد الوحدة: dreizehn، vierzehn."
      },
      {
        "id": "a1-03-m2",
        "promptDe": "Bitte ___ einmal.",
        "promptAr": "أكمل طلب الإعادة:",
        "options": [
          "noch",
          "nicht",
          "auch",
          "aus"
        ],
        "correctIndex": 0,
        "explanationAr": "Bitte noch einmal. عند تهجئة اسم أو بريد، انطق الحروف منفصلة وبإيقاع ثابت."
      },
      {
        "id": "a1-03-m3",
        "promptDe": "Wie schreibt man das?",
        "promptAr": "ما المقصود؟",
        "options": [
          "أين تسكن؟",
          "كيف تُكتب؟",
          "كم عمرك؟",
          "من أين أتيت؟"
        ],
        "correctIndex": 1,
        "explanationAr": "Wie schreibt man das? تعني «كيف تُكتب هذه الكلمة؟»: أداة الاستفهام Wie ثم الفعل schreibt ثم الفاعل man. تُستعمل عند سماع كلمة جديدة لطلب تهجئتها حرفًا حرفًا."
      },
      {
        "id": "a1-03-m4",
        "promptDe": "30",
        "promptAr": "اختر الصيغة الصحيحة لحالة «30»:",
        "options": [
          "dreizehn",
          "dreiundzehn",
          "dreißig",
          "dreiß"
        ],
        "correctIndex": 2,
        "explanationAr": "30 هي dreißig. من 13 إلى 19 نضيف غالبًا zehn بعد الوحدة: dreizehn، vierzehn."
      },
      {
        "id": "a1-03-m5",
        "promptDe": "die Telefonnummer",
        "promptAr": "اختر ضمير الملكية مع ich:",
        "options": [
          "mein Telefonnummer",
          "meinen Telefonnummer",
          "meiner Telefonnummer",
          "meine Telefonnummer"
        ],
        "correctIndex": 3,
        "explanationAr": "الاسم مؤنث: die Telefonnummer، ولذلك يظهر ضمير الملكية meine. mein للمذكر والمحايد، وmeine للمؤنث والجمع، والملكية تتبع جنس الاسم لا جنس صاحبه."
      }
    ]
  },
  {
    "id": "a1-04",
    "level": "A1",
    "module": 2,
    "titleDe": "Meine Familie",
    "titleAr": "عائلتي",
    "questions": [
      {
        "id": "a1-04-m1",
        "promptDe": "Das ist ___ Schwester.",
        "promptAr": "اختر:",
        "options": [
          "mein",
          "meine",
          "meinen",
          "meines"
        ],
        "correctIndex": 1,
        "explanationAr": "die Schwester → meine. كلمة الملكية mein لا تتغير لأن المتكلم ذكر أو أنثى، بل تتغير بحسب الاسم الذي بعدها."
      },
      {
        "id": "a1-04-m2",
        "promptDe": "Das ___ meine Eltern.",
        "promptAr": "أكمل:",
        "options": [
          "sind",
          "ist",
          "bin",
          "habt"
        ],
        "correctIndex": 0,
        "explanationAr": "Eltern جمع → sind. نستعمل Das ist لتقديم شخص أو شيء واحد: Das ist meine Schwester."
      },
      {
        "id": "a1-04-m3",
        "promptDe": "der Vater",
        "promptAr": "اختر الملكية:",
        "options": [
          "mein Vater",
          "meine Vater",
          "meinen Vater ist",
          "meiner Vater"
        ],
        "correctIndex": 0,
        "explanationAr": "في التقديم الأساسي نقول mein Vater. وملكية المتكلم mein أو meine تتبع جنس الاسم التالي: mein Bruder، meine Schwester."
      },
      {
        "id": "a1-04-m4",
        "promptDe": "Hast du ___?",
        "promptAr": "اختر سؤالًا عن الإخوة:",
        "options": [
          "Eltern ist",
          "Geschwister",
          "Bruder sind",
          "Familie hat"
        ],
        "correctIndex": 1,
        "explanationAr": "Hast du Geschwister? سؤال طبيعي عن الإخوة: Geschwister جمع يُستعمل للإخوة والأخوات معًا، وبقية الخيارات تخلط اسمًا وفعلًا لا يبنيان سؤالًا صحيحًا مع Hast du."
      },
      {
        "id": "a1-04-m5",
        "promptDe": "Mehrere Kinder",
        "promptAr": "اختر التقديم الصحيح:",
        "options": [
          "Das ist meine Kinder.",
          "Das sind mein Kind.",
          "Das sind meine Kinder.",
          "Diese ist Kinder."
        ],
        "correctIndex": 2,
        "explanationAr": "Kinder جمع: Das sind meine Kinder. نستعمل Das ist لتقديم شخص أو شيء واحد: Das ist meine Schwester."
      }
    ]
  },
  {
    "id": "a1-05",
    "level": "A1",
    "module": 2,
    "titleDe": "Alter und Kontakte",
    "titleAr": "العمر وبيانات التواصل",
    "questions": [
      {
        "id": "a1-05-m1",
        "promptDe": "Wie alt ___ du?",
        "promptAr": "اختر:",
        "options": [
          "bin",
          "bist",
          "ist",
          "hast"
        ],
        "correctIndex": 1,
        "explanationAr": "مع du لا يكون إلا bist، والخطأ الشائع إسقاطه كلّه: «Ich 22 Jahre» جملة بلا فعل. صحّحها في جملة جديدة: Du bist zwanzig Jahre alt."
      },
      {
        "id": "a1-05-m2",
        "promptDe": "Ich ___ 28 Jahre alt.",
        "promptAr": "اختر:",
        "options": [
          "habe",
          "werde",
          "bin",
          "heiße"
        ],
        "correctIndex": 2,
        "explanationAr": "العمر مع bin. مع wir وsie يصير sind: Wir sind zwanzig Jahre alt."
      },
      {
        "id": "a1-05-m3",
        "promptDe": "Geburtstag ___ Juli",
        "promptAr": "اختر حرف الجر:",
        "options": [
          "im",
          "am",
          "aus",
          "nach"
        ],
        "correctIndex": 0,
        "explanationAr": "الشهر وحده يأخذ im. im = in dem؛ تدخل على الشهور والفصول، أما الأيام فمع am."
      },
      {
        "id": "a1-05-m4",
        "promptDe": "70",
        "promptAr": "اختر الكلمة:",
        "options": [
          "siebzehn",
          "siebzig",
          "siebenzehn",
          "siebundzehn"
        ],
        "correctIndex": 1,
        "explanationAr": "70 = siebzig. وبها تُبنى ما بعدها: siebzehn، achtundsiebzig — الوحدة قبل العشرة."
      },
      {
        "id": "a1-05-m5",
        "promptDe": "Korrektur",
        "promptAr": "اختر عبارة التصحيح:",
        "options": [
          "Kein 17, aber 70 ist.",
          "17 nicht und 70.",
          "Nicht 17, sondern 70.",
          "Sondern nicht 70."
        ],
        "correctIndex": 2,
        "explanationAr": "Nicht X, sondern Y نمط واضح للتصحيح: Nicht 17, sondern 70. الجزء الأول ينفي القيمة الخطأ، وsondern تعني «بل» فتُصلحها، ولا تُستعمل aber في هذا القالب."
      }
    ]
  },
  {
    "id": "a1-06",
    "level": "A1",
    "module": 2,
    "titleDe": "Berufe",
    "titleAr": "المهن والعمل",
    "questions": [
      {
        "id": "a1-06-m1",
        "promptDe": "Ich arbeite ___ Koch.",
        "promptAr": "اختر:",
        "options": [
          "bei",
          "in",
          "als",
          "aus"
        ],
        "correctIndex": 2,
        "explanationAr": "als للمهنة: Ich arbeite als Koch بمعنى «بصفتي طاهيًا»، وهي غير wie التي تعني «مثلما». وbei مع جهة العمل، وin مع المكان أو المجال."
      },
      {
        "id": "a1-06-m2",
        "promptDe": "Ich arbeite ___ einer Firma.",
        "promptAr": "اختر:",
        "options": [
          "als",
          "bei",
          "von",
          "nach"
        ],
        "correctIndex": 1,
        "explanationAr": "bei لجهة العمل. تُسمع كما هي مع اسم الشركة: bei einer Firma، وفي المختصر beim Amt."
      },
      {
        "id": "a1-06-m3",
        "promptDe": "Beruf vorstellen",
        "promptAr": "اختر الصحيح:",
        "options": [
          "Ich bin Lehrer.",
          "Ich bin ein Lehrer.",
          "Ich als Lehrer bin ein.",
          "Ich Beruf Lehrer."
        ],
        "correctIndex": 0,
        "explanationAr": "بعد sein تأتي المهنة عادة بلا أداة. تُبنى صيغة مؤنثة كثيرة بإضافة -in: Lehrer → Lehrerin، Verkäufer → Verkäuferin."
      },
      {
        "id": "a1-06-m4",
        "promptDe": "Feminine Form",
        "promptAr": "ما مؤنث Verkäufer؟",
        "options": [
          "Verkäuferin",
          "Verkauferin",
          "Verkäuferinen",
          "Verkaufrau"
        ],
        "correctIndex": 0,
        "explanationAr": "Verkäuferin. تُبنى صيغة مؤنثة كثيرة بإضافة -in: Lehrer → Lehrerin، Verkäufer → Verkäuferin."
      },
      {
        "id": "a1-06-m5",
        "promptDe": "Arbeitsort",
        "promptAr": "اختر ما يحدد المكان:",
        "options": [
          "als Koch",
          "in Berlin",
          "bei einer Firma",
          "von Beruf"
        ],
        "correctIndex": 1,
        "explanationAr": "in Berlin يحدد المكان. نستعمل als قبل الدور أو المهنة: Ich arbeite als Koch."
      }
    ]
  },
  {
    "id": "a1-07",
    "level": "A1",
    "module": 3,
    "titleDe": "Wie spät ist es?",
    "titleAr": "كم الساعة؟",
    "questions": [
      {
        "id": "a1-07-m1",
        "promptDe": "10:30",
        "promptAr": "اختر الوقت اليومي:",
        "options": [
          "halb zehn",
          "Viertel vor zehn",
          "zehn nach halb",
          "halb elf"
        ],
        "correctIndex": 3,
        "explanationAr": "10:30 = halb elf. في الصيغة الرسمية نقرأ الساعة ثم Uhr ثم الدقائق: zehn Uhr zwanzig."
      },
      {
        "id": "a1-07-m2",
        "promptDe": "Der Film beginnt ___ 20 Uhr.",
        "promptAr": "اختر:",
        "options": [
          "in",
          "von",
          "um",
          "bis"
        ],
        "correctIndex": 2,
        "explanationAr": "الساعة المحددة تدخلها um، أما البداية الممتدة فبـ ab أو seit. مثال من يومك: Der Film beginnt um zwanzig Uhr."
      },
      {
        "id": "a1-07-m3",
        "promptDe": "09:45",
        "promptAr": "أي خيار يحقّق «09:45» في هذا السياق؟",
        "options": [
          "Viertel nach neun",
          "halb zehn",
          "zehn Uhr fünfzehn",
          "Viertel vor zehn"
        ],
        "correctIndex": 3,
        "explanationAr": "ربع قبل العاشرة. في الصيغة الرسمية نقرأ الساعة ثم Uhr ثم الدقائق: zehn Uhr zwanzig."
      },
      {
        "id": "a1-07-m4",
        "promptDe": "Zeitraum",
        "promptAr": "اختر تركيب الفترة:",
        "options": [
          "um neun bis zwölf",
          "in neun zu zwölf",
          "nach neun vor zwölf",
          "von neun bis zwölf"
        ],
        "correctIndex": 3,
        "explanationAr": "الفترة: von … bis. نستعمل um مع لحظة بداية أو موعد محدد: Der Kurs beginnt um neun Uhr."
      },
      {
        "id": "a1-07-m5",
        "promptDe": "Frage nach der Uhrzeit",
        "promptAr": "اختر السؤال الصحيح:",
        "options": [
          "Wie spät ist es?",
          "Wann alt ist es?",
          "Wo Uhr ist?",
          "Was Zeit du?"
        ],
        "correctIndex": 0,
        "explanationAr": "Wie spät ist es? نفس المعنى في صيغة أخرى: Wie viel Uhr haben wir? — والسؤالان عن الوقت وحده."
      }
    ]
  },
  {
    "id": "a1-08",
    "level": "A1",
    "module": 3,
    "titleDe": "Mein Tag",
    "titleAr": "يومي",
    "questions": [
      {
        "id": "a1-08-m1",
        "promptDe": "Ich ___ um sieben ___.",
        "promptAr": "اختر الفعل المنفصل:",
        "options": [
          "stehe / auf",
          "aufstehe / —",
          "steht / auf",
          "stehe / an"
        ],
        "correctIndex": 0,
        "explanationAr": "ich stehe … auf. والفعل المنفصل يذهب جزؤه الثاني إلى نهاية الجملة: Ich stehe um sechs auf."
      },
      {
        "id": "a1-08-m2",
        "promptDe": "Am Abend ___ ich Deutsch.",
        "promptAr": "اختر:",
        "options": [
          "ich lerne",
          "lernen",
          "lernt",
          "lerne"
        ],
        "correctIndex": 3,
        "explanationAr": "بعد الوقت يأتي الفعل ثم ich. يمكن أن تبدأ الجملة بالفاعل: Ich stehe um sieben auf."
      },
      {
        "id": "a1-08-m3",
        "promptDe": "einkaufen",
        "promptAr": "اختر الجملة الصحيحة:",
        "options": [
          "Ich einkaufe heute.",
          "Ich kaufe heute ein.",
          "Ich heute ein kaufe.",
          "Heute ich kaufe ein."
        ],
        "correctIndex": 1,
        "explanationAr": "kaufe في الموقع الثاني وein في النهاية. والبادئة المنفصلة تنزل إلى آخر الجملة: Ich kaufe am Abend ein."
      },
      {
        "id": "a1-08-m4",
        "promptDe": "selten",
        "promptAr": "ما المعنى؟",
        "options": [
          "دائمًا",
          "غالبًا",
          "غدًا",
          "نادرًا"
        ],
        "correctIndex": 3,
        "explanationAr": "selten = نادرًا. نقيضها oft؛ وضعها في الجملة قبل الفعل: Ich gehe selten ins Kino."
      },
      {
        "id": "a1-08-m5",
        "promptDe": "Danach …",
        "promptAr": "اختر الترتيب:",
        "options": [
          "Danach ich arbeite.",
          "Danach arbeite ich.",
          "Danach arbeiten ich.",
          "Ich danach arbeite."
        ],
        "correctIndex": 1,
        "explanationAr": "Danach ثم الفعل ثم الفاعل. يمكن أن تبدأ الجملة بالفاعل: Ich stehe um sieben auf."
      }
    ]
  },
  {
    "id": "a1-09",
    "level": "A1",
    "module": 3,
    "titleDe": "Termine",
    "titleAr": "المواعيد",
    "questions": [
      {
        "id": "a1-09-m1",
        "promptDe": "___ Montag",
        "promptAr": "اختر:",
        "options": [
          "Um",
          "Im",
          "Von",
          "Am"
        ],
        "correctIndex": 3,
        "explanationAr": "أيام الأسبوع مع am. اليوم مع am لكن الساعة لا تدخل عليه: لا «am sechs Uhr»."
      },
      {
        "id": "a1-09-m2",
        "promptDe": "___ sechs Uhr",
        "promptAr": "اختر:",
        "options": [
          "Um",
          "Am",
          "In",
          "Bei"
        ],
        "correctIndex": 0,
        "explanationAr": "الساعة مع um: um sechs Uhr. ومع اليوم يصيران معًا: am Montag um zehn Uhr — am لليوم وum للساعة. لا تُستعمل In أو Bei في تحديد وقت الساعة."
      },
      {
        "id": "a1-09-m3",
        "promptDe": "Wir können uns morgen ___.",
        "promptAr": "أكمل المصدر:",
        "options": [
          "trefft",
          "treffen",
          "getroffen",
          "trifft"
        ],
        "correctIndex": 1,
        "explanationAr": "بعد können يأتي المصدر في النهاية. ومع können يأتي الفعل الناقص ثانيًا والمصدر أخيرًا: Ich kann heute nicht kommen."
      },
      {
        "id": "a1-09-m4",
        "promptDe": "Höfliche Ablehnung",
        "promptAr": "اختر الرفض اللبق:",
        "options": [
          "Nein.",
          "Keine.",
          "Leider kann ich nicht.",
          "Nicht Termin."
        ],
        "correctIndex": 2,
        "explanationAr": "leider تخفف الرفض. والترتيب مع können: الفعل الناقص في الموقع الثاني ثم المصدر في النهاية: Wir können am Freitag starten."
      },
      {
        "id": "a1-09-m5",
        "promptDe": "Vorschlag",
        "promptAr": "اختر الاقتراح:",
        "options": [
          "Ich war Mittwoch.",
          "Wie wäre es am Mittwoch?",
          "Mittwoch ist nicht.",
          "Wo Mittwoch du?"
        ],
        "correctIndex": 1,
        "explanationAr": "Wie wäre es am Mittwoch? صيغة اقتراح مهذبة: wäre هي Konjunktiv II من sein، وتُستعمل لعرض بديل. يُجاب عنها بـJa, gern أو Das passt mir leider nicht."
      }
    ]
  },
  {
    "id": "a1-10",
    "level": "A1",
    "module": 4,
    "titleDe": "Lebensmittel",
    "titleAr": "المواد الغذائية",
    "questions": [
      {
        "id": "a1-10-m1",
        "promptDe": "Ich esse ___ Apfel.",
        "promptAr": "اختر:",
        "options": [
          "ein",
          "eine",
          "einer",
          "einen"
        ],
        "correctIndex": 3,
        "explanationAr": "Apfel مذكر في Akkusativ. في جملة مثل Ich esse einen Apfel يكون الشخص فاعلًا، والتفاحة هي الشيء الذي يقع عليه الفعل."
      },
      {
        "id": "a1-10-m2",
        "promptDe": "Ich habe ___ Milch.",
        "promptAr": "انفِ الجملة:",
        "options": [
          "kein",
          "keinen",
          "keine",
          "nicht eine"
        ],
        "correctIndex": 2,
        "explanationAr": "Milch مؤنث: keine. وgern بعد الفعل تصف ما نحب: Ich trinke gern Kaffee."
      },
      {
        "id": "a1-10-m3",
        "promptDe": "Vorliebe",
        "promptAr": "اختر الجملة الطبيعية:",
        "options": [
          "Ich gern Brot.",
          "Ich esse Brot gernen.",
          "Gern ich esse Brot.",
          "Ich esse gern Brot."
        ],
        "correctIndex": 3,
        "explanationAr": "gern يأتي مع فعل مصرف صحيح. وفي Ich esse einen Apfel يكون المتكلم فاعلًا، وeinen Apfel مفعولًا منصوبًا."
      },
      {
        "id": "a1-10-m4",
        "promptDe": "das Ei",
        "promptAr": "اختر المفعول:",
        "options": [
          "ein Ei",
          "einen Ei",
          "eine Ei",
          "einem Ei"
        ],
        "correctIndex": 0,
        "explanationAr": "Ei محايد: ein. المحايد لا يتغيّر في النصب: Ich sehe ein Ei، بينما يأخذ المذكر einen: einen Apfel."
      },
      {
        "id": "a1-10-m5",
        "promptDe": "der Kaffee",
        "promptAr": "اختر النفي في Akkusativ:",
        "options": [
          "keinen Kaffee",
          "kein Kaffee",
          "keine Kaffee",
          "keinem Kaffee"
        ],
        "correctIndex": 0,
        "explanationAr": "المذكر في Akkusativ: keinen. وللتعبير عن محبة فعل نضيف gern: Ich kaufe gern frisches Brot."
      }
    ]
  },
  {
    "id": "a1-11",
    "level": "A1",
    "module": 4,
    "titleDe": "Einkaufen",
    "titleAr": "التسوّق",
    "questions": [
      {
        "id": "a1-11-m1",
        "promptDe": "___ Packung Reis",
        "promptAr": "اختر:",
        "options": [
          "ein",
          "eine",
          "einen",
          "einem"
        ],
        "correctIndex": 1,
        "explanationAr": "Packung مؤنث. نضع وحدة الكمية قبل المادة: ein Kilo Tomaten، 500 Gramm Käse، eine Flasche Wasser."
      },
      {
        "id": "a1-11-m2",
        "promptDe": "Das Brot ___ zwei Euro.",
        "promptAr": "اختر:",
        "options": [
          "kosten",
          "kostest",
          "kostet",
          "koste"
        ],
        "correctIndex": 2,
        "explanationAr": "Brot مفرد: kostet. وmöchte تجعل الطلب مهذبًا: Ich möchte ein Brot, bitte."
      },
      {
        "id": "a1-11-m3",
        "promptDe": "Die Äpfel ___ drei Euro.",
        "promptAr": "اختر:",
        "options": [
          "kosten",
          "kostet",
          "koste",
          "kost"
        ],
        "correctIndex": 0,
        "explanationAr": "Äpfel جمع: kosten. وللطلب المهذب نستعمل möchte مع المصدر في النهاية: Ich möchte zwei Äpfel."
      },
      {
        "id": "a1-11-m4",
        "promptDe": "Höfliche Bestellung",
        "promptAr": "اختر الطلب المهذب:",
        "options": [
          "Gib Tomaten.",
          "Ich möchte ein Kilo Tomaten.",
          "Tomaten ich.",
          "Ich bin Tomaten."
        ],
        "correctIndex": 1,
        "explanationAr": "Ich möchte … صيغة طلب مناسبة. وmöchte صيغة مهذبة معناها «أرغب في»: Ich möchte ein Kilo Reis."
      },
      {
        "id": "a1-11-m5",
        "promptDe": "Einkauf beenden",
        "promptAr": "اختر التعبير المطابق لـ«Einkauf beenden»:",
        "options": [
          "Alles nicht.",
          "Ich komme Ende.",
          "Sonst nein ist.",
          "Das ist alles, danke."
        ],
        "correctIndex": 3,
        "explanationAr": "عبارة طبيعية لإنهاء الطلب: Das ist alles, danke. تُقال للبائع بعد آخر مادة ثم يُسأل عن طريقة الدفع. ويمكن أن تسبقها Nein, danke إن عُرض عليك المزيد."
      }
    ]
  },
  {
    "id": "a1-12",
    "level": "A1",
    "module": 4,
    "titleDe": "Im Restaurant",
    "titleAr": "في المطعم",
    "questions": [
      {
        "id": "a1-12-m1",
        "promptDe": "Ich nehme ___ Salat.",
        "promptAr": "اختر:",
        "options": [
          "ein",
          "eine",
          "einem",
          "einen"
        ],
        "correctIndex": 3,
        "explanationAr": "Salat مذكر في Akkusativ. ومن صيغ الطلب: Ich nehme …, أو Für mich bitte … في المطعم والمقهى."
      },
      {
        "id": "a1-12-m2",
        "promptDe": "Kaffee ___ Zucker",
        "promptAr": "دون سكر:",
        "options": [
          "mit",
          "ohne",
          "bei",
          "aus"
        ],
        "correctIndex": 1,
        "explanationAr": "ohne = دون. نستعمل mit لإضافة مكوّن وohne لاستبعاده: mit Reis، ohne Zwiebeln."
      },
      {
        "id": "a1-12-m3",
        "promptDe": "Problem nennen",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Problem nennen»:",
        "options": [
          "Ich nicht Bestellung.",
          "Das ist bestellen nicht.",
          "Das habe ich nicht bestellt.",
          "Kein bestelle."
        ],
        "correctIndex": 2,
        "explanationAr": "جملة واضحة لشرح الطبق الخطأ. نستعمل mit لإضافة مكوّن وohne لاستبعاده: mit Reis، ohne Zwiebeln."
      },
      {
        "id": "a1-12-m4",
        "promptDe": "Bezahlen",
        "promptAr": "اطلب الحساب:",
        "options": [
          "Die Rechnung, bitte.",
          "Die Speisekarte, bitte.",
          "Das Essen kalt.",
          "Ein Rechnung ist."
        ],
        "correctIndex": 0,
        "explanationAr": "Die Rechnung, bitte. واطلب بجملة قصيرة واضحة: Ich möchte …, Ich nehme …, أو Für mich bitte …."
      },
      {
        "id": "a1-12-m5",
        "promptDe": "das Wasser",
        "promptAr": "اختر الطلب:",
        "options": [
          "einen Wasser",
          "eine Wasser",
          "ein Wasser",
          "einem Wasser"
        ],
        "correctIndex": 2,
        "explanationAr": "Wasser محايد: ein. وللطلب في السوق تكفي صيغة واحدة صريحة: Ich nehme ein Kilo Tomaten."
      }
    ]
  },
  {
    "id": "a1-13",
    "level": "A1",
    "module": 5,
    "titleDe": "Meine Wohnung",
    "titleAr": "شقّتي",
    "questions": [
      {
        "id": "a1-13-m1",
        "promptDe": "Es gibt ___ Balkon.",
        "promptAr": "اختر:",
        "options": [
          "ein",
          "einen",
          "eine",
          "einer"
        ],
        "correctIndex": 1,
        "explanationAr": "Balkon مذكر بعد es gibt. والتعبير es gibt يعني «يوجد»: Es gibt eine Küche und ein Bad."
      },
      {
        "id": "a1-13-m2",
        "promptDe": "Kein Aufzug",
        "promptAr": "اختر الجملة:",
        "options": [
          "Es gibt kein Aufzug.",
          "Es gibt keine Aufzug.",
          "Es gibt keinen Aufzug.",
          "Es nicht gibt Aufzug."
        ],
        "correctIndex": 2,
        "explanationAr": "keinen للمذكر في Akkusativ. ومع وجود شيء نبدأ بـes gibt: Es gibt keine Garage."
      },
      {
        "id": "a1-13-m3",
        "promptDe": "Mehrere Räume",
        "promptAr": "أي خيار يحقّق «Mehrere Räume» في هذا السياق؟",
        "options": [
          "Es gibt drei Zimmer.",
          "Es gibt drei Zimmers.",
          "Es sind gibt Zimmer.",
          "Drei Zimmer gibt sind."
        ],
        "correctIndex": 0,
        "explanationAr": "Zimmer جمعها دون s هنا. وes gibt تركيب ثابت للإخبار بالوجود: Es gibt viel Licht in der Wohnung."
      },
      {
        "id": "a1-13-m4",
        "promptDe": "Adjektiv nach sein",
        "promptAr": "اختر التعبير المطابق لـ«Adjektiv nach sein»:",
        "options": [
          "Die Wohnung ist ruhige.",
          "Die Wohnung ist ruhig.",
          "Die ruhige ist Wohnung.",
          "Wohnung ruhig eine."
        ],
        "correctIndex": 1,
        "explanationAr": "بعد ist: ruhig دون نهاية. يمكن وصف المسكن بجملة sein: Die Wohnung ist hell und ruhig."
      },
      {
        "id": "a1-13-m5",
        "promptDe": "Frage",
        "promptAr": "اسأل عن القبو:",
        "options": [
          "Hat gibt Keller?",
          "Ist es Keller?",
          "Wo einen Keller gibt?",
          "Gibt es einen Keller?"
        ],
        "correctIndex": 3,
        "explanationAr": "Gibt es …? سؤال الوجود. وللإخبار بوجود شيء نستعمل es gibt: Es gibt einen Garten im Hof."
      }
    ]
  },
  {
    "id": "a1-14",
    "level": "A1",
    "module": 5,
    "titleDe": "Möbel und Dinge",
    "titleAr": "الأثاث والأشياء",
    "questions": [
      {
        "id": "a1-14-m1",
        "promptDe": "auf ___ Tisch",
        "promptAr": "اختر:",
        "options": [
          "dem",
          "der",
          "den",
          "die"
        ],
        "correctIndex": 0,
        "explanationAr": "auf مع السكون تأخذ Dativ: auf dem Tisch؛ والمذكر هنا لا يجمع ولا يتغير شكله."
      },
      {
        "id": "a1-14-m2",
        "promptDe": "in ___ Küche",
        "promptAr": "اختر:",
        "options": [
          "die",
          "der",
          "dem",
          "den"
        ],
        "correctIndex": 1,
        "explanationAr": "in مع المكان المغلق تأخذ Dativ، فيصير المؤنث der: in der Küche. جرّبها على مؤنث آخر: in der Schule، in der Stadt."
      },
      {
        "id": "a1-14-m3",
        "promptDe": "Das Bild ___ an der Wand.",
        "promptAr": "اختر:",
        "options": [
          "hängt",
          "liegt",
          "steht",
          "sitzt"
        ],
        "correctIndex": 0,
        "explanationAr": "الصورة معلقة: hängt. نستعمل stehen غالبًا لشيء قائم أو موضوع على قاعدته، مثل Die Flasche steht auf dem Tisch."
      },
      {
        "id": "a1-14-m4",
        "promptDe": "Das Buch ___ auf dem Tisch.",
        "promptAr": "اختر:",
        "options": [
          "hängt",
          "steht immer",
          "liegt",
          "wohnt"
        ],
        "correctIndex": 2,
        "explanationAr": "الكتاب أفقي: liegt. نستعمل stehen غالبًا لشيء قائم أو موضوع على قاعدته، مثل Die Flasche steht auf dem Tisch."
      },
      {
        "id": "a1-14-m5",
        "promptDe": "Plural Dativ",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Plural Dativ»:",
        "options": [
          "zwischen die Stühle",
          "zwischen dem Stühle",
          "zwischen der Stühlen",
          "zwischen den Stühlen"
        ],
        "correctIndex": 3,
        "explanationAr": "جمع Dativ: den Stühlen — أداة الجمع den ويظهر الاسم منتهيًا بـ-n. لذا zwischen den Stühlen لا dem ولا der، وللجمع في Dativ علامته الخاصة."
      }
    ]
  },
  {
    "id": "a1-15",
    "level": "A1",
    "module": 5,
    "titleDe": "Wohnungssuche",
    "titleAr": "البحث عن سكن",
    "questions": [
      {
        "id": "a1-15-m1",
        "promptDe": "Frage nach der Größe",
        "promptAr": "أي خيار يحقّق «Frage nach der Größe» في هذا السياق؟",
        "options": [
          "Wie viel groß ist sie?",
          "Wie hoch groß?",
          "Was Quadrat Wohnung?",
          "Wie groß ist die Wohnung?"
        ],
        "correctIndex": 3,
        "explanationAr": "Wie groß …? للسؤال نقول Wie groß ist die Wohnung? وWie hoch ist die Miete? وللتجهيزات نستعمل Gibt es …? أما الموعد فنستعمل können: Wann kann ich die Wohnung besichtigen? في الاتصال اذكر الإعلان أو العنوان أولًا حتى يعرف الطرف الآخر موضوع المكالمة."
      },
      {
        "id": "a1-15-m2",
        "promptDe": "Frage nach der Miete",
        "promptAr": "اختر التعبير المطابق لـ«Frage nach der Miete»:",
        "options": [
          "Wie hoch ist die Miete?",
          "Wie groß kostet Miete?",
          "Was Miete hoch?",
          "Welche Euro ist?"
        ],
        "correctIndex": 0,
        "explanationAr": "Wie hoch ist die Miete? للسؤال نقول Wie groß ist die Wohnung? وWie hoch ist die Miete? وللتجهيزات نستعمل Gibt es …? أما الموعد فنستعمل können: Wann kann ich die Wohnung besichtigen? في الاتصال اذكر الإعلان أو العنوان أولًا حتى يعرف الطرف الآخر موضوع المكالمة."
      },
      {
        "id": "a1-15-m3",
        "promptDe": "Warmmiete",
        "promptAr": "ماذا تعني هنا؟",
        "options": [
          "الإيجار الأساسي فقط",
          "التأمين فقط",
          "الإجمالي المذكور مع المصاريف المشمولة",
          "سعر الأثاث"
        ],
        "correctIndex": 2,
        "explanationAr": "هي القيمة الإجمالية وفق تفاصيل الإعلان: Warmmiete تعني الإيجار الشامل مع ما يحدده المعلن مثل التدفئة، أما Kaltmiete فالإيجار الأساسي وحده قبل المصاريف."
      },
      {
        "id": "a1-15-m4",
        "promptDe": "Besichtigung",
        "promptAr": "اختر السؤال الصحيح:",
        "options": [
          "Wann ich Wohnung sehen kann?",
          "Wo kann Wohnung ich?",
          "Besichtigen wann mich?",
          "Wann kann ich die Wohnung besichtigen?"
        ],
        "correctIndex": 3,
        "explanationAr": "الفعل الناقص بعد Wann والمصدر في النهاية. للسؤال نقول Wie groß ist die Wohnung? وWie hoch ist die Miete? وللتجهيزات نستعمل Gibt es …? أما الموعد فنستعمل können: Wann kann ich die Wohnung besichtigen? في الاتصال اذكر الإعلان أو العنوان أولًا حتى يعرف الطرف الآخر موضوع المكالمة."
      },
      {
        "id": "a1-15-m5",
        "promptDe": "Interesse",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Interesse»:",
        "options": [
          "Ich interessiere die Wohnung.",
          "Ich bin Interesse Wohnung.",
          "Ich interessiere mich für die Wohnung.",
          "Für Wohnung ich Interesse."
        ],
        "correctIndex": 2,
        "explanationAr": "sich interessieren für. وللسؤال عن الحجم: Wie groß ist die Wohnung?، وعن الإيجار: Wie hoch ist die Miete?"
      }
    ]
  },
  {
    "id": "a1-16",
    "level": "A1",
    "module": 6,
    "titleDe": "Hobbys",
    "titleAr": "الهوايات",
    "questions": [
      {
        "id": "a1-16-m1",
        "promptDe": "Ich lese ___ als ich fernsehe.",
        "promptAr": "اختر التفضيل:",
        "options": [
          "lieber",
          "gern",
          "am liebsten",
          "gut"
        ],
        "correctIndex": 0,
        "explanationAr": "عند المقارنة نستعمل lieber. وgern بعد الفعل تعني أن النشاط محبوب: Ich koche gern."
      },
      {
        "id": "a1-16-m2",
        "promptDe": "___ du gut tanzen?",
        "promptAr": "اختر:",
        "options": [
          "Kann",
          "Können",
          "Kannt",
          "Kannst"
        ],
        "correctIndex": 3,
        "explanationAr": "في سؤال نعم/لا ينتقل kannst إلى أول الجملة ويبقى فعل النشاط مصدرًا في النهاية: Kannst du am Montag kommen? لا تُدخل zu بين الفعلين."
      },
      {
        "id": "a1-16-m3",
        "promptDe": "Ich kann Gitarre ___.",
        "promptAr": "أكمل:",
        "options": [
          "spiele",
          "spielt",
          "spielen",
          "gespielt"
        ],
        "correctIndex": 2,
        "explanationAr": "المصدر في النهاية. يأتي können مصرفًا في الموقع الثاني، بينما يأتي فعل النشاط في المصدر في نهاية الجملة: Ich kann gut schwimmen."
      },
      {
        "id": "a1-16-m4",
        "promptDe": "Höchste Vorliebe",
        "promptAr": "أي خيار يحقّق «Höchste Vorliebe» في هذا السياق؟",
        "options": [
          "am liebsten",
          "gern",
          "lieber",
          "selten"
        ],
        "correctIndex": 0,
        "explanationAr": "am liebsten أعلى تفضيل. ولمحبة نشاط نضع gern بعد الفعل: Ich schwimme gern."
      },
      {
        "id": "a1-16-m5",
        "promptDe": "Richtige Wortstellung",
        "promptAr": "اختر التعبير المطابق لـ«Richtige Wortstellung»:",
        "options": [
          "Ich gern lese.",
          "Ich lese gern.",
          "Gern ich lese.",
          "Ich lesen gern."
        ],
        "correctIndex": 1,
        "explanationAr": "الفعل المصرف في الموقع الثاني. وgern تنقل الرضا عن النشاط: Ich tanze gern."
      }
    ]
  },
  {
    "id": "a1-17",
    "level": "A1",
    "module": 6,
    "titleDe": "Eine Verabredung",
    "titleAr": "موعد مع صديق",
    "questions": [
      {
        "id": "a1-17-m1",
        "promptDe": "Ich will einen Film ___.",
        "promptAr": "أكمل:",
        "options": [
          "sehe",
          "sieht",
          "gesehen",
          "sehen"
        ],
        "correctIndex": 3,
        "explanationAr": "المصدر في النهاية. بعد wollen لا تأتي zu: Ich will einen Film sehen، لا «zu sehen»."
      },
      {
        "id": "a1-17-m2",
        "promptDe": "___ du mitkommen?",
        "promptAr": "اختر:",
        "options": [
          "Will",
          "Wollen",
          "Willst",
          "Wollt er"
        ],
        "correctIndex": 2,
        "explanationAr": "مع du: willst. نستعمل wollen للتعبير عن قرار أو خطة مباشرة: Ich will einen Film sehen."
      },
      {
        "id": "a1-17-m3",
        "promptDe": "Einladung",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Einladung»:",
        "options": [
          "Bist du Kino?",
          "Machst Kino du?",
          "Lust ist Kino?",
          "Hast du Lust auf Kino?"
        ],
        "correctIndex": 3,
        "explanationAr": "صيغة دعوة شائعة. الموعد الجيد يحتاج نشاطًا ويومًا ووقتًا ومكانًا."
      },
      {
        "id": "a1-17-m4",
        "promptDe": "Alternative",
        "promptAr": "أي خيار يحقّق «Alternative» في هذا السياق؟",
        "options": [
          "Wie wäre es am Samstag?",
          "Nein Ende.",
          "Samstag nicht wo.",
          "Ich bin Alternative."
        ],
        "correctIndex": 0,
        "explanationAr": "Wie wäre es …? تقدم بديلًا. وعند اقتراح موعد اذكر النشاط واليوم والساعة: Wir treffen uns am Samstag um sieben."
      },
      {
        "id": "a1-17-m5",
        "promptDe": "Bestätigung",
        "promptAr": "أي تأكيد مكتمل؟",
        "options": [
          "Samstag vielleicht.",
          "Kino ja.",
          "Wir sehen.",
          "Also Samstag um acht vor dem Kino."
        ],
        "correctIndex": 3,
        "explanationAr": "يحتوي اليوم والوقت والمكان. والاقتراح الكامل يضم اليوم والساعة والمكان: Am Sonntag um zehn am Bahnhof."
      }
    ]
  },
  {
    "id": "a1-18",
    "level": "A1",
    "module": 6,
    "titleDe": "Wetter und Wochenende",
    "titleAr": "الطقس ونهاية الأسبوع",
    "questions": [
      {
        "id": "a1-18-m1",
        "promptDe": "Regen",
        "promptAr": "اختر الجملة:",
        "options": [
          "Es ist regnet.",
          "Der Regen macht.",
          "Es sind Regen.",
          "Es regnet."
        ],
        "correctIndex": 3,
        "explanationAr": "Es regnet. تستعمل جمل الطقس الألمانية es حتى عندما لا يشير إلى شيء محدد: Es regnet، Es ist sonnig، Es schneit."
      },
      {
        "id": "a1-18-m2",
        "promptDe": "20 Grad",
        "promptAr": "اختر التعبير المطابق لـ«20 Grad»:",
        "options": [
          "Es ist 20 Grad.",
          "Das hat 20 Grad.",
          "Es sind 20 Grad.",
          "Sie werden Grad."
        ],
        "correctIndex": 2,
        "explanationAr": "العدد جمع: sind. والطقس يُوصف بـes: Es ist warm، Es regnet، Es schneit."
      },
      {
        "id": "a1-18-m3",
        "promptDe": "deshalb",
        "promptAr": "اختر الترتيب:",
        "options": [
          "Deshalb wir gehen ins Museum.",
          "Deshalb gehen wir ins Museum.",
          "Wir deshalb ins Museum gehen.",
          "Deshalb ins Museum wir."
        ],
        "correctIndex": 1,
        "explanationAr": "الفعل مباشرة بعد deshalb: deshalb في الموقع الأول، والموقع الثاني للفعل المصرف gehen، ثم الفاعل wir ثم ins Museum؛ لا يشغل الضمير الموقع الأول هنا."
      },
      {
        "id": "a1-18-m4",
        "promptDe": "Sonne",
        "promptAr": "أكمل:",
        "options": [
          "Die Sonne scheint.",
          "Die Sonne regnet.",
          "Es sonnt ist.",
          "Sonne macht hellen."
        ],
        "correctIndex": 0,
        "explanationAr": "Die Sonne scheint تصف الطقس وصفًا صحيحًا: الفعل scheinen يأتي مع الشمس، وSonne مؤنث فتأخذ die. أما الأحوال العامة فتُبنى غالبًا بـes مثل Es regnet."
      },
      {
        "id": "a1-18-m5",
        "promptDe": "Wetter",
        "promptAr": "اختر الأداة:",
        "options": [
          "der Wetter",
          "die Wetter",
          "den Wetter",
          "das Wetter"
        ],
        "correctIndex": 3,
        "explanationAr": "das Wetter. الأداة das مع Wetter، وجُمل الطقس تبدأ بـ es: Es ist gutes Wetter."
      }
    ]
  },
  {
    "id": "a1-19",
    "level": "A1",
    "module": 7,
    "titleDe": "Verkehrsmittel",
    "titleAr": "وسائل النقل",
    "questions": [
      {
        "id": "a1-19-m1",
        "promptDe": "mit ___ Bus",
        "promptAr": "اختر:",
        "options": [
          "der",
          "den",
          "die",
          "dem"
        ],
        "correctIndex": 3,
        "explanationAr": "mit dem Bus. mit تطلب Dativ دائمًا، والمذكر والمحايد يأخذان dem."
      },
      {
        "id": "a1-19-m2",
        "promptDe": "mit ___ U-Bahn",
        "promptAr": "اختر:",
        "options": [
          "die",
          "dem",
          "der",
          "den"
        ],
        "correctIndex": 2,
        "explanationAr": "mit der U-Bahn. المؤنث في Dativ يأخذ der ويبقى اسمه مفردًا: mit der U-Bahn."
      },
      {
        "id": "a1-19-m3",
        "promptDe": "gehen",
        "promptAr": "المشي:",
        "options": [
          "mit Fuß",
          "bei Fuß",
          "auf Füße",
          "zu Fuß"
        ],
        "correctIndex": 3,
        "explanationAr": "zu Fuß. لا تُبدّل بها mit Fuß ولا zu dem Fuß؛ العبارة ثابتة كما تُسمع."
      },
      {
        "id": "a1-19-m4",
        "promptDe": "Du ___ mit dem Zug.",
        "promptAr": "اختر:",
        "options": [
          "fährst",
          "fahre",
          "fahrt",
          "fahren"
        ],
        "correctIndex": 0,
        "explanationAr": "du fährst: الفعل fahren يتغير مع الفاعل، فـdu يأخذ نهاية -st وer/sie/es يأخذ fährt. ويُقال في وصف الوسيلة Ich fahre mit dem Bus."
      },
      {
        "id": "a1-19-m5",
        "promptDe": "nehmen",
        "promptAr": "اختر الصيغة الصحيحة لحالة «nehmen»:",
        "options": [
          "Ich nehme dem Bus.",
          "Ich mit Bus nehme.",
          "Ich nehme den Bus.",
          "Ich nehmen der Bus."
        ],
        "correctIndex": 2,
        "explanationAr": "nehmen + Akkusativ: den Bus. نقول Ich fahre mit dem Bus لوصف وسيلة التنقل."
      }
    ]
  },
  {
    "id": "a1-20",
    "level": "A1",
    "module": 7,
    "titleDe": "Der Weg",
    "titleAr": "وصف الطريق",
    "questions": [
      {
        "id": "a1-20-m1",
        "promptDe": "Formeller Imperativ",
        "promptAr": "أي خيار يحقّق «Formeller Imperativ» في هذا السياق؟",
        "options": [
          "Sie gehen geradeaus!",
          "Gehen Sie geradeaus.",
          "Gehst Sie.",
          "Gehen gerade Sie."
        ],
        "correctIndex": 1,
        "explanationAr": "الفعل ثم Sie. وصيغة الأمر الرسمية: الفعل أولًا ثم Sie: Biegen Sie rechts ab."
      },
      {
        "id": "a1-20-m2",
        "promptDe": "abbiegen",
        "promptAr": "اختر التعبير المطابق لـ«abbiegen»:",
        "options": [
          "Ab Sie biegen links.",
          "Sie abbiegen links.",
          "Biegen Sie links ab.",
          "Biegt Sie ab links."
        ],
        "correctIndex": 2,
        "explanationAr": "Biegen Sie … ab. وللتعليم المهذب نستعمل الفعل ثم Sie: Steigen Sie bitte um."
      },
      {
        "id": "a1-20-m3",
        "promptDe": "die Post",
        "promptAr": "إلى البريد:",
        "options": [
          "zum Post",
          "zur Post",
          "zu dem Post",
          "in der Post gehen"
        ],
        "correctIndex": 1,
        "explanationAr": "zur Post. وصف الطريق الجيد لا يعتمد على يمين ويسار فقط، بل يربط الاتجاه بمعلم: an der Ampel links، an der Bank vorbei، gegenüber dem Hotel."
      },
      {
        "id": "a1-20-m4",
        "promptDe": "gegenüber ___ Hotel",
        "promptAr": "اختر:",
        "options": [
          "das",
          "den",
          "dem",
          "der"
        ],
        "correctIndex": 2,
        "explanationAr": "Hotel محايد في Dativ: dem. المحايد والمذكر في Dativ يأخذان dem: im Hotel، am Wochenende."
      },
      {
        "id": "a1-20-m5",
        "promptDe": "Richtung",
        "promptAr": "السهم ← يعني:",
        "options": [
          "rechts",
          "links",
          "geradeaus",
          "zurück"
        ],
        "correctIndex": 1,
        "explanationAr": "links = يسارًا. والأمر الرسمي يبدأ بالفعل ويختم بـSie: Nehmen Sie die Linie 4."
      }
    ]
  },
  {
    "id": "a1-21",
    "level": "A1",
    "module": 7,
    "titleDe": "Eine Reise",
    "titleAr": "رحلة",
    "questions": [
      {
        "id": "a1-21-m1",
        "promptDe": "von Berlin ___ Hamburg",
        "promptAr": "اختر:",
        "options": [
          "zu",
          "nach",
          "bei",
          "in"
        ],
        "correctIndex": 1,
        "explanationAr": "الوجهة مدينة: nach. نستعمل von لذكر نقطة الانطلاق وnach مع معظم أسماء المدن والبلدان دون أداة: von Berlin nach Hamburg، von Tunis nach München."
      },
      {
        "id": "a1-21-m2",
        "promptDe": "Ich ___ umsteigen.",
        "promptAr": "اختر:",
        "options": [
          "muss",
          "musst",
          "müssen",
          "müsse du"
        ],
        "correctIndex": 0,
        "explanationAr": "نفي muss هو muss nicht، ويعني انتفاء الضرورة لا المنع: Ich muss heute nicht arbeiten. أما المنع فبـ dürfen منفيًا: Hier darfst du nicht parken."
      },
      {
        "id": "a1-21-m3",
        "promptDe": "Du ___ eine Fahrkarte kaufen.",
        "promptAr": "اختر:",
        "options": [
          "muss",
          "müssen",
          "müsst",
          "musst"
        ],
        "correctIndex": 3,
        "explanationAr": "مع du تصبح müssen ← musst: Du musst umsteigen. وmüssen تنقل الإلزام، ويأتي المصدر في نهاية الجملة، ثم بقية التفاصيل مثل وسيلة النقل."
      },
      {
        "id": "a1-21-m4",
        "promptDe": "Hin- und Rückfahrt",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Hin- und Rückfahrt»:",
        "options": [
          "hin und zurück",
          "einfach",
          "nur Gleis",
          "ohne Ankunft"
        ],
        "correctIndex": 0,
        "explanationAr": "ذهاب وعودة. للذهاب وحده تقول hin؛ والعبارة كاملة على التذكرة: eine Fahrkarte hin und zurück."
      },
      {
        "id": "a1-21-m5",
        "promptDe": "Abfahrt",
        "promptAr": "ما المعنى؟",
        "options": [
          "الوصول",
          "الانطلاق",
          "الرصيف",
          "التأخير"
        ],
        "correctIndex": 1,
        "explanationAr": "Abfahrt = الانطلاق. عكسها Ankunft (الوصول)؛ وقس المواعيد على الجدول لا على الذاكرة."
      }
    ]
  },
  {
    "id": "a1-22",
    "level": "A1",
    "module": 8,
    "titleDe": "Mein Körper",
    "titleAr": "جسمي",
    "questions": [
      {
        "id": "a1-22-m1",
        "promptDe": "Mein Kopf ___ weh.",
        "promptAr": "اختر:",
        "options": [
          "tun",
          "tut",
          "sind",
          "hat"
        ],
        "correctIndex": 1,
        "explanationAr": "Kopf مفرد: tut. الفاعل هو Kopf، وهو مفرد، لذا يأتي الفعل مفردًا مثله: Mein Kopf tut weh."
      },
      {
        "id": "a1-22-m2",
        "promptDe": "Meine Beine ___ weh.",
        "promptAr": "اختر:",
        "options": [
          "tut",
          "ist",
          "habe",
          "tun"
        ],
        "correctIndex": 3,
        "explanationAr": "Beine جمع: tun. الخطأ الشائع إبقاء tut مع الجمع: „Meine Beine tut weh” غير صحيحة."
      },
      {
        "id": "a1-22-m3",
        "promptDe": "Kopf + Schmerzen",
        "promptAr": "اختر الكتابة:",
        "options": [
          "Kopf Schmerzen",
          "Kopf-schmerzene",
          "Kopfschmerzen",
          "Köpfe Schmerz"
        ],
        "correctIndex": 2,
        "explanationAr": "Kopfschmerzen كلمة مركبة. يمكن وصف أعراض كثيرة باستعمال haben: Ich habe Kopfschmerzen، Ich habe Bauchschmerzen، Ich habe Fieber."
      },
      {
        "id": "a1-22-m4",
        "promptDe": "Schwindel",
        "promptAr": "أي خيار يحقّق «Schwindel» في هذا السياق؟",
        "options": [
          "Ich habe schwindelig.",
          "Mir ist schwindelig.",
          "Mir tut Schwindel.",
          "Ich bin einen Schwindel."
        ],
        "correctIndex": 1,
        "explanationAr": "Mir ist schwindelig: المصاب يُذكر مجرورًا مع ist، لا فاعل مع haben أو tun. هذا النمط ثابت في وصف الأحوال مثل Mir ist kalt وMir ist schlecht."
      },
      {
        "id": "a1-22-m5",
        "promptDe": "Fieber",
        "promptAr": "اختر التعبير المطابق لـ«Fieber»:",
        "options": [
          "Ich habe Fieber.",
          "Ich bin Fieber.",
          "Mir tut Fieber weh.",
          "Fieber sind ich."
        ],
        "correctIndex": 0,
        "explanationAr": "Ich habe Fieber. يمكن وصف أعراض كثيرة باستعمال haben: Ich habe Kopfschmerzen، Ich habe Bauchschmerzen، Ich habe Fieber."
      }
    ]
  },
  {
    "id": "a1-23",
    "level": "A1",
    "module": 8,
    "titleDe": "Beim Arzt",
    "titleAr": "عند الطبيب",
    "questions": [
      {
        "id": "a1-23-m1",
        "promptDe": "___ zwei Tagen",
        "promptAr": "اختر:",
        "options": [
          "Vor",
          "Nach",
          "Bis",
          "Seit"
        ],
        "correctIndex": 3,
        "explanationAr": "مدة مستمرة: seit. نستعمل seit للتعبير عن بداية أو مدة مستمرة إلى الوقت الحالي: seit gestern، seit Montag، seit zwei Tagen."
      },
      {
        "id": "a1-23-m2",
        "promptDe": "Sie ___ viel trinken.",
        "promptAr": "اختر:",
        "options": [
          "sollen",
          "soll",
          "sollst",
          "sollt"
        ],
        "correctIndex": 0,
        "explanationAr": "Sie الرسمية: sollen. نستعمل sollen لنقل ما يُنصح به أو ما يطلبه شخص آخر: Sie sollen viel trinken."
      },
      {
        "id": "a1-23-m3",
        "promptDe": "Du ___ dich ausruhen.",
        "promptAr": "اختر:",
        "options": [
          "soll",
          "sollst",
          "sollen",
          "sollte Sie"
        ],
        "correctIndex": 1,
        "explanationAr": "du sollst. وsollen تنقل نصيحة أو طلبًا من غيرك: Sie sollen sich ausruhen."
      },
      {
        "id": "a1-23-m4",
        "promptDe": "Tabletten",
        "promptAr": "اختر ترتيبًا صحيحًا:",
        "options": [
          "Ich soll nehmen Tabletten.",
          "Ich Tabletten soll nehme.",
          "Nehmen ich soll.",
          "Ich soll Tabletten nehmen."
        ],
        "correctIndex": 3,
        "explanationAr": "المصدر في النهاية. ولنقل ما يُطلب من المريض نستعمل sollen: Er soll viel Wasser trinken."
      },
      {
        "id": "a1-23-m5",
        "promptDe": "Dauer fragen",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Dauer fragen»:",
        "options": [
          "Wie seit Sie?",
          "Wann seit haben?",
          "Wie lange Sie hat?",
          "Seit wann haben Sie das?"
        ],
        "correctIndex": 3,
        "explanationAr": "الترتيب الصحيح „Seit wann haben Sie das?“: أداة المدة في الموقع الأول، ثم الفعل haben، ثم الفاعل Sie الرسمي، ثم المفعول das؛ وهي صيغة السؤال عن بداية مرض مستمر."
      }
    ]
  },
  {
    "id": "a1-24",
    "level": "A1",
    "module": 8,
    "titleDe": "Formulare und Service",
    "titleAr": "النماذج والخدمات",
    "questions": [
      {
        "id": "a1-24-m1",
        "promptDe": "Familienname",
        "promptAr": "أي حقل؟",
        "options": [
          "Vorname",
          "Geburtsort",
          "Anschrift",
          "Nachname"
        ],
        "correctIndex": 3,
        "explanationAr": "حقول النماذج أسماء مركبة تُقرأ من الآخر إلى الأول: Geburtsdatum تاريخُ الميلاد وGeburtsort مكانُه، فلا تخلط بينهما. وفي الاستمارة يُكتب اللقب أولًا عادةً: Nachname, Vorname."
      },
      {
        "id": "a1-24-m2",
        "promptDe": "Ort der Geburt",
        "promptAr": "أي حقل؟",
        "options": [
          "Geburtsort",
          "Geburtsdatum",
          "Unterschrift",
          "Staatsangehörigkeit"
        ],
        "correctIndex": 0,
        "explanationAr": "Geburtsort. تطلب النماذج بيانات محددة: Vorname هو الاسم الأول، Nachname اللقب، Geburtsdatum تاريخ الميلاد، Geburtsort مدينة الميلاد، Anschrift العنوان، Unterschrift التوقيع."
      },
      {
        "id": "a1-24-m3",
        "promptDe": "ausfüllen",
        "promptAr": "اختر الأمر:",
        "options": [
          "Ausfüllen Sie Formular.",
          "Füllen aus das Sie.",
          "Füllen Sie das Formular aus.",
          "Sie Formular füllt aus."
        ],
        "correctIndex": 2,
        "explanationAr": "صيغة الأمر مع فعل منفصل. في الأمر الرسمي نقول Füllen Sie … aus وBringen Sie … mit."
      },
      {
        "id": "a1-24-m4",
        "promptDe": "Erklärung",
        "promptAr": "اطلب تفسيرًا:",
        "options": [
          "Was das bedeuten?",
          "Was bedeutet das?",
          "Wie Bedeutung ist?",
          "Das erklärt was?"
        ],
        "correctIndex": 1,
        "explanationAr": "Was bedeutet das? ترتيب صحيح: أداة الاستفهام Was ثم الفعل bedeutet ثم الفاعل das. لا يُقدَّم الفعل قبل الأداة، ولا تُفصل الأداة عن معناها بكلمة زائدة."
      },
      {
        "id": "a1-24-m5",
        "promptDe": "Unterschrift",
        "promptAr": "اختر التعليمة:",
        "options": [
          "Unterschreiben Sie hier.",
          "Sie hier Unterschrift.",
          "Unterschrift machen du.",
          "Hier Sie unterschreibt."
        ],
        "correctIndex": 0,
        "explanationAr": "الفعل ثم Sie ثم المكان. في الأمر الرسمي نقول Füllen Sie … aus وBringen Sie … mit."
      }
    ]
  }
] as const satisfies readonly LocalTestTemplateLesson[];
