/* Generated by scripts/generate-local-test-templates.ts; do not edit. */
import type { LocalTestTemplateLesson } from "@/core/training/local-test-generator";

export const localTestTemplateBankA2 = [
  {
    "id": "a2-01",
    "level": "A2",
    "module": 1,
    "titleDe": "Gestern",
    "titleAr": "أمس",
    "questions": [
      {
        "id": "a2-01-m1",
        "promptDe": "Ich ___ gearbeitet.",
        "promptAr": "اختر:",
        "options": [
          "habe",
          "bin",
          "ist",
          "werde"
        ],
        "correctIndex": 0,
        "explanationAr": "فعلُ arbeiten لا ينتقل ولا يُغيّر حالة، فيأخذ haben في الماضي: «habe». أمّا bin فأداةُ sein لانتقالٍ كالذهاب، و werde تبني المستقبل. فحص ذاتي: هل كان الحدثُ عملًا أم انتقالًا؟"
      },
      {
        "id": "a2-01-m2",
        "promptDe": "Sie ___ gekommen.",
        "promptAr": "اختر:",
        "options": [
          "hat",
          "ist",
          "wird",
          "habt"
        ],
        "correctIndex": 1,
        "explanationAr": "الفعل kommen انتقالٌ، وفي Perfekt يُسند إلى sein لا haben: «Sie ist gekommen». لذلك تُرفض hat و habt لأنّهما مع haben، أمّا wird فتبني Futur لا الماضي. فحص ذاتي: هل كان الحدثُ انتقالًا أو تغيّرَ حالة؟"
      },
      {
        "id": "a2-01-m3",
        "promptDe": "telefonieren",
        "promptAr": "اختر Partizip:",
        "options": [
          "getelefoniert",
          "telefonieren gehabt",
          "geteleft",
          "telefoniert"
        ],
        "correctIndex": 3,
        "explanationAr": "الأفعال على -ieren تأخذ Partizip II بلا ge-: telefonieren ⇒ telefoniert. ف «getelefoniert» تزيد ge-، و «telefonieren gehabt» تضيف فعلًا، و «geteleft» تُبدّل الجذر. فحص ذاتي: هل بدأتَ ge- بلا سبب؟"
      },
      {
        "id": "a2-01-m4",
        "promptDe": "einkaufen",
        "promptAr": "أي خيار يحقّق «einkaufen» في هذا السياق؟",
        "options": [
          "geeinkauft",
          "einkaufen",
          "eingekauft",
          "eingekaufen"
        ],
        "correctIndex": 2,
        "explanationAr": "الفعلُ einkaufen منفصلُ البادئة، والـPartizip II يحصر الجذر بين ein و ge-: «eingekauft». أمّا geeinkauft فتكرّر ge، و einkaufen تبقى مصدرًا، و eingekaufen تقلب الترتيب. فحص ذاتي: أين وقع الجذرُ بين ein و ge؟"
      },
      {
        "id": "a2-01-m5",
        "promptDe": "Wortstellung",
        "promptAr": "اختر التعبير المطابق ل «Wortstellung» في درس «أمس»:",
        "options": [
          "Ich gestern habe gelernt.",
          "Ich habe gestern gelernt.",
          "Ich habe gelernt gestern immer.",
          "Gestern ich habe gelernt."
        ],
        "correctIndex": 1,
        "explanationAr": "المساعد ثانيًا و Partizip أخيرًا. يُستعمل Perfekt كثيرًا في الحديث عن أحداث مكتملة."
      }
    ]
  },
  {
    "id": "a2-02",
    "level": "A2",
    "module": 1,
    "titleDe": "Eine Geschichte",
    "titleAr": "قصة",
    "questions": [
      {
        "id": "a2-02-m1",
        "promptDe": "anrufen",
        "promptAr": "اختر Partizip:",
        "options": [
          "angerufen",
          "geanrufen",
          "anruft",
          "angeruft"
        ],
        "correctIndex": 0,
        "explanationAr": "«anrufen» فعلٌ منفصل: في Partizip تدخل الـge بين الأُفّ والجذر: «an-ge-rufen». ف «geanrufen» تخطئ موضعَ ge، و «anruft» مضارعٌ لا Partizip، و «angeruft» تأخذ جذرَ المضارع ruft بدل gerufen. فحص ذاتي: أين تقع الـge؟"
      },
      {
        "id": "a2-02-m2",
        "promptDe": "Hintergrund",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Hintergrund»:",
        "options": [
          "Ich bin müde gehabt.",
          "Ich war müde.",
          "Ich habe müde.",
          "Ich gewesen müde."
        ],
        "correctIndex": 1,
        "explanationAr": "الحالةُ في الماضي تُروى ب Präteritum لا ب Perfekt: «Ich war müde.». وأمّا «Ich habe müde.» و «Ich bin müde gehabt.» فيبنيان Perfekt مع صفةٍ لا مع فعل. فحص ذاتي: هل وصفتَ حالةً أم حدثًا؟"
      },
      {
        "id": "a2-02-m3",
        "promptDe": "Überraschung",
        "promptAr": "أي رابط؟",
        "options": [
          "Zuerst",
          "Plötzlich",
          "Am Ende",
          "Seitdem"
        ],
        "correctIndex": 1,
        "explanationAr": "رابطُ المفاجأة في سرد الماضي هو «Plötzlich»: يقطع التوقّع فجأة. أمّا Zuerst فيفتح تسلسلًا عاديًّا، و Am Ende يختم السرد، و Seitdem يربط بدايةً بمدةٍ ممتدة. فحص ذاتي: هل جاء الحدثُ مفاجئًا؟"
      },
      {
        "id": "a2-02-m4",
        "promptDe": "mitnehmen",
        "promptAr": "أي خيار يحقّق «mitnehmen» في هذا السياق؟",
        "options": [
          "mitgenommen",
          "gemitnimmt",
          "mitgenehmt",
          "genommenmit"
        ],
        "correctIndex": 0,
        "explanationAr": "mitnehmen فعلٌ منفصل، وفي Partizip II تُدمج البادئة مع الجذر: «mitgenommen». و «gemitnimmt» تُبدّل الجذرَ نفسه، و «mitgenehmt» تُخطئ في حرفه، أمّا «genommenmit» فيُبقي البادئةَ مفصولة. فحص ذاتي: أين استقرّت ge-؟"
      },
      {
        "id": "a2-02-m5",
        "promptDe": "Wortstellung",
        "promptAr": "اختر التعبير المطابق ل «Wortstellung» في درس «قصة»:",
        "options": [
          "Plötzlich die Tasche war weg.",
          "Plötzlich war die Tasche weg.",
          "Die Tasche plötzlich weg war.",
          "War plötzlich weg Tasche."
        ],
        "correctIndex": 1,
        "explanationAr": "بعد رابط المفاجأة يأتي الفعلُ المصرَّف ثم الفاعل: «Plötzlich war die Tasche weg». فتقديمُ die Tasche أو حشرُها بعد war يكسر ترتيب الجملة الألمانية؛ فحص ذاتي: ما موضع الفعل بعد Plötzlich؟"
      }
    ]
  },
  {
    "id": "a2-03",
    "level": "A2",
    "module": 1,
    "titleDe": "Besondere Momente",
    "titleAr": "لحظات مميزة",
    "questions": [
      {
        "id": "a2-03-m1",
        "promptDe": "___ ich angekommen bin, war es spät.",
        "promptAr": "اختر:",
        "options": [
          "Wenn immer",
          "Deshalb",
          "Als",
          "Seit"
        ],
        "correctIndex": 2,
        "explanationAr": "الحدثُ الفريد في الماضي يُربط ب als وحده: «ich angekommen bin, war es spät» بعد الفراغ. أمّا Wenn فللتكرار أو الشرط، و Deshalb و Seit لا تربطان حدثين متتاليين. فحص ذاتي: حدثٌ مرةً واحدة أم عادة؟"
      },
      {
        "id": "a2-03-m2",
        "promptDe": "Nebensatz",
        "promptAr": "اختر الترتيب:",
        "options": [
          "weil ich kannte den Weg nicht",
          "weil kannte ich nicht",
          "weil den Weg ich kannte nicht",
          "weil ich den Weg nicht kannte"
        ],
        "correctIndex": 3,
        "explanationAr": "في جملة السبب ب weil ينتقل الفعلُ المصرَّف إلى النهاية: «weil ich den Weg nicht kannte». فالترتيب المباشر يقلب الجملة، وحشوُ الفاعل بين den Weg و kannte يكسر القاعدة؛ فحص ذاتي: أين وقف الفعلُ في جملتك؟"
      },
      {
        "id": "a2-03-m3",
        "promptDe": "Folge",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Folge»:",
        "options": [
          "Deshalb habe ich Hilfe gesucht.",
          "Deshalb ich habe Hilfe gesucht.",
          "Deshalb Hilfe ich gesucht.",
          "Ich deshalb Hilfe habe."
        ],
        "correctIndex": 0,
        "explanationAr": "بعد الرابط «Deshalb» يأتي الفعلُ المصرَّف فورًا: «Deshalb habe ich Hilfe gesucht». فالفاعلُ لا يسبق الفعلَ هنا، وإذا سبقه صار الترتيب نقلًا حرفيًّا من العربية؛ فحص ذاتي: هل سبق الفاعلُ الفعلَ بعد الرابط؟"
      },
      {
        "id": "a2-03-m4",
        "promptDe": "sich erinnern",
        "promptAr": "مع ich:",
        "options": [
          "Ich erinnere mir.",
          "Ich erinnere mich.",
          "Ich erinnere sich.",
          "Ich mich erinnere im Hauptsatz."
        ],
        "correctIndex": 1,
        "explanationAr": "erinnern فعلٌ منعكس، ومع ich يكون الضمير mich: «Ich erinnere mich an den Termin». mir تعني «لي» فتقلب المعنى، و sich مع غائب، وتقديمُ mich على الفعل لا يليق بالجملة الرئيسية. فحص ذاتي: هل رجع الضميرُ إلى ich؟"
      },
      {
        "id": "a2-03-m5",
        "promptDe": "Gefühl",
        "promptAr": "اختر جملة الفرح بالماضي:",
        "options": [
          "Ich bin mich gefreut.",
          "Ich habe mir freuen.",
          "Ich habe mich gefreut.",
          "Ich freue gewesen."
        ],
        "correctIndex": 2,
        "explanationAr": "sich freuen في Perfekt مع haben. نستعمل als مع حدث واحد أو مرحلة ماضية نراها كوحدة: Als ich angekommen bin، Als ich zehn Jahre alt war."
      }
    ]
  },
  {
    "id": "a2-04",
    "level": "A2",
    "module": 2,
    "titleDe": "Neue Nachbarn",
    "titleAr": "جيران جدد",
    "questions": [
      {
        "id": "a2-04-m1",
        "promptDe": "helfen + ich",
        "promptAr": "أي خيار يحقّق «helfen + ich» في هذا السياق؟",
        "options": [
          "mich",
          "mein",
          "mir",
          "ich"
        ],
        "correctIndex": 2,
        "explanationAr": "الفعلُ helfen يطلب Dativ فيكون المفعولُ «mir» لا mich ولا ich ولا mein. وهذا ما يفسّر عنوان التمرين helfen + ich: تُصرَّف الضميرةُ في الحالة التي يفتحها الفعل. فحص ذاتي: أيّ حالةٍ يطلبها فعلك؟"
      },
      {
        "id": "a2-04-m2",
        "promptDe": "helfen + du",
        "promptAr": "اختر التعبير المطابق ل «helfen + du»:",
        "options": [
          "dich",
          "dir",
          "dein",
          "du"
        ],
        "correctIndex": 1,
        "explanationAr": "الفعل «helfen» يطلبُ Dativ كما في الحوار: «Kann ich Ihnen mit den Kisten helfen?». ف «dich» Akkusativ، و «dein» صفةُ ملكٍ لا ضميرُ حالة، و «du» رفعٌ لا يلي الفعلَ مباشرةً. فحص ذاتي: أيّ حالةٍ يطلبُ helfen؟"
      },
      {
        "id": "a2-04-m3",
        "promptDe": "geben",
        "promptAr": "اختر الصيغة الصحيحة لحالة «geben»:",
        "options": [
          "Ich gebe dich den Schlüssel.",
          "Ich gebe du der Schlüssel.",
          "Ich dir gebe dem Schlüssel.",
          "Ich gebe dir den Schlüssel."
        ],
        "correctIndex": 3,
        "explanationAr": "الفعل geben يأخذ مفعولين بحالتين: الشخص في Dativ والشيء في Akkusativ، فتصير «Ich gebe dir den Schlüssel». وأمّا dich و du فلا تصلحان للشخص هنا؛ فحص ذاتي: أيّ ضميرٍ لمَن يأخذ الشيء؟"
      },
      {
        "id": "a2-04-m4",
        "promptDe": "wenn",
        "promptAr": "اختر الترتيب:",
        "options": [
          "Wenn du Zeit hast, hilfst du mir.",
          "Wenn du hast Zeit, du hilfst.",
          "Wenn Zeit du, hilfst hast.",
          "Wenn du Zeit, mir helfen."
        ],
        "correctIndex": 0,
        "explanationAr": "في جملة wenn ينتقل الفعلُ المصرَّف إلى آخر الجزء الأوّل: «Wenn du Zeit hast». ثم يبدأ الجوابُ بالفعل: «hilfst du mir»؛ فحص ذاتي: أين وقف الفعلُ في كل نصفٍ من الجملة؟"
      },
      {
        "id": "a2-04-m5",
        "promptDe": "Richtige formelle Form",
        "promptAr": "اختر صيغة المخاطبة الرسمية الصحيحة:",
        "options": [
          "Kann ich ihnen mit dem Paket helfen?",
          "Kann Ihnen ich helfen?",
          "Kann ich Sie helfen?",
          "Kann ich Ihnen helfen?"
        ],
        "correctIndex": 3,
        "explanationAr": "المخاطبة الرسمية «Ihnen» تُكتب بحرف كبير، والعبارة الصحيحة هي «Kann ich Ihnen helfen?». أمّا «ihnen» بحرف صغير فتعني لهم/لهن، و «Sie» هنا مفعول غير مناسب للفعل helfen؛ فحص ذاتي: هل تخاطب الشخص رسميًا أم تتحدث عنهم؟"
      }
    ]
  },
  {
    "id": "a2-05",
    "level": "A2",
    "module": 2,
    "titleDe": "Regeln im Haus",
    "titleAr": "قواعد المنزل",
    "questions": [
      {
        "id": "a2-05-m1",
        "promptDe": "Pflicht",
        "promptAr": "أي خيار يحقّق «Pflicht» في هذا السياق؟",
        "options": [
          "Man darf den Müll trennen.",
          "Man muss den Müll trennen.",
          "Man will Müll.",
          "Man kann nicht müssen."
        ],
        "correctIndex": 1,
        "explanationAr": "الواجبُ في نظام المبنى بصيغة müssen: «Den Müll muss man in vier Tonnen trennen». أمّا darf فتُبيح ولا تلزم، و will تُبدي رغبةً فقط. فحص ذاتي: هل فرّقتَ بين الإلزام والإباحة؟"
      },
      {
        "id": "a2-05-m2",
        "promptDe": "Verbot",
        "promptAr": "اختر التعبير المطابق ل «Verbot»:",
        "options": [
          "Man muss nicht rauchen.",
          "Man kann rauchen.",
          "Man möchte nicht Regel.",
          "Man darf nicht rauchen."
        ],
        "correctIndex": 3,
        "explanationAr": "المنعُ يُصاغ ب dürfen مع nicht: «Man darf nicht rauchen.». وأمّا «Man muss nicht rauchen.» فتعني أنّ التدخين غيرُ مطلوب (إباحة)، و «Man kann rauchen.» تُبيحه صراحةً. فحص ذاتي: هل منعتَ أم أبيحتَ؟"
      },
      {
        "id": "a2-05-m3",
        "promptDe": "man",
        "promptAr": "اختر التصريف:",
        "options": [
          "man muss",
          "man müssen",
          "man müsst",
          "man musst"
        ],
        "correctIndex": 0,
        "explanationAr": "man ضميرٌ مفردٌ محايد، فيأخذ تصريف المفرد الغائب: «man muss» في قاعدةِ المبنى. أمّا müssen فجمعٌ، و müsst تخصّ ihr، و musst تخصّ du — ولا واحدٌ منها يصلح بعد man. فحص ذاتي: مَن الفاعلُ في الجملة؟"
      },
      {
        "id": "a2-05-m4",
        "promptDe": "Erlaubnis",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Erlaubnis»:",
        "options": [
          "Man muss nicht Garten.",
          "Man darf den Garten benutzen.",
          "Man dürfen Garten.",
          "Garten erlaubt man darf ist."
        ],
        "correctIndex": 1,
        "explanationAr": "الإباحةُ بـ dürfen: «Man darf den Garten benutzen» حتى الواحدة والعشرين مساءً. أمّا muss فتُلزم، و «Man dürfen Garten» يخالف تصريفَ المفرد. فحص ذاتي: هل أبحتَ أم ألزمتَ؟"
      },
      {
        "id": "a2-05-m5",
        "promptDe": "Höfliche Bitte",
        "promptAr": "أي خيار يحقّق «Höfliche Bitte» في هذا السياق؟",
        "options": [
          "Sei leise!",
          "Du immer laut.",
          "Könnten Sie die Musik bitte leiser machen?",
          "Musik aus jetzt."
        ],
        "correctIndex": 2,
        "explanationAr": "الطلبُ المهذّب مع الاحترام في Konjunktiv II: «Könnten Sie die Musik bitte leiser machen?». أمّا «Sei leise!» فأمرٌ مباشر غير رسمي، و «Musik aus jetzt» بلا تصريف. فحص ذاتي: هل بقي الأسلوبُ لاطفًا؟"
      }
    ]
  },
  {
    "id": "a2-06",
    "level": "A2",
    "module": 2,
    "titleDe": "Zusammen leben",
    "titleAr": "العيش معًا",
    "questions": [
      {
        "id": "a2-06-m1",
        "promptDe": "Höfliche Bitte",
        "promptAr": "اختر التعبير المطابق ل «Höfliche Bitte»:",
        "options": [
          "Räum sofort auf!",
          "Du aufräumen jetzt.",
          "Können du räumt?",
          "Könntest du bitte aufräumen?"
        ],
        "correctIndex": 3,
        "explanationAr": "الطلبُ المهذّب يبدأ ب «Könntest du bitte aufräumen?» فيبقى الفعلُ في النهاية. وأمّا «Räum sofort auf!» فأمرٌ جافّ، و «Können du räumt?» و «Du aufräumen jetzt.» فجملتان مكسورتان. فحص ذاتي: هل بقي طلبُك مؤدّبًا؟"
      },
      {
        "id": "a2-06-m2",
        "promptDe": "wenn",
        "promptAr": "اختر الصيغة الصحيحة لحالة «wenn»:",
        "options": [
          "Wenn jeder mithilft, sind wir fertig.",
          "Wenn jeder hilft mit, wir sind.",
          "Wenn mithilft jeder, wir fertig.",
          "Wenn jeder mithelfen, sind."
        ],
        "correctIndex": 0,
        "explanationAr": "الفعلُ المنفصل في جملة wenn يجتمع في نهايتها: «Wenn jeder mithilft». وبعدها يبدأ الشقُّ الآخر بالفعل «sind wir fertig»؛ فحص ذاتي: هل رجعت البادئةُ إلى آخر الفعل المنفصل؟"
      },
      {
        "id": "a2-06-m3",
        "promptDe": "obwohl",
        "promptAr": "أي خيار يحقّق «obwohl» في سياق درس «العيش معًا»؟",
        "options": [
          "Obwohl er ist müde, er räumt.",
          "Obwohl müde, auf er räumt.",
          "Obwohl er müde, ist räumt.",
          "Obwohl er müde ist, räumt er auf."
        ],
        "correctIndex": 3,
        "explanationAr": "الفعل في النهاية ثم فعل الجملة الرئيسية. تقدم obwohl معلومة تجعل النتيجة غير متوقعة: Obwohl Jonas spät arbeitet, übernimmt er eine Aufgabe."
      },
      {
        "id": "a2-06-m4",
        "promptDe": "Zustimmung",
        "promptAr": "اختر الموافقة:",
        "options": [
          "Das stört ich.",
          "Keine Lösung bin.",
          "Kompromiss nicht passt alle.",
          "Damit bin ich einverstanden."
        ],
        "correctIndex": 3,
        "explanationAr": "الموافقةُ على حلٍّ وسط جملةٌ كاملة: «Damit bin ich einverstanden.». وأمّا «Das stört ich.» و «Kompromiss nicht passt alle.» فبلا فاعلٍ صحيح وبترتيبٍ عربيٍّ بالكلمات الألمانية. فحص ذاتي: هل جملتُك مبنيّة؟"
      },
      {
        "id": "a2-06-m5",
        "promptDe": "abwechselnd",
        "promptAr": "المعنى:",
        "options": [
          "معًا دائمًا",
          "فورًا",
          "بالتناوب",
          "سرًا"
        ],
        "correctIndex": 2,
        "explanationAr": "المعنى المطلوب هو توزيع الدور لا المصاحبة الدائمة: «بالتناوب». وخطةُ الشقة المشتركة في النصّ تعتمد عليه في إخراج النفايات؛ فحص ذاتي: هل يوزّع abwechselnd المهمةَ أم يجمعها؟"
      }
    ]
  },
  {
    "id": "a2-07",
    "level": "A2",
    "module": 3,
    "titleDe": "Mein Arbeitsplatz",
    "titleAr": "مكان عملي",
    "questions": [
      {
        "id": "a2-07-m1",
        "promptDe": "zuständig ___",
        "promptAr": "اختر:",
        "options": [
          "um",
          "mit",
          "für",
          "an"
        ],
        "correctIndex": 2,
        "explanationAr": "الصفةُ zuständig تأتي مع für: «Mara ist für neue Kundenanfragen zuständig». فلا يُستعمل معها um ولا mit ولا an؛ ومع um ينتقل المعنى إلى sich kümmern. فحص ذاتي: مع أيّ حرفِ جرٍّ حفظتَها؟"
      },
      {
        "id": "a2-07-m2",
        "promptDe": "Ich kümmere ___ um Termine.",
        "promptAr": "اختر:",
        "options": [
          "mir",
          "mich",
          "sich",
          "mein"
        ],
        "correctIndex": 1,
        "explanationAr": "sich kümmern يأخذ mich مع ich: «Ich kümmere mich um Termine». mir تُفيد «لي» لا الرجوع، و mein يُضاف إلى اسمٍ بعده، و sich للغيبة — فتبقى العبارةُ سليمةَ اللفظ مقلوبةَ المعنى. فحص ذاتي: هل الفعلُ عنك أنت؟"
      },
      {
        "id": "a2-07-m3",
        "promptDe": "wenn",
        "promptAr": "اختر التعبير المطابق ل «wenn»:",
        "options": [
          "Wenn ein Kunde ruft an, ich notiere.",
          "Wenn anruft ein Kunde, ich notiere.",
          "Wenn Kunde anrufen, notiere.",
          "Wenn ein Kunde anruft, notiere ich den Namen."
        ],
        "correctIndex": 3,
        "explanationAr": "في جملة wenn ينتقل الفعلُ المصرَّف إلى نهايتها: «Wenn ein Kunde anruft». والشقُّ الآخر يبدأ بالفعل «notiere ich den Namen»؛ فحص ذاتي: أين وقف anrufen في جملتك أنت؟"
      },
      {
        "id": "a2-07-m4",
        "promptDe": "dafür",
        "promptAr": "اختر الصيغة الصحيحة لحالة «dafür»:",
        "options": [
          "Dafür ist Mara zuständig.",
          "Dafür Mara zuständig ist.",
          "Mara dafür zuständig.",
          "Ist dafür zuständig Mara?"
        ],
        "correctIndex": 0,
        "explanationAr": "الرابط «Dafür» يفتح الجملة فيأتي بعده الفعلُ المصرَّف: «Dafür ist Mara zuständig». وإذا تأخّر الفعلُ أو حُذف صار الترتيب عربيًّا بمفردات ألمانية؛ فحص ذاتي: ما موضع ist في جملتك؟"
      },
      {
        "id": "a2-07-m5",
        "promptDe": "Aufgabe",
        "promptAr": "اختر التركيب:",
        "options": [
          "Kunden antworten Anfrage machen",
          "Kundenanfragen beantworten",
          "Anfragen Kunden ist",
          "beantworten für Kundenanfrage"
        ],
        "correctIndex": 1,
        "explanationAr": "التركيبُ الألماني يجمع الاسمَ في مركّب واحد ثم يأتي بالفعل: «Kundenanfragen beantworten». ف «Kunden antworten Anfrage machen» تكرّر فعلين بلا مركّب. فحص ذاتي: هل نسخت تركيبَ الألمان؟"
      }
    ]
  },
  {
    "id": "a2-08",
    "level": "A2",
    "module": 3,
    "titleDe": "Eine Bewerbung",
    "titleAr": "طلب عمل",
    "questions": [
      {
        "id": "a2-08-m1",
        "promptDe": "dass",
        "promptAr": "أي خيار يحقّق «dass» في سياق درس «طلب عمل»؟",
        "options": [
          "dass passt die Stelle gut",
          "dass gut die Stelle passt sie",
          "dass die Stelle gut passt",
          "dass die Stelle passen"
        ],
        "correctIndex": 2,
        "explanationAr": "بعد «dass» يبقى الفعلُ في النهاية: «dass die Stelle gut passt». ف «dass gut die Stelle passt sie» خطأ، و «dass die Stelle passen» فقدت «sie»، و «passt sie» فعلانِ متجاوران. فحص ذاتي: أين فعلُ الجملة الفرعية؟"
      },
      {
        "id": "a2-08-m2",
        "promptDe": "sich interessieren",
        "promptAr": "اختر الحرف:",
        "options": [
          "an",
          "für",
          "um",
          "mit"
        ],
        "correctIndex": 1,
        "explanationAr": "الفعل sich interessieren يطلب حرف الجرّ «für»: ich interessiere mich für Deutsch. وأمّا an و um و mit فلا يفتحها هذا الفعل بهذا المعنى؛ فحص ذاتي: أيّ حرفٍ يحفظه المعجم مع هذا الفعل؟"
      },
      {
        "id": "a2-08-m3",
        "promptDe": "weil",
        "promptAr": "اختر التعبير المطابق ل «weil»:",
        "options": [
          "weil ich Erfahrung habe",
          "weil ich habe Erfahrung",
          "weil Erfahrung ich habe es",
          "weil habe ich Erfahrung"
        ],
        "correctIndex": 0,
        "explanationAr": "«weil» جملةُ سببٍ فيختتم الفعلُ: «weil ich Erfahrung habe». ف «weil ich habe Erfahrung» ترتيبُ الاستقلال، و «weil habe ich» انعكاسٌ، و «weil Erfahrung ich habe es» على غير مَحَلٍّ. فحص ذاتي: أين الفعلُ بعدَ weil؟"
      },
      {
        "id": "a2-08-m4",
        "promptDe": "Formeller Gruß",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Formeller Gruß»:",
        "options": [
          "Tschüs",
          "Bis später",
          "Hallo Leute",
          "Mit freundlichen Grüßen"
        ],
        "correctIndex": 3,
        "explanationAr": "«Mit freundlichen Grüßen» خاتمةٌ رسمية للرسالة المهنية، أمّا Tschüs و Hallo Leute فودّيتانِ لا تُناسبانِ طلبًا أو بلاغًا، و «Bis später» تُستعمل لموعدٍ متَّفق عليه. فحص ذاتي: هل كان السياقُ رسميًا؟"
      },
      {
        "id": "a2-08-m5",
        "promptDe": "Bewerbungsunterlagen",
        "promptAr": "أي خيار يحقّق «Bewerbungsunterlagen» في هذا السياق؟",
        "options": [
          "Anschreiben und Lebenslauf",
          "Fahrkarte und Passfoto",
          "Mietvertrag",
          "Speisekarte"
        ],
        "correctIndex": 0,
        "explanationAr": "رسالة تقديم وسيرة حسب الإعلان: Anschreiben und Lebenslauf هما جوهر ملف التقديم. الصورة تُطلب أحيانًا، أما عقد السكن أو تذكرة السفر فليستا من الملف."
      }
    ]
  },
  {
    "id": "a2-09",
    "level": "A2",
    "module": 3,
    "titleDe": "Am Telefon",
    "titleAr": "على الهاتف",
    "questions": [
      {
        "id": "a2-09-m1",
        "promptDe": "Indirekte Frage",
        "promptAr": "اختر التعبير المطابق ل «Indirekte Frage»:",
        "options": [
          "ob ist Frau Keller da",
          "wenn Frau Keller ist da",
          "ob Frau Keller ist da sie",
          "ob Frau Keller da ist"
        ],
        "correctIndex": 3,
        "explanationAr": "السؤالُ غيرُ المباشرِ ب «ob»: الفعلُ في النهاية: «ob Frau Keller da ist». ف «ob ist Frau Keller da» سؤالٌ مباشر، و «wenn» لا تصلحُ هنا، و «ob Frau Keller ist da sie» تُقحم ضميرًا زائدًا. فحص ذاتي: أين فعلُ ob؟"
      },
      {
        "id": "a2-09-m2",
        "promptDe": "Telefonische Vorstellung",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Telefonische Vorstellung»:",
        "options": [
          "Hier spricht Sami Mansour.",
          "Ich hier bin Sami.",
          "Sami spricht mich.",
          "Wer bin Telefon Sami."
        ],
        "correctIndex": 0,
        "explanationAr": "التعريفُ على الهاتف كما في المكالمة: «Hier spricht Nabil Osman von der Firma Meditex». أمّا «Ich hier bin Sami» فيُقدّم الظرفَ على الضمير، و «Sami spricht mich» يقلب المعنى. فحص ذاتي: هل الترتيبُ ألماني؟"
      },
      {
        "id": "a2-09-m3",
        "promptDe": "Rückruf mit sollen",
        "promptAr": "أي خيار يحقّق «Rückruf mit sollen» في هذا السياق؟",
        "options": [
          "Sie soll ruft zurück.",
          "Sie zurück soll rufen.",
          "Sie soll zurückrufen.",
          "Zurück sie rufen sollt."
        ],
        "correctIndex": 2,
        "explanationAr": "الطلبُ المنقول بـ sollen يُبقي المصدرَ في النهاية: «Sie soll zurückrufen.». ف «Sie soll ruft zurück.» تصرّف الفعلَ بعد sollen فيصير فعلين. فحص ذاتي: كم فعلًا صرّفتَ؟"
      },
      {
        "id": "a2-09-m4",
        "promptDe": "Gespräch beenden",
        "promptAr": "اختر التعبير المطابق ل «Gespräch beenden»:",
        "options": [
          "Auf Wiedersehen im Telefon.",
          "Tschau Leute Firma.",
          "Ende jetzt.",
          "Auf Wiederhören."
        ],
        "correctIndex": 3,
        "explanationAr": "في المكالمة تُختم ب «Auf Wiederhören» لأنها تُسمع لا تُرى، و «Auf Wiedersehen» عند اللقاء الحضوري. وصيغٌ مثل «Ende jetzt» ليست ألمانية؛ فحص ذاتي: هل تُنهي مكالمةً أم لقاءً؟"
      },
      {
        "id": "a2-09-m5",
        "promptDe": "Es geht ___ meine Bestellung.",
        "promptAr": "اختر:",
        "options": [
          "für",
          "mit",
          "um",
          "nach"
        ],
        "correctIndex": 2,
        "explanationAr": "العبارةُ الثابتة es geht um تعني «الموضوع هو»: «Es geht um meine Bestellung». für و mit و nach تنقل المعنى إلى غايةٍ أو مشاركةٍ أو زمان، فلا يبقى «المقصودُ هذا الشيء». فحص ذاتي: عن أيّ شيءٍ تتحدّث؟"
      }
    ]
  },
  {
    "id": "a2-10",
    "level": "A2",
    "module": 4,
    "titleDe": "Reiseplanung",
    "titleAr": "تخطيط السفر",
    "questions": [
      {
        "id": "a2-10-m1",
        "promptDe": "Komparativ",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Komparativ»:",
        "options": [
          "schneller wie",
          "so schneller als",
          "am schnell als",
          "schneller als"
        ],
        "correctIndex": 3,
        "explanationAr": "صيغةُ التفضيل تُلحق -er بالصفة ثم تأتي als: «Diese Verbindung ist schneller als die Bahn». so … wie للمساواة، و «am schnell als» تركّب صيغةَ التفوّق على مقارنة. فحص ذاتي: هل بعد -er جاءت als؟"
      },
      {
        "id": "a2-10-m2",
        "promptDe": "Gleichheit",
        "promptAr": "أي خيار يحقّق «Gleichheit» في هذا السياق؟",
        "options": [
          "so günstig wie",
          "günstiger wie",
          "so günstiger als",
          "am günstig wie"
        ],
        "correctIndex": 0,
        "explanationAr": "المساواةُ بـ so + الصفة كما هي + wie: «Diese Verbindung ist so günstig wie die andere». أمّا -er فتقارن وتحتاج als، و «günstiger wie» تُدخل أداةَ المساواة على مقارنة. فحص ذاتي: أيّ أداتين التقيتا؟"
      },
      {
        "id": "a2-10-m3",
        "promptDe": "gut",
        "promptAr": "صيغة المقارنة:",
        "options": [
          "guter",
          "mehr gut",
          "besser",
          "günstiger"
        ],
        "correctIndex": 2,
        "explanationAr": "لصفة gut مقارنةٌ شاذّة: besser، ثم am besten في التفضيل الأقصى. و «guter» تُطبّق اللاحقةَ المنتظمة على صفةٍ لا تقبلها، و «mehr gut» ترجمةٌ حرفية، و günstiger صفةٌ أخرى لا شكلٌ لـ gut. فحص ذاتي: هل تذكّرتَ الشذوذ؟"
      },
      {
        "id": "a2-10-m4",
        "promptDe": "Superlativ günstig",
        "promptAr": "اختر التعبير المطابق ل «Superlativ günstig»:",
        "options": [
          "am günstiger",
          "der mehr günstig",
          "so günstigsten",
          "am günstigsten"
        ],
        "correctIndex": 3,
        "explanationAr": "الأقصى في المقارنة بصيغة am …sten: «am günstigsten». ف «am günstiger» تخلط الدرجتين، و «der mehr günstig» ترجمةٌ حرفية، و «so günstigsten» للمساواة. فحص ذاتي: أيّ درجتين التقيتَ؟"
      },
      {
        "id": "a2-10-m5",
        "promptDe": "kurz",
        "promptAr": "اختر Komparativ:",
        "options": [
          "kurzer",
          "mehr kurz",
          "kürzer",
          "am kurz"
        ],
        "correctIndex": 2,
        "explanationAr": "الصفةُ قصيرةُ المقطع تُعتلّ مع اللاحقة: kurz ⇒ kürzer. ف «kurzer» تنسى الاعتلال، و «mehr kurz» ترجمةٌ حرفية، و «am kurz» تُبقي الأصلَ حيث تُطلب المقارنة. فحص ذاتي: هل تحرّك حرفُ العلّة؟"
      }
    ]
  },
  {
    "id": "a2-11",
    "level": "A2",
    "module": 4,
    "titleDe": "Unterkunft",
    "titleAr": "الإقامة",
    "questions": [
      {
        "id": "a2-11-m1",
        "promptDe": "Höflich buchen",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Höflich buchen»:",
        "options": [
          "Ich will Zimmer.",
          "Buchen du mir.",
          "Ich bin Buchung.",
          "Ich würde gern buchen."
        ],
        "correctIndex": 3,
        "explanationAr": "لطلبٍ مهذَّبٍ: «würde gern» + المصدر: «Ich würde gern buchen». ف «Ich will Zimmer» جَفاءٌ وكلمةٌ ناقصة، و «Buchen du mir» أمرٌ بلا ترتيب، و «Ich bin Buchung» خلطٌ بين «bin» واسم. فحص ذاتي: أيّ صيغةٍ تلطّفُ الطلبَ؟"
      },
      {
        "id": "a2-11-m2",
        "promptDe": "wir",
        "promptAr": "أي خيار يحقّق «wir» في هذا السياق؟",
        "options": [
          "wir würden",
          "wir würde",
          "wir wurdet",
          "wir würden gern bleibt"
        ],
        "correctIndex": 0,
        "explanationAr": "صيغةُ التمنّي تُصرَّف مع الفاعل: wir würden. و «wir würde» تُبقي صيغةَ المفرد، و «wir wurdet» تخلط الماضي بالافتراض. الفكرةُ مجاملةٌ مشروطة: würde ثم المصدر في الآخر. فحص ذاتي: هل انفرد المصدر بالنهاية؟"
      },
      {
        "id": "a2-11-m3",
        "promptDe": "ob",
        "promptAr": "اختر التعبير المطابق ل «ob»:",
        "options": [
          "ob ist Frühstück inklusive",
          "ob Frühstück ist inklusive es",
          "ob inklusive Frühstück",
          "ob Frühstück inklusive ist"
        ],
        "correctIndex": 3,
        "explanationAr": "بعد «ob» يختتمُ الفعلُ: «ob Frühstück inklusive ist». ف «ob ist Frühstück inklusive» سؤالٌ مباشر، و «Frühstück ist inklusive es» ضميرٌ زائد، و «ob inklusive Frühstück» بلا فعلٍ أصلًا. فحص ذاتي: أين يقع الفعلُ؟"
      },
      {
        "id": "a2-11-m4",
        "promptDe": "inklusive",
        "promptAr": "المعنى:",
        "options": [
          "إضافي",
          "ملغى",
          "مشمول",
          "بعيد"
        ],
        "correctIndex": 2,
        "explanationAr": "الكلمةُ «inklusive» تُدرج الخدمةَ في السعر المعلن، فلا يُطلب مبلغٌ إضافي عند الوصول، ولا تعني إلغاءً للحجز ولا بُعدًا للمكان. فحص ذاتي: هل زاد المبلغ أم ابتلع الخدمة؟"
      },
      {
        "id": "a2-11-m5",
        "promptDe": "Storno",
        "promptAr": "اختر السؤال:",
        "options": [
          "Kann kostenlos man storniert?",
          "Kann man kostenlos stornieren?",
          "Ist Storno wie?",
          "Stornieren kostet wo?"
        ],
        "correctIndex": 1,
        "explanationAr": "السؤالُ يبدأ ب «Kann man» ويُختم بالمصدر: «Kann man kostenlos stornieren?». و «Storno wie?» بلا فعلٍ مصرَّف، و «Kann kostenlos man storniert?» يخلط موضع الفعل؛ فحص ذاتي: أين وقف فعلك؟"
      }
    ]
  },
  {
    "id": "a2-12",
    "level": "A2",
    "module": 4,
    "titleDe": "Wenn etwas schiefgeht",
    "titleAr": "عندما تحدث مشكلة",
    "questions": [
      {
        "id": "a2-12-m1",
        "promptDe": "Sachliche Reklamation",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Sachliche Reklamation»:",
        "options": [
          "Alles ist furchtbar!",
          "Sie machen immer Fehler!",
          "Geld jetzt!",
          "Es gibt ein Problem mit meinem Zimmer."
        ],
        "correctIndex": 3,
        "explanationAr": "الشكوى الموضوعية تُسمّي المشكلة: «Es gibt ein Problem mit meinem Zimmer». أمّا «Alles ist furchtbar!» فحكمٌ عامٌّ، و «Geld jetzt!» أمرٌ جافّ بلا توضيح. فحص ذاتي: هل وصفتَ الوقائع لا الانفعال؟"
      },
      {
        "id": "a2-12-m2",
        "promptDe": "obwohl",
        "promptAr": "أي خيار يحقّق «obwohl» في سياق درس «عندما تحدث مشكلة»؟",
        "options": [
          "Obwohl ich reserviert habe, ist kein Zimmer frei.",
          "Obwohl ich habe reserviert, kein Zimmer.",
          "Obwohl reserviert ich, ist frei nicht.",
          "Ich obwohl habe reserviert."
        ],
        "correctIndex": 0,
        "explanationAr": "الفعل في نهاية الجملة الفرعية. تربط aber جملتين رئيسيتين دون تغيير خاص: Ich habe gebucht, aber das Zimmer ist nicht frei."
      },
      {
        "id": "a2-12-m3",
        "promptDe": "deshalb",
        "promptAr": "اختر التعبير المطابق ل «deshalb»:",
        "options": [
          "Deshalb ich brauche Lösung.",
          "Ich deshalb eine Lösung brauche.",
          "Deshalb brauche ich eine Lösung.",
          "Brauche deshalb ich."
        ],
        "correctIndex": 2,
        "explanationAr": "الرابط deshalb يُقدَّم فيأتي الفعلُ مباشرةً بعده: «Deshalb brauche ich eine Lösung.». ف «Deshalb ich brauche Lösung.» تُبقي ترتيبَ الجملة العادية فتفقد أثرَ الرابط. فحص ذاتي: هل جاء الفعل بعد الرابط مباشرة؟"
      },
      {
        "id": "a2-12-m4",
        "promptDe": "Höfliche Lösung",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Höfliche Lösung»:",
        "options": [
          "Geben Zimmer sofort!",
          "Könnten Sie mir ein anderes Zimmer geben?",
          "Ich will alles Geld.",
          "Zimmer schlecht Sie."
        ],
        "correctIndex": 1,
        "explanationAr": "طلبُ الحلّ مع الاحترام: «Könnten Sie mir ein anderes Zimmer geben?». أمّا «Geben Zimmer sofort!» فأمرٌ بلا مُرسِل مهذَّب، و «Ich will alles Geld» تهديدٌ لا طلب. فحص ذاتي: هل بقي طلبُك مهذّبًا؟"
      },
      {
        "id": "a2-12-m5",
        "promptDe": "Beleg",
        "promptAr": "اختر دليل الحجز:",
        "options": [
          "Speisekarte",
          "Fahrplan",
          "Buchungsbestätigung",
          "Wetterbericht"
        ],
        "correctIndex": 2,
        "explanationAr": "تأكيد الحجز هو الدليل المباشر: Buchungsbestätigung تحمل رقم الحجز والتاريخ والسعر، وتُطلب عند الوصول أو التعديل. أما قائمة الطعام وتوقعات الطقس فليست دليلًا."
      }
    ]
  },
  {
    "id": "a2-13",
    "level": "A2",
    "module": 5,
    "titleDe": "Gesund leben",
    "titleAr": "حياة صحية",
    "questions": [
      {
        "id": "a2-13-m1",
        "promptDe": "Rat",
        "promptAr": "أي خيار يحقّق «Rat» في هذا السياق؟",
        "options": [
          "Du sollte mehr schläfst.",
          "Du mehr schlafen soll.",
          "Du solltest mehr schlafen.",
          "Du bist sollte Schlaf."
        ],
        "correctIndex": 2,
        "explanationAr": "النصيحةُ ب «solltest» ثم الفعلُ في النهاية: «Du solltest mehr schlafen». ف «Du sollte» فقدت سَها، و «Du mehr schlafen soll» فعلٌ في الوسط، و «Du bist sollte Schlaf» ليس جملةً أصلًا. فحص ذاتي: أين يقعُ المصدر؟"
      },
      {
        "id": "a2-13-m2",
        "promptDe": "ich",
        "promptAr": "اختر الضمير:",
        "options": [
          "sich",
          "mir",
          "mich",
          "dich"
        ],
        "correctIndex": 2,
        "explanationAr": "الفعلُ الانعكاسي مع ich يأخذ الضميرَ «mich»: ich entspanne mich. وأمّا sich فللغائب، و dich للمخاطَب، و mir ضميرُ جرٍّ لا يطلبه هذا الفعل. فحص ذاتي: مَن الفاعل ومَن الضمير العائد إليه؟"
      },
      {
        "id": "a2-13-m3",
        "promptDe": "wir",
        "promptAr": "اختر التعبير المطابق ل «wir»:",
        "options": [
          "Wir bewegen sich.",
          "Wir bewegen uns.",
          "Wir bewegen euch.",
          "Wir uns bewegen im Hauptsatz."
        ],
        "correctIndex": 1,
        "explanationAr": "الفعلُ المنعكس يرجع إلى فاعله، ومع wir يكون الضمير uns: «Wir bewegen uns jeden Tag». sich للغيبة و euch لـ ihr، ف «Wir bewegen sich» يترك الفاعلَ بلا رجوعٍ صحيح. فحص ذاتي: هل رجع إلى فاعله؟"
      },
      {
        "id": "a2-13-m4",
        "promptDe": "weniger",
        "promptAr": "المعنى:",
        "options": [
          "أقل",
          "أكثر",
          "كافٍ",
          "دائمًا"
        ],
        "correctIndex": 0,
        "explanationAr": "weniger تفيد التقليل، كما في عنوان النصّ: «Sieben Tage weniger Ablenkung» أي تشتيتٌ أقلّ. أمّا mehr فتزيد، und genug للكفاية، و immer للدوام. فحص ذاتي: هل زاد الشيءُ أم نقص؟"
      },
      {
        "id": "a2-13-m5",
        "promptDe": "Messbares Ziel",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Messbares Ziel»:",
        "options": [
          "Montag und Donnerstag je 20 Minuten gehen.",
          "Mehr Sport irgendwann.",
          "Immer gesund sein.",
          "Alles sofort ändern."
        ],
        "correctIndex": 0,
        "explanationAr": "الهدفُ الصحّي القابل للقياس يسمّي اليومَ والمدة معًا: «Montag und Donnerstag je 20 Minuten gehen.». أمّا «Immer gesund sein.» نتيجةٌ لا خطة. فحص ذاتي: هل يمكن التحقّق من هدفك؟"
      }
    ]
  },
  {
    "id": "a2-14",
    "level": "A2",
    "module": 5,
    "titleDe": "Krankmeldung",
    "titleAr": "الإبلاغ عن المرض",
    "questions": [
      {
        "id": "a2-14-m1",
        "promptDe": "Krankmeldung",
        "promptAr": "أي خيار يحقّق «Krankmeldung» في هذا السياق؟",
        "options": [
          "Ich bin krankmelden.",
          "Mich krank Arbeit.",
          "Ich melde krank mich heute bin.",
          "Ich muss mich heute krankmelden."
        ],
        "correctIndex": 3,
        "explanationAr": "الإخبارُ بالمرض فعلٌ منفصلٌ منعكس: «Ich muss mich heute krankmelden» — muss بعد الفاعل مباشرةً، و mich يرجع إليه، و krankmelden مصدرًا في النهاية. فحص ذاتي: هل انفرد krankmelden بالآخر؟"
      },
      {
        "id": "a2-14-m2",
        "promptDe": "dass",
        "promptAr": "اختر التعبير المطابق ل «dass»:",
        "options": [
          "dass kann ich heute nicht kommen",
          "dass ich kann nicht kommen heute",
          "dass ich heute nicht kommen kann",
          "dass heute kann kommen nicht"
        ],
        "correctIndex": 2,
        "explanationAr": "بعد «dass» الفعلُ في النهاية: «dass ich heute nicht kommen kann». ف «kann ich» ترتيبُ سؤالٍ بعدَ الأداة، و «ich kann nicht kommen heute» فعلٌ في الوسط، و «heute kann kommen nicht» بلا ترتيب. فحص ذاتي: أين الفعلُ؟"
      },
      {
        "id": "a2-14-m3",
        "promptDe": "ob",
        "promptAr": "اختر الصيغة الصحيحة لحالة «ob»:",
        "options": [
          "ob kann ich morgen arbeiten",
          "ob ich kann arbeiten morgen",
          "ob morgen arbeiten ich",
          "ob ich morgen arbeiten kann"
        ],
        "correctIndex": 3,
        "explanationAr": "جملةُ ob الجانبية تُبقي الفعلَ المُصرَّف في الآخر: «… ob ich morgen arbeiten kann». ف «ob kann ich morgen arbeiten» تبدأ بالفعل كأنّها سؤالٌ مستقلّ. فحص ذاتي: أين انتهى الفعلُ في جملتك؟"
      },
      {
        "id": "a2-14-m4",
        "promptDe": "voraussichtlich",
        "promptAr": "المعنى:",
        "options": [
          "على الأرجح",
          "بالتأكيد المطلق",
          "أمس",
          "سرًا"
        ],
        "correctIndex": 0,
        "explanationAr": "voraussichtlich ترجيحٌ قويّ لا قطع: «Voraussichtlich fehle ich auch morgen». لذلك لا تعني «بالتأكيد المطلق»، ولا تشير إلى زمانٍ كالأمس ولا إلى الكتمان؛ وهي تُبقي تحديثًا لاحقًا مفتوحًا. فحص ذاتي: هل بقي الاحتمال؟"
      },
      {
        "id": "a2-14-m5",
        "promptDe": "Gute …",
        "promptAr": "أكمل:",
        "options": [
          "Arbeit",
          "Krank",
          "Pause nur",
          "Besserung"
        ],
        "correctIndex": 3,
        "explanationAr": "لتمنّي الشفاء تُستعمل العبارةُ الجاهزة «Gute Besserung» كما في رسالة زميلٍ مريض. أمّا Gute Arbeit فتُثني على إنجاز، و Gute Pause تخصّ الاستراحة. فحص ذاتي: إلى مَن يتّجه الكلام؟"
      }
    ]
  },
  {
    "id": "a2-15",
    "level": "A2",
    "module": 5,
    "titleDe": "Apotheke und Rat",
    "titleAr": "الصيدلية والنصيحة",
    "questions": [
      {
        "id": "a2-15-m1",
        "promptDe": "Häufigkeit",
        "promptAr": "أي عبارة؟",
        "options": [
          "zweimal täglich",
          "eine Tablette",
          "nach dem Essen",
          "fünf Tage"
        ],
        "correctIndex": 0,
        "explanationAr": "المطلوب تكرارُ الجرعة لا كمّيتها: «zweimal täglich» يحدّد عدد المرات في اليوم. وأمّا «eine Tablette» فالكمية، و «nach dem Essen» الوقت، و «fünf Tage» المدة؛ فحص ذاتي: أيُّ لفظٍ يجيب عن «كم مرة»؟"
      },
      {
        "id": "a2-15-m2",
        "promptDe": "Zeitpunkt",
        "promptAr": "أي خيار يحقّق «Zeitpunkt» في هذا السياق؟",
        "options": [
          "zwei Tabletten",
          "fünf Tage",
          "mit Wasser",
          "nach dem Essen"
        ],
        "correctIndex": 3,
        "explanationAr": "السؤالُ عن Zeitpunkt يسأل عن وقت تناول القرص: «nach dem Essen». وأمّا zwei Tabletten فالكمية، و fünf Tage مدةُ الاستعمال، و mit Wasser طريقةُ البلع. فحص ذاتي: أتجيب عن وقتٍ أم عن كمية؟"
      },
      {
        "id": "a2-15-m3",
        "promptDe": "sollen",
        "promptAr": "اختر التعبير المطابق ل «sollen»:",
        "options": [
          "Ich soll die Tablette nehmen.",
          "Ich soll nehme die Tablette.",
          "Ich die Tablette soll nimmt.",
          "Soll ich genommen Tablette."
        ],
        "correctIndex": 0,
        "explanationAr": "sollen تنقل توصيةَ الطبيب وتُبقي المصدرَ في النهاية: «Ich soll die Tablette nehmen.». ف «Ich soll nehme die Tablette.» تصرّف الفعلَ بعد sollen. فحص ذاتي: هل بقي الفعل مصدرًا؟"
      },
      {
        "id": "a2-15-m4",
        "promptDe": "Imperativ Sie",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Imperativ Sie»:",
        "options": [
          "Sie nehmen das!",
          "Nimmst Sie das.",
          "Nehmen das Sie Wasser.",
          "Nehmen Sie das mit Wasser."
        ],
        "correctIndex": 3,
        "explanationAr": "الأمرُ مع صيغة الاحترام يبدأ بالفعل ثم Sie: «Nehmen Sie das mit Wasser». و «Sie nehmen das!» جملةٌ خبرية، و «Nimmst Sie» تخلط تصريفَ المفرد غير الرسمي مع Sie. فحص ذاتي: مَن يقصد الحديثُ رسميًا؟"
      },
      {
        "id": "a2-15-m5",
        "promptDe": "Sichere Rückfrage",
        "promptAr": "أي خيار يحقّق «Sichere Rückfrage» في هذا السياق؟",
        "options": [
          "Ich nehme alles zusammen.",
          "Nebenwirkungen sind egal.",
          "Die Übersetzung reicht immer.",
          "Verträgt sich das mit meinem Medikament?"
        ],
        "correctIndex": 3,
        "explanationAr": "طلب التحقق هو الخيار الآمن لغويًا. قبل استعمال دواء اسأل عن الحساسية والأدوية الأخرى والآثار الجانبية ومتى يلزم الطبيب."
      }
    ]
  },
  {
    "id": "a2-16",
    "level": "A2",
    "module": 6,
    "titleDe": "Nachrichten",
    "titleAr": "الأخبار",
    "questions": [
      {
        "id": "a2-16-m1",
        "promptDe": "Tatsache",
        "promptAr": "اختر التعبير المطابق ل «Tatsache»:",
        "options": [
          "Das ist eine schlechte Idee.",
          "Ich finde den Plan langweilig.",
          "Der Zug fällt um 18 Uhr aus.",
          "Das Projekt ist wunderbar."
        ],
        "correctIndex": 2,
        "explanationAr": "الخبرُ واقعةٌ قابلة للتحقق: «Der Zug fällt um 18 Uhr aus» تحمل وقتًا يمكن التأكد منه. وأمّا «eine schlechte Idee» و «wunderbar» فأحكامٌ تقييمية؛ فحص ذاتي: هل يمكن التحقق من جملتك؟"
      },
      {
        "id": "a2-16-m2",
        "promptDe": "Meinung",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Meinung»:",
        "options": [
          "am Montag",
          "laut Polizei",
          "in der Hafenstraße",
          "meiner Meinung nach"
        ],
        "correctIndex": 3,
        "explanationAr": "«meiner Meinung nach» عبارةٌ واحدة بمعنى «في رأيي»: «Meiner Meinung nach ist das zu teuer». am Montag يومٌ، و laut Polizei مصدرٌ رسمي، و in der Hafenstraße مكان — لا واحد منها يُبدي رأيًا. فحص ذاتي: هل قلتَ رأيك؟"
      },
      {
        "id": "a2-16-m3",
        "promptDe": "Quelle",
        "promptAr": "اختر صياغة:",
        "options": [
          "Laut der Stadt …",
          "Ich laut Stadt denke …",
          "Die Stadt laut mich …",
          "Laut ist die Meinung …"
        ],
        "correctIndex": 0,
        "explanationAr": "laut + Dativ/Genitiv حسب التركيب؛ هنا laut der Stadt. الحقيقة خبر يمكن التحقق منه: Der Zug fällt um 18 Uhr aus."
      },
      {
        "id": "a2-16-m4",
        "promptDe": "dass",
        "promptAr": "أي خيار يحقّق «dass» في سياق درس «الأخبار»؟",
        "options": [
          "dass fallen zwei Linien aus",
          "dass zwei Linien fallen aus",
          "dass aus zwei Linien fallen",
          "dass zwei Linien ausfallen"
        ],
        "correctIndex": 3,
        "explanationAr": "الفعل المنفصل يجتمع في نهاية الجملة الفرعية. ابدأ بالمصدر ثم الحدث: Laut der Stadt … أو Im Artikel steht, dass …."
      },
      {
        "id": "a2-16-m5",
        "promptDe": "Kernfragen",
        "promptAr": "أي مجموعة؟",
        "options": [
          "schön, schlecht, toll",
          "teuer, billig",
          "Wer, was, wann, wo",
          "ja oder nein"
        ],
        "correctIndex": 2,
        "explanationAr": "شبكةُ الخبر تُبنى على أسئلةٍ تُغطّي الحدث: «Wer, was, wann, wo». وأمّا الصفاتُ العامة (schön, schlecht, toll) والأسئلةُ التي تُجاب بنعم أو لا فلا تُنتج خبرًا. فحص ذاتي: أيُّ سؤالٍ يبقى بلا جواب في مسودتك؟"
      }
    ]
  },
  {
    "id": "a2-17",
    "level": "A2",
    "module": 6,
    "titleDe": "Online sein",
    "titleAr": "الحياة على الإنترنت",
    "questions": [
      {
        "id": "a2-17-m1",
        "promptDe": "Gleicher Handelnder",
        "promptAr": "اختر التعبير المطابق ل «Gleicher Handelnder»:",
        "options": [
          "Ich lese, damit informiert zu bleiben.",
          "Um ich informiert bleibe.",
          "Ich lese, um informiert zu bleiben.",
          "Ich um bleiben informiert."
        ],
        "correctIndex": 2,
        "explanationAr": "حين يتّحد الفاعلان يُستعمل um … zu بدل damit: «Ich lese, um informiert zu bleiben». وأمّا «Ich lese, damit informiert zu bleiben.» فتخلط الأداتين، وسائرُ الجمل تكسر الترتيب. فحص ذاتي: أفاعلٌ واحد أم فاعلان؟"
      },
      {
        "id": "a2-17-m2",
        "promptDe": "Andere Person",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Andere Person»:",
        "options": [
          "Ich sende es, um du es liest.",
          "Ich sende es, damit du es liest.",
          "Damit du liest es, ich sende.",
          "Ich sende, damit lesen du."
        ],
        "correctIndex": 1,
        "explanationAr": "لمّا اختلف الفاعلان لم يصلح um … zu فجاء damit: «Ich sende es, damit du es liest.». ف «Ich sende es, um du es liest.» تُبقي um مع فاعلٍ ثانٍ. فحص ذاتي: هل اتّحد الفاعلان أم اختلفا؟"
      },
      {
        "id": "a2-17-m3",
        "promptDe": "anmelden mit zu",
        "promptAr": "أي خيار يحقّق «anmelden mit zu» في هذا السياق؟",
        "options": [
          "zu anmelden",
          "anzumelden",
          "anmelden zu",
          "angezumelden"
        ],
        "correctIndex": 1,
        "explanationAr": "مع «zu» ينقسمُ فعلُ الانفصال حوله: an ⇒ an-zu-melden. ف «zu anmelden» تُبقي الأُفّ مفصولًا، و «anmelden zu» بلا حركةٍ للفعل، و «angezumelden» تلقي ge زائدًا. فحص ذاتي: أين تدخلُ zu بالضبط؟"
      },
      {
        "id": "a2-17-m4",
        "promptDe": "Vor dem Posten",
        "promptAr": "الأفضل:",
        "options": [
          "Zustimmung und Publikum prüfen",
          "Alles öffentlich stellen",
          "Standort hinzufügen",
          "Passwort mitschicken"
        ],
        "correctIndex": 0,
        "explanationAr": "قبل النشر يُقاس أمران: «Zustimmung und Publikum prüfen»، فلا يُنشر ما يخصّ غيرَك بلا إذن. وإضافةُ الموقع أو الصور تزيد المدى بلا ضرورة؛ فحص ذاتي: مَن سيرى المنشور وهل يوافق أصحابُه؟"
      },
      {
        "id": "a2-17-m5",
        "promptDe": "damit",
        "promptAr": "اختر الترتيب:",
        "options": [
          "damit können alle entscheiden",
          "damit alle können entscheiden",
          "damit entscheiden können alle sie",
          "damit alle entscheiden können"
        ],
        "correctIndex": 3,
        "explanationAr": "الرابط damit يفتح جملةَ غايةٍ ويُبقي الفعلَ المُصرَّف في النهاية: «damit alle entscheiden können». ف «damit können alle entscheiden» تُقدّم الفعل بعد الرابط مباشرة. فحص ذاتي: أين انتهى الفعل في جملتك؟"
      }
    ]
  },
  {
    "id": "a2-18",
    "level": "A2",
    "module": 6,
    "titleDe": "Eine Meinung",
    "titleAr": "التعبير عن رأي",
    "questions": [
      {
        "id": "a2-18-m1",
        "promptDe": "Meinung mit dass",
        "promptAr": "اختر التعبير المطابق ل «Meinung mit dass»:",
        "options": [
          "Ich finde, dass sind Handys nützlich.",
          "Ich finde, dass Handys nützlich sind.",
          "Dass Handys ich finde nützlich.",
          "Ich finde Handys dass."
        ],
        "correctIndex": 1,
        "explanationAr": "صيغةُ الرأي تبدأ بـ finde ثم dass وفعلُها المساعد في النهاية: «Ich finde, dass Handys nützlich sind.». ف «dass sind Handys nützlich» تقلب ترتيب الجملة التابعة. فحص ذاتي: هل بقي الفعل في آخر الجملة؟"
      },
      {
        "id": "a2-18-m2",
        "promptDe": "Beispiel",
        "promptAr": "أي عبارة؟",
        "options": [
          "Meiner Meinung nach …",
          "Trotzdem …",
          "Zum Beispiel …",
          "Obwohl …"
        ],
        "correctIndex": 2,
        "explanationAr": "المثالُ يُقدَّم ب «Zum Beispiel …» ثم يأتي الشرحُ بعده. و Meiner Meinung nach يُبدي رأيًا، و Trotzdem يُقابل أمرًا سابقًا، و Obwohl يقدّم تناقضًا — لا واحد منها يُورِد مثالًا. فحص ذاتي: هل طلب السياقُ مثالًا؟"
      },
      {
        "id": "a2-18-m3",
        "promptDe": "Teilweise Zustimmung",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Teilweise Zustimmung»:",
        "options": [
          "Das stimmt, aber …",
          "Du bist falsch.",
          "Nein, Ende.",
          "Keine Meinung du."
        ],
        "correctIndex": 0,
        "explanationAr": "الموافقة الجزئية تُبنى على ربطٍ صريح: «Das stimmt, aber …» يقرّ بوجهٍ ثم يعترض. والرفضُ الجاف أو غيابُ الرأي لا يفتحان حوارًا؛ فحص ذاتي: هل أقْررتَ ثم أبديتَ تحفّظك؟"
      },
      {
        "id": "a2-18-m4",
        "promptDe": "Abwägung",
        "promptAr": "أي خيار يحقّق «Abwägung» في سياق درس «التعبير عن رأي»؟",
        "options": [
          "weil … deshalb",
          "ob … wenn",
          "um … dass",
          "zwar … aber"
        ],
        "correctIndex": 3,
        "explanationAr": "الموازنةُ تُبنى على رابطين متقابلين: «zwar … aber» يذكر وجهًا ثم يقابله بآخر. وأمّا «um … dass» فقد رُكِّبا خطأً، و «weil … deshalb» يجمع سببيْن؛ فحص ذاتي: أيّ رابطين يوازنان؟"
      },
      {
        "id": "a2-18-m5",
        "promptDe": "Respektvoll widersprechen",
        "promptAr": "اختر التعبير المطابق ل «Respektvoll widersprechen»:",
        "options": [
          "Du verstehst nichts.",
          "Das ist dumm.",
          "Nur ich habe recht.",
          "Ich sehe das etwas anders."
        ],
        "correctIndex": 3,
        "explanationAr": "الاعتراض المهنيّ يبقى في نطاق الرأي: «Ich sehe das etwas anders» ينفي الاتفاق لا الشخص. وأمّا «Das ist dumm» و «Nur ich habe recht» فتهاجم المخاطَب؛ فحص ذاتي: هل اعترضتَ على الفكرة أم على صاحبها؟"
      }
    ]
  },
  {
    "id": "a2-19",
    "level": "A2",
    "module": 7,
    "titleDe": "So lerne ich",
    "titleAr": "هكذا أتعلم",
    "questions": [
      {
        "id": "a2-19-m1",
        "promptDe": "Aktiver Abruf",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Aktiver Abruf»:",
        "options": [
          "Antwort sehen und lesen",
          "Liste dekorieren",
          "Antwort verdecken und selbst sagen",
          "Lösung kopieren"
        ],
        "correctIndex": 2,
        "explanationAr": "الاسترجاعُ النشط يعني الإخفاء والإنتاج لا القراءة: «Antwort verdecken und selbst sagen». فالقراءةُ تعطي إحساسًا زائفًا بالمعرفة، ونسخُ الحلّ لا يبني استدعاءً؛ فحص ذاتي: هل رأيت الجوابَ قبل المحاولة؟"
      },
      {
        "id": "a2-19-m2",
        "promptDe": "wenn",
        "promptAr": "أي خيار يحقّق «wenn» في هذا السياق؟",
        "options": [
          "Wenn ich bin müde, ich Pause mache.",
          "Wenn müde ich, mache bin.",
          "Wenn ich müde, Pause.",
          "Wenn ich müde bin, mache ich Pause."
        ],
        "correctIndex": 3,
        "explanationAr": "جملةُ الشرط تنقل الفعلَ إلى نهايتها ثم تبدأ الجوابَ به: «Wenn ich müde bin, mache ich Pause». فالترتيبُ الألماني لا يقدّم الفاعلَ ولا يحذف الفعل، وصيغةُ الأمر لا تصلح جوابًا؛ فحص ذاتي: أين وقف الفعلُ في كل نصف؟"
      },
      {
        "id": "a2-19-m3",
        "promptDe": "Zweck",
        "promptAr": "اختر التعبير المطابق ل «Zweck»:",
        "options": [
          "um besser zu sprechen",
          "damit besser zu sprechen",
          "um ich spreche besser",
          "zu um sprechen"
        ],
        "correctIndex": 0,
        "explanationAr": "الغايةُ مع نفس الفاعل بـ um … zu والمصدر في الآخر: «Ich übe jeden Tag, um besser zu sprechen». damit تأخذ فاعلًا مختلفًا وجملةً مُصرَّفة، و «damit … zu» يمزج الأداتين. فحص ذاتي: مَن الفاعل هنا؟"
      },
      {
        "id": "a2-19-m4",
        "promptDe": "Messbar",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Messbar»:",
        "options": [
          "viel lernen",
          "zehn Karten fünf Tage testen",
          "alles verstehen",
          "immer motiviert sein"
        ],
        "correctIndex": 1,
        "explanationAr": "الهدفُ القابل للقياس يحمل عددًا ومدةً معًا: «zehn Karten fünf Tage testen». أمّا «viel lernen» و «alles verstehen» فعامّان لا يتحقّق منهما شيء. فحص ذاتي: هل في هدفك رقمٌ وتاريخ؟"
      },
      {
        "id": "a2-19-m5",
        "promptDe": "Verzögerter Test",
        "promptAr": "متى؟",
        "options": [
          "فقط مباشرة بعد القراءة",
          "والحل ظاهر",
          "بعد يوم أو عدة أيام",
          "دون محاولة أولى"
        ],
        "correctIndex": 2,
        "explanationAr": "الاختبارُ المرجّأ يفصل المذاكرةَ عن السؤال: «بعد يوم أو عدة أيام» حتى يقيس الاحتفاظ لا الذاكرةَ اللحظية. فالتكرارُ المباشر يقيس الانتباه؛ فحص ذاتي: هل مرّ وقتٌ كافٍ بينهما؟"
      }
    ]
  },
  {
    "id": "a2-20",
    "level": "A2",
    "module": 7,
    "titleDe": "Kurse und Prüfungen",
    "titleAr": "الدورات والاختبارات",
    "questions": [
      {
        "id": "a2-20-m1",
        "promptDe": "bevor",
        "promptAr": "أي خيار يحقّق «bevor» في هذا السياق؟",
        "options": [
          "Bevor ich melde mich an, lese.",
          "Bevor ich mich anmelde, lese ich alles.",
          "Bevor anmelden ich, ich lese.",
          "Ich bevor mich anmelden."
        ],
        "correctIndex": 1,
        "explanationAr": "في جملة bevor ينتقل الفعلُ المصرَّف إلى نهايتها: «Bevor ich mich anmelde». والضميرُ الانعكاسي يبقى قريبًا منه، والشقُّ الآخر يبدأ بالفعل «lese ich alles»؛ فحص ذاتي: أين وقف الفعلُ في كل نصف؟"
      },
      {
        "id": "a2-20-m2",
        "promptDe": "Nach vorangestelltem Nebensatz",
        "promptAr": "اختر التعبير المطابق ل «Nach vorangestelltem Nebensatz»:",
        "options": [
          "Bevor der Kurs beginnt, mache ich einen Test.",
          "Bevor der Kurs beginnt, ich mache einen Test.",
          "Bevor beginnt Kurs, Test ich.",
          "Der Kurs bevor, mache."
        ],
        "correctIndex": 0,
        "explanationAr": "فعل الجملة الرئيسية يأتي بعد الفاصلة. تقدم bevor حدثًا يقع قبل حدث آخر: Bevor ich mich anmelde, lese ich die Bedingungen."
      },
      {
        "id": "a2-20-m3",
        "promptDe": "Interner Test",
        "promptAr": "ماذا يعني؟",
        "options": [
          "شهادة رسمية دائمًا",
          "تقييم داخل الدورة",
          "امتحان Goethe تلقائي",
          "ضمان نجاح"
        ],
        "correctIndex": 1,
        "explanationAr": "«Interner Test» تقييمٌ داخل الدورة تُوَظِّفه المدرسةُ لنفسها، أما الشهادةُ الرسمية فتُصدرها جهةُ امتحانٍ خارجيّة. والنصّ لا يعدُضمانَ نجاحٍ ولا يربط اختبارَ المستوى بموعدِ Goethe. فحص ذاتي: من يُصدر الوثيقة؟"
      },
      {
        "id": "a2-20-m4",
        "promptDe": "Vor Anmeldung",
        "promptAr": "الأفضل:",
        "options": [
          "Nur den Titel lesen",
          "Sofort bezahlen",
          "Ziele, Zeit, Kosten und Prüfung prüfen",
          "Erfolg garantieren lassen"
        ],
        "correctIndex": 2,
        "explanationAr": "قبل التسجيل تُفحص أربعةُ أشياء صراحةً: «Ziele, Zeit, Kosten und Prüfung prüfen». فقراءةُ العنوان وحدها لا تكشف الرسوم ولا حالات الالتحاق. فحص ذاتي: ما سألتَ عنه قبل أن تدفع؟"
      },
      {
        "id": "a2-20-m5",
        "promptDe": "Indirekte Frage",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Indirekte Frage»:",
        "options": [
          "ob gibt es eine Prüfung",
          "ob eine Prüfung gibt es",
          "ob Prüfung es",
          "ob es eine Prüfung gibt"
        ],
        "correctIndex": 3,
        "explanationAr": "السؤالُ غير المباشر يبدأ بـ ob ويُبقي الفعلَ في النهاية: «ob es eine Prüfung gibt». ف «ob gibt es eine Prüfung» تنقل ترتيبَ السؤال المباشر إلى التابعة. فحص ذاتي: هل حرّكت الفعل بعد ob؟"
      }
    ]
  },
  {
    "id": "a2-21",
    "level": "A2",
    "module": 7,
    "titleDe": "Pläne",
    "titleAr": "الخطط",
    "questions": [
      {
        "id": "a2-21-m1",
        "promptDe": "vorhaben",
        "promptAr": "أي خيار يحقّق «vorhaben» في هذا السياق؟",
        "options": [
          "Ich habe vor, mehr zu lernen.",
          "Ich habe vor, ich lerne.",
          "Ich vor mehr lernen habe.",
          "Ich habe zu vor."
        ],
        "correctIndex": 0,
        "explanationAr": "الفعل vorhaben يطلب المصدرَ مع zu في الآخر: «Ich habe vor, mehr zu lernen». و «Ich habe vor, ich lerne» يُصرّف الجملةَ بعد الأداة، و «Ich habe zu vor» يفصل zu عن مصدرها. فحص ذاتي: هل جاء zu قبل المصدر؟"
      },
      {
        "id": "a2-21-m2",
        "promptDe": "aufstehen mit zu",
        "promptAr": "اختر التعبير المطابق ل «aufstehen mit zu»:",
        "options": [
          "zu aufstehen",
          "aufstehen zu",
          "aufgestanden zu",
          "aufzustehen"
        ],
        "correctIndex": 3,
        "explanationAr": "مع الأفعال المنفصلة تدخل zu بين البادئة والمصدر: auf + zu + stehen ⇒ «aufzustehen». و «zu aufstehen» تضع الأداةَ أمام البادئة، و «aufgestanden zu» تأتي بتصريف الماضي حيث يُطلب المصدر. فحص ذاتي: أين استقرّت zu؟"
      },
      {
        "id": "a2-21-m3",
        "promptDe": "Futur I",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Futur I»:",
        "options": [
          "Ich werde prüfe den Plan.",
          "Ich den Plan werden geprüft.",
          "Ich werde den Plan prüfen.",
          "Ich prüfen werde Plan."
        ],
        "correctIndex": 2,
        "explanationAr": "المستقبل يُصاغ ب werden ثانيًا والمصدر في النهاية: «Ich werde den Plan prüfen». فلا يُصرَّف الفعلُ الأصلي ولا يُنتزَع المصدرُ من آخره؛ فحص ذاتي: أين وقف prüfen في جملتك؟"
      },
      {
        "id": "a2-21-m4",
        "promptDe": "Präsens مستقبل",
        "promptAr": "أي خيار يحقّق «Präsens مستقبل» في هذا السياق؟",
        "options": [
          "Nächste Woche ich beginne.",
          "Beginnen ich nächste Woche.",
          "Nächste Woche begonnen ich.",
          "Nächste Woche beginne ich den Kurs."
        ],
        "correctIndex": 3,
        "explanationAr": "الظرفُ الزمني يتقدّم على الفعل المصرَّف: «Nächste Woche beginne ich den Kurs». فهذه هي طريقة الألمانية في التعبير عن المستقبل بالحاضر، مع «Nächste Woche» واضحة؛ فحص ذاتي: هل تقدّم الظرفُ على الفعل والفاعل؟"
      },
      {
        "id": "a2-21-m5",
        "promptDe": "Gutes Ziel",
        "promptAr": "اختر التعبير المطابق ل «Gutes Ziel»:",
        "options": [
          "Viermal pro Woche 45 Minuten mit Wochenkontrolle.",
          "Mehr Deutsch bald.",
          "Alles perfekt.",
          "Motivation immer."
        ],
        "correctIndex": 0,
        "explanationAr": "الهدفُ الجيد يحدّد المقدارَ والزمنَ والمراقبة معًا: «Viermal pro Woche 45 Minuten mit Wochenkontrolle». وأمّا «Mehr Deutsch bald» و «Alles perfekt» فعباراتٌ عامة؛ فحص ذاتي: كيف تعرف أنك تقدّمت؟"
      }
    ]
  },
  {
    "id": "a2-22",
    "level": "A2",
    "module": 8,
    "titleDe": "Feste",
    "titleAr": "المناسبات والاحتفالات",
    "questions": [
      {
        "id": "a2-22-m1",
        "promptDe": "Wiederholt",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Wiederholt»:",
        "options": [
          "Als wir jeden Monat feiern …",
          "Als immer Gäste kommen …",
          "Wenn ich gestern 18 wurde …",
          "Wenn wir feiern …"
        ],
        "correctIndex": 3,
        "explanationAr": "للتكرار المعتاد تأتي wenn: «Wenn wir feiern, …». أمّا als فلموقفٍ واحدٍ في الماضي، لذلك «Als wir jeden Monat feiern» يمزج الماضي بالتكرار و «Wenn ich gestern … wurde» يكرّر مفردًا. فحص ذاتي: متكررٌ أم مفرد؟"
      },
      {
        "id": "a2-22-m2",
        "promptDe": "Einmal Vergangenheit",
        "promptAr": "أي خيار يحقّق «Einmal Vergangenheit» في هذا السياق؟",
        "options": [
          "Wenn ich 18 wurde gestern …",
          "Wenn ich immer 18 bin …",
          "Als ich 18 wurde …",
          "Als ich jeden Geburtstag …"
        ],
        "correctIndex": 2,
        "explanationAr": "لحدثٍ واحدٍ منقضٍ في الماضي تأتي als: «Als ich 18 wurde, …». أمّا wenn فللتكرار أو الشرط، لذلك «Wenn ich 18 wurde gestern» يكرّر مفردًا. فحص ذاتي: حدثٌ واحدٌ أم عادةٌ متكرّرة؟"
      },
      {
        "id": "a2-22-m3",
        "promptDe": "Zusage",
        "promptAr": "اختر التعبير المطابق ل «Zusage»:",
        "options": [
          "Ich absage ja.",
          "Ich würde gern kommen.",
          "Vielleicht sicher nein.",
          "Kommen ich Einladung."
        ],
        "correctIndex": 1,
        "explanationAr": "القبولُ المؤدَّب يتمنّى ولا يقطع: «Ich würde gern kommen». و «Ich absage ja» يجمع إثباتًا ورفضًا، و «Vielleicht sicher nein» تناقض، و «Kommen ich Einladung» بلا تصريف. فحص ذاتي: هل بقي البابُ مفتوحًا؟"
      },
      {
        "id": "a2-22-m4",
        "promptDe": "Absage",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Absage»:",
        "options": [
          "Leider kann ich nicht teilnehmen.",
          "Nein Feier.",
          "Ich komme nicht, schlecht.",
          "Absage bin."
        ],
        "correctIndex": 0,
        "explanationAr": "الاعتذارُ المؤدَّب جملةٌ كاملة مع kann: «Leider kann ich nicht teilnehmen». أمّا «Nein Feier» و «Absage bin» فبلا تصريفٍ ومعنىً ناقص، و «Ich komme nicht, schlecht» جافّةٌ لا مجاملة. فحص ذاتي: هل بقي الرفضُ مهذّبًا؟"
      },
      {
        "id": "a2-22-m5",
        "promptDe": "Kulturell vorsichtig",
        "promptAr": "أي خيار يحقّق «Kulturell vorsichtig» في هذا السياق؟",
        "options": [
          "Alle Menschen dort …",
          "Jeder macht immer …",
          "In meiner Familie …",
          "Diese Kultur ist so."
        ],
        "correctIndex": 2,
        "explanationAr": "الصياغة الحذرة تحصر الحكم في تجربتك: «In meiner Familie …» خبرٌ عن نطاقٍ تعرفه. وأمّا «Alle Menschen dort» و «Diese Kultur ist so» فتعميمٌ بلا دليل؛ فحص ذاتي: هل تحدّثت عن معرفتك أم عن «كلّ» الناس؟"
      }
    ]
  },
  {
    "id": "a2-23",
    "level": "A2",
    "module": 8,
    "titleDe": "Engagement",
    "titleAr": "المشاركة المجتمعية",
    "questions": [
      {
        "id": "a2-23-m1",
        "promptDe": "der Helfer",
        "promptAr": "اختر الضمير:",
        "options": [
          "der",
          "die",
          "das",
          "den"
        ],
        "correctIndex": 0,
        "explanationAr": "الاسمُ «der Helfer» مذكّر، فيأخذ في Nominativ الأداةَ «der». وأمّا «die» فللمؤنث، و «das» للمحايد، و «den» تُستعمل في المفعول (Akkusativ)؛ فحص ذاتي: هل الاسمُ فاعلٌ في الجملة أم مفعول؟"
      },
      {
        "id": "a2-23-m2",
        "promptDe": "die Initiative",
        "promptAr": "اختر التعبير المطابق ل «die Initiative»:",
        "options": [
          "der",
          "die",
          "das",
          "den"
        ],
        "correctIndex": 1,
        "explanationAr": "الأسماءُ المنتهية بـ -tion مؤنّثة: die Initiative، مثل die Station و die Information. der و das تُخطئان الجنس، و «den» لا يكون أداةً للمبتدأ — يبقى المعنى وتَسقط الفصاحة. فحص ذاتي: هل حفظتَ الاسمَ بأداته؟"
      },
      {
        "id": "a2-23-m3",
        "promptDe": "das Projekt",
        "promptAr": "اختر الصيغة الصحيحة لحالة «das Projekt»:",
        "options": [
          "das",
          "der",
          "die",
          "dem"
        ],
        "correctIndex": 0,
        "explanationAr": "اسمُ Projekt يأخذ das في المفرد: das Projekt، والجمع die Projekte. لذلك لا تكون der ولا die أداةً معه، و dem formٌ آخر لا يصلح لمبتدأٍ في هذه الصيغة. فحص ذاتي: هل حفظتَ الاسمَ بأداته؟"
      },
      {
        "id": "a2-23-m4",
        "promptDe": "Plural Personen",
        "promptAr": "أي خيار يحقّق «Plural Personen» في هذا السياق؟",
        "options": [
          "der",
          "das",
          "die",
          "den"
        ],
        "correctIndex": 2,
        "explanationAr": "الفاعلُ المعرّف في الجمع يأخذ die في Nominativ، وهو «die» في هذا التمرين. وأمّا der و das فمفرد، و den تُستعمل في الجمع المنصوب (Akkusativ). فحص ذاتي: أهو فاعلٌ أم مفعولٌ في جملتك؟"
      },
      {
        "id": "a2-23-m5",
        "promptDe": "Realistisch",
        "promptAr": "اختر التعبير المطابق ل «Realistisch»:",
        "options": [
          "Alle Aufgaben immer übernehmen.",
          "Vier Wochen je eine Stunde ausprobieren.",
          "Ohne Einführung starten.",
          "Daten frei sammeln."
        ],
        "correctIndex": 1,
        "explanationAr": "الانخراطُ الواقعيّ يحدّد مدةً ومقدارًا معًا: «Vier Wochen je eine Stunde ausprobieren». أمّا تبنّي كلّ المهامّ دائمًا فينتهي بالانسحاب. فحص ذاتي: هل بيّنتَ وقتك المتاح؟"
      }
    ]
  },
  {
    "id": "a2-24",
    "level": "A2",
    "module": 8,
    "titleDe": "Gemeinsam entscheiden",
    "titleAr": "اتخاذ قرار مشترك",
    "questions": [
      {
        "id": "a2-24-m1",
        "promptDe": "Alternative",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Alternative»:",
        "options": [
          "weder … noch",
          "entweder … oder",
          "sowohl … als auch",
          "zwar … weil"
        ],
        "correctIndex": 1,
        "explanationAr": "«entweder … oder» يطرح بديلين يُختار أحدهما: «Entweder gehen wir jetzt oder wir bleiben». weder … noch تنفي الاثنين، و sowohl … als auch تجمع بينهما، و «zwar … weil» ليس رابطًا موجودًا. فحص ذاتي: كم احتمالًا بقي؟"
      },
      {
        "id": "a2-24-m2",
        "promptDe": "Negation von zwei Dingen",
        "promptAr": "أي خيار يحقّق «Negation von zwei Dingen» في هذا السياق؟",
        "options": [
          "weder … noch",
          "entweder … oder",
          "sowohl … als auch",
          "um … zu"
        ],
        "correctIndex": 0,
        "explanationAr": "نفيُ شيئين معًا ب «weder … noch»: «Weder kalt noch hungrig». أمّا entweder … oder فتطرح أحدَ الاحتمالين، و sowohl … als auch تجمعهما إثباتًا، و um … zu أداةُ غاية. فحص ذاتي: كم شيءًا يبقى بعد الرابط؟"
      },
      {
        "id": "a2-24-m3",
        "promptDe": "Beide Eigenschaften",
        "promptAr": "اختر التعبير المطابق ل «Beide Eigenschaften»:",
        "options": [
          "weder … noch",
          "sowohl … als auch",
          "entweder … oder",
          "ob … wenn"
        ],
        "correctIndex": 1,
        "explanationAr": "الجمعُ بين صفتين إثباتًا ب «sowohl … als auch»: «sowohl schnell als auch günstig». و entweder … oder تختار واحدًا، و weder … noch تنفي الاثنين، و «ob … wenn» رابطٌ غير موجود. فحص ذاتي: هل الصفتانِ قائمتان؟"
      },
      {
        "id": "a2-24-m4",
        "promptDe": "Richtig negieren",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Richtig negieren»:",
        "options": [
          "weder keine Zeit noch kein Geld",
          "nicht weder Zeit",
          "weder Zeit noch Geld",
          "kein Zeit und noch"
        ],
        "correctIndex": 2,
        "explanationAr": "النفيُ المزدوج بـ weder … noch بلا نفيٍ زائد: «weder Zeit noch Geld». ف «weder keine Zeit noch kein Geld» يُضيف kein مرّتين، و «nicht weder Zeit» يترك أحدَ الطرفين. فحص ذاتي: كم نفيًا تكفي الجملة؟"
      },
      {
        "id": "a2-24-m5",
        "promptDe": "Umsetzbarer Beschluss",
        "promptAr": "أي خيار يحقّق «Umsetzbarer Beschluss» في هذا السياق؟",
        "options": [
          "Mara bucht bis Dienstag; Plan B ist online.",
          "Wir machen etwas.",
          "Alle wissen es.",
          "Später vielleicht."
        ],
        "correctIndex": 0,
        "explanationAr": "القرارُ القابل للتنفيذ يسمّي مسؤولًا وموعدًا وبديلًا: «Mara bucht bis Dienstag; Plan B ist online.». أمّا «Später vielleicht.» فبلا تاريخ فلا يمكن متابعته. فحص ذاتي: مَن ينفّذ ومتى وما البديل؟"
      }
    ]
  }
] as const satisfies readonly LocalTestTemplateLesson[];
