/* Generated by scripts/generate-local-test-templates.ts; do not edit. */
import type { LocalTestTemplateLesson } from "@/core/training/local-test-generator";

export const localTestTemplateBankB1 = [
  {
    "id": "b1-01",
    "level": "B1",
    "module": 1,
    "titleDe": "Lebenswege",
    "titleAr": "مسارات الحياة",
    "questions": [
      {
        "id": "b1-01-m1",
        "promptDe": "werden Präteritum",
        "promptAr": "اختر التعبير المطابق لـ«werden Präteritum»:",
        "options": [
          "wurde",
          "hat geworden",
          "wirdete",
          "war werden"
        ],
        "correctIndex": 0,
        "explanationAr": "wurde. تظهر السير المكتوبة كثيرًا في Präteritum: wurde، wuchs auf، studierte، arbeitete، zog."
      },
      {
        "id": "b1-01-m2",
        "promptDe": "haben Präteritum",
        "promptAr": "اختر الصيغة الصحيحة لحالة «haben Präteritum»:",
        "options": [
          "habe gehabt",
          "hatte",
          "habte",
          "war haben"
        ],
        "correctIndex": 1,
        "explanationAr": "hatte. تستعمل war وhatte وkonnte وmusste وwollte كثيرًا في الكلام والكتابة: Er war jung، hatte wenig Geld، musste arbeiten، konnte nicht reisen."
      },
      {
        "id": "b1-01-m3",
        "promptDe": "können Präteritum",
        "promptAr": "أي خيار يحقّق «können Präteritum» في هذا السياق؟",
        "options": [
          "kannte",
          "gekonnt hat",
          "könnte",
          "konnte"
        ],
        "correctIndex": 3,
        "explanationAr": "konnte. تستعمل war وhatte وkonnte وmusste وwollte كثيرًا في الكلام والكتابة: Er war jung، hatte wenig Geld، musste arbeiten، konnte nicht reisen."
      },
      {
        "id": "b1-01-m4",
        "promptDe": "Zeitstruktur",
        "promptAr": "اختر التعبير المطابق لـ«Zeitstruktur»:",
        "options": [
          "Während des Studiums er arbeitete.",
          "Während arbeitete Studium er.",
          "Während des Studiums arbeitete er.",
          "Er während Studium."
        ],
        "correctIndex": 2,
        "explanationAr": "عنصر الزمن ثم الفعل. اربط السيرة بعبارات مثل zunächst، während، nach dem Abschluss، einige Jahre später، als، seitdem."
      },
      {
        "id": "b1-01-m5",
        "promptDe": "Rückblick",
        "promptAr": "أفضل خاتمة:",
        "options": [
          "Dann Ende.",
          "Rückblickend brachte jede Phase eine wichtige Fähigkeit.",
          "Alle Jahre waren gleich.",
          "Biografie fertig."
        ],
        "correctIndex": 1,
        "explanationAr": "تربط المراحل بدلالتها. اربط السيرة بعبارات مثل zunächst، während، nach dem Abschluss، einige Jahre später، als، seitdem."
      }
    ]
  },
  {
    "id": "b1-02",
    "level": "B1",
    "module": 1,
    "titleDe": "Entscheidungen",
    "titleAr": "القرارات",
    "questions": [
      {
        "id": "b1-02-m1",
        "promptDe": "entscheiden",
        "promptAr": "اختر الصيغة الصحيحة لحالة «entscheiden»:",
        "options": [
          "Ich entscheide mich für den Kurs.",
          "Ich entscheide für den Kurs.",
          "Ich mich für Kurs entscheide.",
          "Ich bin Entscheidung Kurs."
        ],
        "correctIndex": 0,
        "explanationAr": "الفعل انعكاسي مع für. الفعل انعكاسي: ich entscheide mich، du entscheidest dich."
      },
      {
        "id": "b1-02-m2",
        "promptDe": "Abwägung",
        "promptAr": "أي خيار يحقّق «Abwägung» في سياق درس «القرارات»؟",
        "options": [
          "Entweder … weil …",
          "Einerseits … andererseits …",
          "Weder … deshalb …",
          "Als … wenn …"
        ],
        "correctIndex": 1,
        "explanationAr": "عرض جانبين. يربط einerseits … andererseits جانبين مهمين: Einerseits ist die Stelle sicher, andererseits bietet sie wenig Entwicklung."
      },
      {
        "id": "b1-02-m3",
        "promptDe": "Hypothese",
        "promptAr": "اختر التعبير المطابق لـ«Hypothese»:",
        "options": [
          "Wenn ich würde wählen, ich umziehe.",
          "Wenn wähle ich, würde umziehen.",
          "Ich müsste wenn würde.",
          "Wenn ich wählen müsste, würde ich umziehen."
        ],
        "correctIndex": 3,
        "explanationAr": "شرط Konjunktiv II وwürde في الرئيسية. نستعمل würde + مصدر للتحدث عن قرار غير واقع أو مشروط: Wenn ich wählen müsste, würde ich die flexiblere Stelle nehmen."
      },
      {
        "id": "b1-02-m4",
        "promptDe": "wir Perfekt",
        "promptAr": "اختر الصيغة الصحيحة لحالة «wir Perfekt»:",
        "options": [
          "Wir sind uns entscheidet.",
          "Wir haben sich entschieden.",
          "Wir haben uns entschieden.",
          "Wir entschieden uns haben."
        ],
        "correctIndex": 2,
        "explanationAr": "wir → uns، Perfekt مع haben. الفعل انعكاسي: ich entscheide mich، du entscheidest dich."
      },
      {
        "id": "b1-02-m5",
        "promptDe": "Gute Entscheidung",
        "promptAr": "الأفضل:",
        "options": [
          "Nur der erste Eindruck",
          "Kriterien, Risiko und Prüftermin",
          "Keine neuen Informationen",
          "Eine Entscheidung ohne Alternative"
        ],
        "correctIndex": 1,
        "explanationAr": "معايير وخطر ومراجعة. نستعمل würde + مصدر للتحدث عن قرار غير واقع أو مشروط: Wenn ich wählen müsste, würde ich die flexiblere Stelle nehmen."
      }
    ]
  },
  {
    "id": "b1-03",
    "level": "B1",
    "module": 1,
    "titleDe": "Wendepunkte",
    "titleAr": "نقاط التحول",
    "questions": [
      {
        "id": "b1-03-m1",
        "promptDe": "Plusquamperfekt",
        "promptAr": "أي خيار يحقّق «Plusquamperfekt» في هذا السياق؟",
        "options": [
          "Sie hatte den Kurs beendet.",
          "Sie hat den Kurs beendet.",
          "Sie hatte beendet den Kurs.",
          "Sie war beendet."
        ],
        "correctIndex": 0,
        "explanationAr": "hatte + Partizip في النهاية. نستعمل Plusquamperfekt عندما نحتاج توضيح أن حدثًا اكتمل قبل حدث ماضٍ آخر."
      },
      {
        "id": "b1-03-m2",
        "promptDe": "Bewegung",
        "promptAr": "اختر التعبير المطابق لـ«Bewegung»:",
        "options": [
          "Der Zug hatte abgefahren.",
          "Der Zug ist abgefahren",
          "Der Zug war abfahren.",
          "Der Zug war abgefahren."
        ],
        "correctIndex": 3,
        "explanationAr": "sein في Plusquamperfekt: war abgefahren. نستعمل Plusquamperfekt عندما نحتاج توضيح أن حدثًا اكتمل قبل حدث ماضٍ آخر."
      },
      {
        "id": "b1-03-m3",
        "promptDe": "nachdem",
        "promptAr": "اختر الصيغة الصحيحة لحالة «nachdem»:",
        "options": [
          "Nachdem sie hatte gelernt, sie bestand.",
          "Nachdem gelernt sie, bestand.",
          "Nachdem sie gelernt hatte, bestand sie.",
          "Sie nachdem hatte gelernt."
        ],
        "correctIndex": 2,
        "explanationAr": "الفعل المصرف آخر جملة nachdem. تقدم nachdem الحدث الذي اكتمل أولًا: Nachdem sie den Kurs beendet hatte, bekam sie ein Angebot."
      },
      {
        "id": "b1-03-m4",
        "promptDe": "seitdem",
        "promptAr": "أفضل أثر:",
        "options": [
          "Seitdem alles anders.",
          "Seitdem war gestern.",
          "Seitdem ich prüfe alles.",
          "Seitdem prüfe ich wöchentlich meinen Plan."
        ],
        "correctIndex": 3,
        "explanationAr": "سلوك مستمر واضح. تقدم nachdem الحدث الذي اكتمل أولًا: Nachdem sie den Kurs beendet hatte, bekam sie ein Angebot."
      },
      {
        "id": "b1-03-m5",
        "promptDe": "Zeitfolge",
        "promptAr": "أي خيار يحقّق «Zeitfolge» في هذا السياق؟",
        "options": [
          "Vorbereitung im Plusquamperfekt, Wendepunkt im Erzähltempus",
          "Alle Ereignisse im Plusquamperfekt",
          "Keine zeitlichen Verbindungen",
          "seitdem"
        ],
        "correctIndex": 0,
        "explanationAr": "فصل الطبقات الزمنية: الحدث الأسبق من نقطة التحول يُروى في Plusquamperfekt، ونقطة التحول نفسها في زمن القصّ Präteritum، فيعرف القارئ ما وقع قبل وما وقع بعد."
      }
    ]
  },
  {
    "id": "b1-04",
    "level": "B1",
    "module": 2,
    "titleDe": "Teamarbeit",
    "titleAr": "العمل الجماعي",
    "questions": [
      {
        "id": "b1-04-m1",
        "promptDe": "Passiv",
        "promptAr": "اختر التعبير المطابق لـ«Passiv»:",
        "options": [
          "Der Plan wird erstellt.",
          "Der Plan wird erstellen.",
          "Der Plan erstellt wird er.",
          "Der Plan ist erstellen."
        ],
        "correctIndex": 0,
        "explanationAr": "werden + Partizip. يتكون Passiv الإجرائي في الحاضر من werden مصرفًا وPartizip II في النهاية: Die Texte werden geprüft."
      },
      {
        "id": "b1-04-m2",
        "promptDe": "Plural",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Plural»:",
        "options": [
          "Die Texte wird geprüft.",
          "Die Texte werden geprüft.",
          "Die Texte werden prüfen.",
          "Die Texte sind prüfen."
        ],
        "correctIndex": 1,
        "explanationAr": "Plural: werden. يتكون Passiv الإجرائي في الحاضر من werden مصرفًا وPartizip II في النهاية: Die Texte werden geprüft."
      },
      {
        "id": "b1-04-m3",
        "promptDe": "Agens",
        "promptAr": "أي خيار يحقّق «Agens» في هذا السياق؟",
        "options": [
          "mit Mara",
          "für Mara",
          "von Mara",
          "zu Mara"
        ],
        "correctIndex": 2,
        "explanationAr": "von + Dativ للمنفذ. كل مهمة واضحة تحتاج مسؤولًا واحدًا أساسيًا، ومخرجًا قابلًا للفحص، وموعدًا، واعتمادًا على مهام أخرى."
      },
      {
        "id": "b1-04-m4",
        "promptDe": "Klare Aufgabe",
        "promptAr": "الأفضل:",
        "options": [
          "Alle machen alles.",
          "Technik irgendwann.",
          "Man kümmert sich.",
          "Ben testet das Mikrofon bis Donnerstag."
        ],
        "correctIndex": 3,
        "explanationAr": "مسؤول ومخرج وموعد. كل مهمة واضحة تحتاج مسؤولًا واحدًا أساسيًا، ومخرجًا قابلًا للفحص، وموعدًا، واعتمادًا على مهام أخرى."
      },
      {
        "id": "b1-04-m5",
        "promptDe": "Feedback",
        "promptAr": "الأفضل:",
        "options": [
          "Du bist schlecht.",
          "Immer machst du Fehler.",
          "Die Datei war spät; dadurch wartete das Team. Bitte informiere früher.",
          "Alles war falsch."
        ],
        "correctIndex": 2,
        "explanationAr": "سلوك وأثر وخطوة. ابدأ بموقف محدد: Mir ist aufgefallen, dass die Datei zweimal spät kam."
      }
    ]
  },
  {
    "id": "b1-05",
    "level": "B1",
    "module": 2,
    "titleDe": "Konflikte",
    "titleAr": "الخلافات",
    "questions": [
      {
        "id": "b1-05-m1",
        "promptDe": "Beobachtung",
        "promptAr": "اختر التعبير المطابق لـ«Beobachtung» في درس «الخلافات»:",
        "options": [
          "Die Datei kam am Freitag.",
          "Du warst unpünktlich.",
          "Der Termin war schlecht gewählt.",
          "Die Datei kam ohne jede Abstimmung."
        ],
        "correctIndex": 0,
        "explanationAr": "حدث قابل للتحقق: Die Datei kam am Freitag. يمكن إثباته أو نفيه من سجل الإرسال، بخلاف «Du warst unpünktlich» الذي يحكم على الشخص. اذكر الحدث وتاريخه لا انطباعك."
      },
      {
        "id": "b1-05-m2",
        "promptDe": "obwohl",
        "promptAr": "اختر الصيغة الصحيحة لحالة «obwohl»:",
        "options": [
          "Weil er wenig Zeit hatte, dass er half.",
          "Er half, dass er wenig Zeit hatte.",
          "Obwohl wenig Zeit, half er sofort.",
          "Obwohl er wenig Zeit hatte, half er."
        ],
        "correctIndex": 3,
        "explanationAr": "الفعل في نهاية الجملة الفرعية. obwohl تبدأ جملة فرعية والفعل في نهايتها: Obwohl Jonas geschrieben hatte, sah Mariam die Nachricht nicht."
      },
      {
        "id": "b1-05-m3",
        "promptDe": "trotzdem",
        "promptAr": "أي خيار يحقّق «trotzdem» في هذا السياق؟",
        "options": [
          "Trotzdem fanden wir eine Lösung.",
          "Trotzdem wir fanden eine Lösung.",
          "Trotzdem eine Lösung wir.",
          "Wir trotzdem Lösung fanden."
        ],
        "correctIndex": 0,
        "explanationAr": "الفعل بعد trotzdem. obwohl تبدأ جملة فرعية والفعل في نهايتها: Obwohl Jonas geschrieben hatte, sah Mariam die Nachricht nicht."
      },
      {
        "id": "b1-05-m4",
        "promptDe": "Vorschlag",
        "promptAr": "اختر التعبير المطابق لـ«Vorschlag»:",
        "options": [
          "Wir müssen die Änderung sofort bestätigen.",
          "Wir könnten direkt bestätigen.",
          "Bestätige das sofort.",
          "Du hast die Änderung wieder nicht bestätigt."
        ],
        "correctIndex": 1,
        "explanationAr": "يفتح التفاوض. استعمل könnten أو würde لاقتراح لا يفرض الحل: Wir könnten zusätzlich anrufen."
      },
      {
        "id": "b1-05-m5",
        "promptDe": "Vereinbarung",
        "promptAr": "الأفضل:",
        "options": [
          "Ab morgen gilt die neue Regel für immer, ohne weitere Abstimmung.",
          "Wir testen die Regel zwei Wochen und prüfen sie Freitag.",
          "Wir sprechen über die Regel und verschieben alles auf nächsten Monat.",
          "Die Regel wird getestet, wenn alle zustimmen."
        ],
        "correctIndex": 1,
        "explanationAr": "مدة وموعد مراجعة. obwohl تبدأ جملة فرعية والفعل في نهايتها: Obwohl Jonas geschrieben hatte, sah Mariam die Nachricht nicht."
      }
    ]
  },
  {
    "id": "b1-06",
    "level": "B1",
    "module": 2,
    "titleDe": "Bewerbungsgespräch",
    "titleAr": "مقابلة عمل",
    "questions": [
      {
        "id": "b1-06-m1",
        "promptDe": "STAR",
        "promptAr": "أي جزء يصف ما فعلته؟",
        "options": [
          "Situation",
          "Handlung",
          "Aufgabe",
          "Ergebnis"
        ],
        "correctIndex": 1,
        "explanationAr": "Handlung. يبني نموذج STAR جوابًا واضحًا: Situation تعطي السياق، Aufgabe تحدد مسؤوليتك، Handlung تشرح ما فعلته أنت، Ergebnis يوضح النتيجة أو التعلم."
      },
      {
        "id": "b1-06-m2",
        "promptDe": "Beleg",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Beleg»:",
        "options": [
          "Ich bin organisiert.",
          "Organisation ist gut.",
          "Ich koordinierte fünf Termine und hielt alle Fristen ein.",
          "Alle sagen das."
        ],
        "correctIndex": 2,
        "explanationAr": "فعل ونتيجة: Ich koordinierte fünf Termine und hielt alle Fristen ein. الفعل المحدد والعدد يثبتان القدرة. لا تكتفِ بـIch bin organisiert لأنها دعوى بلا دليل."
      },
      {
        "id": "b1-06-m3",
        "promptDe": "Ergebnis",
        "promptAr": "أي خيار يحقّق «Ergebnis» في هذا السياق؟",
        "options": [
          "Der Lieferant fiel aus.",
          "Ich musste Ersatz finden.",
          "Ich verglich Anbieter.",
          "Der Termin blieb pünktlich und im Budget."
        ],
        "correctIndex": 3,
        "explanationAr": "هذه النتيجة. يبني نموذج STAR جوابًا واضحًا: Situation تعطي السياق، Aufgabe تحدد مسؤوليتك، Handlung تشرح ما فعلته أنت، Ergebnis يوضح النتيجة أو التعلم."
      },
      {
        "id": "b1-06-m4",
        "promptDe": "Entwicklungsfeld",
        "promptAr": "الأفضل:",
        "options": [
          "Spontane Präsentationen sind schwierig; ich übe wöchentlich.",
          "Ich habe keine Schwächen.",
          "Perfektionismus",
          "Alles ist schwierig."
        ],
        "correctIndex": 0,
        "explanationAr": "جانب وإجراء: Spontane Präsentationen sind schwierig; ich übe wöchentlich. اذكر نقطة تطوير واقعية ثم الخطوة التي تعمل عليها، ولا تقل إنك بلا ضعف فذلك يوقف التقدم."
      },
      {
        "id": "b1-06-m5",
        "promptDe": "Rückfrage",
        "promptAr": "اختر التعبير المطابق لـ«Rückfrage»:",
        "options": [
          "Woran wird Erfolg gemessen?",
          "Was macht die Firma?",
          "Ist die Arbeit leicht?",
          "Bekomme ich sicher die Stelle?"
        ],
        "correctIndex": 0,
        "explanationAr": "سؤال مهني مفيد. في نهاية المقابلة اسأل عن المهام والأولويات والفريق والتدريب وطريقة قياس النجاح والخطوة التالية."
      }
    ]
  },
  {
    "id": "b1-07",
    "level": "B1",
    "module": 3,
    "titleDe": "Stadt oder Land?",
    "titleAr": "المدينة أم الريف؟",
    "questions": [
      {
        "id": "b1-07-m1",
        "promptDe": "während",
        "promptAr": "اختر الصيغة الصحيحة لحالة «während»:",
        "options": [
          "während ist das Land ruhig",
          "während das Land ist ruhig",
          "während das Land ruhig ist",
          "während ruhig das Land"
        ],
        "correctIndex": 2,
        "explanationAr": "الفعل في النهاية. تستعمل während هنا لمقابلة واقعين: In der Stadt gibt es viele Angebote, während das Land mehr Ruhe bietet."
      },
      {
        "id": "b1-07-m2",
        "promptDe": "je … desto",
        "promptAr": "أي خيار يحقّق «je … desto» في هذا السياق؟",
        "options": [
          "Je weiter ist der Weg, desto er länger dauert.",
          "Je der Weg weiter, desto dauert länger.",
          "Weiter je, länger desto.",
          "Je weiter der Weg ist, desto länger dauert er."
        ],
        "correctIndex": 3,
        "explanationAr": "ترتيب صحيح. تربط je … desto متغيرين: Je weiter man vom Zentrum wohnt, desto günstiger ist oft die Miete."
      },
      {
        "id": "b1-07-m3",
        "promptDe": "Kontrast",
        "promptAr": "اختر التعبير المطابق لـ«Kontrast»:",
        "options": [
          "Die Miete ist niedriger; dafür ist der Weg länger.",
          "Die Miete niedriger während der Weg",
          "Dafür der Weg ist länger und die Miete viel niedriger",
          "Niedriger als dafür die Miete und Weg"
        ],
        "correctIndex": 0,
        "explanationAr": "dafür في الخانة الأولى والفعل ثانيًا. تربط je … desto متغيرين: Je weiter man vom Zentrum wohnt, desto günstiger ist oft die Miete."
      },
      {
        "id": "b1-07-m4",
        "promptDe": "Differenziert",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Differenziert»:",
        "options": [
          "Für alle Menschen ist das Land immer besser geeignet",
          "Alle Stadtbewohner sind gestresst und unzufrieden",
          "Dörfer sind grundsätzlich billig und laut",
          "Für Familien kann mehr Platz wichtiger sein."
        ],
        "correctIndex": 3,
        "explanationAr": "صياغة محددة وغير مطلقة. استعمل معايير وقيودًا: Für meine aktuelle Situation ist … wichtiger، Unter der Bedingung, dass …، Wenn ich täglich pendeln müsste …."
      },
      {
        "id": "b1-07-m5",
        "promptDe": "Bedingung",
        "promptAr": "أي خيار يحقّق «Bedingung» في هذا السياق؟",
        "options": [
          "Wenn der Zug regelmäßig fährt, würde ich dort wohnen.",
          "Wenn regelmäßig der Zug fahren würde, dann dort ich wohnen",
          "Ich dort wohnen würde, wenn der Zug regelmäßig",
          "Zug fährt regelmäßig, dann ich dort wohnen würde"
        ],
        "correctIndex": 0,
        "explanationAr": "شرط وقرار افتراضي. استعمل معايير وقيودًا: Für meine aktuelle Situation ist … wichtiger، Unter der Bedingung, dass …، Wenn ich täglich pendeln müsste …."
      }
    ]
  },
  {
    "id": "b1-08",
    "level": "B1",
    "module": 3,
    "titleDe": "Mietprobleme",
    "titleAr": "مشكلات الإيجار",
    "questions": [
      {
        "id": "b1-08-m1",
        "promptDe": "Nominativ",
        "promptAr": "اختر التعبير المطابق لـ«Nominativ»:",
        "options": [
          "der Techniker, den kommt",
          "der Techniker, der kommt",
          "der Techniker, dem kommt",
          "der Techniker, die kommt"
        ],
        "correctIndex": 1,
        "explanationAr": "الضمير فاعل. يأخذ الضمير الموصول جنس وعدد الاسم السابق، لكن حالته تأتي من وظيفته داخل الجملة."
      },
      {
        "id": "b1-08-m2",
        "promptDe": "Akkusativ",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Akkusativ»:",
        "options": [
          "der Techniker, der ich anrufe",
          "der Techniker, dem ich anrufe",
          "der Techniker, den ich anrufe",
          "den Techniker, die ich"
        ],
        "correctIndex": 2,
        "explanationAr": "مفعول مذكر: den. يأخذ الضمير الموصول جنس وعدد الاسم السابق، لكن حالته تأتي من وظيفته داخل الجملة."
      },
      {
        "id": "b1-08-m3",
        "promptDe": "Dativ feminin",
        "promptAr": "أي خيار يحقّق «Dativ feminin» في هذا السياق؟",
        "options": [
          "die Firma, die ich schreibe",
          "die Firma, der ich schreibe",
          "die Firma, den ich schreibe",
          "die Firma, dem ich schreibe"
        ],
        "correctIndex": 1,
        "explanationAr": "Dativ مؤنث: der. يأخذ الضمير الموصول جنس وعدد الاسم السابق، لكن حالته تأتي من وظيفته داخل الجملة."
      },
      {
        "id": "b1-08-m4",
        "promptDe": "Dokumentation",
        "promptAr": "الأقوى:",
        "options": [
          "seit Montag zweimal, morgens 15 Grad",
          "immer kalt",
          "sehr schlecht",
          "Eine Katastrophe"
        ],
        "correctIndex": 0,
        "explanationAr": "محدد وقابل للتحقق. سجل مكان العيب ووقت بدايته وتكراره وأثره ومحاولات التواصل، وأرفق دليلًا مناسبًا دون بيانات زائدة."
      },
      {
        "id": "b1-08-m5",
        "promptDe": "Reparaturbitte",
        "promptAr": "اختر التعبير المطابق لـ«Reparaturbitte»:",
        "options": [
          "Alles sofort!",
          "Sie kennen das Gesetz sicher.",
          "Keine Details nötig.",
          "Bitte teilen Sie mir bis Freitag einen Termin mit."
        ],
        "correctIndex": 3,
        "explanationAr": "طلب وموعد رد. اطلب فحصًا أو إصلاحًا وحدد مهلة واقعية للرد، ثم اطلب حلًا مؤقتًا إذا لزم."
      }
    ]
  },
  {
    "id": "b1-09",
    "level": "B1",
    "module": 3,
    "titleDe": "Stadtentwicklung",
    "titleAr": "تطوير المدينة",
    "questions": [
      {
        "id": "b1-09-m1",
        "promptDe": "indem",
        "promptAr": "اختر الصيغة الصحيحة لحالة «indem» في درس «تطوير المدينة»:",
        "options": [
          "indem wir schützen den Radweg",
          "indem wir den Radweg schützen",
          "indem schützen wir",
          "wir indem Radweg"
        ],
        "correctIndex": 1,
        "explanationAr": "الفعل في النهاية. تستعمل indem للإجابة عن كيف يتحقق شيء: Wir erhöhen die Sicherheit, indem wir einen Radweg bauen."
      },
      {
        "id": "b1-09-m2",
        "promptDe": "Ziel vs Indikator",
        "promptAr": "اختر المؤشر:",
        "options": [
          "mehr Sicherheit",
          "bessere Stadt",
          "weniger gezählte Unfälle",
          "schönere Zukunft"
        ],
        "correctIndex": 2,
        "explanationAr": "عدد الحوادث قابل للقياس: weniger gezählte Unfälle. الهدف العام مثل sicherer أو schöner لا يُقاس، أما العدد فيقبل الرصد والمقارنة قبل الإجراء وبعده."
      },
      {
        "id": "b1-09-m3",
        "promptDe": "Pilot",
        "promptAr": "الأفضل:",
        "options": [
          "Eine endgültige Entscheidung im Namen eines Versuchs",
          "Ohne Messung",
          "Nur eine Seite",
          "Dauer, Daten, Kriterien und Anpassung"
        ],
        "correctIndex": 3,
        "explanationAr": "تصميم قابل للتقييم. تستعمل indem للإجابة عن كيف يتحقق شيء: Wir erhöhen die Sicherheit, indem wir einen Radweg bauen."
      },
      {
        "id": "b1-09-m4",
        "promptDe": "Passiv",
        "promptAr": "أي خيار يحقّق «Passiv» في هذا السياق؟",
        "options": [
          "Die Daten werden veröffentlicht.",
          "Die Daten werden veröffentlichen.",
          "Die Daten veröffentlicht werden sie.",
          "Die Daten sind veröffentlichen."
        ],
        "correctIndex": 0,
        "explanationAr": "werden + Partizip. تستعمل indem للإجابة عن كيف يتحقق شيء: Wir erhöhen die Sicherheit, indem wir einen Radweg bauen."
      },
      {
        "id": "b1-09-m5",
        "promptDe": "Perspektiven",
        "promptAr": "الأفضل:",
        "options": [
          "Nur die Meinung der Planer",
          "Die Mehrheit ohne Wirkung",
          "Anwohner, Geschäfte, Verkehr und Barrierefreiheit",
          "Keine Risiken"
        ],
        "correctIndex": 2,
        "explanationAr": "فئات وتأثيرات متعددة. تستعمل indem للإجابة عن كيف يتحقق شيء: Wir erhöhen die Sicherheit, indem wir einen Radweg bauen."
      }
    ]
  },
  {
    "id": "b1-10",
    "level": "B1",
    "module": 4,
    "titleDe": "Konsum",
    "titleAr": "الاستهلاك",
    "questions": [
      {
        "id": "b1-10-m1",
        "promptDe": "statt",
        "promptAr": "اختر التعبير المطابق لـ«statt»:",
        "options": [
          "statt neu zu kaufen",
          "statt ich neu kaufe",
          "statt zu neu kaufen",
          "statt kaufen neu"
        ],
        "correctIndex": 0,
        "explanationAr": "مصدر مع zu. نستعمل statt … zu عندما يقوم الفاعل بفعل بدل فعل آخر: Statt ein neues Gerät zu kaufen, repariert sie das alte."
      },
      {
        "id": "b1-10-m2",
        "promptDe": "ohne",
        "promptAr": "اختر الصيغة الصحيحة لحالة «ohne»:",
        "options": [
          "ohne zu die Preise vergleichen",
          "ohne vergleicht Preise",
          "ohne Preise vergleichen hat",
          "ohne die Preise zu vergleichen"
        ],
        "correctIndex": 3,
        "explanationAr": "ترتيب صحيح. تصف ohne … zu فعلًا حدث من دون فعل آخر متوقع: Sie bestellt, ohne die Preise zu vergleichen."
      },
      {
        "id": "b1-10-m3",
        "promptDe": "wegwerfen + zu",
        "promptAr": "أي خيار يحقّق «wegwerfen + zu» في هذا السياق؟",
        "options": [
          "zu wegwerfen",
          "wegwerfen zu",
          "wegzuwerfen",
          "gewegzuwerfen"
        ],
        "correctIndex": 2,
        "explanationAr": "wegzuwerfen. نستعمل statt … zu عندما يقوم الفاعل بفعل بدل فعل آخر: Statt ein neues Gerät zu kaufen, repariert sie das alte."
      },
      {
        "id": "b1-10-m4",
        "promptDe": "Gesamtkosten",
        "promptAr": "تشمل:",
        "options": [
          "Kauf",
          "Kauf, Nutzung, Wartung und Reparatur",
          "Nur der Rabatt",
          "Die Werbung"
        ],
        "correctIndex": 1,
        "explanationAr": "تكلفة دورة الاستخدام. قارن الحاجة والعمر المتوقع والإصلاح والطاقة والضمان وإعادة البيع والتخلص."
      },
      {
        "id": "b1-10-m5",
        "promptDe": "Informiert entscheiden",
        "promptAr": "الأفضل:",
        "options": [
          "Angebot sofort nehmen",
          "Werbung glauben",
          "Bedarf, Optionen und Lebensdauer prüfen",
          "Reparatur ignorieren"
        ],
        "correctIndex": 2,
        "explanationAr": "قرار متعدد المعايير. تصف ohne … zu فعلًا حدث من دون فعل آخر متوقع: Sie bestellt, ohne die Preise zu vergleichen."
      }
    ]
  },
  {
    "id": "b1-11",
    "level": "B1",
    "module": 4,
    "titleDe": "Mobilität",
    "titleAr": "التنقل المستدام",
    "questions": [
      {
        "id": "b1-11-m1",
        "promptDe": "dadurch, dass",
        "promptAr": "اختر التعبير المطابق لـ«dadurch, dass»:",
        "options": [
          "dadurch, dass fahren weniger Autos",
          "dadurch indem Autos",
          "dass dadurch Autos fahren weniger",
          "dadurch, dass weniger Autos fahren"
        ],
        "correctIndex": 3,
        "explanationAr": "التركيب „dadurch, dass weniger Autos fahren“ صحيح: dass تفتح جملة فرعية يذهب فعلها fahren إلى النهاية. والخيارات الأخرى تخلط بين dadurch وindem أو تقدّم الفعل قبل الفاعل."
      },
      {
        "id": "b1-11-m2",
        "promptDe": "indem",
        "promptAr": "اختر الصيغة الصحيحة لحالة «indem» في درس «التنقل المستدام»:",
        "options": [
          "indem kombinieren wir Wege",
          "indem Wege wir kombinieren sie",
          "indem wir Wege kombinieren",
          "wir indem Wege"
        ],
        "correctIndex": 2,
        "explanationAr": "الترتيب الصحيح „indem wir Wege kombinieren“: indem في الموقع الأول ثم الفاعل wir ثم المفعول ثم الفعل kombinieren في النهاية، وindem تربط الوسيلة بالنتيجة."
      },
      {
        "id": "b1-11-m3",
        "promptDe": "Nicht kombinieren",
        "promptAr": "اختر الصحيح:",
        "options": [
          "dadurch, indem",
          "dadurch, dass",
          "indem, dass",
          "dass indem"
        ],
        "correctIndex": 1,
        "explanationAr": "dadurch, dass بنية واحدة. نستعمل dadurch, dass لشرح كيف حدثت نتيجة: Die Emissionen sinken dadurch, dass weniger Autos fahren."
      },
      {
        "id": "b1-11-m4",
        "promptDe": "Daten",
        "promptAr": "الأفضل:",
        "options": [
          "Nur der Durchschnitt",
          "Keine Hinweise",
          "Durchschnitt plus Gruppenunterschiede",
          "Erfolg für alle angenommen"
        ],
        "correctIndex": 2,
        "explanationAr": "تقسيم النتائج: Durchschnitt plus Gruppenunterschiede. المتوسط وحده يخفي اختلاف المجموعات، فقد يتحسن المتوسط ويبقى ضعف في مجموعة بعينها؛ اعرض الاثنين معًا."
      },
      {
        "id": "b1-11-m5",
        "promptDe": "Inklusiv",
        "promptAr": "الأفضل:",
        "options": [
          "عدة بدائل مع فحص الوصول",
          "دراجة للجميع",
          "سيارة للجميع",
          "تجاهل الليل"
        ],
        "correctIndex": 0,
        "explanationAr": "حزمة خيارات: عدة بدائل مع فحص الوصول. حل واحد للجميع لا يحقق الشمول، والشرط ألا يُستبعد أحد بسبب الليل أو السعر أو صعوبة الحركة."
      }
    ]
  },
  {
    "id": "b1-12",
    "level": "B1",
    "module": 4,
    "titleDe": "Eine Initiative",
    "titleAr": "مبادرة",
    "questions": [
      {
        "id": "b1-12-m1",
        "promptDe": "Aktivität",
        "promptAr": "أي خيار يحقّق «Aktivität» في هذا السياق؟",
        "options": [
          "Tauschmarkt organisieren",
          "Den Abfall im Viertel reduzieren",
          "Bewohner",
          "Die Termine verschieben"
        ],
        "correctIndex": 0,
        "explanationAr": "هذا نشاط: Tauschmarkt organisieren. ابدأ بمشكلة محددة وفئة متأثرة، فالنشاط إجراء ملموس. أما Bewohner فوصف للفئة، وdie Termine verschieben لا يعالج المشكلة."
      },
      {
        "id": "b1-12-m2",
        "promptDe": "Indikator",
        "promptAr": "اختر التعبير المطابق لـ«Indikator»:",
        "options": [
          "Gute Idee",
          "Schöne Zukunft für alle",
          "Zahl getauschter Dinge",
          "Motivation der Freiwilligen"
        ],
        "correctIndex": 2,
        "explanationAr": "قابل للقياس: Zahl getauschter Dinge. عدد الأشياء المتبادلة يمكن رصده ومقارنته قبل المشروع وبعده، بخلاف Gute Idee أو Schöne Zukunft التي لا تُقاس."
      },
      {
        "id": "b1-12-m3",
        "promptDe": "falls",
        "promptAr": "اختر الصيغة الصحيحة لحالة «falls»:",
        "options": [
          "Falls es wird regnen, nutzen wir innen Platz",
          "Falls es regnet, nutzen wir den Innenraum.",
          "Falls regnet es, den Innenraum wir nutzen",
          "Wir nutzen den Innenraum"
        ],
        "correctIndex": 1,
        "explanationAr": "فعل الشرط في النهاية. تستعمل falls بمعنى «في حال» عندما نعرض احتمالًا ونتيجته: Falls der Raum nicht frei ist, nutzen wir die Schule."
      },
      {
        "id": "b1-12-m4",
        "promptDe": "Risiko",
        "promptAr": "الأفضل:",
        "options": [
          "Wir hoffen einfach, dass genug Leute kommen",
          "Einen Plan B brauchen wir für solche Fälle wirklich nicht",
          "Falls zu wenige kommen, verkürzen wir das Programm.",
          "Danach entscheiden wir, was wir machen können"
        ],
        "correctIndex": 2,
        "explanationAr": "خطر وخطة B. تستعمل falls بمعنى «في حال» عندما نعرض احتمالًا ونتيجته: Falls der Raum nicht frei ist, nutzen wir die Schule."
      },
      {
        "id": "b1-12-m5",
        "promptDe": "Bilanz",
        "promptAr": "يجب أن تشمل:",
        "options": [
          "Nur die positiven Ergebnisse",
          "Fotos ohne jegliche Zahlen",
          "Wirkung behaupten",
          "Erfolge und Probleme"
        ],
        "correctIndex": 3,
        "explanationAr": "حصيلة صادقة. ما يذكر الإيجابيات وحده لا يقيّم التجربة؛ اذكر الأثر والمشكلة معًا."
      }
    ]
  },
  {
    "id": "b1-13",
    "level": "B1",
    "module": 5,
    "titleDe": "Lernwege",
    "titleAr": "مسارات التعلم",
    "questions": [
      {
        "id": "b1-13-m1",
        "promptDe": "Nominalisierung",
        "promptAr": "اختر الصيغة الصحيحة للاسم المشتق بعد beim:",
        "options": [
          "im Lesen",
          "beim gelesen",
          "beim Lesen",
          "beim zu lesen"
        ],
        "correctIndex": 1,
        "explanationAr": "اسم بحرف كبير. beim اختصار bei dem، ويمكن أن يأتي بعده فعل محول إلى اسم: beim Lesen، beim Schreiben، beim Sprechen."
      },
      {
        "id": "b1-13-m2",
        "promptDe": "durch",
        "promptAr": "أي خيار يحقّق «durch» في هذا السياق؟",
        "options": [
          "durch ein Kurs",
          "durch einem Kurs",
          "durch einen Kurs",
          "durch der Kurs"
        ],
        "correctIndex": 2,
        "explanationAr": "Akkusativ مذكر. durch يطلب Akkusativ، والمذكر يبقى einen: durch einen Kurs."
      },
      {
        "id": "b1-13-m3",
        "promptDe": "Beleg",
        "promptAr": "الأفضل:",
        "options": [
          "Ich fühle mich besser.",
          "Die App ist toll.",
          "Ich lerne viel.",
          "Gleiche Aufgabe: mehr Wörter und weniger Pausen."
        ],
        "correctIndex": 3,
        "explanationAr": "مؤشرات قابلة للمقارنة. beim اختصار bei dem، ويمكن أن يأتي بعده فعل محول إلى اسم: beim Lesen، beim Schreiben، beim Sprechen."
      },
      {
        "id": "b1-13-m4",
        "promptDe": "Ursache vorsichtig",
        "promptAr": "اختر التعبير المطابق لـ«Ursache vorsichtig»:",
        "options": [
          "Das könnte an mehreren Faktoren liegen.",
          "Nur die App war sicher der Grund.",
          "Keine Daten nötig.",
          "Fortschritt hat nie Ursachen."
        ],
        "correctIndex": 0,
        "explanationAr": "لغة احتمالية دقيقة. قارن المهمة نفسها قبل وبعد: طول النص، عدد التوقفات، نسبة الإجابات الجديدة، نوع الأخطاء."
      },
      {
        "id": "b1-13-m5",
        "promptDe": "Experiment",
        "promptAr": "الأفضل:",
        "options": [
          "Alles gleichzeitig ändern.",
          "Einen Faktor ändern und dieselbe Aufgabe vergleichen.",
          "Nur Motivation messen.",
          "Keine Zeit festlegen."
        ],
        "correctIndex": 1,
        "explanationAr": "تصميم أبسط للاستنتاج: Einen Faktor ändern und dieselbe Aufgabe vergleichen. إذا تغيّر أكثر من عامل معًا لا تعرف أيها أحدث الفرق، فتُغيّر عاملًا واحدًا وتقيس بالمهمة نفسها."
      }
    ]
  },
  {
    "id": "b1-14",
    "level": "B1",
    "module": 5,
    "titleDe": "Weiterbildung",
    "titleAr": "التكوين المستمر",
    "questions": [
      {
        "id": "b1-14-m1",
        "promptDe": "lassen",
        "promptAr": "اختر الصيغة الصحيحة لحالة «lassen»:",
        "options": [
          "Ich lasse den Abschluss zu prüfen.",
          "Ich prüfen lasse Abschluss.",
          "Ich lasse geprüft den Abschluss.",
          "Ich lasse den Abschluss prüfen."
        ],
        "correctIndex": 3,
        "explanationAr": "مصدر بلا zu. نستعمل lassen + مصدر عندما نطلب أو نسمح لشخص آخر بتنفيذ فعل: Ich lasse die Unterlagen übersetzen."
      },
      {
        "id": "b1-14-m2",
        "promptDe": "Reflexiv",
        "promptAr": "أي خيار يحقّق «Reflexiv» في هذا السياق؟",
        "options": [
          "Wir lassen sich beraten.",
          "Wir beraten lassen uns falsch.",
          "Wir lassen uns beraten.",
          "Wir lassen uns zu beraten."
        ],
        "correctIndex": 2,
        "explanationAr": "wir → uns. نستعمل lassen + مصدر عندما نطلب أو نسمح لشخص آخر بتنفيذ فعل: Ich lasse die Unterlagen übersetzen."
      },
      {
        "id": "b1-14-m3",
        "promptDe": "Perfekt",
        "promptAr": "اختر التعبير المطابق لـ«Perfekt»:",
        "options": [
          "Ich habe prüfen gelassen den Vertrag.",
          "Ich ließ geprüft hat.",
          "Ich habe den Vertrag zu prüfen lassen.",
          "Ich habe den Vertrag prüfen lassen."
        ],
        "correctIndex": 3,
        "explanationAr": "مصدران في النهاية. نستعمل lassen + مصدر عندما نطلب أو نسمح لشخص آخر بتنفيذ فعل: Ich lasse die Unterlagen übersetzen."
      },
      {
        "id": "b1-14-m4",
        "promptDe": "Anerkennung",
        "promptAr": "السؤال الأدق:",
        "options": [
          "Wer erkennt den Abschluss für welchen Zweck an?",
          "Ist es stark?",
          "Ist er schön?",
          "Sagt die Werbung, dass es ausgezeichnet ist?"
        ],
        "correctIndex": 0,
        "explanationAr": "جهة وغرض. قد تكون وثيقة مفيدة للتعلم لكنها غير كافية لوظيفة أو جهة معينة."
      },
      {
        "id": "b1-14-m5",
        "promptDe": "Gesamtaufwand",
        "promptAr": "يشمل:",
        "options": [
          "Gebühr",
          "Das Logo",
          "Nur das Zertifikat",
          "Geld, Unterricht, Selbststudium, Fahrt und Prüfung"
        ],
        "correctIndex": 3,
        "explanationAr": "كل الموارد. قارن رسوم الدورة والمواد والامتحان والتنقل، إضافة إلى ساعات الدرس والدراسة الذاتية والمشروعات."
      }
    ]
  },
  {
    "id": "b1-15",
    "level": "B1",
    "module": 5,
    "titleDe": "Präsentieren",
    "titleAr": "تقديم عرض",
    "questions": [
      {
        "id": "b1-15-m1",
        "promptDe": "Roter Faden",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Roter Faden»:",
        "options": [
          "Titel–Witze–Musik–Applaus–Schluss",
          "Frage–Methode–Ergebnis–Grenze–Fazit",
          "Zahlen–Tabellen–Farben–Schriftart",
          "Begrüßung–Werbung–Danke–Verabschiedung"
        ],
        "correctIndex": 1,
        "explanationAr": "بنية منطقية. ابدأ بسؤال مركزي وقل لماذا يهم، ثم اعرض الطريقة أو الخلفية والأدلة والنتيجة والقيود."
      },
      {
        "id": "b1-15-m2",
        "promptDe": "Signal",
        "promptAr": "أي خيار يحقّق «Signal» في هذا السياق؟",
        "options": [
          "Anschließend zeige ich die Daten.",
          "Anschließend ich zeige die Daten.",
          "Anschließend die Daten ich zeige.",
          "Anschließend ich die Daten zeige."
        ],
        "correctIndex": 0,
        "explanationAr": "الفعل ثانيًا. ابدأ بسؤال مركزي وقل لماذا يهم، ثم اعرض الطريقة أو الخلفية والأدلة والنتيجة والقيود."
      },
      {
        "id": "b1-15-m3",
        "promptDe": "Grenze",
        "promptAr": "اختر التعبير المطابق لـ«Grenze» في درس «تقديم عرض»:",
        "options": [
          "Die Methode gilt für alle Gruppen gleichermaßen.",
          "Eine Einschränkung ist die kleine Gruppe.",
          "Grenzen sind für den Vortrag unwichtig.",
          "Keine Daten beweisen überhaupt etwas."
        ],
        "correctIndex": 1,
        "explanationAr": "قيد واضح. ابدأ بسؤال مركزي وقل لماذا يهم، ثم اعرض الطريقة أو الخلفية والأدلة والنتيجة والقيود."
      },
      {
        "id": "b1-15-m4",
        "promptDe": "Unbekannte Antwort",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Unbekannte Antwort»:",
        "options": [
          "Ich erfinde eine Zahl.",
          "Ich danke und überspringe die Frage.",
          "Dazu liegen mir keine Daten vor.",
          "Ich antworte mit einem sicheren Ja."
        ],
        "correctIndex": 2,
        "explanationAr": "صدق وحد معرفي. ضع فكرة واحدة وعنوانًا ورسمة أو نقاطًا قليلة في كل شريحة."
      },
      {
        "id": "b1-15-m5",
        "promptDe": "Folie",
        "promptAr": "الأفضل:",
        "options": [
          "Alle Details auf einer Folie",
          "Ein langer Fließtext darunter",
          "Kein Titel über der Grafik",
          "Eine Aussage und ein Beleg"
        ],
        "correctIndex": 3,
        "explanationAr": "دعم بصري مركز. ابدأ بسؤال مركزي وقل لماذا يهم، ثم اعرض الطريقة أو الخلفية والأدلة والنتيجة والقيود."
      }
    ]
  },
  {
    "id": "b1-16",
    "level": "B1",
    "module": 6,
    "titleDe": "Mediennutzung",
    "titleAr": "استخدام الإعلام",
    "questions": [
      {
        "id": "b1-16-m1",
        "promptDe": "Gleiches Subjekt",
        "promptAr": "أي خيار يحقّق «Gleiches Subjekt» في هذا السياق؟",
        "options": [
          "Statt dass ich sofort zu antworten, nur zu warten",
          "Statt ich antworte sofort und warte überhaupt nicht",
          "Statt sofort zu antworten, warte ich.",
          "Statt zu antworten und zu warten"
        ],
        "correctIndex": 2,
        "explanationAr": "فاعل واحد. نستعمل statt … zu عندما يقوم الشخص نفسه بالفعلين: Statt sofort zu antworten, sammle ich Nachrichten."
      },
      {
        "id": "b1-16-m2",
        "promptDe": "Verschiedene Subjekte",
        "promptAr": "اختر التعبير المطابق لـ«Verschiedene Subjekte»:",
        "options": [
          "Statt dass die App entscheidet, wähle ich selbst",
          "Statt die App entscheidet alles",
          "Die App statt ich wählt allein",
          "Statt dass die App entscheidet, wähle ich."
        ],
        "correctIndex": 3,
        "explanationAr": "فاعل مختلف مع dass. نستعمل statt … zu عندما يقوم الشخص نفسه بالفعلين: Statt sofort zu antworten, sammle ich Nachrichten."
      },
      {
        "id": "b1-16-m3",
        "promptDe": "Messung",
        "promptAr": "الأفضل:",
        "options": [
          "Nur die Uhrzeit allein und sonst nichts",
          "Das gute Gefühl allein genügt hier für eine ganze Analyse",
          "Dauer, Zeitpunkt, Unterbrechungen und Wirkung",
          "Der Typ des Telefons ist dafür entscheidend"
        ],
        "correctIndex": 2,
        "explanationAr": "قياس متعدد. افصل مقدار الاستخدام عن توقيته ونوعه وسياقه وأثره."
      },
      {
        "id": "b1-16-m4",
        "promptDe": "Experiment",
        "promptAr": "الأفضل:",
        "options": [
          "Alles gleichzeitig ohne Vergleich ändern",
          "Eine Dauer fehlt im Testplan",
          "Ohne Vergleich bleibt der Wert unklar",
          "Eine Regel sieben Tage testen."
        ],
        "correctIndex": 3,
        "explanationAr": "قاعدة ومدة. اختر مشكلة واحدة وقاعدة واحدة لمدة أسبوع أو أسبوعين."
      },
      {
        "id": "b1-16-m5",
        "promptDe": "nicht nur",
        "promptAr": "أكمل:",
        "options": [
          "sondern auch",
          "aber nur",
          "weder noch",
          "als ob"
        ],
        "correctIndex": 0,
        "explanationAr": "nicht nur … sondern auch: الإطار يقدّم طرفين معطوفين، فالتكملة الصحيحة sondern auch. أما aber nur وweder noch فتقلبان المعنى إلى استدراك أو نفي مزدوج."
      }
    ]
  },
  {
    "id": "b1-17",
    "level": "B1",
    "module": 6,
    "titleDe": "Film und Literatur",
    "titleAr": "الفيلم والأدب",
    "questions": [
      {
        "id": "b1-17-m1",
        "promptDe": "Partizip II",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Partizip II»:",
        "options": [
          "die erzählen Geschichte",
          "die erzählend Geschichte",
          "die Geschichte geerzählt",
          "die erzählte Geschichte"
        ],
        "correctIndex": 3,
        "explanationAr": "Partizip II كصفة. يمكن أن يعمل Partizip II كصفة قبل الاسم: die erzählte Geschichte، die gut gespielte Rolle، das sorgfältig geschriebene Buch."
      },
      {
        "id": "b1-17-m2",
        "promptDe": "Partizip I",
        "promptAr": "أي خيار يحقّق «Partizip I» في هذا السياق؟",
        "options": [
          "eine berührt Szene",
          "eine zu berühren Szene",
          "eine berührende Szene",
          "eine berührene Szene"
        ],
        "correctIndex": 2,
        "explanationAr": "berührend + e. يتكون Partizip I من المصدر + d: überzeugen → überzeugend، berühren → berührend."
      },
      {
        "id": "b1-17-m3",
        "promptDe": "überzeugen",
        "promptAr": "الفيلم مقنع:",
        "options": [
          "Der Film ist überzeugt.",
          "Der Film überzeugt gewesen Adjektiv.",
          "Der überzeugte Film mich ist.",
          "Der Film ist überzeugend."
        ],
        "correctIndex": 3,
        "explanationAr": "überzeugend. يمكن أن يعمل Partizip II كصفة قبل الاسم: die erzählte Geschichte، die gut gespielte Rolle، das sorgfältig geschriebene Buch."
      },
      {
        "id": "b1-17-m4",
        "promptDe": "Beleg",
        "promptAr": "الأفضل:",
        "options": [
          "Die Atmosphäre ist gut.",
          "Die langen stillen Einstellungen erzeugen eine angespannte Atmosphäre.",
          "Alles ist toll.",
          "Ich mag es einfach."
        ],
        "correctIndex": 1,
        "explanationAr": "معيار ودليل. يمكن أن يعمل Partizip II كصفة قبل الاسم: die erzählte Geschichte، die gut gespielte Rolle، das sorgfältig geschriebene Buch."
      },
      {
        "id": "b1-17-m5",
        "promptDe": "Empfehlung",
        "promptAr": "الأدق:",
        "options": [
          "Für alle geeignet.",
          "Wer es nicht mag, versteht nichts.",
          "Geeignet für Fans ruhiger Dramen.",
          "Der beste Film sicher."
        ],
        "correctIndex": 2,
        "explanationAr": "جمهور محدد. لخص الفرضية الأساسية دون النهاية، ثم قيّم عناصر محددة: الحبكة والشخصيات واللغة والإيقاع."
      }
    ]
  },
  {
    "id": "b1-18",
    "level": "B1",
    "module": 6,
    "titleDe": "Informationen prüfen",
    "titleAr": "التحقق من المعلومات",
    "questions": [
      {
        "id": "b1-18-m1",
        "promptDe": "Distanz",
        "promptAr": "اختر التعبير المطابق لـ«Distanz»:",
        "options": [
          "Die Methode soll helfen.",
          "Die Methode hilft sicher.",
          "Ich muss die Methode.",
          "Die Methode ist Fakt."
        ],
        "correctIndex": 0,
        "explanationAr": "sollen تنقل ادعاء. يمكن استعمال sollen لنقل معلومة سمعناها ولم نؤكدها: Die Methode soll das Lernen beschleunigen."
      },
      {
        "id": "b1-18-m2",
        "promptDe": "angeblich",
        "promptAr": "المعنى:",
        "options": [
          "مؤكد رسميًا",
          "ممنوع",
          "في الماضي",
          "كما يُزعم/غير مؤكد"
        ],
        "correctIndex": 3,
        "explanationAr": "angeblich تُبقي المعلومة منقولة بلا تأكيد: Das soll helfen أي هذا ما يُقال لا ما تحقّق منه. لا تخلطها بـ definitiv."
      },
      {
        "id": "b1-18-m3",
        "promptDe": "Primärquelle",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Primärquelle»:",
        "options": [
          "ursprüngliche Studie",
          "Blog über Blog",
          "Kommentar",
          "geteilte Überschrift"
        ],
        "correctIndex": 0,
        "explanationAr": "المصدر الأصلي. يمكن استعمال sollen لنقل معلومة سمعناها ولم نؤكدها: Die Methode soll das Lernen beschleunigen."
      },
      {
        "id": "b1-18-m4",
        "promptDe": "Begrenztes Urteil",
        "promptAr": "أي خيار يحقّق «Begrenztes Urteil» في هذا السياق؟",
        "options": [
          "Sicher für alle.",
          "Teilweise richtig, aber übertrieben.",
          "Ohne Beleg immer falsch.",
          "Titel reicht."
        ],
        "correctIndex": 1,
        "explanationAr": "يحافظ على النطاق. اكتب الادعاء بدقة، ثم ابحث عن المصدر الأولي، وافحص التاريخ والمؤلف والعينة والمقارنة والمقياس والمدة."
      },
      {
        "id": "b1-18-m5",
        "promptDe": "Reichweite",
        "promptAr": "السؤال الأفضل:",
        "options": [
          "Ist der Titel schön?",
          "Wer wurde womit und wie lange getestet?",
          "Nur wie viele Teilnehmende?",
          "Mag ich das Ergebnis?"
        ],
        "correctIndex": 1,
        "explanationAr": "عينة ومهمة ومدة: Wer wurde womit und wie lange getestet? السؤال يطلب وصف المجموعة والأداة والمدة، وهي شروط قراءة النتيجة وتقدير حدود التعميم."
      }
    ]
  },
  {
    "id": "b1-19",
    "level": "B1",
    "module": 7,
    "titleDe": "Missverständnisse",
    "titleAr": "سوء الفهم",
    "questions": [
      {
        "id": "b1-19-m1",
        "promptDe": "Person",
        "promptAr": "اختر التعبير المطابق لـ«Person» في درس «سوء الفهم»:",
        "options": [
          "Was bedeutest du?",
          "Was meinst du?",
          "Was heißt du das?",
          "Welche Bedeutung bist du?"
        ],
        "correctIndex": 1,
        "explanationAr": "نية الشخص: meinen. نستعمل meinen للسؤال عما يقصده شخص: Was meinst du? ونستعمل bedeuten للسؤال عن معنى كلمة أو علامة أو صياغة: Was bedeutet diese Abkürzung? يمكن أن نقول Ich meinte, dass … لنوضح نيتنا."
      },
      {
        "id": "b1-19-m2",
        "promptDe": "Wort",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Wort»:",
        "options": [
          "Was meint das Wort als Person?",
          "Was bedeutest du Wort?",
          "Was bedeutet das Wort?",
          "Das Wort meinen was?"
        ],
        "correctIndex": 2,
        "explanationAr": "معنى الشيء: bedeuten. نستعمل meinen للسؤال عما يقصده شخص: Was meinst du? ونستعمل bedeuten للسؤال عن معنى كلمة أو علامة أو صياغة: Was bedeutet diese Abkürzung? يمكن أن نقول Ich meinte, dass … لنوضح نيتنا."
      },
      {
        "id": "b1-19-m3",
        "promptDe": "ob",
        "promptAr": "أي خيار يحقّق «ob» في هذا السياق؟",
        "options": [
          "ob ist der Termin morgen",
          "ob morgen ist der Termin",
          "ob der Termin ist morgen er",
          "ob der Termin morgen ist"
        ],
        "correctIndex": 3,
        "explanationAr": "الفعل في النهاية. نستعمل meinen للسؤال عما يقصده شخص: Was meinst du? ونستعمل bedeuten للسؤال عن معنى كلمة أو علامة أو صياغة: Was bedeutet diese Abkürzung? يمكن أن نقول Ich meinte, dass … لنوضح نيتنا."
      },
      {
        "id": "b1-19-m4",
        "promptDe": "Paraphrase",
        "promptAr": "الأفضل:",
        "options": [
          "Wenn ich dich richtig verstehe, brauchst du es Donnerstag.",
          "Alles klar?",
          "Du erklärst schlecht.",
          "Ich verstehe sicher alles."
        ],
        "correctIndex": 0,
        "explanationAr": "تلخيص قابل للتأكيد. بدل قول Du hast falsch erklärt، لخص فهمك: Wenn ich dich richtig verstehe, brauchst du die Datei Donnerstagabend."
      },
      {
        "id": "b1-19-m5",
        "promptDe": "Korrektur",
        "promptAr": "اختر التعبير المطابق لـ«Korrektur»:",
        "options": [
          "nicht Freitag, aber Donnerstag",
          "weder Freitag sondern",
          "nicht Freitag, sondern Donnerstag",
          "Freitag nicht Donnerstag"
        ],
        "correctIndex": 2,
        "explanationAr": "nicht … sondern. بدل قول Du hast falsch erklärt، لخص فهمك: Wenn ich dich richtig verstehe, brauchst du die Datei Donnerstagabend."
      }
    ]
  },
  {
    "id": "b1-20",
    "level": "B1",
    "module": 7,
    "titleDe": "Ratschläge",
    "titleAr": "النصائح",
    "questions": [
      {
        "id": "b1-20-m1",
        "promptDe": "Rat",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Rat»:",
        "options": [
          "Du musst genau das tun, sonst klappt nichts",
          "Ich entscheide für dich und nicht umgekehrt",
          "Fragen sind dafür nicht nötig",
          "An deiner Stelle würde ich nachfragen."
        ],
        "correctIndex": 3,
        "explanationAr": "نصيحة افتراضية. نستعمل An deiner Stelle würde ich … وDu könntest … وEine Möglichkeit wäre … لعرض خيارات."
      },
      {
        "id": "b1-20-m2",
        "promptDe": "Möglichkeit",
        "promptAr": "أي خيار يحقّق «Möglichkeit» في هذا السياق؟",
        "options": [
          "Eine Möglichkeit ist du musst …",
          "Möglich wäre tut.",
          "Eine Möglichkeit wäre …",
          "Du Möglichkeit."
        ],
        "correctIndex": 2,
        "explanationAr": "صيغة خيار. نستعمل An deiner Stelle würde ich … وDu könntest … وEine Möglichkeit wäre … لعرض خيارات."
      },
      {
        "id": "b1-20-m3",
        "promptDe": "Vor dem Rat",
        "promptAr": "الأفضل:",
        "options": [
          "Löse das sofort, ohne Rückfrage",
          "Meine eigene Erfahrung reicht hier völlig aus",
          "Die Risiken sind unwichtig",
          "Ziel und Einschränkungen fragen"
        ],
        "correctIndex": 3,
        "explanationAr": "فهم السياق. اذكر ما تعرفه وما لا تعرفه، خاصة في الصحة والقانون والمال."
      },
      {
        "id": "b1-20-m4",
        "promptDe": "Grenze",
        "promptAr": "اختر التعبير المطابق لـ«Grenze» في درس «النصائح»:",
        "options": [
          "Das müsste ein Fachberater prüfen.",
          "Ich weiß sicher alles darüber und brauche keine Hilfe",
          "Jeder Vertrag ist gleich, das ist doch klar",
          "Eine Quelle brauche ich nicht"
        ],
        "correctIndex": 0,
        "explanationAr": "حد معرفي: Das müsste ein Fachberater prüfen. الاعتراف بحدود المعرفة وحاجة الاختصاصي موقف مهني لا يُنقص الحجة، بخلاف ادعاء معرفة كل شيء."
      },
      {
        "id": "b1-20-m5",
        "promptDe": "Entscheidung",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Entscheidung»:",
        "options": [
          "Ich entscheide für dich, nicht du",
          "Du darfst nur meine Lösung nehmen, sonst keine",
          "Die Entscheidung liegt bei dir.",
          "Rat ist Pflicht für alle"
        ],
        "correctIndex": 2,
        "explanationAr": "القرار للطرف. اذكر ما تعرفه وما لا تعرفه، خاصة في الصحة والقانون والمال."
      }
    ]
  },
  {
    "id": "b1-21",
    "level": "B1",
    "module": 7,
    "titleDe": "Gemeinsam handeln",
    "titleAr": "العمل المشترك",
    "questions": [
      {
        "id": "b1-21-m1",
        "promptDe": "wer",
        "promptAr": "أي خيار يحقّق «wer» في هذا السياق؟",
        "options": [
          "Wer Hilfe braucht, fragt früh.",
          "Wer braucht Hilfe, fragt früh.",
          "Wer Hilfe, früh fragt.",
          "Wer fragt Hilfe braucht."
        ],
        "correctIndex": 0,
        "explanationAr": "الفعل في نهاية جملة wer. تستعمل wer لجملة عامة عن أي شخص يحقق الشرط: Wer die Aufgabe übernimmt, der informiert das Team."
      },
      {
        "id": "b1-21-m2",
        "promptDe": "wer … der",
        "promptAr": "اختر التعبير المطابق لـ«wer … der»:",
        "options": [
          "Wer entscheidet der, Verantwortung übernimmt.",
          "Wer der entscheidet übernimmt.",
          "Entscheidet wer der.",
          "Wer entscheidet, der übernimmt Verantwortung."
        ],
        "correctIndex": 3,
        "explanationAr": "بنية صحيحة. تستعمل wer لجملة عامة عن أي شخص يحقق الشرط: Wer die Aufgabe übernimmt, der informiert das Team."
      },
      {
        "id": "b1-21-m3",
        "promptDe": "was … das",
        "promptAr": "اختر الصيغة الصحيحة لحالة «was … das»:",
        "options": [
          "Was entscheiden wir, dokumentieren das.",
          "Was wir entscheiden, wir das.",
          "Das was entscheiden.",
          "Was wir entscheiden, das dokumentieren wir."
        ],
        "correctIndex": 3,
        "explanationAr": "das ثم الفعل. تستعمل was للإشارة إلى فكرة أو شيء غير محدد: Was wir entscheiden, das dokumentieren wir."
      },
      {
        "id": "b1-21-m4",
        "promptDe": "Status",
        "promptAr": "الأفضل:",
        "options": [
          "Nur ein Prozentwert",
          "Wir arbeiten daran.",
          "Ergebnis, Hindernis, Hilfe, nächster Schritt",
          "Kein Termin"
        ],
        "correctIndex": 2,
        "explanationAr": "حقول قرار. تستعمل wer لجملة عامة عن أي شخص يحقق الشرط: Wer die Aufgabe übernimmt, der informiert das Team."
      },
      {
        "id": "b1-21-m5",
        "promptDe": "Abhängigkeit",
        "promptAr": "أي خيار يحقّق «Abhängigkeit» في هذا السياق؟",
        "options": [
          "Jede Aufgabe ist immer unabhängig.",
          "Namenskarten starten nach Teilnehmerliste.",
          "Wir verbergen die Wartezeit.",
          "Keine Alternative."
        ],
        "correctIndex": 1,
        "explanationAr": "توضح العلاقة: Namenskarten starten nach Teilnehmerliste — الترتيب يبيّن الاعتماد بين المهمتين، وحذفه يجعل الجدول غامضًا للقارئ."
      }
    ]
  },
  {
    "id": "b1-22",
    "level": "B1",
    "module": 8,
    "titleDe": "Ziele",
    "titleAr": "الأهداف",
    "questions": [
      {
        "id": "b1-22-m1",
        "promptDe": "Gleiches Subjekt",
        "promptAr": "اختر التعبير المطابق لـ«Gleiches Subjekt»:",
        "options": [
          "ohne dass mich zu überfordern",
          "ohne ich überfordere",
          "ohne mich zu überfordern",
          "ohne zu mich"
        ],
        "correctIndex": 2,
        "explanationAr": "فاعل واحد. نستعمل ohne … zu عندما يكون الفاعل نفسه: Ich übe, ohne mich zu überfordern."
      },
      {
        "id": "b1-22-m2",
        "promptDe": "Anderes Subjekt",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Anderes Subjekt»:",
        "options": [
          "ohne dass die verlorenen Daten wieder auftauchen",
          "ohne dass die Daten verloren gehen",
          "ohne die Daten zu gehen verloren",
          "ohne dass verloren die Daten"
        ],
        "correctIndex": 1,
        "explanationAr": "جملة dass بفعل نهائي. نستعمل ohne … zu عندما يكون الفاعل نفسه: Ich übe, ohne mich zu überfordern."
      },
      {
        "id": "b1-22-m3",
        "promptDe": "Frühindikator",
        "promptAr": "أي خيار يحقّق «Frühindikator» في هذا السياق؟",
        "options": [
          "zwei überarbeitete Texte pro Woche",
          "Der endgültige Erfolg ohne jeden Zweifel",
          "Ein sehr gutes Gefühl nur am frühen Morgen",
          "Ein Zeugnis am Ende"
        ],
        "correctIndex": 0,
        "explanationAr": "سلوك أسبوعي مبكر. مؤشر النتيجة يقيس الهدف النهائي مثل درجة اختبار جديد."
      },
      {
        "id": "b1-22-m4",
        "promptDe": "Ergebnisindikator",
        "promptAr": "اختر التعبير المطابق لـ«Ergebnisindikator»:",
        "options": [
          "Die App jeden Morgen kurz und langsam öffnen",
          "Die Zahl der Klicker",
          "unbekannter Test unter Zeitdruck",
          "Den Plan einmal laut vorlesen"
        ],
        "correctIndex": 2,
        "explanationAr": "يقيس أداء قريبًا من النتيجة. مؤشر النتيجة يقيس الهدف النهائي مثل درجة اختبار جديد."
      },
      {
        "id": "b1-22-m5",
        "promptDe": "Anpassung",
        "promptAr": "الأفضل:",
        "options": [
          "Alles wird verdoppelt und danach genau gemessen",
          "Das Datum wird gelöscht",
          "Warnsignal, eine Änderung, neuer Testtermin",
          "Es gibt dafür keine Messung im Protokoll"
        ],
        "correctIndex": 2,
        "explanationAr": "قاعدة محددة: Warnsignal, eine Änderung, neuer Testtermin — تعديل واحد لكل خطوة مع موعد قياس جديد. تغيير كل شيء معًا يمنع معرفة السبب."
      }
    ]
  },
  {
    "id": "b1-23",
    "level": "B1",
    "module": 8,
    "titleDe": "Technik im Alltag",
    "titleAr": "التقنية في الحياة اليومية",
    "questions": [
      {
        "id": "b1-23-m1",
        "promptDe": "für eine Sache",
        "promptAr": "اختر الصيغة الصحيحة لحالة «für eine Sache»:",
        "options": [
          "Für wen? Dafür.",
          "Womit? Dafür.",
          "Wofür? Dafür.",
          "Woran? Damit."
        ],
        "correctIndex": 2,
        "explanationAr": "wofür/dafür. عندما يشير حرف الجر إلى شيء أو فكرة، نستعمل wo- للسؤال وda- للجواب: Wofür? Dafür."
      },
      {
        "id": "b1-23-m2",
        "promptDe": "mit einer Sache",
        "promptAr": "أي خيار يحقّق «mit einer Sache» في هذا السياق؟",
        "options": [
          "Mit wem? Damit Person.",
          "Wofür? Daran.",
          "Womit? Damit.",
          "Worüber? Damit."
        ],
        "correctIndex": 2,
        "explanationAr": "womit/damit. عندما يشير حرف الجر إلى شيء أو فكرة، نستعمل wo- للسؤال وda- للجواب: Wofür? Dafür."
      },
      {
        "id": "b1-23-m3",
        "promptDe": "Person",
        "promptAr": "اختر التعبير المطابق لـ«Person» في درس «التقنية في الحياة اليومية»:",
        "options": [
          "Womit arbeitest du?",
          "Damit Person.",
          "Wofür Sara?",
          "Mit wem arbeitest du?"
        ],
        "correctIndex": 3,
        "explanationAr": "mit wem للأشخاص. عندما يشير حرف الجر إلى شيء أو فكرة، نستعمل wo- للسؤال وda- للجواب: Wofür? Dafür."
      },
      {
        "id": "b1-23-m4",
        "promptDe": "r-Brücke",
        "promptAr": "اختر الصيغة الصحيحة لحالة «r-Brücke»:",
        "options": [
          "woan / daan",
          "womit / daramit",
          "woüber / daüber",
          "woran / daran"
        ],
        "correctIndex": 3,
        "explanationAr": "r قبل حرف يبدأ بحركة. عندما يشير حرف الجر إلى شيء أو فكرة، نستعمل wo- للسؤال وda- للجواب: Wofür? Dafür."
      },
      {
        "id": "b1-23-m5",
        "promptDe": "Pilot",
        "promptAr": "الأفضل:",
        "options": [
          "Alle Daten sofort",
          "Keine Alternative",
          "Testdaten, Offline, Export, Plan B",
          "Nur die Eigenschaften"
        ],
        "correctIndex": 2,
        "explanationAr": "تجربة محدودة قابلة للرجوع. ابدأ بالمشكلة والهدف، ثم افحص المستخدمين والتوافق والوصول والبيانات والتكلفة والعمل دون اتصال والتصدير."
      }
    ]
  },
  {
    "id": "b1-24",
    "level": "B1",
    "module": 8,
    "titleDe": "B1-Projekt",
    "titleAr": "مشروع B1 التكميلي",
    "questions": [
      {
        "id": "b1-24-m1",
        "promptDe": "sich konzentrieren auf",
        "promptAr": "أي خيار يحقّق «sich konzentrieren auf» في هذا السياق؟",
        "options": [
          "wovon/davon",
          "womit/damit",
          "worauf/darauf",
          "worüber/darüber"
        ],
        "correctIndex": 2,
        "explanationAr": "auf. نستعمل worauf/darauf مع sich konzentrieren auf، وwovon/davon مع abhängen von، وwodurch/dadurch مع تغير بسبب وسيلة، وworüber/darüber مع berichten über."
      },
      {
        "id": "b1-24-m2",
        "promptDe": "abhängen von",
        "promptAr": "اختر التعبير المطابق لـ«abhängen von»:",
        "options": [
          "wovon/davon",
          "worauf/darauf",
          "womit/damit",
          "wofür/dafür"
        ],
        "correctIndex": 0,
        "explanationAr": "von. نستعمل worauf/darauf مع sich konzentrieren auf، وwovon/davon مع abhängen von، وwodurch/dadurch مع تغير بسبب وسيلة، وworüber/darüber مع berichten über."
      },
      {
        "id": "b1-24-m3",
        "promptDe": "berichten über",
        "promptAr": "اختر الصيغة الصحيحة لحالة «berichten über»:",
        "options": [
          "woran/daran",
          "wovon/davon",
          "womit/damit",
          "worüber/darüber"
        ],
        "correctIndex": 3,
        "explanationAr": "über. نستعمل worauf/darauf مع sich konzentrieren auf، وwovon/davon مع abhängen von، وwodurch/dadurch مع تغير بسبب وسيلة، وworüber/darüber مع berichten über."
      },
      {
        "id": "b1-24-m4",
        "promptDe": "Begrenztes Ergebnis",
        "promptAr": "أي خيار يحقّق «Begrenztes Ergebnis» في هذا السياق؟",
        "options": [
          "Erfolg für alle.",
          "Besser, ohne Zahlen.",
          "Keine Grenzen.",
          "Von 18 auf 10 Minuten bei 20 Personen in 4 Wochen."
        ],
        "correctIndex": 3,
        "explanationAr": "نطاق واضح. ابدأ بسؤال محدد، اجمع مصادر وخط بداية، صمم تدخلًا صغيرًا، ثم قس قبل وبعد."
      },
      {
        "id": "b1-24-m5",
        "promptDe": "Nächster Schritt",
        "promptAr": "اختر التعبير المطابق لـ«Nächster Schritt»:",
        "options": [
          "Sofortige Verallgemeinerung",
          "Daten löschen",
          "Größerer Test mit Geräten und Barrierefreiheit",
          "Keine Überprüfung"
        ],
        "correctIndex": 2,
        "explanationAr": "يعالج حدود العينة: Größerer Test mit Geräten und Barrierefreiheit. إذا كانت العينة صغيرة أو المهمة واحدة، فالخطوة توسيع الأجهزة والوصول لا تعميم النتيجة على الجميع."
      }
    ]
  }
] as const satisfies readonly LocalTestTemplateLesson[];
