/* Generated by scripts/generate-local-test-templates.ts; do not edit. */
import type { LocalTestTemplateLesson } from "@/core/training/local-test-generator";

export const localTestTemplateBankB2 = [
  {
    "id": "b2-01",
    "level": "B2",
    "module": 1,
    "titleDe": "Standpunkte",
    "titleAr": "بناء وجهة نظر",
    "questions": [
      {
        "id": "b2-01-m1",
        "promptDe": "These",
        "promptAr": "اختر الصيغة الصحيحة لحالة «These»:",
        "options": [
          "Handys sind schlecht für alle Lernenden und gehören verbannt.",
          "Eine aufgabenspezifische Regel ist sinnvoller als ein Totalverbot.",
          "Ich finde Handys praktisch und deshalb bleiben sie erlaubt.",
          "Technik gehört in jeden modernen Sprachkurs, und zwar ohne jede Regel."
        ],
        "correctIndex": 1,
        "explanationAr": "محددة وقابلة للنقاش: Eine aufgabenspezifische Regel ist sinnvoller als ein Totalverbot. الأطروحة موقف تدافع عنه، فهي قابلة للفحص والنقض، بخلاف المجازات والمواقف المطلقة."
      },
      {
        "id": "b2-01-m2",
        "promptDe": "Beleg",
        "promptAr": "أي خيار يحقّق «Beleg» في هذا السياق؟",
        "options": [
          "Ich finde das Ergebnis eigentlich ganz gut.",
          "Ein Freund von mir hat es auch getestet.",
          "70 % lösten die Aufgabe besser.",
          "Das klingt modern."
        ],
        "correctIndex": 2,
        "explanationAr": "بيانات محددة: 70 % lösten die Aufgabe besser. الرقم والنسبة يمكن تتبعهما إلى القياس، أما رأي صديق أو انطباع شخصي فليس دليلًا يمكن مناقشته."
      },
      {
        "id": "b2-01-m3",
        "promptDe": "Konzession",
        "promptAr": "اختر التعبير المطابق ل «Konzession»:",
        "options": [
          "Nachrichten stören beim Lernen überhaupt nicht, also brauchen wir keine Regel.",
          "Der Einwand ist völlig unzutreffend und kann ignoriert werden.",
          "Nur unsere eigene Auswertung zählt, die Gegenargumente sind irrelevant.",
          "Zwar lenken Nachrichten ab, jedoch sind nicht alle Nutzungen gleich."
        ],
        "correctIndex": 3,
        "explanationAr": "اعتراف وتحديد. تسمح zwar … jedoch/aber و allerdings بالاعتراف بجزء من الحجة المقابلة دون التخلي عن موقفك: Zwar lenken Nachrichten ab, jedoch sind nicht alle Nutzungen gleich."
      },
      {
        "id": "b2-01-m4",
        "promptDe": "Reichweite",
        "promptAr": "الأدق:",
        "options": [
          "Das gilt für diese zwei Kurse.",
          "Das gilt für alle immer.",
          "Eine Grenze ist hier nicht nötig.",
          "Ein Pilot beweist alles."
        ],
        "correctIndex": 0,
        "explanationAr": "نطاق محدد: Das gilt für diese zwei Kurse. حدّد العينة والمدة والمهمة والسياق قبل الاستنتاج، ولا تعمّم من تجربة صغيرة على «الجميع دائمًا»."
      },
      {
        "id": "b2-01-m5",
        "promptDe": "Vorschlag",
        "promptAr": "الأفضل:",
        "options": [
          "Verbieten Sie die Geräte sofort und dauerhaft.",
          "Sammeln Sie dazu keine Daten.",
          "Klare Regel vier Wochen testen und messen.",
          "Erlauben Sie einfach alles."
        ],
        "correctIndex": 2,
        "explanationAr": "قابل للفحص: Klare Regel vier Wochen testen und messen. الأطروحة تتحول إلى إجراء له مدة ومعيار قياس، بخلاف المنع الفوري أو السماح الشامل بلا بيانات."
      }
    ]
  },
  {
    "id": "b2-02",
    "level": "B2",
    "module": 1,
    "titleDe": "Debatte",
    "titleAr": "المناظرة",
    "questions": [
      {
        "id": "b2-02-m1",
        "promptDe": "Faire Paraphrase",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Faire Paraphrase»:",
        "options": [
          "Sie sind offenbar gegen jeden Fortschritt in unserem Unternehmen.",
          "Ihr Argument ist dumm und verdient keine Antwort.",
          "Sie befürchten unbezahlte Mehrarbeit und höheren Druck.",
          "Sie lehnen jede zusätzliche Arbeit rundweg ab."
        ],
        "correctIndex": 2,
        "explanationAr": "يلخص المخاوف الفعلية. قبل الرد، لخص الحجة بصورة يمكن لصاحبها قبولها واطلب التأكيد."
      },
      {
        "id": "b2-02-m2",
        "promptDe": "selbst wenn",
        "promptAr": "أي خيار يحقّق «selbst wenn» في هذا السياق؟",
        "options": [
          "Selbst wenn die Leistung steigt, prüfen wir die Belastung.",
          "Selbst wenn steigt die Leistung, wir prüfen die Belastung.",
          "Selbst wenn die Leistung steigt, wir die Belastung prüfen.",
          "Selbst die Leistung wenn steigt, prüfen wir die Belastung."
        ],
        "correctIndex": 0,
        "explanationAr": "فعل الشرط في النهاية. تقدم selbst wenn شرطًا لا يغير النتيجة الرئيسية: Selbst wenn die Produktivität steigt, müssen Überstunden geprüft werden."
      },
      {
        "id": "b2-02-m3",
        "promptDe": "wohingegen",
        "promptAr": "اختر التعبير المطابق ل «wohingegen»:",
        "options": [
          "Büros flexibel sind, wohingegen Kliniken Schichten brauchen.",
          "Wohingegen Kliniken Schichten brauchen, Büros sind flexibel.",
          "Büros sind flexibel, wohingegen Kliniken Schichten brauchen.",
          "Büros sind flexibel, wohingegen brauchen Kliniken Schichten."
        ],
        "correctIndex": 2,
        "explanationAr": "فعل الجملة الفرعية في النهاية. تستعمل wohingegen للمقابلة الواضحة: Büros können Zeiten flexibel verteilen, wohingegen Kliniken eine kontinuierliche Besetzung brauchen."
      },
      {
        "id": "b2-02-m4",
        "promptDe": "Konzession",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Konzession»:",
        "options": [
          "Der Einwand ist völlig lächerlich und wird nicht beachtet.",
          "Es zählen hier nur meine eigenen Daten aus dem letzten Projekt.",
          "Diesen Einwand ignoriere ich einfach und sage gar nichts dazu.",
          "Der Einwand ist berechtigt; allerdings fehlt ein Belastungsmaß."
        ],
        "correctIndex": 3,
        "explanationAr": "اعتراف ثم فجوة: Der Einwand ist berechtigt; allerdings fehlt ein Belastungsmaß. تُقرّ بصحة الاعتراف ثم تحدّد النقص، فلا تتجاهل الطرف الآخر ولا تنكره."
      },
      {
        "id": "b2-02-m5",
        "promptDe": "Debattenziel",
        "promptAr": "الأفضل:",
        "options": [
          "Den anderen so lange unterbrechen, bis er schweigt",
          "Mit der meisten Stimme gewinnen",
          "Gemeinsamkeit und offene Frage klären",
          "Die Position des Gegners verzerren"
        ],
        "correctIndex": 2,
        "explanationAr": "نقاش تعاوني: Gemeinsamkeit und offene Frage klären. هدف النقاش فهم المسألة وفتح سؤال جديد، لا إسكات الطرف الآخر أو كسب الأصوات."
      }
    ]
  },
  {
    "id": "b2-03",
    "level": "B2",
    "module": 1,
    "titleDe": "Arbeitsmodelle",
    "titleAr": "نماذج العمل",
    "questions": [
      {
        "id": "b2-03-m1",
        "promptDe": "sofern",
        "promptAr": "أي خيار يحقّق «sofern» في هذا السياق؟",
        "options": [
          "Das gilt, sofern ist die Aufgabe geeignet.",
          "Sofern die Aufgabe ist geeignet.",
          "Das gilt, sofern die Aufgabe geeignet ist.",
          "Das gilt sofern Aufgabe."
        ],
        "correctIndex": 2,
        "explanationAr": "الفعل في النهاية. تستعمل sofern بمعنى «بشرط أن/ما دام» في سياق رسمي نسبيًا: Homeoffice ist möglich, sofern die Aufgabe dafür geeignet ist."
      },
      {
        "id": "b2-03-m2",
        "promptDe": "je nachdem",
        "promptAr": "اختر التعبير المطابق ل «je nachdem»:",
        "options": [
          "Je nachdem, welche Rolle hat jemand …",
          "Je nachdem, welche Rolle jemand hat …",
          "Je nachdem jemand hat welche Rolle …",
          "Welche Rolle je nachdem …"
        ],
        "correctIndex": 1,
        "explanationAr": "فعل الجزء التابع في النهاية. تستعمل je nachdem عندما تعتمد النتيجة على حالة متغيرة: Je nachdem, ob Kundentermine stattfinden, arbeitet das Team vor Ort."
      },
      {
        "id": "b2-03-m3",
        "promptDe": "Gerechtigkeit",
        "promptAr": "الأدق:",
        "options": [
          "Gleiche Regel kann unterschiedliche Wirkungen haben.",
          "Gleiche Regel ist immer gerecht.",
          "Der Durchschnitt reicht.",
          "Eine Ausnahme ist immer ungerecht."
        ],
        "correctIndex": 0,
        "explanationAr": "الأثر يعتمد على الظروف. تستعمل sofern بمعنى «بشرط أن/ما دام» في سياق رسمي نسبيًا: Homeoffice ist möglich, sofern die Aufgabe dafür geeignet ist."
      },
      {
        "id": "b2-03-m4",
        "promptDe": "Verteilungsanalyse",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Verteilungsanalyse»:",
        "options": [
          "Rolle, Schicht, Weg, Betreuung und Ausstattung",
          "Nur der Durchschnitt",
          "Nur die Produktion",
          "Nur die Meinung"
        ],
        "correctIndex": 0,
        "explanationAr": "أبعاد التوزيع. تستعمل je nachdem عندما تعتمد النتيجة على حالة متغيرة: Je nachdem, ob Kundentermine stattfinden, arbeitet das Team vor Ort."
      },
      {
        "id": "b2-03-m5",
        "promptDe": "Pilotentscheidung",
        "promptAr": "الأفضل:",
        "options": [
          "Immer für alle.",
          "Keine zusätzliche Messung.",
          "Fortsetzen nur bei klaren Belastungs- und Zugangskriterien.",
          "Die spontane Arbeit verbergen."
        ],
        "correctIndex": 2,
        "explanationAr": "شرط قرار واضح: Fortsetzen nur bei klaren Belastungs- und Zugangskriterien. استمرار المشروع مشروط بمعايير قابلة للقياس، لا بقرار شامل دائم ولا بإخفاء النتائج."
      }
    ]
  },
  {
    "id": "b2-04",
    "level": "B2",
    "module": 1,
    "titleDe": "Komplexe Kommunikation",
    "titleAr": "التواصل المركب",
    "questions": [
      {
        "id": "b2-04-m1",
        "promptDe": "Thema",
        "promptAr": "أي خيار يحقّق «Thema» في هذا السياق؟",
        "options": [
          "hinsichtlich der Frist",
          "angesichts der Frist",
          "unter Berücksichtigung",
          "selbst wenn"
        ],
        "correctIndex": 0,
        "explanationAr": "hinsichtlich للموضوع: hinsichtlich der Frist يعني «فيما يخص الموعد»، وتُستعمل مع اسم مجرور في Genitiv. أما angesichts فللظرف أو السبب، و unter Berücksichtigung تركيب آخر."
      },
      {
        "id": "b2-04-m2",
        "promptDe": "Grund/Lage",
        "promptAr": "اختر التعبير المطابق ل «Grund/Lage»:",
        "options": [
          "hinsichtlich des Risikos",
          "im Hinblick auf",
          "wohingegen",
          "angesichts des Risikos"
        ],
        "correctIndex": 3,
        "explanationAr": "angesichts للظرف أو السبب: angesichts des Risikos تعني «في ضوء الخطر». الصيغة تأخذ Genitiv، و im Hinblick auf تأخذ Akkusativ وتبرز الاتجاه أو الهدف."
      },
      {
        "id": "b2-04-m3",
        "promptDe": "Perspektive",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Perspektive»:",
        "options": [
          "im Hinblick auf die Qualität",
          "im Hinblick der Qualität",
          "hinsichtlich auf Qualität",
          "angesichts auf"
        ],
        "correctIndex": 0,
        "explanationAr": "im Hinblick auf + Akkusativ: im Hinblick auf die Qualität. المركّب يقبل حرف الجر auf بعد hin، ولا يأتي هكذا: im Hinblick der Qualität، وحرف الجر يحدد النصب."
      },
      {
        "id": "b2-04-m4",
        "promptDe": "Klarer Stil",
        "promptAr": "الأفضل:",
        "options": [
          "Angesichts Frist Lieferung Kernumfang Montag.",
          "Angesichts der Frist liefern wir Montag den Kernumfang.",
          "Durchführung Lieferung Prüfung Umsetzung.",
          "Frist hinsichtlich ohne Verb."
        ],
        "correctIndex": 1,
        "explanationAr": "إطار ثم فعل وفاعل. بعد المقدمة الاسمية اذكر من يستطيع فعل ماذا ومتى: Angesichts der Frist können wir den Kernumfang Montag liefern."
      },
      {
        "id": "b2-04-m5",
        "promptDe": "Eskalation",
        "promptAr": "الأفضل:",
        "options": [
          "Optionen und Risiken bis Frist vorlegen, dann Leitung entscheiden lassen.",
          "Eine persönliche Drohung.",
          "Keine Alternativen.",
          "Sofortige Eskalation ohne Informationen."
        ],
        "correctIndex": 0,
        "explanationAr": "مسار قرار موضوعي. حدد الطلب الأساسي والقيد والآثار، ثم قدم بدائل قابلة للمقارنة."
      }
    ]
  },
  {
    "id": "b2-05",
    "level": "B2",
    "module": 2,
    "titleDe": "Daten verstehen",
    "titleAr": "فهم البيانات",
    "questions": [
      {
        "id": "b2-05-m1",
        "promptDe": "Von 50 auf 60 Prozent",
        "promptAr": "ما الوصف الصحيح؟",
        "options": [
          "plus zehn Prozentpunkte und relativ minus zwanzig Prozent",
          "relativ plus zehn Prozent und genau null Punkte",
          "minus fünf Prozentpunkte und relativ null",
          "plus zehn Prozentpunkte, relativ plus zwanzig Prozent"
        ],
        "correctIndex": 3,
        "explanationAr": "الفرق 10 نقاط، وهو 10÷50 = 20% نسبيًا. إذا ارتفعت نسبة من 20% إلى 30% فالتغير المطلق عشر نقاط مئوية، أما التغير النسبي فهو 50% قياسًا إلى 20."
      },
      {
        "id": "b2-05-m2",
        "promptDe": "Korrelation",
        "promptAr": "أي صياغة أدق؟",
        "options": [
          "X beweist Y.",
          "Weil X, deshalb immer Y.",
          "X ging mit Y einher.",
          "X ist die einzige Ursache."
        ],
        "correctIndex": 2,
        "explanationAr": "تصف علاقة دون ادعاء سببي. قد يتحرك متغيران معًا بسبب متغير ثالث أو اختيار المشاركين لأنفسهم أو اتجاه سببي معاكس."
      },
      {
        "id": "b2-05-m3",
        "promptDe": "Stichprobe",
        "promptAr": "ما السؤال الأهم؟",
        "options": [
          "Welche Personen wurden verglichen?",
          "Wer wurde wie ausgewählt?",
          "Wie groß war sie?",
          "War der Zufall dabei?"
        ],
        "correctIndex": 1,
        "explanationAr": "طريقة الاختيار تحدد التمثيل والتعميم: Wer wurde wie ausgewählt? إن لم تعرف كيف اختيرت العينة لا تعرف من تمثله النتيجة، ويبقى التعميم على غيرها بلا سند."
      },
      {
        "id": "b2-05-m4",
        "promptDe": "Mittelwert",
        "promptAr": "ما الذي يجب إضافته؟",
        "options": [
          "Verteilung und Gruppenunterschiede",
          "Ein einziger Grund wurde belegt",
          "die Streuung innerhalb beider Gruppen",
          "die Reihenfolge der Texte"
        ],
        "correctIndex": 0,
        "explanationAr": "التوزيع يكشف ما يخفيه المتوسط: Verteilung und Gruppenunterschiede. متوسط متقارب قد يخفي مجموعتين مختلفتين، فاعرض المدى أو الفروق بين المجموعات."
      },
      {
        "id": "b2-05-m5",
        "promptDe": "Begrenzte Schlussfolgerung",
        "promptAr": "أي خيار يحقّق «Begrenzte Schlussfolgerung» في هذا السياق؟",
        "options": [
          "Die Daten zeigen in dieser freiwilligen Stichprobe einen Zusammenhang.",
          "Die Daten deuten in dieser Stichprobe auf einen Zusammenhang hin.",
          "Der Trend gilt für jeden einzelnen Menschen unverändert.",
          "Andere Erklärungen sind nicht ausgeschlossen und bleiben offen."
        ],
        "correctIndex": 1,
        "explanationAr": "تحدد الدليل والعينة دون يقين زائد. قد يتحرك متغيران معًا بسبب متغير ثالث أو اختيار المشاركين لأنفسهم أو اتجاه سببي معاكس."
      }
    ]
  },
  {
    "id": "b2-06",
    "level": "B2",
    "module": 2,
    "titleDe": "Wissenschaft vermitteln",
    "titleAr": "تبسيط المعرفة العلمية",
    "questions": [
      {
        "id": "b2-06-m1",
        "promptDe": "Adressatengerechte Definition",
        "promptAr": "اختر التعبير المطابق ل «Adressatengerechte Definition»:",
        "options": [
          "Stichprobe ist Stichprobe.",
          "Sample ist nur ein anderes Wort.",
          "Unter einer Stichprobe versteht man den untersuchten Teil einer größeren Gruppe.",
          "Keine Definition oder Beispiel nötig."
        ],
        "correctIndex": 2,
        "explanationAr": "تعريف قصير يؤدي وظيفة المصطلح. لا تستبدل المصطلح دائمًا؛ قد يحتاجه المتلقي لاحقًا."
      },
      {
        "id": "b2-06-m2",
        "promptDe": "Passiv Präteritum",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Passiv Präteritum»:",
        "options": [
          "Die Werte wurden gemessen.",
          "Die Werte wurden messen.",
          "Die Werte worden gemesst.",
          "Die Werte werden gestern messen."
        ],
        "correctIndex": 0,
        "explanationAr": "wurden + Partizip II. التقارير تكثر من أسماء مثل Durchführung و Auswertung."
      },
      {
        "id": "b2-06-m3",
        "promptDe": "Klare Verbform",
        "promptAr": "الأوضح:",
        "options": [
          "Die Durchführung der Datenauswertung erfolgte.",
          "Das Team wertete die Daten aus.",
          "Auswertung Durchführung Daten.",
          "Es erfolgte die Vollziehung der Durchführung."
        ],
        "correctIndex": 1,
        "explanationAr": "فاعل وفعل واضحان. التقارير تكثر من أسماء مثل Durchführung و Auswertung."
      },
      {
        "id": "b2-06-m4",
        "promptDe": "wobei",
        "promptAr": "أي وظيفة؟",
        "options": [
          "Ein gesicherter Ursache-Wirkung-Zusammenhang",
          "Das Ergebnis streichen",
          "Verallgemeinerung auf alle",
          "Eine relevante Einschränkung direkt ergänzen"
        ],
        "correctIndex": 3,
        "explanationAr": "تلحق تفصيلًا أو قيدًا مرتبطًا. لا تستبدل المصطلح دائمًا؛ قد يحتاجه المتلقي لاحقًا."
      },
      {
        "id": "b2-06-m5",
        "promptDe": "Wissenschaft vermitteln",
        "promptAr": "ما البنية الأمينة؟",
        "options": [
          "Nur eine spannende Überschrift",
          "Ein Ergebnis ohne Methode",
          "Frage, Methode, Ergebnis, Grenze und Bedeutung",
          "Fachbegriffe ohne Beispiele"
        ],
        "correctIndex": 2,
        "explanationAr": "تحفظ الدليل والحد والمعنى. لا تستبدل المصطلح دائمًا؛ قد يحتاجه المتلقي لاحقًا."
      }
    ]
  },
  {
    "id": "b2-07",
    "level": "B2",
    "module": 2,
    "titleDe": "Teilhabe",
    "titleAr": "المشاركة المجتمعية",
    "questions": [
      {
        "id": "b2-07-m1",
        "promptDe": "Tatsächliche Teilhabe",
        "promptAr": "ما الذي يجب تحليله؟",
        "options": [
          "Zugang, Stimme, Einfluss und Rückmeldung",
          "Anzahl der Teilnehmenden, Dauer und Kosten der Veranstaltung",
          "Pressestimmen, Fotos und die Resonanz im Netz",
          "Termine, Räume und die Technik im Saal"
        ],
        "correctIndex": 0,
        "explanationAr": "هذه سلسلة المشاركة الفعلية. حلل المشاركة في ثلاث درجات: هل وصلت الدعوة؟"
      },
      {
        "id": "b2-07-m2",
        "promptDe": "indem",
        "promptAr": "اختر الصحيح:",
        "options": [
          "Wir senken Barrieren, indem wir bieten Betreuung an.",
          "Wir senken Barrieren, indem wir Betreuung anbieten.",
          "Indem wir Betreuung anbieten wir senken.",
          "Wir senken Betreuung indem anbieten."
        ],
        "correctIndex": 1,
        "explanationAr": "فاعل ثم مفعول ثم فعل في نهاية التابعة. تجيب indem عن سؤال wie?: Die Stadt senkt Barrieren, indem sie Betreuung anbietet."
      },
      {
        "id": "b2-07-m3",
        "promptDe": "Repräsentation",
        "promptAr": "أي شرط أدق؟",
        "options": [
          "Möglichst viele Einladungen versenden und die Anwesenheit zählen",
          "Die Teilnehmenden nach Alter und Beruf auswählen lassen",
          "Auswahl, Mandat, Rücksprache und Grenzen klären",
          "Ergebnisse veröffentlichen und kommentieren"
        ],
        "correctIndex": 2,
        "explanationAr": "التمثيل يحتاج آلية وتفويضًا: Auswahl, Mandat, Rücksprache und Grenzen klären. يجب معرفة من اختار المشاركين وبأي تفويض، وكيف يُرجع إليهم، وما حدود القرار."
      },
      {
        "id": "b2-07-m4",
        "promptDe": "Anhörung",
        "promptAr": "ماذا تعني؟",
        "options": [
          "Alle Beteiligten dürfen ihre Sicht darlegen, entscheiden aber nicht über das Ergebnis.",
          "Die Verwaltung hört Beschwerden an und antwortet darauf in einem offiziellen Schreiben.",
          "Die Teilnehmenden einigen sich dort auf einen gemeinsamen Beschluss.",
          "Perspektiven werden gehört, ohne automatisch die Endentscheidung zu übertragen."
        ],
        "correctIndex": 3,
        "explanationAr": "الاستماع لا يساوي القرار المشترك. حلل المشاركة في ثلاث درجات: هل وصلت الدعوة؟"
      },
      {
        "id": "b2-07-m5",
        "promptDe": "Rückkopplung",
        "promptAr": "أفضل ممارسة:",
        "options": [
          "Vorschläge dokumentieren und Annahme, Änderung oder Ablehnung begründen",
          "Jeden Vorschlag erfassen und den Personen eine nachvollziehbare Antwort geben.",
          "Die besten Vorschläge auswählen und die anderen ohne Erklärung ausschließen.",
          "Eine Umfrage machen und das Ergebnis in einer Präsentation zeigen."
        ],
        "correctIndex": 0,
        "explanationAr": "الرد المعلل يغلق الحلقة. حلل المشاركة في ثلاث درجات: هل وصلت الدعوة؟"
      }
    ]
  },
  {
    "id": "b2-08",
    "level": "B2",
    "module": 2,
    "titleDe": "Medienkritik",
    "titleAr": "نقد الإعلام",
    "questions": [
      {
        "id": "b2-08-m1",
        "promptDe": "Belegkette",
        "promptAr": "ما الخطوة الأولى؟",
        "options": [
          "Die Meldung eines anderen Mediums als Bestätigung zitieren.",
          "Zur ursprünglichen Quelle und Messung zurückgehen",
          "Die Zahl übernehmen und sie im eigenen Beitrag wiederholen.",
          "Die Kommentare unter dem Beitrag lesen."
        ],
        "correctIndex": 1,
        "explanationAr": "الأصل يبين ما المادة الداعمة فعلًا: Zur ursprünglichen Quelle und Messung zurückgehen. نقلاً عن نقلك لا يضيف دليلًا، والسؤال الأصلي يكشف هل المادة داعمة أصلًا."
      },
      {
        "id": "b2-08-m2",
        "promptDe": "Konjunktiv I",
        "promptAr": "أي خيار يحقّق «Konjunktiv I» في هذا السياق؟",
        "options": [
          "Er sagt, die Studie ist unabhängig und klar belegt.",
          "Er sagt, sei die Studie unabhängig?",
          "Er sei sagt die Studie unabhängig.",
          "Er sagt, die Studie sei unabhängig."
        ],
        "correctIndex": 3,
        "explanationAr": "sei علامة نقل غير مباشر واضحة. ينقل Konjunktiv I كلام المصدر دون أن يتبناه الكاتب: Sie sagt, die Daten zeigten/zeigen? الصيغ الواضحة: er sei, er habe, er werde؛ مع الجمع قد تتطابق صيغة Konjunktiv I مع الحاضر، فيستعمل Konjunktiv II للتمييز: sie hätten."
      },
      {
        "id": "b2-08-m3",
        "promptDe": "Selbsteinschätzung",
        "promptAr": "ماذا تثبت مباشرة؟",
        "options": [
          "Dass die Teilnehmenden ihre Kompetenz höher bewerteten.",
          "Dass objektiv bessere Kompetenzwerte gemessen wurden.",
          "Was Befragte über ihre Wahrnehmung berichten",
          "Dass der Kurs bei allen gut ankam."
        ],
        "correctIndex": 2,
        "explanationAr": "التقييم الذاتي يقيس التقرير الذاتي. استخرج الجملة المركزية، ثم اسأل ما المادة التي تسندها: وثيقة، بيانات، مقابلة، صورة أم مصدر مجهول؟"
      },
      {
        "id": "b2-08-m4",
        "promptDe": "Interessenkonflikt",
        "promptAr": "التقييم الأدق:",
        "options": [
          "Offenlegen und Methode sowie unabhängige Prüfung beachten",
          "Ein Interessenkonflikt macht Ergebnisse falsch und gehört in keine Analyse.",
          "Interessenkonflikte sind unerheblich, wenn die Methodik sauber arbeitet.",
          "Der Konflikt widerlegt jede einzelne Zahl der Studie."
        ],
        "correctIndex": 0,
        "explanationAr": "الشفافية والفحص أنسب من الحكم الآلي. استخرج الجملة المركزية، ثم اسأل ما المادة التي تسندها: وثيقة، بيانات، مقابلة، صورة أم مصدر مجهول؟"
      },
      {
        "id": "b2-08-m5",
        "promptDe": "Transparente Korrektur",
        "promptAr": "ما الذي تحتويه؟",
        "options": [
          "Änderung, Datum, Grund und die Quellen nennen",
          "Nur die Korrektur selbst, ohne Erklärung",
          "Eine knappe Entschuldigung",
          "Änderung, Zeitpunkt, Grund und Belege"
        ],
        "correctIndex": 3,
        "explanationAr": "أثر التصحيح يجعل المسار قابلًا للتتبع: Änderung, Zeitpunkt, Grund und Belege. القارئ يحتاج ما تغيّر ومتى ولماذا وأين الدليل، لا اعتذارًا مختصرًا بلا أثر."
      }
    ]
  },
  {
    "id": "b2-09",
    "level": "B2",
    "module": 3,
    "titleDe": "Perspektiven",
    "titleAr": "وجهات النظر الثقافية",
    "questions": [
      {
        "id": "b2-09-m1",
        "promptDe": "Beobachtung",
        "promptAr": "اختر التعبير المطابق ل «Beobachtung» في درس «وجهات النظر الثقافية»:",
        "options": [
          "Er war arrogant.",
          "Er wollte die Gruppe beleidigen.",
          "Er sprach zweimal und verließ um zehn Uhr den Raum.",
          "Seine Kultur erklärt sein Verhalten."
        ],
        "correctIndex": 2,
        "explanationAr": "أفعال وزمن قابلان للملاحظة. الملاحظة تصف ما يمكن سماعه أو رؤيته: من تكلم وكم ومتى."
      },
      {
        "id": "b2-09-m2",
        "promptDe": "Präzise kulturelle Aussage",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Präzise kulturelle Aussage»:",
        "options": [
          "In manchen Teams wird Kritik direkter formuliert; Rolle und Situation variieren.",
          "Alle Angehörigen eines Landes sind gleich.",
          "Die Nationalität erklärt jedes Schweigen.",
          "Es gibt keine Unterschiede innerhalb der Gruppen."
        ],
        "correctIndex": 0,
        "explanationAr": "تحدد الميل والسياق والتنوع. يمكن للسياق الثقافي أن يؤثر، لكنه ليس متغيرًا وحيدًا ولا يحدد كل فرد."
      },
      {
        "id": "b2-09-m3",
        "promptDe": "Partizip I",
        "promptAr": "أي تركيب صحيح؟",
        "options": [
          "die gewartete Gäste",
          "die warten Gäste",
          "die wartend Gästen",
          "die wartenden Gäste"
        ],
        "correctIndex": 3,
        "explanationAr": "warten + d + en. Partizip I يصف فعلًا جاريًا أو فاعلًا: die wartenden Gäste = die Gäste, die warten."
      },
      {
        "id": "b2-09-m4",
        "promptDe": "Partizip II als Attribut",
        "promptAr": "أي خيار يحقّق «Partizip II als Attribut» في هذا السياق؟",
        "options": [
          "der mehrsprachig verfassen Bericht",
          "der verfasst mehrsprachige Bericht",
          "der mehrsprachig verfasste Bericht",
          "dem verfasste Bericht"
        ],
        "correctIndex": 2,
        "explanationAr": "Partizip II مع نهاية الصفة قبل الاسم. Partizip I يصف فعلًا جاريًا أو فاعلًا: die wartenden Gäste = die Gäste, die warten."
      },
      {
        "id": "b2-09-m5",
        "promptDe": "Perspektivenvergleich",
        "promptAr": "ما الخلاصة الجيدة؟",
        "options": [
          "Die richtige Nationalität auswählen",
          "Deutungen am Gegenstand belegen und die eigene Position mitreflektieren",
          "Jede Aussage ohne Beleg akzeptieren",
          "Den individuellen Kontext streichen"
        ],
        "correctIndex": 1,
        "explanationAr": "يجمع تعدد المنظور مع معيار الدليل: Deutungen am Gegenstand belegen und die eigene Position mitreflektieren. لا يكفي قبول كل قول، ولا إلغاء السياق الفردي."
      }
    ]
  },
  {
    "id": "b2-10",
    "level": "B2",
    "module": 3,
    "titleDe": "Vermitteln",
    "titleAr": "الوساطة اللغوية الدقيقة",
    "questions": [
      {
        "id": "b2-10-m1",
        "promptDe": "Modalität",
        "promptAr": "ما النقل الصحيح؟",
        "options": [
          "kann = Garantie",
          "kann = Möglichkeit",
          "sollte = striktes Verbot",
          "muss = freie Wahl"
        ],
        "correctIndex": 1,
        "explanationAr": "kann تعبر عن الإمكانية لا اليقين: kann = Möglichkeit. أما Garantie فتحتاج مؤشرًا أقوى مثل versprechen، و sollte نصيحة، و muss إلزامًا."
      },
      {
        "id": "b2-10-m2",
        "promptDe": "es sei denn",
        "promptAr": "ما وظيفته؟",
        "options": [
          "Den Grund bestätigen",
          "Jede Bedingung aufheben",
          "Eine Ausnahme zur Regel einführen",
          "Eine Möglichkeit in eine Pflicht verwandeln"
        ],
        "correctIndex": 2,
        "explanationAr": "يقدم الحالة المستثناة من القاعدة. sofern/vorausgesetzt, dass يحددان شرط سريان القاعدة."
      },
      {
        "id": "b2-10-m3",
        "promptDe": "sofern",
        "promptAr": "اختر الصحيح:",
        "options": [
          "Die Zusage gilt, sofern wird sie bestätigt.",
          "Sofern sie wird bestätigt, gilt.",
          "Die Zusage sofern Bestätigung.",
          "Die Zusage gilt, sofern sie bestätigt wird."
        ],
        "correctIndex": 3,
        "explanationAr": "الفعل في نهاية جملة الشرط. sofern/vorausgesetzt, dass يحددان شرط سريان القاعدة."
      },
      {
        "id": "b2-10-m4",
        "promptDe": "Adressatengerechte Auswahl",
        "promptAr": "ما الذي يأتي أولًا؟",
        "options": [
          "Handlung, Frist und entscheidungsrelevante Bedingungen",
          "Den Text ausschmücken",
          "Der gesamte Hintergrund der Organisation",
          "Die nicht angegebene Meinung des Vermittlers"
        ],
        "correctIndex": 0,
        "explanationAr": "المتلقي يحتاج الفعل وما يغيره أولًا: Handlung, Frist und entscheidungsrelevante Bedingungen. لا تُغرق النص بخلفية المؤسسة قبل أن تعرف المطلوب وموعده."
      },
      {
        "id": "b2-10-m5",
        "promptDe": "Eigene Ergänzung",
        "promptAr": "أفضل صياغة:",
        "options": [
          "Die Quelle hat das versprochen, obwohl sie es nicht getan hat.",
          "Ich streiche die Grenzen der Ergänzung.",
          "Ich präsentiere meine Vermutung als Tatsache.",
          "Zur Erklärung ergänze ich …; das ist keine Zusage der Quelle."
        ],
        "correctIndex": 3,
        "explanationAr": "تعلم مصدر الإضافة وحدودها. sofern/vorausgesetzt, dass يحددان شرط سريان القاعدة."
      }
    ]
  },
  {
    "id": "b2-11",
    "level": "B2",
    "module": 3,
    "titleDe": "Schreiben und Sprechen",
    "titleAr": "الكتابة والمحادثة تحت الوقت",
    "questions": [
      {
        "id": "b2-11-m1",
        "promptDe": "abwägen",
        "promptAr": "أي أداء يحققه؟",
        "options": [
          "Eine Seite nennen, ohne einen Maßstab zu zeigen",
          "Den Titel übersetzen und drei Wörter erklären",
          "Die Situation weglassen",
          "Zwei Seiten anhand klarer Kriterien gewichten"
        ],
        "correctIndex": 3,
        "explanationAr": "المعيار والترجيح جوهر الموازنة. ضع خطًا تحت أفعال المهمة: beschreiben يعرض السمات، erläutern يشرحها بمثال، vergleichen يحدد معيارًا وقاسمًا وفارقًا، abwägen يزن الجانبين، Stellung nehmen يعلن موقفًا، vorschlagen يقدم إجراءً."
      },
      {
        "id": "b2-11-m2",
        "promptDe": "vorschlagen",
        "promptAr": "أفضل صياغة:",
        "options": [
          "Man sollte etwas tun, etwa mehr Personal, ohne Zahl und ohne Frist",
          "Die Bibliothek testet acht Wochen zwei Zonen und misst Nutzung sowie Beschwerden.",
          "Eine Lösung wäre gut, zum Beispiel längere Öffnungszeiten am Wochenende",
          "Das Thema ist interessant und betrifft viele Nutzer, doch fehlt ein konkreter Vorschlag"
        ],
        "correctIndex": 1,
        "explanationAr": "فاعل وإجراء ومدة ومؤشرات. ضع خطًا تحت أفعال المهمة: beschreiben يعرض السمات، erläutern يشرحها بمثال، vergleichen يحدد معيارًا وقاسمًا وفارقًا، abwägen يزن الجانبين، Stellung nehmen يعلن موقفًا، vorschlagen يقدم إجراءً."
      },
      {
        "id": "b2-11-m3",
        "promptDe": "zwar … jedoch",
        "promptAr": "ما الوظيفة؟",
        "options": [
          "Einen einzigen Grund angeben, warum etwas so ist",
          "Nur eine zeitliche Abfolge von zwei Schritten nennen",
          "Eine Konzession mit anschließendem Gegensatz",
          "Ein Zitat wörtlich wiedergeben"
        ],
        "correctIndex": 2,
        "explanationAr": "تعترف بجانب ثم تقابله. في عرض قصير، أعلن المسار: Thema، zwei Aspekte، Position، Beispiel، Schluss."
      },
      {
        "id": "b2-11-m4",
        "promptDe": "Sprechreparatur",
        "promptAr": "اختر التعبير المطابق ل «Sprechreparatur»:",
        "options": [
          "Ich korrigiere mich: zwölf statt zehn Prozent.",
          "Ich beginne den ganzen Vortrag einfach noch einmal von vorn",
          "Ich höre auf und beende den Beitrag hier",
          "Ich erkläre eine Minute lang, warum der Fehler passierte"
        ],
        "correctIndex": 0,
        "explanationAr": "إصلاح موجز للمعلومة. في عرض قصير، أعلن المسار: Thema، zwei Aspekte، Position، Beispiel، Schluss."
      },
      {
        "id": "b2-11-m5",
        "promptDe": "Zeitreserve",
        "promptAr": "كيف تستعمل؟",
        "options": [
          "Schwierige Wörter einfügen, ohne den roten Faden zu wahren",
          "Operatoren, Bezüge, Verbposition und Schluss prüfen",
          "Die ausgewogene Passage löschen und neu beginnen",
          "Den Standpunkt wechseln, ohne den Grund zu nennen"
        ],
        "correctIndex": 1,
        "explanationAr": "مراجعة عالية العائد. ابن مقدمة تحدد السؤال، ثم فقرات لكل منها وظيفة وجملة محور، وخاتمة تجيب لا تكرر."
      }
    ]
  },
  {
    "id": "b2-12",
    "level": "B2",
    "module": 3,
    "titleDe": "Generalprobe",
    "titleAr": "البروفة النهائية الداخلية",
    "questions": [
      {
        "id": "b2-12-m1",
        "promptDe": "Mindeststrategie",
        "promptAr": "ما الأولوية؟",
        "options": [
          "Alle Operatoren mit einer vollständigen Grundantwort sichern",
          "Zuerst die seltensten Wörter suchen und dann mit dem Schreiben beginnen",
          "Die Einleitung so lange überarbeiten, bis der erste Absatz sicher klingt",
          "Nur die Einleitung ausarbeiten, den Rest auslassen"
        ],
        "correctIndex": 0,
        "explanationAr": "الحد الأدنى الكامل يحمي المهمة. قبل البدء اكتب عقدًا قصيرًا: المنتج، الجمهور، الأفعال، الطول أو الزمن، المصادر، والمخرجات."
      },
      {
        "id": "b2-12-m2",
        "promptDe": "Quellensynthese",
        "promptAr": "اختر الصيغة الصحيحة لحالة «Quellensynthese»:",
        "options": [
          "Beide Quellen nacheinander zusammenfassen und die eigene Bewertung dabei vollständig weglassen",
          "Die eigene These voranstellen und die Herkunft der Belege nicht zu nennen",
          "Den Bericht auswerten, das Gespräch aber als private Meinung ausblenden",
          "Bericht als Beleg, Gespräch als Einwand und eigene begrenzte Folgerung verbinden"
        ],
        "correctIndex": 3,
        "explanationAr": "يربط الوظائف ويحفظ النسبة. لا تكتب «النص يقول… ثم التسجيل يقول…» فقط."
      },
      {
        "id": "b2-12-m3",
        "promptDe": "Evidenzspur",
        "promptAr": "ماذا تتضمن؟",
        "options": [
          "Zahl der Fehler, Note des Tests und die Meinung des Lehrers notieren",
          "Stelle, Muster/Ursache, Wirkung, Folgeübung und neuen Nachweis",
          "Eine Wortliste anlegen und sie nur nach Häufigkeit sortieren",
          "Nur beschreiben, was passiert ist, ohne Nachweis"
        ],
        "correctIndex": 1,
        "explanationAr": "هذه السلسلة تحول النتيجة إلى تدريب. بعد البروفة لا تكتب «سيئ في الكلام»."
      },
      {
        "id": "b2-12-m4",
        "promptDe": "Anbietertrennung",
        "promptAr": "ما الصحيح؟",
        "options": [
          "Gemeinsame B2-Kompetenzen intern üben, offizielle Anbieterformate danach strikt trennen",
          "Beide Anbieterformate von Anfang an gemeinsam trainieren, damit die Prüfung vertraut wird",
          "Die interne Kompetenzübung weglassen und stattdessen nur offizielle Probeprüfungen zu lösen",
          "Die Goethe-Formate intern üben und dabei alle telc-Aufgaben komplett weglassen"
        ],
        "correctIndex": 0,
        "explanationAr": "المهارات المشتركة لا تبرر خلط الصيغ الرسمية: Gemeinsame B2-Kompetenzen intern üben, offizielle Anbieterformate danach strikt trennen. التدريب المشترك لا يعني الاستعداد لصيغة لم تُقَس عليها."
      },
      {
        "id": "b2-12-m5",
        "promptDe": "Selbst wenn",
        "promptAr": "اختر الصحيح:",
        "options": [
          "Auch wenn ein Wort fehlt, rede ich kurz weiter und kehre dann zurück",
          "Bei einem fehlenden Wort fange ich von vorn an",
          "Selbst wenn ein Wort fehlt, bleibe ich handlungsfähig.",
          "Wenn ein Wort fehlt, höre ich auf und bitte um einen neuen Anlauf"
        ],
        "correctIndex": 2,
        "explanationAr": "الفعل في نهاية جملة wenn، ثم الفعل ثانيًا في الرئيسية. قبل البدء اكتب عقدًا قصيرًا: المنتج، الجمهور، الأفعال، الطول أو الزمن، المصادر، والمخرجات."
      }
    ]
  },
  {
    "id": "b2-13",
    "level": "B2",
    "module": 4,
    "titleDe": "Die eigene Position revidieren",
    "titleAr": "تصحيح الموقف أمام الأدلة",
    "questions": [
      {
        "id": "b2-13-m1",
        "promptDe": "Reichweite",
        "promptAr": "اختر الأدق:",
        "options": [
          "Die Studie beweist die Regel für alle Kurse",
          "Die Studie stützt die Regel für diese zwei Kurse.",
          "Alle Kurse profitieren sicher und dauerhaft davon",
          "Die Regel ist durch nichts widerlegt"
        ],
        "correctIndex": 1,
        "explanationAr": "تطابق الدليل والعينة. العبارة الصحيحة تأخذ مداها من الدليل: نتائج مجموعتين تدعمان «في هاتين المجموعتين»، لا «في كل الدورات»."
      },
      {
        "id": "b2-13-m2",
        "promptDe": "Kriterium",
        "promptAr": "أي جملة تثبّت معيارًا مسبقًا؟",
        "options": [
          "Ich bleibe bei meiner Meinung, egal was die Daten zeigen",
          "Die Daten sind gut, deshalb bleibt alles",
          "Bleibt der Effekt aus, entfällt die Regelung.",
          "Wir messen später im nächsten Kurs erneut"
        ],
        "correctIndex": 2,
        "explanationAr": "شرط قابل للقياس. الرجوع الدقيق يُميَّز فيه ثلاث طبقات: الهدف يبقى، والوسيلة تتغيّر، والمقياس الجديد يُعلَن."
      },
      {
        "id": "b2-13-m3",
        "promptDe": "Alternativerklärung",
        "promptAr": "ما الذي يجب ذكره؟",
        "options": [
          "Nur der eigene Befund zählt am Ende des gesamten Kurses und danach",
          "Die Meinung der Gruppe ist dafür nicht relevant",
          "Ein möglicher Störfaktor wie der Niveauunterschied.",
          "Die Schlussfolgerung aus dem zweiten Bericht"
        ],
        "correctIndex": 2,
        "explanationAr": "تفسير بديل يُضعف التعميم: Ein möglicher Störfaktor wie der Niveauunterschied ينافس التفسير المطروح. ذكره يجعل الحجة أدق، وإخفاؤه يوهم بأن النتيجة محسومة."
      },
      {
        "id": "b2-13-m4",
        "promptDe": "Revision",
        "promptAr": "التراجع المنظم يعني:",
        "options": [
          "Alles zurückziehen und neu beginnen",
          "Ziel behalten, Maßnahme anpassen.",
          "Den Gegner persönlich angreifen",
          "Am Montag nichts ändern"
        ],
        "correctIndex": 1,
        "explanationAr": "يبقى الهدف وتُعدّل الوسيلة: Revision تعني تعديل الإجراء مع الحفاظ على الهدف، لا التراجع عن كل شيء ولا مهاجمة الطرف الآخر."
      },
      {
        "id": "b2-13-m5",
        "promptDe": "Belegstatus",
        "promptAr": "نتيجة لا تُعاد:",
        "options": [
          "ist ein Beleg.",
          "beweist nichts und alles.",
          "ist eine Regel.",
          "ist ein Hinweis."
        ],
        "correctIndex": 3,
        "explanationAr": "قرينة تحتاج بيانات: ist ein Hinweis يعني مؤشرًا مبدئيًا يستدعي قياسًا إضافيًا، ولا يصبح beleg أو Regel قبل أن تُضاف البيانات الداعمة."
      }
    ]
  },
  {
    "id": "b2-14",
    "level": "B2",
    "module": 4,
    "titleDe": "Kohäsion im langen Text",
    "titleAr": "تماسك النص الطويل",
    "questions": [
      {
        "id": "b2-14-m1",
        "promptDe": "Eindeutiger Verweis",
        "promptAr": "أي إحالة أوضح؟",
        "options": [
          "…der Termin und der Antrag. Dieser Antrag war unvollständig.",
          "…der Termin und der Antrag. Dieses war zu spät.",
          "…dieses. Das.",
          "…es."
        ],
        "correctIndex": 0,
        "explanationAr": "اسم مكرر يقطع الشك. كل الضمائر والأسماء الإشارةية (dieser, jener, es, man, derselbe) تحتاج مرجعًا واحدًا لا يحتمل الشك."
      },
      {
        "id": "b2-14-m2",
        "promptDe": "Relation",
        "promptAr": "للتقابل بين حلّين نختار:",
        "options": [
          "deshalb",
          "während",
          "außerdem",
          "sobald"
        ],
        "correctIndex": 1,
        "explanationAr": "während للمقابلة. Ein Konnektor trägt Bedeutung nur, wenn er die Relation nennt: Grund (weil, da), Folge (sodann, folglich, dadurch, dass … folgt), Gegensatz (während, hingegen, wohingegen), Einschränkung (allerdings, freilich), Bedingung (sofern, vorausgesetzt, dass), Mittel (indem, dadurch dass)."
      },
      {
        "id": "b2-14-m3",
        "promptDe": "Wortstellung",
        "promptAr": "بعد «Anschließend»:",
        "options": [
          "der Termin wurde bestätigt.",
          "wurde der Termin bestätigt.",
          "bestätigt wurde der Termin.",
          "den Termin bestätigte wurde."
        ],
        "correctIndex": 1,
        "explanationAr": "الفعل مباشرة بعد الموضع الأول. Ein Konnektor trägt Bedeutung nur, wenn er die Relation nennt: Grund (weil, da), Folge (sodann, folglich, dadurch, dass … folgt), Gegensatz (während, hingegen, wohingegen), Einschränkung (allerdings, freilich), Bedingung (sofern, vorausgesetzt, dass), Mittel (indem, dadurch dass)."
      },
      {
        "id": "b2-14-m4",
        "promptDe": "Nominalstil",
        "promptAr": "الحد المعقول للأسمار في جملة:",
        "options": [
          "عنقود اسمي واحد، والباقي أفعال",
          "بلا حد",
          "لا أفعال إطلاقًا",
          "أسمار في كل جملة"
        ],
        "correctIndex": 0,
        "explanationAr": "ضغط مع بقاء فعل: عنقود اسمي واحد والباقي أفعال. الأسلوب الاسمي يقصر الجملة ويكثّف المعنى، لكن إعدام الأفعال كلها يجعل النص جافًا وغامض المسؤول."
      },
      {
        "id": "b2-14-m5",
        "promptDe": "Prüfschritt",
        "promptAr": "أفضل فحص أخير:",
        "options": [
          "Rechtschreibung nur",
          "Satzlänge verdoppeln",
          "Zitattrennung hinzufügen",
          "jeden Konnektor und jedes Fürwort einzeln befragen"
        ],
        "correctIndex": 3,
        "explanationAr": "مساءلة العلاقات والمراجع: jeden Konnektor und jedes Fürwort einzeln befragen. فحص الإملاء وحده لا يكشف رابطًا مضللًا أو ضميرًا غامضًا، والسؤال عن كل أداة يكشف موضع اللبس."
      }
    ]
  },
  {
    "id": "b2-15",
    "level": "B2",
    "module": 4,
    "titleDe": "Zeitplan unter Druck",
    "titleAr": "خطة الوقت تحت الضغط",
    "questions": [
      {
        "id": "b2-15-m1",
        "promptDe": "Zwei Subjekte",
        "promptAr": "أي رابط يناسب فاعلين؟",
        "options": [
          "um … zu",
          "zu",
          "damit",
          "ohne … zu"
        ],
        "correctIndex": 2,
        "explanationAr": "مع فاعل مذكور في جملة الغرض: «damit». الغرض يُعبَّر عنه بطريقتين، والفرق ليس أسلوبيًا بل تركيبيًا: إذا كان الفاعل واحدًا في الجملتين اختيرت مجموعة «zu» أي «um … zu» بلا فاعل مذكور، وإذا ظهر فاعل في جملة الغرض لزم «damit» مع فعل مصروف في آخر الجملة."
      },
      {
        "id": "b2-15-m2",
        "promptDe": "Zeitliche Reihenfolge",
        "promptAr": "أي جملة ترتب حدثين ماضيين صحيحًا؟",
        "options": [
          "Nachdem er schrieb, las er die Aufgabe.",
          "Bevor er die Aufgabe gelesen hatte, schrieb er später.",
          "Sobald er geschrieben hatte, vorher las er.",
          "Nachdem er die Aufgabe gelesen hatte, schrieb er."
        ],
        "correctIndex": 3,
        "explanationAr": "الأسبق له أسبق الماضي. هذه الروابط تحدد أيّ الحدثين أسبق، والفعل يذهب إلى آخر الجملة."
      },
      {
        "id": "b2-15-m3",
        "promptDe": "Wortstellung",
        "promptAr": "أين الفعل في جملة بدأت ب «Bevor»؟",
        "options": [
          "nach dem Subjekt",
          "am Anfang",
          "am Ende",
          "nach dem Komma des Hauptsatzes"
        ],
        "correctIndex": 2,
        "explanationAr": "في الجملة التابعة يذهب الفعل آخرًا: بعد Bevor steht das Verb am Ende der Nebensatz، فالفعل المصرف ينتقل إلى نهاية الجملة التابعة، والجملة الرئيسية تبدأ بعدها."
      },
      {
        "id": "b2-15-m4",
        "promptDe": "Sinn des Puffers",
        "promptAr": "ماوظيفة الهامش في النص؟",
        "options": [
          "geschützte Zeit für die Kontrolle",
          "Zeit für zusätzliche Aufgaben",
          "Zeit für Rückfragen der Aufsicht",
          "Zeit zum Abschriften"
        ],
        "correctIndex": 0,
        "explanationAr": "وقت محجوز للمراجعة لا فضلات. الغرض يُعبَّر عنه بطريقتين، والفرق ليس أسلوبيًا بل تركيبيًا: إذا كان الفاعل واحدًا في الجملتين اختيرت مجموعة «zu» أي «um … zu» بلا فاعل مذكور، وإذا ظهر فاعل في جملة الغرض لزم «damit» مع فعل مصروف في آخر الجملة."
      },
      {
        "id": "b2-15-m5",
        "promptDe": "Fehlerquelle oder Flüchtigkeitsfehler",
        "promptAr": "متى يصبح الخطأ مصدرًا لا زلّة؟",
        "options": [
          "wenn er zweimal vorkommt",
          "wenn der Prüfer ihn findet",
          "wenn er in der letzten Zeile steht",
          "wenn er dreimal dieselbe Form trifft"
        ],
        "correctIndex": 3,
        "explanationAr": "التكرر المنهجي علامة نقص في التعلم. التخطيط الواقعي يفترض أن المرحلة الأخيرة مهددة بالحذف دائمًا، لذلك تُكتب لها مدة وموضع: لا «إن بقي وقت»، بل دقائق محجوزة في آخر الزمن."
      }
    ]
  },
  {
    "id": "b2-16",
    "level": "B2",
    "module": 4,
    "titleDe": "Nachlese ohne Anklage",
    "titleAr": "مراجعة بلا اتهام",
    "questions": [
      {
        "id": "b2-16-m1",
        "promptDe": "Hilfsverb wählen",
        "promptAr": "أي جملة اختارت المساعد صحيحًا؟",
        "options": [
          "Er wäre nach Hause gegangen.",
          "Er hätte nach Hause gegangen.",
          "Er wäre nach Hause gehen.",
          "Er hätte nach Hause gehen gewesen."
        ],
        "correctIndex": 0,
        "explanationAr": "«gehen» حركة ⇒ wäre + Partizip II. للحديث عن ماضٍ لم يقع يأتي الفعل المساعد في صيغة الشرط ثم التصريف الثاني في آخر الجملة: «hätte gelesen», «wäre gekommen»."
      },
      {
        "id": "b2-16-m2",
        "promptDe": "als ob",
        "promptAr": "أي صيغة تناسب «als ob» في الماضي؟",
        "options": [
          "… als ob er die Mahnung bekommt.",
          "… als ob er die Mahnung bekommen hätte.",
          "… als ob er hat die Mahnung.",
          "… als ob die Mahnung ihm ist."
        ],
        "correctIndex": 1,
        "explanationAr": "المنفي الواقع يأخذ التصريف مع المساند المؤجَّل. «als ob» و «als wenn» تصفان انطباعًا يشبه حالة لا تؤكَّدها: الفعل مؤجَّل إلى الآخر ويأتي في صيغة الشرط، وفي الماضي مركّبًا («als ob er die Frist gekannt hätte»)."
      },
      {
        "id": "b2-16-m3",
        "promptDe": "Doppelinfinitiv",
        "promptAr": "أين يقف التركيب الصحيح؟",
        "options": [
          "Das hätte ich sollen prüfen.",
          "Das ich hätte prüfen sollen.",
          "Das prüfen hätte ich sollen.",
          "Das hätte ich prüfen sollen."
        ],
        "correctIndex": 3,
        "explanationAr": "المساعد في وسط الجملة والزوج في الآخر. للنقد الذاتي أو الاعتراض المؤدَّب تُستعمل صيغة الشرط مع الأفعال الناقصة في تركيب «hätte … sollen/wollen/müssen» (وفي الجنوبية يُسمَع «hätte … gesollt» بدل «sollen» — كلاهما يُفهم، والأول هو المكتوب المعتاد): «Das hätte ich früher prüfen sollen.» هذه الصيغة تقرّ بالتقصير وتفتح في الوقت نفسه احتمال الظروف؛ ولهذا تُقرأ مهذّبة لا متهرّبة."
      },
      {
        "id": "b2-16-m4",
        "promptDe": "Ton der Nachlese",
        "promptAr": "أي جملة مراجعة لا تبرير؟",
        "options": [
          "Die Post war schuld, ich nichts.",
          "Ohne die Mahnung wäre alles gut gewesen.",
          "Das weiß jeder, dass die Aufsicht stört.",
          "Hätte ich die Frist geprüft, wäre die Gebühr entfallen."
        ],
        "correctIndex": 3,
        "explanationAr": "شرط يُسمّي خطوة لا مذنبًا. للحديث عن ماضٍ لم يقع يأتي الفعل المساعد في صيغة الشرط ثم التصريف الثاني في آخر الجملة: «hätte gelesen», «wäre gekommen»."
      },
      {
        "id": "b2-16-m5",
        "promptDe": "Abschwächung",
        "promptAr": "ما وظيفة «doch» في «Das wäre doch zu klären gewesen»؟",
        "options": [
          "Es färbt die Note höflicher, ohne die Pflicht zu ersetzen.",
          "Es verstärkt den Vorwurf.",
          "Es macht den Satz zur Frage.",
          "Es ersetzt das Partizip."
        ],
        "correctIndex": 0,
        "explanationAr": "تليّن ولا تُعفي. للحديث عن ماضٍ لم يقع يأتي الفعل المساعد في صيغة الشرط ثم التصريف الثاني في آخر الجملة: «hätte gelesen», «wäre gekommen»."
      }
    ]
  },
  {
    "id": "b2-17",
    "level": "B2",
    "module": 5,
    "titleDe": "Forderungen ohne Täter: Passiversatzformen",
    "titleAr": "طلب بلا فاعل: بدائل المبني للمجهول",
    "questions": [
      {
        "id": "b2-17-m1",
        "promptDe": "Pflicht ohne Träger",
        "promptAr": "أي جملة تفرض واجبًا وتترك الجهة معلّقة؟",
        "options": [
          "Die Belege lassen sich später beifügen.",
          "Die Belege sind bis Freitag beizufügen.",
          "Die Belege sind umgehend und vollständig beizufügen.",
          "Wir fügen die Belege selbst bei."
        ],
        "correctIndex": 1,
        "explanationAr": "«sind … beizufügen» إلزام، و «lassen sich» إمكان، والصفة تقييم."
      },
      {
        "id": "b2-17-m2",
        "promptDe": "Zu und getrennte Vorsilbe",
        "promptAr": "أين وضع «zu» صحيح مع البادئة المنفصلة؟",
        "options": [
          "einzureichen",
          "einreichen",
          "einzu reichen",
          "einreichen zu"
        ],
        "correctIndex": 0,
        "explanationAr": "مع البادئة المنفصلة تنزل zu بين الجزأين: ein + zu + reichen = einzureichen. البادئة ein في البداية و zu داخل الفعل قبل الجزء الأساسي."
      },
      {
        "id": "b2-17-m3",
        "promptDe": "Verneinte Möglichkeit",
        "promptAr": "أي جملة تنفي إمكان الإثبات لا وجوبه؟",
        "options": [
          "Das ist mit unseren Daten nicht zu belegen und bleibt offen.",
          "Das konnte bisher nicht belegt werden.",
          "Das lässt sich mit unseren Daten nicht belegen.",
          "Das muss für unsere Zwecke unbelegt bleiben."
        ],
        "correctIndex": 2,
        "explanationAr": "النفي مع «sich lassen» ينفي الإمكان عند كل أحد. تقول «Das lässt sich belegen»: الشيء قابل للإثبات، ولا تقول إن أحدًا ملزم به."
      },
      {
        "id": "b2-17-m4",
        "promptDe": "Bewertung oder Beschreibung",
        "promptAr": "ما فرق «unzumutbar» عن «nicht zumutbar»؟",
        "options": [
          "Das erste ist höflicher, das zweite ist sachlich.",
          "Das erste ist ein Werturteil, das zweite eine Feststellung.",
          "Es gibt zwischen beiden Sätzen überhaupt keinen Unterschied.",
          "Das zweite ist ein Werturteil, das erste eine schlichte Feststellung."
        ],
        "correctIndex": 1,
        "explanationAr": "«un-» يعترض، و «nicht» ينفي الواقع. تقول «Das lässt sich belegen»: الشيء قابل للإثبات، ولا تقول إن أحدًا ملزم به."
      },
      {
        "id": "b2-17-m5",
        "promptDe": "Verteilung im Brief",
        "promptAr": "أي فقرة موزّعة الوظائف لأجل خاتمة رسمية؟",
        "options": [
          "Wir bitten Sie, die Anlagen bis zum 5. zu prüfen; ein Termin ließe sich kurzfristig vereinbaren, eine mündliche Auskunft wäre nicht nachvollziehbar.",
          "Wir bitten Sie, die Anlagen bis zum 5. zu prüfen; ein Termin ließe sich kurzfristig vereinbaren, und eine mündliche Auskunft wäre danach möglich.",
          "Man könnte die Anlagen vielleicht prüfen, sofern ein Termin vereinbart wird; eine Auskunft wäre dann mündlich und nicht mehr nachvollziehbar.",
          "Wir bitten Sie, die Anlagen bis zum 5. zu prüfen; ein Termin ließe sich kurzfristig vereinbaren, und eine schriftliche Auskunft wäre in jedem Fall zumutbar."
        ],
        "correctIndex": 0,
        "explanationAr": "رجاء + إمكان + تقييم، بلا تراكم أوامر. في شكوى أو طلب تُغلِق صيغة واحدة النص: ثلاث جمل ب «sein + zu» تُقرأ أوامر مغلقة، وثلاث ب «sich lassen» تُقرأ تبريًا من المسؤولية، والصفات وحدها لا تُلزم أحدًا."
      }
    ]
  },
  {
    "id": "b2-18",
    "level": "B2",
    "module": 5,
    "titleDe": "Funktionsverbgefüge: Das Nomen steuert",
    "titleAr": "اسمٌ يقود وفعلٌ يُنفّذ: التراكيب الوظيفية في الكتابة الرسمية",
    "questions": [
      {
        "id": "b2-18-m1",
        "promptDe": "Registriert, nicht entschieden",
        "promptAr": "أي جملة تثبّت الاستلام ولا تعد بنتيجة؟",
        "options": [
          "Ihr Antrag wird zur Kenntnis genommen.",
          "Ihr Antrag wird zum Abschluss gebracht.",
          "Über Ihren Antrag ist entschieden.",
          "Wir stellen Ihnen die Unterlagen zur Verfügung."
        ],
        "correctIndex": 0,
        "explanationAr": "«zur Kenntnis nehmen» = وصول مُسجَّل؛ الباقي إما قرار أو إتمام أو عرض."
      },
      {
        "id": "b2-18-m2",
        "promptDe": "Offene Prüfung",
        "promptAr": "أين يبقى النظر مفتوحًا بلا قرار؟",
        "options": [
          "Wir haben zwei Termine festgesetzt.",
          "Wir treffen eine bindende Entscheidung.",
          "Wir ziehen zwei Termine in Betracht.",
          "Wir bringen die Prüfung zum Abschluss."
        ],
        "correctIndex": 2,
        "explanationAr": "«in Betracht ziehen» يسمّي النظر ولا يسمّي النتيجة. من يختار أحد هذه التراكيب فإنما يختار مرحلة من الإجراء: „zur Kenntnis nehmen“ sagt nur: angekommen und registriert, keine Reaktion versprochen."
      },
      {
        "id": "b2-18-m3",
        "promptDe": "Feste Präposition",
        "promptAr": "أي ربط صحيح بالجهة؟",
        "options": [
          "Wir richten unser Gesuch für die Studienberatung.",
          "Wir richten unser Gesuch der Studienberatung an.",
          "Wir richten an unser Gesuch die Studienberatung.",
          "Wir richten unser Gesuch an die Studienberatung."
        ],
        "correctIndex": 3,
        "explanationAr": "«ein Gesuch richten an» بحرفه الثابت وما بعده في موضع المفعول المباشر للحرف."
      },
      {
        "id": "b2-18-m4",
        "promptDe": "Ohne Handelnden",
        "promptAr": "أي صيغة تبقى مهذّبة لأنها لا تسمّي ملزَمًا؟",
        "options": [
          "Wir nehmen Ihren Hinweis zur Kenntnis und prüfen ihn bis Freitag.",
          "Sie haben Ihren Hinweis nicht beachtet.",
          "Ihr Hinweis findet Berücksichtigung.",
          "Wir entscheiden heute über Ihren Hinweis."
        ],
        "correctIndex": 2,
        "explanationAr": "«Berücksichtigung finden» يجعل الاهتمام فاعلًا، فلا وعد من جهة ولا تاريخ."
      },
      {
        "id": "b2-18-m5",
        "promptDe": "Kürzen statt aufblasen",
        "promptAr": "أي بديل يبقي الرسمية ويحذف النفخ؟",
        "options": [
          "Wir treffen eine Entscheidung über Ihren Antrag und nehmen eine Prüfung Ihrer Unterlagen vor.",
          "Wir entscheiden über Ihren Antrag und prüfen Ihre Unterlagen.",
          "Ihr Antrag wird von uns einer Entscheidung zugeführt.",
          "Seitens der Stelle erfolgt eine Prüfung Ihrerseits."
        ],
        "correctIndex": 1,
        "explanationAr": "فعلان مباشران يحفظان الرسمية في نصف الطول؛ الثلاثة الأخرى تدفع كلمات بلا مرحلة."
      }
    ]
  },
  {
    "id": "b2-19",
    "level": "B2",
    "module": 5,
    "titleDe": "Modalpartikeln: Wie ein kurzes Wort die Haltung sagt",
    "titleAr": "أدوات النبرة: كلمة قصيرة تحمل الموقف كلّه",
    "questions": [
      {
        "id": "b2-19-m1",
        "promptDe": "Antwort auf eine Verneinung",
        "promptAr": "«ألم تُرسل المستندات؟» — كيف تُثبت أنك أرسلتها؟",
        "options": [
          "Ja, am Montag habe ich sie ganz sicher nicht abgeschickt.",
          "Nein, abgeschickt habe ich sie am Montag ebenfalls nicht.",
          "Doch, ich habe sie am Montag abgeschickt.",
          "Doch, am Montag schicke ich sie ab."
        ],
        "correctIndex": 2,
        "explanationAr": "الإثبات بعد سؤال منفيّ ب «Doch»؛ «Ja» توافق على النفي. ل «doch» ثلاث وظائف يُخطئ المتعلم في خلطها: (1) ردّ الإثبات بعد سؤال منفيّ — «Hast du das nicht bekommen?» «Doch!»; (2) أداة خفيفة داخل الجملة تنفي افتراضًا عند المخاطَب — «Das habe ich dir doch gesagt»; (3) ظرف منبور قابل للتقديم يعني «jedoch/alles in allem» — «Es ist ein Versuch, doch kein Beweis»."
      },
      {
        "id": "b2-19-m2",
        "promptDe": "Partikel in Mitte",
        "promptAr": "أين موضع «nur» الصحيح في جملة خبرية؟",
        "options": [
          "Nur ich frage, ob der Termin gilt.",
          "Ich frage nur, ob der Termin gilt.",
          "Ich, nur frage ob der Termin gilt.",
          "Frage ich nur, ob der Termin gilt?"
        ],
        "correctIndex": 1,
        "explanationAr": "الأداة خفيفة في الوسط، بعد الفعل المُصرَّف وقبل بقية المجموعة."
      },
      {
        "id": "b2-19-m3",
        "promptDe": "Vorsicht statt Behauptung",
        "promptAr": "أي جماعة تُبقي ما تقول فرضية لا جزمًا؟",
        "options": [
          "Das ist wohl ein Versehen in der Liste.",
          "Das ist ein Versehen in der Liste; ich bestehe darauf.",
          "Das ist sicher ein Versehen in der Liste, ohne Zweifel.",
          "In der Liste steht alles richtig."
        ],
        "correctIndex": 0,
        "explanationAr": "«wohl» تُبقي الاحتمال احتمالًا؛ الباقي يجزم أو يُفترض علمًا مشتركًا."
      },
      {
        "id": "b2-19-m4",
        "promptDe": "Register in der Beschwerde",
        "promptAr": "أيّ جملة تصلح لمقال شكوى مكتوبة؟",
        "options": [
          "Ihr Bescheid vom 2. April nennt die Frist nicht; ich bitte um eine Berichtigung bis zum 15.",
          "Ihr Bescheid vom 2. April nennt die Frist nicht, und ich verlange hiermit eine Berichtigung.",
          "Sie haben die Frist in Ihrem Bescheid vom 2. April absichtlich weggelassen, oder etwa nicht?",
          "Ich danke Ihnen für Ihren Bescheid vom 2. April und komme später darauf zurück."
        ],
        "correctIndex": 0,
        "explanationAr": "الأولى وقائع وتاريخ وطلب؛ الأدوات الثلاث الباقية تحاور ولا تُثبّت."
      },
      {
        "id": "b2-19-m5",
        "promptDe": "betont oder unbetont",
        "promptAr": "متى تكون «doch» بمعنى «jedoch»؟",
        "options": [
          "Es ist ein Hinweis, doch kein Beleg.",
          "Das ist nur ein Beleg, doch kein Hinweis für uns.",
          "Ein solcher Hinweis genügt hier völlig.",
          "Belege habe ich hier keine."
        ],
        "correctIndex": 0,
        "explanationAr": "في الأولى تقابل بين شيئين وتقبل الوقوع بعد الاسم؛ في الباقي أداة خفيفة تعترض على ظنّ."
      }
    ]
  },
  {
    "id": "b2-20",
    "level": "B2",
    "module": 5,
    "titleDe": "Zweiteilige Konnektoren: Ein Satz, zwei Klammern",
    "titleAr": "الروابط ثنائية الأجزاء: جملة واحدة وقوسان",
    "questions": [
      {
        "id": "b2-20-m1",
        "promptDe": "je … desto",
        "promptAr": "أي صيغة صحيحة؟",
        "options": [
          "Je mehr Personen helfen, desto schneller ist es fertig.",
          "Je mehr Personen helfen, es ist desto schneller fertig.",
          "Je mehr Personen helfen desto, es ist schneller fertig.",
          "Je mehr helfen Personen, desto schneller ist es."
        ],
        "correctIndex": 0,
        "explanationAr": "القياس في مستهل الجزء الثاني ثم الفعل. جملة «je» جملة موقوعة فيلتصق فعلها بآخرها، والجزء الثاني يبدأ بالقياس («desto voller») ثم الفعل مباشرة."
      },
      {
        "id": "b2-20-m2",
        "promptDe": "sowohl … als auch",
        "promptAr": "ما العدد الصحيح للفعل؟",
        "options": [
          "Singular, weil das nächste Glied zählt.",
          "Plural, weil beide Glieder zusammen zählen.",
          "Immer Plural in jeder Position.",
          "Kein Verb nach „als auch“."
        ],
        "correctIndex": 1,
        "explanationAr": "الفاعل طرفان معًا: sowohl … als auch يجعله جمعًا، فيأتي الفعل Plural لأن الفاعل مركب. لا عبرة بالجزء الأخير وحده ولا موقعه."
      },
      {
        "id": "b2-20-m3",
        "promptDe": "weder … noch",
        "promptAr": "أي جملة صحيحة؟",
        "options": [
          "Weder die Mail noch das Formular hat keine Antwort.",
          "Weder die Mail oder das Formular sind da.",
          "Weder die Mail noch das Formular sind angekommen.",
          "Die Mail weder noch das Formular fehlt."
        ],
        "correctIndex": 2,
        "explanationAr": "طرفان منفيان بلا أداة نفي ثالثة. الجزآن في مرتبة واحدة: اسم مع اسم، صفة مع صفة، جملة جانبية مع جملة جانبية."
      },
      {
        "id": "b2-20-m4",
        "promptDe": "Schwerpunkt",
        "promptAr": "أين المعلومة الجديدة؟",
        "options": [
          "nach „sondern auch“.",
          "vor „nicht nur“.",
          "im ersten Hauptsatz.",
          "im Nebensatz nach „je“."
        ],
        "correctIndex": 0,
        "explanationAr": "الثقل بعد «sondern». «nicht nur …, sondern auch» يجعل الجديد بعد «sondern»؛ و «weder … noch» يوزّع النفي على الطرفين فيمنع فهمًا ناقصًا؛ و «zwar …, aber» يعترف ثم يعترض."
      },
      {
        "id": "b2-20-m5",
        "promptDe": "offizieller Ton",
        "promptAr": "أي فقرة تصلح لبريد رسمي؟",
        "options": [
          "Du hast die Bestätigung ja wieder vergessen, oder?",
          "Natürlich ist das schon wieder euer Problem!",
          "Zwar fehlt die Bestätigung, aber ich brauche sie bis Freitag, 12 Uhr.",
          "Ihr wart wohl wieder zu spät, ne?"
        ],
        "correctIndex": 2,
        "explanationAr": "اعتراف + طلب مؤرَّخ بلا نبرة. «nicht nur …, sondern auch» يجعل الجديد بعد «sondern»؛ و «weder … noch» يوزّع النفي على الطرفين فيمنع فهمًا ناقصًا؛ و «zwar …, aber» يعترف ثم يعترض."
      }
    ]
  },
  {
    "id": "b2-21",
    "level": "B2",
    "module": 6,
    "titleDe": "Berichtete Rede: Wer spricht, und wer behauptet nur?",
    "titleAr": "النقل غير المباشر: من تكلّم فعلًا، ومن يدّعي فحسب؟",
    "questions": [
      {
        "id": "b2-21-m1",
        "promptDe": "„Ich bin umgezogen.“",
        "promptAr": "ما نقل الماضي هنا؟",
        "options": [
          "Er sagte, er bin umgezogen.",
          "Er sagte, er sei umgezogen.",
          "Er sagte, er ware umgezogen.",
          "Er sagte, er umgezogen sei."
        ],
        "correctIndex": 1,
        "explanationAr": "صيغة مركّبة بـ sei تحفظ السابقة. للنقل ثلاث درجات: الحاضر (er komme)، وما سبق لحظة القول (er sei gekommen، er habe gearbeitet)، وما يُنسب إلى ما بعد التقرير (er werde prüfen)."
      },
      {
        "id": "b2-21-m2",
        "promptDe": "Wann weicht man auf eine Ersatzform aus?",
        "promptAr": "متى نلجأ إلى البديل؟",
        "options": [
          "Wenn das Verb unregelmäßig ist.",
          "Wenn das Subjekt „ich“ lautet.",
          "Nie; die Form ist Pflicht.",
          "Wenn die Form mit dem Indikativ gleich ist."
        ],
        "correctIndex": 3,
        "explanationAr": "التطابق الشكلي يُبطل قيمة التمييز: wenn die Form mit dem Indikativ gleich ist. إذا كانت صيغة Konjunktiv I مثل صيغة الخبر فلا يفيد الاستعمال، فنلجأ إلى Ersatzform."
      },
      {
        "id": "b2-21-m3",
        "promptDe": "Welcher Satz ist neutral?",
        "promptAr": "أي جملة محايدة؟",
        "options": [
          "Der Antragsteller erklärte, das Formular sei unleserlich gestempelt worden.",
          "Der Antragsteller behauptete schon wieder, …",
          "Wie üblich beschwerte sich der Antragsteller, …",
          "Man weiß ja, dass er übertreibt."
        ],
        "correctIndex": 0,
        "explanationAr": "فعل نسبة محايد مع صيغة مناسبة. صيغة النقل تُبقي المسافة: أنت تُبلّغ ولا تتبنّى."
      },
      {
        "id": "b2-21-m4",
        "promptDe": "„Wir werden entscheiden“ →",
        "promptAr": "انقل المستقبل:",
        "options": [
          "…, man entschieden werde.",
          "…, man werde entscheiden.",
          "…, man wird entscheiden.",
          "…, man entscheiden werde sein."
        ],
        "correctIndex": 1,
        "explanationAr": "الدرجة اللاحقة بـ werde في آخر الجملة. للنقل ثلاث درجات: الحاضر (er komme)، وما سبق لحظة القول (er sei gekommen، er habe gearbeitet)، وما يُنسب إلى ما بعد التقرير (er werde prüfen)."
      },
      {
        "id": "b2-21-m5",
        "promptDe": "„Laut Zeitung habe er gestohlen.“",
        "promptAr": "ما التقييم الصحيح لهذه الجملة؟",
        "options": [
          "Formal falsch: „habe“ gehört nicht hierher.",
          "Der Satz ist nur mit Anführungszeichen erlaubt.",
          "Formal korrekt, aber die Zuordnung bleibt überprüfungsbedürftig.",
          "Er ist unbrauchbar, weil „laut“ umgangssprachlich ist."
        ],
        "correctIndex": 2,
        "explanationAr": "الصيغة صحيحة والخطر في النسبة: laut Zeitung habe er gestohlen رسميًا سليم، لكن نسبة الفعل إلى شخص تحتاج تحققًا، لأن الصيغة لا تضمن صحة المضمون المنقول."
      }
    ]
  },
  {
    "id": "b2-22",
    "level": "B2",
    "module": 6,
    "titleDe": "Attribute, die den Satz strecken: Partizipien und Zusätze",
    "titleAr": "نَعْتٌ يَمُدّ الجملة: اسم الفاعل والمفعول والتوسعة",
    "questions": [
      {
        "id": "b2-22-m1",
        "promptDe": "Partizip I von „gelten“",
        "promptAr": "ما صيغة الحال من gelten؟",
        "options": [
          "die gegoltene Frist",
          "die gelten Frist",
          "die zu geltende Frist",
          "die geltende Frist"
        ],
        "correctIndex": 3,
        "explanationAr": "الحال المستمر بـ -end. يُبنى اسم الفاعل من المضارع + der: die fehlende Rückmeldung، der wahrende Anspruch."
      },
      {
        "id": "b2-22-m2",
        "promptDe": "Kommas bei erweitertem Attribut",
        "promptAr": "أي وضع للفواصل صحيح؟",
        "options": [
          "Der am Montag eingegangene Antrag wurde bearbeitet.",
          "Der, am Montag eingegangene, Antrag wurde bearbeitet.",
          "Der am, Montag, eingegangene Antrag wurde bearbeitet.",
          "Der am Montag, eingegangene Antrag, wurde bearbeitet."
        ],
        "correctIndex": 0,
        "explanationAr": "التوسعة بين الفاصلتين فقط عند الإدراج. الحلقة الوصفية كلها محصورة بفاصلتين حين تسبق الاسم: „die am Montag eingegangene, schriftlich bestätigte Beschwerde“؛ وحين تتّسع الحلقة تُستبدل بجملة موصولة."
      },
      {
        "id": "b2-22-m3",
        "promptDe": "Welche Form ist falsch?",
        "promptAr": "أي صيغة خطأ؟",
        "options": [
          "die eingegangene Beschwerde",
          "die zu bearbeitende Beschwerde",
          "die fehlende Rückmeldung",
          "die eingegangen Beschwerde"
        ],
        "correctIndex": 3,
        "explanationAr": "ينقصها نهاية الإعراب -e: die eingegangen Beschwerde خطأ، والصحيح die eingegangene Beschwerde. الصفة المشتقة من Partizip II تأخذ نهاية الإعراب عند الإضافة."
      },
      {
        "id": "b2-22-m4",
        "promptDe": "Zu + Infinitiv",
        "promptAr": "ما دلالة „der zu klärende Punkt“؟",
        "options": [
          "Er wurde bereits geklärt.",
          "Er wird gerade geklärt.",
          "Er muss noch geklärt werden.",
          "Er kann nicht geklärt werden."
        ],
        "correctIndex": 2,
        "explanationAr": "الإلزام المستقبلي: der zu klärende Punkt يعني نقطة يجب أن تُحل لاحقًا، لا حُلّت ولا تُحل الآن. التركيب zu + Partizip I ينقل ما ينتظر الإنجاز."
      },
      {
        "id": "b2-22-m5",
        "promptDe": "Bester Text für Lesende",
        "promptAr": "أي نسخة أنسب للقارئ؟",
        "options": [
          "Ein Satz mit fünf engen Attributen.",
          "Zwei kurze Sätze mit klarem Subjekt.",
          "Ein Satz ohne Artikel.",
          "Drei Sätze ohne Zeitangabe."
        ],
        "correctIndex": 1,
        "explanationAr": "الوضوح قبل الضغط: Zwei kurze Sätze mit klarem Subjekt أفضل من جملة بخمس سمات ضيقة. القارئ يتابع المعنى أسرع حين يعرف من يفعل ماذا في كل جملة."
      }
    ]
  },
  {
    "id": "b2-23",
    "level": "B2",
    "module": 6,
    "titleDe": "Ketten lösen: Genitiv und Kompositum",
    "titleAr": "سلاسل تُفَكّ: إضافة الاسم والمركّب الاسمي",
    "questions": [
      {
        "id": "b2-23-m1",
        "promptDe": "Genus von „Nachforderung“",
        "promptAr": "ما أداة „Nachforderung“؟",
        "options": [
          "der",
          "die",
          "das",
          "den"
        ],
        "correctIndex": 1,
        "explanationAr": "الرأس -ung مؤنّث دائمًا. الرأس -ung مؤنّث، فيأخذ المركّب كله die: die Studienberatung."
      },
      {
        "id": "b2-23-m2",
        "promptDe": "Was ist die Fuge in „Prüfungsamt“?",
        "promptAr": "ما الوصلة في „Prüfungsamt“؟",
        "options": [
          "-n-",
          "-e-",
          "—",
          "-s-"
        ],
        "correctIndex": 3,
        "explanationAr": "وصلة المفرد الشائعة -s-. وصلة -s- شائعة قبل المؤنث: Studien + s + Beratung، وليست قاعدة لكل المركّبات."
      },
      {
        "id": "b2-23-m3",
        "promptDe": "Welche Schreibung ist korrekt?",
        "promptAr": "أي كتابة صحيحة؟",
        "options": [
          "Studien Beratung",
          "Studienberatung",
          "Studien-Beratung-2",
          "Studienberatung2024 im Titel"
        ],
        "correctIndex": 1,
        "explanationAr": "متصل بلا مسافة. يُكتب المركّب كلمة واحدة؛ «Studien Beratung» بفراغ خطأ إملائي."
      },
      {
        "id": "b2-23-m4",
        "promptDe": "Womit löst du „die Überprüfung der Zahlungen des Mieters“ auf?",
        "promptAr": "كيف تُزيل اللبس عن هذه السلسلة؟",
        "options": [
          "Die Zahlungen prüften den Mieter.",
          "Es wurde gezahlt und geprüft.",
          "Der Vermieter prüfte die Zahlungen des Mieters.",
          "Der Mieter überprüfte seine Zahlungen selbst und die Vermieter auch."
        ],
        "correctIndex": 2,
        "explanationAr": "فاعل وفعل يقطعان الغموض. لكل حلقة وظيفتان محتملتان: فاعلية (die Prüfung des Kandidaten = هو يُمتحَن/يفحص) ومفعولية (هو مَن يُفتَش)."
      },
      {
        "id": "b2-23-m5",
        "promptDe": "Wo bleibt der amtliche Betreff unverändert?",
        "promptAr": "أين يبقى العنوان الرسمي دون تغيير؟",
        "options": [
          "Im Betreff der eigenen E-Mail",
          "In jedem Fließtext",
          "Nirgends; er ist immer umzuschreiben",
          "Nur in der mündlichen Auskunft"
        ],
        "correctIndex": 0,
        "explanationAr": "المرجع في السطر الأول يُنقل حرفيًا. في نصٍّ موجّه إلى جمهور يُفتَح المكتظّ: سلسلة من أربع حلقات تصبح جملتين بفعل مصوغ."
      }
    ]
  },
  {
    "id": "b2-24",
    "level": "B2",
    "module": 6,
    "titleDe": "Kommas, die Struktur zeigen: Zeichensetzung im langen Satz",
    "titleAr": "فواصل تُظهر البنية: الترقيم في الجملة الطويلة",
    "questions": [
      {
        "id": "b2-24-m1",
        "promptDe": "Pflichtkomma?",
        "promptAr": "أين الفاصلة إلزامية؟",
        "options": [
          "Er versuchte zu schlafen.",
          "Sie fing an zu lesen.",
          "Ohne die Frist zu versäumen, reichten wir ein.",
          "Wir baten zu prüfen."
        ],
        "correctIndex": 2,
        "explanationAr": "„ohne … zu“ في أول الجملة. الفاصلة إلزامية إذا بدأت المجموعة بـ um, ohne, statt, anstatt, außer, aber، أو إذا كانت مرتبطة باسم أو بفعل يحتاج إلى توضيح، أو إذا سبقها كلمة إشارة (darum, daran, dazu, hierfür)."
      },
      {
        "id": "b2-24-m2",
        "promptDe": "Rechte Klammer",
        "promptAr": "أي جملة أُغلق قوسها صحيحًا؟",
        "options": [
          "Dass er widersprach, ist notiert.",
          "Dass er widersprach ist notiert.",
          "Dass, er widersprach, ist notiert.",
          "Dass er, widersprach ist notiert."
        ],
        "correctIndex": 0,
        "explanationAr": "القوس الأيمن يأتي بعد فعل الجملة الجانبية. كل جملة جانبية محصورة بفاصلتين: قبل أداة الربط وقبل الفعل المسند في نهاية الجملة الرئيسية."
      },
      {
        "id": "b2-24-m3",
        "promptDe": "Vor „und“",
        "promptAr": "متى تُكتب فاصلة قبل und؟",
        "options": [
          "Nie.",
          "Wenn ein Nebensatz zu schließen ist.",
          "Immer bei Aufzählungen.",
          "Nur in Briefen."
        ],
        "correctIndex": 1,
        "explanationAr": "الغرض إغلاق القوس لا ربط المستقلّين: الفاصلة قبل und تأتي عندما تُغلق جملة فرعية قبلها. أما عطف عنصرين مستقلّين في العادة فلا يحتاج فاصلة."
      },
      {
        "id": "b2-24-m4",
        "promptDe": "Hinweiswort",
        "promptAr": "أي كلمة تُوجب الفاصلة قبل المصدر؟",
        "options": [
          "dann",
          "vielleicht",
          "kaum",
          "darum"
        ],
        "correctIndex": 3,
        "explanationAr": "„darum/daran/dazu“ كلمات إشارة. الفاصلة إلزامية إذا بدأت المجموعة بـ um, ohne, statt, anstatt, außer, aber، أو إذا كانت مرتبطة باسم أو بفعل يحتاج إلى توضيح، أو إذا سبقها كلمة إشارة (darum, daran, dazu, hierfür)."
      },
      {
        "id": "b2-24-m5",
        "promptDe": "Vor der Abgabe",
        "promptAr": "ما أول خطوة في الفحص؟",
        "options": [
          "Satzlänge verdoppeln.",
          "Synonyme einsetzen.",
          "Offene Klammern zählen.",
          "Alle Kommas löschen."
        ],
        "correctIndex": 2,
        "explanationAr": "العَدّ قبل الذوق: Offene Klammern zählen. أول خطوة عملية في الفحص أن تتأكد أن كل قوس مفتوح له قوس مغلق، ثم تُراجع الفواصل والأسطر."
      }
    ]
  }
] as const satisfies readonly LocalTestTemplateLesson[];
