"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { AlertTriangle, ArrowLeft, Check, ClipboardList, LockKeyhole, RotateCcw, ShieldCheck, Unlock } from "lucide-react";
import { academicLessonList } from "@/data/academic-lessons";
import { useLearning } from "./learning-provider";

const a1Lessons=academicLessonList.filter((lesson)=>lesson.level==="A1");
const questions=a1Lessons.flatMap((lesson)=>lesson.miniTest.slice(0,2).map((question)=>({...question,module:lesson.module,lessonId:lesson.id})));

export function A1LevelAssessment(){
  const{state,update}=useLearning();const[answers,setAnswers]=useState<Record<string,number>>({});const[finished,setFinished]=useState(false);
  const score=questions.filter((q)=>answers[q.id]===q.correctIndex).length;
  const moduleScores=useMemo(()=>Object.fromEntries(Array.from({length:8},(_,i)=>{const qs=questions.filter((q)=>q.module===i+1);return[i+1,qs.filter((q)=>answers[q.id]===q.correctIndex).length]})),[answers]);
  const criteria={knowledge:score>=38,lessons:state.completedLessonIds.filter((id)=>id.startsWith("a1-")).length>=24,writing:state.writingSubmissions.filter((x)=>x.status!=="draft").length>=3,speaking:state.speakingAttempts.length>=3,diagnostic:!!state.diagnosticResult};
  const ready=Object.values(criteria).every(Boolean);
  function finish(){setFinished(true);update((current)=>({...current,mastery:{...current.mastery,"level-a1-knowledge":Math.round(score/questions.length*100),"level-a1-ready":ready?100:0},studyHistory:[...current.studyHistory,{date:new Date().toISOString().slice(0,10),minutes:45,evidenceCount:questions.length}]}))}
  if(finished)return <div className="level-result"><header><span className={ready?"ready":"locked"}>{ready?<Unlock size={28}/>:<LockKeyhole size={28}/>}</span><small>بوابة A1 — تقييم داخلي غير رسمي</small><h1>{score}<i>/48</i></h1><h2>{ready?"أدلة A1 مكتملة — يمكن بدء A2":"المعرفة جزء واحد من الجاهزية"}</h2><p>لا يفتح النظام A2 من علامة اختيارات فقط. يجب إكمال المسار وتقديم أدلة كتابة ومحادثة وتشخيص أولي.</p></header><div className="gate-criteria">{[
    ["knowledge","اختبار المعرفة",`${score}/48 — المطلوب 38`],["lessons","الدروس المكتملة",`${state.completedLessonIds.filter((id)=>id.startsWith("a1-")).length}/24`],["writing","عينات الكتابة",`${state.writingSubmissions.filter((x)=>x.status!=="draft").length}/3`],["speaking","عينات المحادثة",`${state.speakingAttempts.length}/3`],["diagnostic","التشخيص","مكتمل قبل التخطيط"],
  ].map(([key,label,detail])=><article key={key} className={criteria[key as keyof typeof criteria]?"passed":""}><span>{criteria[key as keyof typeof criteria]?<Check size={15}/>:<LockKeyhole size={15}/>}</span><div><strong>{label}</strong><small>{detail}</small></div></article>)}</div><section className="module-score-report"><h3>توزيع المعرفة حسب الوحدة</h3><div>{Object.entries(moduleScores).map(([module,value])=><article key={module}><span>الوحدة {module}</span><i><b style={{width:`${Number(value)/6*100}%`}}/></i><strong>{String(value)}/6</strong></article>)}</div></section><footer><Link href={ready?"/today":"/errors"} className="primary-button">{ready?"ابنِ أول مهمة A2":"عالج الفجوات"}<ArrowLeft size={17}/></Link><button className="secondary-button" onClick={()=>{setFinished(false);setAnswers({})}}><RotateCcw size={16}/> صيغة تدريب جديدة لاحقًا</button></footer></div>;
  return <div className="wide-page"><header className="page-heading"><div><span className="eyebrow"><ClipboardList size={15}/> تقييم نهاية A1</span><h1>اختبر النقل، <em>لا الذاكرة القريبة.</em></h1><p>48 سؤالًا يغطي الوحدات الثماني. أجب دون فتح الدروس. النتيجة المعرفية لا تكفي وحدها لفتح A2.</p></div><div className="path-summary"><strong>{Object.keys(answers).length}</strong><span>إجابة<br/>من أصل 48</span></div></header><div className="assessment-warning"><AlertTriangle size={18}/><p><b>وضع تقييم:</b> لا تظهر التفسيرات الآن. بعد الإنهاء يعرض النظام الوحدات الضعيفة ويعيدك إلى العلاج، لا إلى حفظ نفس الأسئلة.</p></div><div className="level-question-list">{Array.from({length:8},(_,moduleIndex)=><section key={moduleIndex}><header><span>A1 · الوحدة {moduleIndex+1}</span><strong>{Object.keys(answers).filter((id)=>questions.find((q)=>q.id===id)?.module===moduleIndex+1).length}/6</strong></header>{questions.filter((q)=>q.module===moduleIndex+1).map((question,index)=><article key={question.id}><small>{index+1}</small><div><h3>{question.promptAr}</h3><p lang="de" dir="ltr">{question.promptDe}</p></div><select value={answers[question.id]??""} onChange={(e)=>setAnswers((current)=>({...current,[question.id]:Number(e.target.value)}))}><option value="">اختر الجواب</option>{question.options.map((option,optionIndex)=><option key={option} value={optionIndex}>{option}</option>)}</select></article>)}</section>)}</div><button className="primary-button level-submit" disabled={Object.keys(answers).length<questions.length} onClick={finish}><ShieldCheck size={17}/> إنهاء وحساب بوابة A1</button></div>
}
