"use client";
import { useMemo,useState } from "react";
import Link from "next/link";
import { AlertTriangle,ArrowLeft,Check,ClipboardList,LockKeyhole,RotateCcw,ShieldCheck,Unlock } from "lucide-react";
import { academicLessonList } from "@/data/academic-lessons";
import { useLearning } from "./learning-provider";

const a2Lessons=academicLessonList.filter((lesson)=>lesson.level==="A2");
const questions=a2Lessons.flatMap((lesson)=>lesson.miniTest.slice(0,2).map((question)=>({...question,module:lesson.module,lessonId:lesson.id})));

export function A2LevelAssessment(){
  const{state,update}=useLearning();const[answers,setAnswers]=useState<Record<string,number>>({});const[finished,setFinished]=useState(false);const score=questions.filter((q)=>answers[q.id]===q.correctIndex).length;
  const moduleScores=useMemo(()=>Object.fromEntries(Array.from({length:8},(_,index)=>{const items=questions.filter((q)=>q.module===index+1);return[index+1,items.filter((q)=>answers[q.id]===q.correctIndex).length]})),[answers]);
  const a2Writing=state.writingSubmissions.filter((item)=>item.taskId.startsWith("a2-")&&item.status!=="draft").length;const a2Speaking=state.speakingAttempts.filter((item)=>item.taskId.startsWith("a2-")).length;const completed=state.completedLessonIds.filter((id)=>id.startsWith("a2-")).length;
  const criteria={prerequisite:(state.mastery["level-a1-ready"]??0)>=100,knowledge:score>=38,lessons:completed>=24,writing:a2Writing>=4,speaking:a2Speaking>=4,diagnostic:!!state.diagnosticResult};const ready=Object.values(criteria).every(Boolean);
  function finish(){setFinished(true);update((current)=>({...current,mastery:{...current.mastery,"level-a2-knowledge":Math.round(score/questions.length*100),"level-a2-ready":ready?100:0},studyHistory:[...current.studyHistory,{date:new Date().toISOString().slice(0,10),minutes:55,evidenceCount:questions.length}]}))}
  if(finished)return <div className="level-result"><header><span className={ready?"ready":"locked"}>{ready?<Unlock size={28}/>:<LockKeyhole size={28}/>}</span><small>بوابة A2 — تقييم داخلي غير رسمي</small><h1>{score}<i>/48</i></h1><h2>{ready?"أدلة A2 مكتملة — يمكن بدء B1":"العلامة لا تكفي دون إنتاج واحتفاظ"}</h2><p>تحتاج البوابة إلى نجاح معرفي، إكمال المسار، عينات كتابة ومحادثة مرتبطة بـA2، وبوابة A1 السابقة.</p></header><div className="gate-criteria">{[
    ["prerequisite","بوابة A1",criteria.prerequisite?"مكتملة":"غير مكتملة"],["knowledge","اختبار المعرفة",`${score}/48 — المطلوب 38`],["lessons","دروس A2",`${completed}/24`],["writing","كتابات A2",`${a2Writing}/4`],["speaking","محاولات A2",`${a2Speaking}/4`],["diagnostic","التشخيص","دليل البداية"],
  ].map(([key,label,detail])=><article key={String(key)} className={criteria[key as keyof typeof criteria]?"passed":""}><span>{criteria[key as keyof typeof criteria]?<Check size={15}/>:<LockKeyhole size={15}/>}</span><div><strong>{label}</strong><small>{String(detail)}</small></div></article>)}</div><section className="module-score-report"><h3>نتيجة المعرفة حسب وحدة A2</h3><div>{Object.entries(moduleScores).map(([module,value])=><article key={module}><span>الوحدة {module}</span><i><b style={{width:`${Number(value)/6*100}%`}}/></i><strong>{String(value)}/6</strong></article>)}</div></section><footer><Link href={ready?"/today":"/errors"} className="primary-button">{ready?"ابنِ أول مهمة B1":"عالج الفجوات"}<ArrowLeft size={17}/></Link><button className="secondary-button" onClick={()=>{setFinished(false);setAnswers({})}}><RotateCcw size={16}/> إعادة صيغة تدريب</button></footer></div>;
  return <div className="wide-page"><header className="page-heading"><div><span className="eyebrow"><ClipboardList size={15}/> تقييم نهاية A2</span><h1>أثبت الاستقلال الأول، <em>لا حفظ الخيارات.</em></h1><p>48 سؤالًا متوازنًا على ثماني وحدات. بعدها تُفحص أدلة الكتابة والمحادثة وإكمال المسار قبل B1.</p></div><div className="path-summary"><strong>{Object.keys(answers).length}</strong><span>إجابة<br/>من أصل 48</span></div></header><div className="assessment-warning"><AlertTriangle size={18}/><p><b>وضع تقييم:</b> أجب دون فتح الدروس. النتيجة المنخفضة تعيدك إلى الوحدة الأضعف، والمرتفعة لا تلغي متطلبات الإنتاج.</p></div><div className="level-question-list">{Array.from({length:8},(_,moduleIndex)=><section key={moduleIndex}><header><span>A2 · الوحدة {moduleIndex+1}</span><strong>{Object.keys(answers).filter((id)=>questions.find((q)=>q.id===id)?.module===moduleIndex+1).length}/6</strong></header>{questions.filter((q)=>q.module===moduleIndex+1).map((question,index)=><article key={question.id}><small>{index+1}</small><div><h3>{question.promptAr}</h3><p lang="de" dir="ltr">{question.promptDe}</p></div><select value={answers[question.id]??""} onChange={(event)=>setAnswers((current)=>({...current,[question.id]:Number(event.target.value)}))}><option value="">اختر الجواب</option>{question.options.map((option,optionIndex)=><option key={option} value={optionIndex}>{option}</option>)}</select></article>)}</section>)}</div><button className="primary-button level-submit" disabled={Object.keys(answers).length<questions.length} onClick={finish}><ShieldCheck size={17}/> إنهاء وحساب بوابة A2</button></div>
}
