"use client";
import { useMemo,useState } from "react";
import Link from "next/link";
import { AlertTriangle,ArrowLeft,Check,ClipboardList,LockKeyhole,RotateCcw,ShieldCheck,Unlock } from "lucide-react";
import { academicLessonList } from "@/data/academic-lessons";
import { useLearning } from "./learning-provider";
const lessons=academicLessonList.filter((lesson)=>lesson.level==="B1");
const questions=lessons.flatMap((lesson)=>lesson.miniTest.slice(0,2).map((question)=>({...question,module:lesson.module,lessonId:lesson.id})));
export function B1LevelAssessment(){
 const{state,update}=useLearning();const[answers,setAnswers]=useState<Record<string,number>>({});const[finished,setFinished]=useState(false);const score=questions.filter((q)=>answers[q.id]===q.correctIndex).length;const moduleScores=useMemo(()=>Object.fromEntries(Array.from({length:8},(_,i)=>{const items=questions.filter((q)=>q.module===i+1);return[i+1,items.filter((q)=>answers[q.id]===q.correctIndex).length]})),[answers]);
 const writing=state.writingSubmissions.filter((item)=>item.taskId.startsWith("b1-")&&item.status!=="draft").length;const speaking=state.speakingAttempts.filter((item)=>item.taskId.startsWith("b1-")).length;const completed=state.completedLessonIds.filter((id)=>id.startsWith("b1-")).length;const criteria={prerequisite:(state.mastery["level-a2-ready"]??0)>=100,knowledge:score>=38,lessons:completed>=24,writing:writing>=5,speaking:speaking>=5,diagnostic:!!state.diagnosticResult};const ready=Object.values(criteria).every(Boolean);
 function finish(){setFinished(true);update((current)=>({...current,mastery:{...current.mastery,"level-b1-knowledge":Math.round(score/questions.length*100),"level-b1-ready":ready?100:0},studyHistory:[...current.studyHistory,{date:new Date().toISOString().slice(0,10),minutes:60,evidenceCount:questions.length}]}))}
 if(finished)return <div className="level-result"><header><span className={ready?"ready":"locked"}>{ready?<Unlock size={28}/>:<LockKeyhole size={28}/>}</span><small>بوابة B1 — تقييم داخلي غير رسمي</small><h1>{score}<i>/48</i></h1><h2>{ready?"أدلة B1 مكتملة — يمكن بدء B2":"الاستقلال في B1 يحتاج إنتاجًا ومشروعًا متماسكًا"}</h2><p>لا يكفي اختبار الاختيارات. تُفحص بوابة A2 وإكمال 24 درسًا وخمس كتابات وخمس محاولات محادثة مرتبطة بـB1.</p></header><div className="gate-criteria">{[["prerequisite","بوابة A2",criteria.prerequisite?"مكتملة":"غير مكتملة"],["knowledge","اختبار المعرفة",`${score}/48 — المطلوب 38`],["lessons","دروس B1",`${completed}/24`],["writing","كتابات B1",`${writing}/5`],["speaking","محاولات B1",`${speaking}/5`],["diagnostic","التشخيص","دليل البداية"]].map(([key,label,detail])=><article key={String(key)} className={criteria[key as keyof typeof criteria]?"passed":""}><span>{criteria[key as keyof typeof criteria]?<Check size={15}/>:<LockKeyhole size={15}/>}</span><div><strong>{label}</strong><small>{String(detail)}</small></div></article>)}</div><section className="module-score-report"><h3>نتيجة المعرفة حسب وحدة B1</h3><div>{Object.entries(moduleScores).map(([module,value])=><article key={module}><span>الوحدة {module}</span><i><b style={{width:`${Number(value)/6*100}%`}}/></i><strong>{String(value)}/6</strong></article>)}</div></section><footer><Link href={ready?"/today":"/errors"} className="primary-button">{ready?"ابنِ أول مهمة B2":"عالج الفجوات"}<ArrowLeft size={17}/></Link><button className="secondary-button" onClick={()=>{setFinished(false);setAnswers({})}}><RotateCcw size={16}/> إعادة صيغة تدريب</button></footer></div>;
 return <div className="wide-page"><header className="page-heading"><div><span className="eyebrow"><ClipboardList size={15}/> تقييم نهاية B1</span><h1>أثبت الاستقلال، <em>ثم ابدأ B2.</em></h1><p>48 سؤالًا موزعًا على الوحدات الثماني، مع بوابة إنتاج تمنع الانتقال اعتمادًا على التعرف فقط.</p></div><div className="path-summary"><strong>{Object.keys(answers).length}</strong><span>إجابة<br/>من أصل 48</span></div></header><div className="assessment-warning"><AlertTriangle size={18}/><p><b>وضع تقييم:</b> لا تفتح الدروس أثناء الاختبار. ستُعرض الوحدات الضعيفة بعد الإنهاء، وتبقى الكتابة والمحادثة شرطًا مستقلًا.</p></div><div className="level-question-list">{Array.from({length:8},(_,moduleIndex)=><section key={moduleIndex}><header><span>B1 · الوحدة {moduleIndex+1}</span><strong>{Object.keys(answers).filter((id)=>questions.find((q)=>q.id===id)?.module===moduleIndex+1).length}/6</strong></header>{questions.filter((q)=>q.module===moduleIndex+1).map((question,index)=><article key={question.id}><small>{index+1}</small><div><h3>{question.promptAr}</h3><p lang="de" dir="ltr">{question.promptDe}</p></div><select value={answers[question.id]??""} onChange={(event)=>setAnswers((current)=>({...current,[question.id]:Number(event.target.value)}))}><option value="">اختر الجواب</option>{question.options.map((option,optionIndex)=><option key={option} value={optionIndex}>{option}</option>)}</select></article>)}</section>)}</div><button className="primary-button level-submit" disabled={Object.keys(answers).length<questions.length} onClick={finish}><ShieldCheck size={17}/> إنهاء وحساب بوابة B1</button></div>
}
