"use client";

import { Activity, CalendarClock, CheckCircle2, CircleAlert, TrendingDown, TrendingUp } from "lucide-react";
import { buildErrorInterventionTimeline, buildWeeklyErrorTrend, ERROR_INTERVENTION_TIMELINE_POLICY, ERROR_WEEKLY_TREND_POLICY } from "@/core/errors/insights";
import { useLearning } from "./learning-provider";

const directionLabel={decreasing:"يتناقص في الأسابيع المرصودة",stable:"مستقر تقريبًا",increasing:"يحتاج انتباهًا", "insufficient-data":"بيانات غير كافية"} as const;

export function ErrorInsightsPanel(){
  const{state}=useLearning();const trend=buildWeeklyErrorTrend(state);const timeline=buildErrorInterventionTimeline(state);const observed=trend.weeks.map((week,index)=>week.errorRatePercent===null?null:{x:30+index*(640/Math.max(1,trend.weeks.length-1)),y:145-week.errorRatePercent*1.15,value:week.errorRatePercent});const points=observed.filter(Boolean) as Array<{x:number;y:number;value:number}>;const path=points.map((point,index)=>`${index?"L":"M"}${point.x.toFixed(1)},${point.y.toFixed(1)}`).join(" ");
  return <section className="error-insights-panel" aria-label="اتجاه الأخطاء والتدخلات">
    <article className="weekly-error-trend" data-error-trend-policy={ERROR_WEEKLY_TREND_POLICY}><header><span>{trend.direction==="decreasing"?<TrendingDown size={20}/>:trend.direction==="increasing"?<TrendingUp size={20}/>:<Activity size={20}/>}</span><div><small>آخر ثمانية أسابيع · من محاولات فعلية فقط</small><h2>هل تقل أخطائي مع الوقت؟</h2><p>{trend.summaryAr}</p></div><b>{directionLabel[trend.direction]}</b></header><svg viewBox="0 0 700 180" role="img" aria-label="منحنى نسبة المحاولات الخاطئة أسبوعيًا من صفر إلى مئة بالمئة"><line x1="30" y1="30" x2="30" y2="145"/><line x1="30" y1="145" x2="670" y2="145"/>{path&&<path d={path}/>} {points.map((point,index)=><circle key={`${point.x}:${index}`} cx={point.x} cy={point.y} r="6"><title>{point.value}%</title></circle>)}</svg><div>{trend.weeks.map((week)=><span key={week.weekStart} className={week.errorRatePercent===null?"empty":""}><small>{week.labelAr}</small><b>{week.errorRatePercent===null?"—":`${week.errorRatePercent}%`}</b><em>{week.attemptCount} محاولة · {week.uniqueErrorItems} عناصر مختلفة</em></span>)}</div><footer>النسبة = المحاولات الخاطئة ÷ جميع محاولات التمرين في الأسبوع. الاتجاه وصفي، ولا يثبت أن تدخلًا معينًا سبّب التحسن أو التراجع.</footer></article>
    <article className="error-intervention-timeline" data-intervention-timeline-policy={ERROR_INTERVENTION_TIMELINE_POLICY}><header><span><CalendarClock size={20}/></span><div><small>تسلسل زمني مشتق دون نص إجابتك</small><h2>ماذا جربنا، وماذا حدث بعده؟</h2></div><b>{timeline.length} حدثًا</b></header>{timeline.length?<ol>{timeline.slice(0,12).map((event)=><li key={event.id} className={event.sensitiveInPrint?"sensitive-in-print":""}><span>{event.kind==="error-confirmed"||event.kind==="repair-succeeded"?<CheckCircle2 size={16}/>:<CircleAlert size={16}/>}</span><div><small>{new Intl.DateTimeFormat("ar-TN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(event.occurredAt))}{event.errorType?` · ${event.errorType}`:""}</small><strong>{event.titleAr}</strong><p>{event.outcomeAr}</p></div></li>)}</ol>:<p className="empty-timeline">ستظهر هنا محاولات العلاج والعيادة والمراجعة بعد أن تسجل أخطاء فعلية. لا نصنع أحداثًا افتراضية.</p>}<footer>هذا ترتيب زمني لا تجربة سببية: النجاح بعد تدخل لا يثبت أن التدخل وحده هو السبب. الأحداث الحساسة للطباعة تختفي مع سجلها.</footer></article>
  </section>;
}
