"use client";

import { useEffect,useRef,useState } from "react";
import { Keyboard,X } from "lucide-react";
import { GERMAN_CHARACTERS,GERMAN_CHARACTER_KEYBOARD_POLICY,insertGermanCharacter,isGermanTextEntry,type GermanCharacter } from "@/core/accessibility/german-character-input";

export function GermanCharacterDock(){
  const targetRef=useRef<HTMLInputElement|HTMLTextAreaElement|null>(null);const[visible,setVisible]=useState(false);const[collapsed,setCollapsed]=useState(false);
  useEffect(()=>{let hideTimer:number|undefined;const focusIn=(event:FocusEvent)=>{if(isGermanTextEntry(event.target)){targetRef.current=event.target;setCollapsed(false);setVisible(true)}};const focusOut=()=>{hideTimer=window.setTimeout(()=>{if(!isGermanTextEntry(document.activeElement)){targetRef.current=null;setVisible(false)}},80)};const inputChanged=(event:Event)=>{if(event.target===targetRef.current)setCollapsed(true)};const keyDown=(event:KeyboardEvent)=>{if(event.key==="Escape"&&visible){setVisible(false);targetRef.current?.focus()}};document.addEventListener("focusin",focusIn);document.addEventListener("focusout",focusOut);document.addEventListener("input",inputChanged);document.addEventListener("keydown",keyDown);return()=>{if(hideTimer)window.clearTimeout(hideTimer);document.removeEventListener("focusin",focusIn);document.removeEventListener("focusout",focusOut);document.removeEventListener("input",inputChanged);document.removeEventListener("keydown",keyDown)}},[visible]);
  function insert(character:GermanCharacter){const target=targetRef.current;if(!target)return;const next=insertGermanCharacter(target.value,target.selectionStart,target.selectionEnd,character);const prototype=target instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;const setter=Object.getOwnPropertyDescriptor(prototype,"value")?.set;setter?.call(target,next.value);target.dispatchEvent(new Event("input",{bubbles:true}));target.focus();target.setSelectionRange(next.selectionStart,next.selectionEnd);setCollapsed(true)}
  if(!visible)return null;
  if(collapsed)return <aside className="german-character-dock collapsed" data-german-keyboard-policy={GERMAN_CHARACTER_KEYBOARD_POLICY}><button type="button" onPointerDown={(event)=>event.preventDefault()} onClick={()=>setCollapsed(false)} aria-label="إظهار لوحة الحروف الألمانية"><Keyboard size={19}/></button></aside>;
  return <aside className="german-character-dock" data-german-keyboard-policy={GERMAN_CHARACTER_KEYBOARD_POLICY} aria-label="لوحة الحروف الألمانية"><header><Keyboard size={15}/><span><b>Deutsche Zeichen</b><small>أحرف ألمانية للحقل الحالي</small></span><button type="button" onPointerDown={(event)=>event.preventDefault()} onClick={()=>setVisible(false)} aria-label="إغلاق لوحة الحروف"><X size={15}/></button></header><div lang="de" dir="ltr">{GERMAN_CHARACTERS.map((character)=><button type="button" key={character} onPointerDown={(event)=>event.preventDefault()} onClick={()=>insert(character)} aria-label={`إدخال الحرف الألماني ${character}`}>{character}</button>)}</div><footer>تكتب الحرف عند المؤشر فقط؛ لا تصحح الإجابة ولا ترسل النص.</footer></aside>;
}
