"use client";
import {createContext,useCallback,useContext,useEffect,useMemo,useState} from "react";
import type{LearningState}from"@/types/learning";
import{createLearningProfile,defaultState,deleteLearningProfile,ensureProfileRegistry,listLearningProfiles,loadLearningState,renameLearningProfile,saveLearningState,switchLearningProfile,type LocalProfileSummary}from"@/core/portability/db";
type LearningContextValue={state:LearningState;ready:boolean;activeProfileId:string;profiles:LocalProfileSummary[];update:(updater:(current:LearningState)=>LearningState)=>void;replace:(state:LearningState)=>void;adoptCommittedState:(state:LearningState,profileId:string)=>Promise<void>;refreshProfiles:()=>Promise<void>;switchProfile:(id:string)=>Promise<void>;addProfile:(state:LearningState,id?:string)=>Promise<string>;renameProfile:(id:string,name:string)=>Promise<void>;deleteProfile:(id:string)=>Promise<void>};
const LearningContext=createContext<LearningContextValue|null>(null);
export function LearningProvider({children}:{children:React.ReactNode}){const[state,setState]=useState<LearningState>(defaultState);const[ready,setReady]=useState(false);const[activeProfileId,setActiveProfileId]=useState("primary");const[profiles,setProfiles]=useState<LocalProfileSummary[]>([]);
 useEffect(()=>{let active=true;const fallback=window.setTimeout(()=>{if(active)setReady(true)},750);loadLearningState().then(loaded=>{if(!active)return;setState(loaded);setReady(true);void ensureProfileRegistry(loaded).then(registry=>{if(!active)return;setActiveProfileId(registry.activeId);setProfiles(registry.profiles)}).catch(()=>{if(active)setProfiles([])})}).catch(()=>{if(active)setReady(true)});return()=>{active=false;window.clearTimeout(fallback)}},[]);
 const refreshProfiles=useCallback(async()=>setProfiles(await listLearningProfiles()),[]);
 const replace=useCallback((next:LearningState)=>{const stamped={...next,updatedAt:new Date().toISOString()};setState(stamped);void saveLearningState(stamped).then(refreshProfiles)},[refreshProfiles]);
 const adoptCommittedState=useCallback(async(next:LearningState,profileId:string)=>{setState(next);setActiveProfileId(profileId);await refreshProfiles()},[refreshProfiles]);
 const update=useCallback((updater:(current:LearningState)=>LearningState)=>{setState(current=>{const next={...updater(current),updatedAt:new Date().toISOString()};void saveLearningState(next).then(refreshProfiles);return next})},[refreshProfiles]);
 const switchProfile=useCallback(async(id:string)=>{const next=await switchLearningProfile(id,state);setState(next);setActiveProfileId(id);await refreshProfiles()},[state,refreshProfiles]);
 const addProfile=useCallback(async(next:LearningState,id?:string)=>{const created=await createLearningProfile(next,id);await refreshProfiles();return created},[refreshProfiles]);
 const renameProfile=useCallback(async(id:string,name:string)=>{const clean=name.trim();if(!clean)throw new Error("اسم الملف لا يمكن أن يكون فارغًا.");if(id===activeProfileId&&state.profile){const next={...state,profile:{...state.profile,name:clean},updatedAt:new Date().toISOString()};setState(next);await saveLearningState(next);}else await renameLearningProfile(id,name);await refreshProfiles()},[activeProfileId,state,refreshProfiles]);
 const deleteProfile=useCallback(async(id:string)=>{await deleteLearningProfile(id);await refreshProfiles()},[refreshProfiles]);
 const value=useMemo(()=>({state,ready,activeProfileId,profiles,update,replace,adoptCommittedState,refreshProfiles,switchProfile,addProfile,renameProfile,deleteProfile}),[state,ready,activeProfileId,profiles,update,replace,adoptCommittedState,refreshProfiles,switchProfile,addProfile,renameProfile,deleteProfile]);return<LearningContext.Provider value={value}>{children}</LearningContext.Provider>}
export function useLearning(){const value=useContext(LearningContext);if(!value)throw new Error("useLearning must be used inside LearningProvider");return value}
