"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, BookOpenText, Check, Clock3, Lightbulb, LockKeyhole, Mic2, PenLine, Volume2 } from "lucide-react";
import type { FullLesson, LessonStageKey } from "@/types/lesson-content";
import type { ListeningFocusId, ListeningProcessEventKind, SupportUsageKind } from "@/types/learning";
import { LESSON_STAGE_KEYS } from "@/types/lesson-content";
import { useLearning } from "./learning-provider";
import { ExerciseCard, QuestionQuiz, type LessonAttemptMetadata } from "./exercise-card";
import { PhraseRecallDeck } from "./phrase-recall-deck";
import { FourSkillVocabularyCycle } from "./four-skill-vocabulary-cycle";
import { LessonListeningSequence } from "./lesson-listening-sequence";
import { PronunciationArticulationLab } from "./pronunciation-articulation-lab";
import { buildLessonSrsCards } from "@/core/srs/lesson-cards";
import { lessonEvidenceGate } from "@/core/lessons/evidence-gate";
import { BEGINNER_READABLE_COMPLETION_POLICY, lessonCompletionGuidance, nextLessonCompletionGuidance } from "@/core/lessons/completion-guidance";
import { captureLessonError } from "@/core/errors/capture";
import { readingEvidenceMap } from "@/core/lesson/support";
import { lessonMasteryFromAttempts } from "@/core/evidence/mastery-weighting";
import { appendSupportUsageEvent, createSupportUsageEvent } from "@/core/evidence/support-usage";
import { applySpeechPreferences } from "@/core/audio/speech-preferences";
import { LexicalGrammarPanel } from "./lexical-grammar-panel";
import { MeaningFirstCasePanel } from "./meaning-first-case-panel";
import { TunisianSupportPanel } from "./tunisian-support-panel";
import { NursingLayerPanel } from "./nursing-layer-panel";
import { ClaimBoundaryPanel } from "./claim-boundary-panel";
import { ContentNoteControl } from "./content-note-control";
import { ContentErrorReportControl } from "./content-error-report-control";
import { appendListeningProcessEvent, createListeningProcessEvent } from "@/core/listening/sequence";
import { createPronunciationContrastAttempt, upsertPronunciationContrastAttempt } from "@/core/pronunciation/articulation";
import { RuleProgressionPanel } from "./rule-progression-panel";
import { questionTaxonomyForLesson } from "@/core/comprehension/question-taxonomy";
import { ProsodyProgressionPanel } from "./prosody-progression-panel";
import { completedFourSkillPhraseIndexes, fourSkillPhraseAttemptId } from "@/core/lessons/four-skill-cycle";

const stageMeta: Record<LessonStageKey,{de:string;ar:string;icon:string}> = {
  objectives:{de:"Lernziele",ar:"أهداف اليوم",icon:"◎"},entry:{de:"Einstieg",ar:"موقف البداية",icon:"→"},vocabulary:{de:"Wortschatz",ar:"العبارات",icon:"Aa"},discover:{de:"Entdecken",ar:"اكتشف النمط",icon:"?"},rule:{de:"Regel",ar:"القاعدة والمقارنة",icon:"§"},controlled:{de:"Üben",ar:"تدريب موجّه",icon:"✓"},reading:{de:"Lesen",ar:"القراءة",icon:"▤"},listening:{de:"Hören",ar:"الاستماع",icon:"♫"},pronunciation:{de:"Aussprache",ar:"النطق",icon:"◖"},writing:{de:"Schreiben",ar:"الكتابة",icon:"✎"},speaking:{de:"Sprechen",ar:"المحادثة",icon:"◉"},mediation:{de:"Mediation",ar:"الوساطة",icon:"⇄"},errors:{de:"Fehlerklinik",ar:"عيادة الأخطاء",icon:"!"},test:{de:"Mini-Test",ar:"الاختبار والخطة",icon:"★"},
};

export function LessonRunner({lesson,nextLessonId}:{lesson:FullLesson;nextLessonId?:string}) {
  const {state,update}=useLearning();
  const stageIndex=state.lessonProgress[lesson.id]??0;
  const stageKey=LESSON_STAGE_KEYS[stageIndex];
  const stage=stageMeta[stageKey];
  const progress=Math.round(((stageIndex+1)/LESSON_STAGE_KEYS.length)*100);
  const [speechStatus,setSpeechStatus]=useState("");
  const stageHeadingRef=useRef<HTMLHeadingElement>(null);
  const previousStageRef=useRef(stageIndex);
  const srsCardCount=buildLessonSrsCards(lesson).length;
  const evidenceGate=lessonEvidenceGate(lesson,state);
  const nextCompletion=nextLessonCompletionGuidance(evidenceGate.criteria);
  const readingQuestionIds=new Set(lesson.reading.questions.map((question)=>question.id));
  const readingAttempted=state.exerciseAttempts.some((attempt)=>attempt.lessonId===lesson.id&&readingQuestionIds.has(attempt.exerciseId));
  const readingEvidence=readingEvidenceMap(lesson.reading.textDe,lesson.reading.questions);
  const questionTaxonomy=questionTaxonomyForLesson(lesson);
  const completedVocabularyPhraseIndexes=completedFourSkillPhraseIndexes(lesson.id,lesson.phrases.length,state.exerciseAttempts);

  useEffect(()=>{if(previousStageRef.current===stageIndex)return;previousStageRef.current=stageIndex;stageHeadingRef.current?.focus()},[stageIndex]);

  function go(next:number){update((current)=>({...current,currentLessonId:lesson.id,currentStage:Math.max(0,Math.min(13,next)),lessonProgress:{...current.lessonProgress,[lesson.id]:Math.max(0,Math.min(13,next))}}))}
  function recordExercise(exerciseId:string,answer:string,correct:boolean,metadata?:LessonAttemptMetadata){const now=new Date();update((current)=>({...current,exerciseAttempts:[...current.exerciseAttempts,{id:`attempt-${crypto.randomUUID()}`,lessonId:lesson.id,exerciseId,answer,correct,...metadata,createdAt:now.toISOString()}],errors:correct?current.errors:captureLessonError(current.errors,lesson,exerciseId,answer,now,metadata?.confidence)}))}
  function recordQuestion(id:string,answer:string,correct:boolean,metadata?:LessonAttemptMetadata){recordExercise(id,answer,correct,metadata)}
  function recordSupport(kind:SupportUsageKind,contentId:string,afterCommit:boolean,supportLevel?:1|2){const event=createSupportUsageEvent({kind,surface:"lesson",contentId,lessonId:lesson.id,supportLevel,afterCommit});update((current)=>({...current,supportUsageEvents:appendSupportUsageEvent(current.supportUsageEvents,event)}))}
  function recordListeningProcess(event:ListeningProcessEventKind,details:{focusId?:ListeningFocusId;questionId?:string}={}){const next=createListeningProcessEvent({lessonId:lesson.id,event,...details});update((current)=>({...current,listeningProcessEvents:appendListeningProcessEvent(current.listeningProcessEvents,next)}))}
  function recordPronunciationContrast(pairId:string,targetSide:"left"|"right",selectedSide:"left"|"right"){const next=createPronunciationContrastAttempt({lessonId:lesson.id,pairId,targetSide,selectedSide});update((current)=>({...current,pronunciationContrastAttempts:upsertPronunciationContrastAttempt(current.pronunciationContrastAttempts,next)}))}
  function speak(text:string,rate=.92):Promise<boolean>{
    if(!window.speechSynthesis){setSpeechStatus("هذا المتصفح لا يدعم النطق المجاني.");return Promise.resolve(false)}
    window.speechSynthesis.cancel();
    const utterance=applySpeechPreferences(new SpeechSynthesisUtterance(text),state.speechPreferences,window.speechSynthesis.getVoices());
    utterance.lang="de-DE";utterance.rate=rate;
    return new Promise((resolve)=>{
      let settled=false;
      const settle=(started:boolean)=>{if(settled)return;settled=true;resolve(started)};
      const timeout=window.setTimeout(()=>{setSpeechStatus("لم يبدأ الصوت. اختر صوتًا ألمانيًا آخر من الإعدادات.");settle(false)},1800);
      utterance.onstart=()=>{window.clearTimeout(timeout);setSpeechStatus("يتم التشغيل الآن…");settle(true)};
      utterance.onend=()=>{window.clearTimeout(timeout);setSpeechStatus("");settle(true)};
      utterance.onerror=()=>{window.clearTimeout(timeout);setSpeechStatus("تعذر تشغيل الصوت الألماني.");settle(false)};
      window.speechSynthesis.speak(utterance);
    });
  }
  function finish(){if(!evidenceGate.passed)return;update((current)=>{if(current.completedLessonIds.includes(lesson.id))return current;const mastery=lessonMasteryFromAttempts(lesson,current.exerciseAttempts);return{...current,completedLessonIds:[...current.completedLessonIds,lesson.id],dueReviews:current.dueReviews+srsCardCount,studyHistory:[...current.studyHistory,{date:new Date().toISOString().slice(0,10),minutes:lesson.estimatedMinutes,evidenceCount:mastery.evidence.novelItemCount}],mastery:{...current.mastery,[lesson.id]:mastery.score}}})}

  const content=(()=>{
    switch(stageKey){
      case "objectives": return <section className="lesson-section-block"><div className="section-lead"><span>{stage.icon}</span><div><h2>ماذا ستستطيع أن تفعل؟</h2><p>{lesson.descriptionAr}</p></div></div><div className="objective-list">{lesson.objectives.map((objective,index)=><article key={objective.de}><span>{index+1}</span><div><strong>{objective.ar}</strong><small lang="de" dir="ltr">{objective.de}</small></div></article>)}</div><div className="evidence-note"><Lightbulb size={18}/><p>لن نعتبر قراءة الأهداف إتقانًا. ستحتاج إلى إنتاج مستقل واختبار جديد ومراجعة مؤجلة.</p></div></section>;
      case "entry": return <section className="lesson-section-block"><div className="section-lead"><span>→</span><div><h2>{lesson.entry.titleAr}</h2><p>{lesson.entry.sceneAr}</p></div></div><div className="dialogue-list">{lesson.entry.dialogue.map((line,index)=><article key={`${line.speaker}-${index}`}><span>{line.speaker.slice(0,1)}</span><div><strong>{line.speaker}</strong><p lang="de" dir="ltr">{line.de}</p><small>{line.ar}</small></div></article>)}</div></section>;
      case "vocabulary": return <section className="lesson-section-block full"><div className="section-lead"><span>Aa</span><div><h2>احفظ العبارة في موقف</h2><p>ادرسها أولًا، ثم انتقل إلى الاسترجاع دون كشف. قل الجواب بصوتك قبل رؤية الحل.</p></div></div><PhraseRecallDeck lesson={lesson} onSpeak={(text)=>{void speak(text)}} onGrade={(id,remembered)=>recordExercise(id,remembered?"remembered":"retry",remembered)}/><FourSkillVocabularyCycle lesson={lesson} completedPhraseIndexes={completedVocabularyPhraseIndexes} onPlayModel={(text)=>speak(text)} onPhraseAttempt={(phraseIndex,transcript,complete)=>recordExercise(fourSkillPhraseAttemptId(lesson.id,phraseIndex),transcript||"no-word-confirmed",complete)} onComplete={()=>go(3)}/><LexicalGrammarPanel lessonId={lesson.id}/></section>;
      case "discover": return <section className="lesson-section-block"><div className="section-lead"><span>?</span><div><h2>اكتشف قبل قراءة القاعدة</h2><p>{lesson.discovery.instructionAr}</p></div></div><div className="discovery-examples" lang="de" dir="ltr">{lesson.discovery.examples.map((example)=><button key={example} onClick={()=>speak(example)}><Volume2 size={15}/>{example}</button>)}</div><div className="noticing-questions">{lesson.discovery.questionsAr.map((question,index)=><p key={question}><span>{index+1}</span>{question}</p>)}</div></section>;
      case "rule": return <section className="lesson-section-block full"><RuleProgressionPanel lessonId={lesson.id}/><MeaningFirstCasePanel lessonId={lesson.id}/><TunisianSupportPanel lessonId={lesson.id} mode={state.profile?.arabicSupport}/><NursingLayerPanel lessonId={lesson.id} level={lesson.level} onSpeak={(text)=>{void speak(text)}}/><ClaimBoundaryPanel lesson={lesson}/><div className="theory-stack">{lesson.theory.map((block)=><article key={block.id} className="theory-card"><header><span><Lightbulb size={20}/></span><div><small lang="de" dir="ltr">{block.titleDe}</small><h2>{block.titleAr}</h2></div></header><p>{block.explanationAr}</p><div className="contrast-box"><b>المقارنة مع العربية</b><span>{block.contrastAr}</span></div>{block.formula&&<code lang="de" dir="ltr">{block.formula}</code>}<div className="theory-examples">{block.examples.map((example)=><button key={example.de} onClick={()=>speak(example.de)}><strong dir="ltr" lang="de">{example.de}</strong><span>{example.ar}</span></button>)}</div><footer><b>تريك التذكر</b>{block.trickAr}</footer></article>)}</div></section>;
      case "controlled": return <section className="lesson-section-block full"><div className="section-lead"><span>✓</span><div><h2>تدرّب ثم اقرأ التفسير</h2><p>المحاولة الأولى تُحفظ منفصلة. لا تكرر السؤال فقط من أجل علامة جميلة.</p></div></div><div className="exercise-grid">{lesson.exercises.map((exercise)=><ExerciseCard key={exercise.id} exercise={exercise} onAttempt={(answer,correct,metadata)=>recordExercise(exercise.id,answer,correct,metadata)} onSupport={(contentId,level)=>recordSupport("hint",contentId,false,level)}/>)}</div></section>;
      case "reading": return <section className="lesson-section-block full"><div className="text-header"><div><small lang="de" dir="ltr">{lesson.reading.titleDe}</small><h2>{lesson.reading.titleAr}</h2></div><span>{lesson.reading.textDe.trim().split(/\s+/).length} كلمة</span></div><article className="reading-text" lang="de" dir="ltr">{lesson.reading.textDe}</article>{readingAttempted?<><details className="translation-panel" onToggle={(event)=>{if(event.currentTarget.open)recordSupport("reading-translation",`${lesson.id}:reading-translation`,true)}}><summary>افتح المعنى العربي بعد المحاولة</summary><p>{lesson.reading.textAr}</p></details><div className="glossary-strip" aria-label="قاموس القراءة بعد محاولة الاستنتاج">{lesson.reading.glossary.map((item)=><span key={item.lemma}><b lang="de" dir="ltr">{item.surfaceForm}</b>{item.ar}</span>)}</div></>:<div className="reading-support-lock"><LockKeyhole size={18}/><div><strong>القاموس والترجمة مؤجلان</strong><p>اختر جوابًا لسؤال قراءة واحد وثبّت المحاولة أولًا. بعد ذلك يظهر المعنى، ويعرض كل تصحيح موضع دليل مقتبسًا من النص.</p></div></div>}<QuestionQuiz questions={lesson.reading.questions} onAttempt={recordQuestion} onSupport={(contentId,level)=>recordSupport("hint",contentId,false,level)} evidenceByQuestionId={readingEvidence} taxonomyByQuestionId={questionTaxonomy} shuffleSeed={`${lesson.id}:reading`}/></section>;
      case "listening": return <LessonListeningSequence lesson={lesson} attempts={state.exerciseAttempts} processEvents={state.listeningProcessEvents} speechStatus={speechStatus} onBrowserTts={(rate)=>speak(lesson.listening.transcriptDe,rate)} onQuestionAttempt={recordQuestion} onProcessEvent={recordListeningProcess} onTranscriptOpen={()=>recordSupport("listening-transcript",`${lesson.id}:listening-transcript`,true)} onHint={(contentId,level)=>recordSupport("hint",contentId,false,level)}/>;
      case "pronunciation": return <section className="lesson-section-block full"><div className="section-lead"><span>◖</span><div><h2>{lesson.pronunciation.titleAr}</h2><p>{lesson.pronunciation.explanationAr}</p></div></div><div className="pronunciation-grid">{lesson.pronunciation.items.map((item)=><button key={item.de} onClick={()=>speak(item.de,.72)}><Volume2 size={16}/><strong lang="de" dir="ltr">{item.de}</strong><code dir="ltr" data-bidi-scope="technical">{item.ipa}</code><small>{item.ar}</small></button>)}</div><div className="evidence-note"><Lightbulb size={18}/><p><b>تريك:</b> {lesson.pronunciation.trickAr}</p></div><ProsodyProgressionPanel level={lesson.level}/><PronunciationArticulationLab lesson={lesson} attempts={state.pronunciationContrastAttempts} onSpeak={speak} onAttempt={recordPronunciationContrast}/></section>;
      case "writing": return <section className="lesson-section-block"><div className="section-lead"><span><PenLine size={23}/></span><div><h2>{lesson.writing.titleAr}</h2><p lang="de" dir="ltr">{lesson.writing.promptDe}</p></div></div><p className="arabic-task">{lesson.writing.promptAr}</p><div className="task-checklist">{lesson.writing.checklistAr.map((item)=><span key={item}><Check size={14}/>{item}</span>)}</div><details className="translation-panel" onToggle={(event)=>{if(event.currentTarget.open)recordSupport("writing-model",`${lesson.id}:writing-model`,state.writingSubmissions.some((item)=>item.taskId===lesson.id&&item.status!=="draft"))}}><summary>نموذج للمقارنة بعد كتابة مسودتك</summary><p lang="de" dir="ltr">{lesson.writing.modelDe}</p></details><Link href={`/writing?lesson=${lesson.id}`} className="primary-button">افتح مختبر الكتابة <ArrowLeft size={17}/></Link></section>;
      case "speaking": return <section className="lesson-section-block"><div className="section-lead"><span><Mic2 size={23}/></span><div><h2>{lesson.speaking.titleAr}</h2><p lang="de" dir="ltr">{lesson.speaking.promptDe}</p></div></div><p className="arabic-task">{lesson.speaking.promptAr}</p><div className="prompt-chips" lang="de" dir="ltr">{lesson.speaking.usefulPhrases.map((phrase)=><span key={phrase}>{phrase}</span>)}</div><div className="task-checklist">{lesson.speaking.successCriteriaAr.map((item)=><span key={item}><Check size={14}/>{item}</span>)}</div><Link href={`/speaking?lesson=${lesson.id}`} className="primary-button">تدرّب على العبارات ثم سجّل <Mic2 size={17}/></Link></section>;
      case "mediation": return <section className="lesson-section-block"><div className="section-lead"><span>⇄</span><div><h2>افهم الرسالة ثم ساعد شخصًا آخر</h2><p>{lesson.mediation.scenarioAr}</p></div></div><blockquote lang="de" dir="ltr">{lesson.mediation.sourceDe}</blockquote><div className="mediation-task"><b>مهمتك</b><p>{lesson.mediation.taskAr}</p></div><details className="translation-panel" onToggle={(event)=>{if(event.currentTarget.open)recordSupport("mediation-model",`${lesson.id}:mediation-model`,state.mediationSubmissions.some((item)=>item.taskId===lesson.id&&item.status!=="draft"))}}><summary>اقتراح بعد المحاولة</summary><p>{lesson.mediation.suggestedAr}</p></details><Link href={`/mediation?lesson=${lesson.id}`} className="primary-button">ابدأ المساعدة خطوة بخطوة <ArrowLeft size={17}/></Link></section>;
      case "errors": return <section className="lesson-section-block full"><div className="section-lead"><span>!</span><div><h2>مصائد شائعة وتريكات علاجها</h2><p>ابحث عن سبب الخطأ، لا تحفظ التصحيح وحده.</p></div></div><div className="mistake-list">{lesson.mistakes.map((item)=><article key={item.wrong}><span>!</span><div><del lang="de" dir="ltr">{item.wrong}</del><strong lang="de" dir="ltr">{item.correct}</strong><p>{item.whyAr}</p><small><b>تريك:</b> {item.trickAr}</small></div></article>)}</div></section>;
      case "test": return <section className="lesson-section-block full"><div className="section-lead"><span>★</span><div><h2>اختبار قصير وخطوة تالية واضحة</h2><p>أجب عن أسئلة الاختبار، وإذا بقي جزء من الدرس فسنأخذك إليه مباشرة دون رموز أو حسابات مبهمة.</p></div></div><div className={evidenceGate.passed?"lesson-evidence-gate passed":"lesson-evidence-gate"} data-completion-policy={BEGINNER_READABLE_COMPLETION_POLICY}><header><div><strong>{evidenceGate.passed?"أكملت متطلبات هذا الدرس":"ما المتبقي لإكمال هذا الدرس؟"}</strong><small>{evidenceGate.passed?"أحسنت. يمكنك إنهاء الدرس والانتقال إلى خطوتك التالية.":"اتبع المهمة التالية أولًا، وافتح القائمة لمعرفة بقية الأجزاء."}</small></div><span aria-label={`${evidenceGate.criteria.filter((criterion)=>criterion.passed).length} من 4 مكتملة`}>{evidenceGate.criteria.filter((criterion)=>criterion.passed).length}/4</span></header>{nextCompletion&&<aside className="lesson-next-completion"><small>خطوتك التالية</small><strong>{nextCompletion.actionAr}</strong><p>{nextCompletion.detailAr}</p><button className="primary-button" onClick={()=>go(nextCompletion.criterionId==="controlled"?5:nextCompletion.criterionId==="reading"?6:nextCompletion.criterionId==="listening"?7:13)}>{nextCompletion.actionAr} <ArrowLeft size={15}/></button></aside>}<div>{evidenceGate.criteria.map((criterion)=>{const guidance=lessonCompletionGuidance(criterion);const remediationStage=criterion.id==="controlled"?5:criterion.id==="reading"?6:criterion.id==="listening"?7:13;return <article key={criterion.id} className={criterion.passed?"passed":""}><span aria-hidden="true">{criterion.passed?<Check size={13}/>:"○"}</span><div><strong>{criterion.labelAr}</strong><small><b>{guidance.statusAr}</b> · {guidance.detailAr}</small></div>{!criterion.passed&&<button onClick={()=>go(remediationStage)}>{guidance.actionAr}</button>}</article>})}</div></div><QuestionQuiz questions={lesson.miniTest} taxonomyByQuestionId={questionTaxonomy} onAttempt={recordQuestion} onSupport={(contentId,level)=>recordSupport("hint",contentId,false,level)} shuffleSeed={`${lesson.id}:mini-test`}/></section>;
    }
  })();

  return <div className="lesson-layout"><aside className="lesson-steps"><Link href="/today" className="back-link"><ArrowRight size={16}/> العودة إلى اليوم</Link><div className="lesson-mini-title"><span>{lesson.level} · {lesson.id.split("-")[1]}</span><h2>{lesson.titleAr}</h2><small lang="de" dir="ltr">{lesson.titleDe}</small></div><nav aria-label="مراحل الدرس الأربع عشرة">{LESSON_STAGE_KEYS.map((key,index)=>{const item=stageMeta[key];return <button key={key} aria-current={index===stageIndex?"step":undefined} onClick={()=>go(index)} className={index===stageIndex?"active":index<stageIndex?"passed":""}><span>{index<stageIndex?<Check size={13}/>:index+1}</span><div><strong>{item.ar}</strong><small lang="de" dir="ltr">{item.de}</small></div></button>})}</nav></aside><section className="lesson-workspace"><header><div><span className="eyebrow"><BookOpenText size={15}/> المرحلة {stageIndex+1} من 14</span><h1 id="lesson-stage-heading" ref={stageHeadingRef} tabIndex={-1}>{stage.ar} <small lang="de" dir="ltr">{stage.de}</small></h1></div><div className="lesson-progress"><span><Clock3 size={14}/> {lesson.estimatedMinutes} دقيقة</span><strong>{progress}%</strong></div></header><div className="lesson-progress-bar" role="progressbar" aria-label="تقدم مراحل الدرس" aria-valuemin={1} aria-valuemax={14} aria-valuenow={stageIndex+1}><i style={{width:`${progress}%`}}/></div><div className="personal-content-tools"><ContentNoteControl kind="lesson" contentId={lesson.id}/><ContentErrorReportControl kind="lesson" contentId={lesson.id}/></div><div className="lesson-content" aria-labelledby="lesson-stage-heading">{content}</div><footer className="lesson-controls"><button onClick={()=>go(stageIndex-1)} disabled={stageIndex===0} className="secondary-button"><ArrowRight size={17}/> السابق</button>{stageIndex<13?<button onClick={()=>go(stageIndex+1)} className="primary-button">أكملت هذه الخطوة <ArrowLeft size={17}/></button>:evidenceGate.passed?<Link href={nextLessonId?`/lernen/${nextLessonId}`:"/progress"} onClick={finish} className="primary-button">إنهاء وتحديث الخطة <Check size={17}/></Link>:<button className="primary-button" disabled title="أكمل الأجزاء الأربعة الموضحة في القائمة أولًا">أكمل الخطوة التالية أولًا <Check size={17}/></button>}</footer></section></div>;
}
