"use client";
import { useEffect, useState } from "react";
import { BookOpenCheck, Check, Headphones, LibraryBig } from "lucide-react";
import { listeningLibrary, readingLibrary } from "@/data/library-registry";
import type { CEFRLevel } from "@/types/learning";
import { LibraryAudioPlayer } from "./library-audio-player";
import { libraryAudioManifest } from "@/data/library-audio-assets";
export function LibraryView(){
 const[kind,setKind]=useState<"reading"|"listening">("reading");const[level,setLevel]=useState<CEFRLevel|"all">("all");const[answers,setAnswers]=useState<Record<string,number>>({});
 useEffect(()=>{const targetId=decodeURIComponent(window.location.hash.slice(1));if(!targetId)return;const target=[...readingLibrary,...listeningLibrary].find(item=>item.id===targetId);if(!target)return;const timeout=window.setTimeout(()=>{setKind(target.kind);setLevel("all");window.setTimeout(()=>{const element=document.getElementById(targetId);if(element instanceof HTMLDetailsElement){element.open=true;element.scrollIntoView({block:"center"})}},50)},0);return()=>window.clearTimeout(timeout)},[]);
 const items=(kind==="reading"?readingLibrary:listeningLibrary).filter(x=>level==="all"||x.level===level);
 return <div className="wide-page library-page"><header className="page-heading"><div><span className="eyebrow"><LibraryBig size={15}/> المكتبة الموسعة</span><h1>نصوص مستقلة، <em>لا إعادة للدروس.</em></h1><p>دفعة أصلية للقراءة والاستماع عبر A1–B2. تغطي ملفات MP3 الاصطناعية المولّدة للمشروع جميع مواد الاستماع {libraryAudioManifest.generatedAssetCount}/80، ويبقى Browser TTS بديلًا فقط. الصوت معلّم بوضوح بأنه غير امتحاني.</p></div><div className="path-summary"><strong>{readingLibrary.length+listeningLibrary.length}</strong><span>مواد منشورة<br/>في الدفعة الأولى</span></div></header><div className="library-toolbar"><div><button className={kind==="reading"?"active":""} onClick={()=>setKind("reading")}><BookOpenCheck size={16}/> قراءة {readingLibrary.length}</button><button className={kind==="listening"?"active":""} onClick={()=>setKind("listening")}><Headphones size={16}/> استماع {listeningLibrary.length}</button></div><select aria-label="تصفية المكتبة حسب المستوى" value={level} onChange={e=>setLevel(e.target.value as CEFRLevel|"all")}><option value="all">كل المستويات</option>{["A1","A2","B1","B2"].map(x=><option key={x} value={x}>{x}</option>)}</select></div><div className="library-list">{items.map(item=><details key={item.id} id={item.id}><summary><span className={`level-badge ${item.level.toLowerCase()}`}>{item.level}</span><div><small>{item.categoryAr} · {item.estimatedMinutes} دقائق</small><strong lang="de" dir="ltr">{item.titleDe}</strong><p>{item.titleAr}</p></div><i>{item.kind==="reading"?<BookOpenCheck/>:<Headphones/>}</i></summary><section>{item.kind==="reading"?<><article className="library-text" lang="de" dir="ltr">{item.textDe}</article><p className="library-summary">{item.summaryAr}</p></>:<><LibraryAudioPlayer item={item}/><details className="translation-panel"><summary>النص بعد الاستماع</summary><p lang="de" dir="ltr">{item.transcriptDe}</p><small>{item.summaryAr}</small></details></>}<div className="library-questions">{item.questions.map((question,index)=><article key={question.id}><strong>{index+1}. <span lang="de" dir="ltr">{question.promptDe}</span></strong><small>{question.promptAr}</small><div>{question.options.map((option,optionIndex)=>{const picked=answers[question.id]===optionIndex;const answered=answers[question.id]!==undefined;const correct=optionIndex===question.correctIndex;return <button key={option} className={picked?(correct?"correct":"wrong"):answered&&correct?"correct":""} onClick={()=>setAnswers(a=>({...a,[question.id]:optionIndex}))}>{picked&&correct?<Check size={12}/>:null}{option}</button>})}</div>{answers[question.id]!==undefined&&<p>{question.explanationAr}</p>}</article>)}</div></section></details>)}</div></div>
}
