"use client";

import Link from "next/link";
import { Check, Clock3, LockKeyhole, MapPin, Sparkles } from "lucide-react";
import { curriculum, moduleTitles } from "@/data/curriculum";
import type { CEFRLevel } from "@/types/learning";
import { useLearning } from "./learning-provider";

const levelCopy: Record<CEFRLevel, string> = { A1: "الأساس", A2: "الاستقلال الأول", B1: "التواصل المترابط", B2: "الطلاقة والامتحان" };

export function PathView() {
  const { state } = useLearning();
  const levels: CEFRLevel[] = ["A1", "A2", "B1", "B2"];
  return (
    <div className="wide-page">
      <header className="page-heading"><div><span className="eyebrow"><MapPin size={15}/> مسارك الموجّه</span><h1>من أول جملة إلى <em>B2</em></h1><p>84 محطة أصلية. المدرب يختار لك الطريق؛ وهذه الخريطة للاستكشاف وفهم الصورة الكبرى.</p></div><div className="path-summary"><strong>{curriculum.filter((lesson) => lesson.status === "published").length}</strong><span>دروس متاحة أكاديميًا<br/>من أصل 84 مخططًا</span></div></header>
      <div className="level-stack">
        {levels.map((level) => {
          const lessons = curriculum.filter((lesson) => lesson.level === level);
          return <section key={level} className="level-section">
            <div className="level-heading"><span className={`level-badge ${level.toLowerCase()}`}>{level}</span><div><h2>{levelCopy[level]}</h2><p>{moduleTitles[level].length} وحدات · {lessons.length} درسًا</p></div></div>
            <div className="lesson-grid">
              {lessons.map((lesson, index) => {
                const completed = state.completedLessonIds.includes(lesson.id);
                const available = lesson.status === "published";
                const card = <>
                  <div className="lesson-card-top"><span>{completed ? <Check size={15}/> : String(index + 1).padStart(2, "0")}</span>{available ? <i><Sparkles size={13}/> متاح</i> : <LockKeyhole size={15}/>}</div>
                  <small>الوحدة {lesson.module}</small><h3 lang="de" dir="ltr">{lesson.titleDe}</h3><p>{lesson.titleAr}</p><div className="lesson-objective">{lesson.objectiveAr}</div><footer><Clock3 size={14}/>{lesson.estimatedMinutes} دقيقة</footer>
                </>;
                return available ? <Link href={`/lernen/${lesson.id}`} key={lesson.id} className="lesson-card available">{card}</Link> : <article key={lesson.id} className="lesson-card planned" title="مخطط منهجيًا ولم يكتمل محتواه الأكاديمي بعد">{card}</article>;
              })}
            </div>
            {level === "A1" && <div className="module-links"><Link href="/module/a1-1" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة الأولى</span><strong>الدروس 1–3 · مكتملة</strong></Link><Link href="/module/a1-2" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة الثانية</span><strong>الدروس 4–6 · مكتملة</strong></Link><Link href="/module/a1-3" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة الثالثة</span><strong>الدروس 7–9 · مكتملة</strong></Link><Link href="/module/a1-4" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة الرابعة</span><strong>الدروس 10–12 · مكتملة</strong></Link><Link href="/module/a1-5" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة الخامسة</span><strong>الدروس 13–15 · مكتملة</strong></Link><Link href="/module/a1-6" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة السادسة</span><strong>الدروس 16–18 · مكتملة</strong></Link><Link href="/module/a1-7" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة السابعة</span><strong>الدروس 19–21 · مكتملة</strong></Link><Link href="/module/a1-8" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة الثامنة</span><strong>الدروس 22–24 · مكتملة</strong></Link><Link href="/assessment/a1" className="module-review-link level-final"><span><Sparkles size={16}/> اختبار وبوابة مستوى A1</span><strong>48 سؤالًا · أدلة إنتاج · تقرير فجوات</strong></Link></div>}
            {level === "A2" && <div className="module-links"><Link href="/module/a2-1" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة الأولى A2</span><strong>الدروس A2-01–03 · مكتملة</strong></Link><Link href="/module/a2-2" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة الثانية A2</span><strong>الدروس A2-04–06 · مكتملة</strong></Link><Link href="/module/a2-3" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة الثالثة A2</span><strong>الدروس A2-07–09 · مكتملة</strong></Link><Link href="/module/a2-4" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة الرابعة A2</span><strong>الدروس A2-10–12 · مكتملة</strong></Link><Link href="/module/a2-5" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة الخامسة A2</span><strong>الدروس A2-13–15 · مكتملة</strong></Link><Link href="/module/a2-6" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة السادسة A2</span><strong>الدروس A2-16–18 · مكتملة</strong></Link><Link href="/module/a2-7" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة السابعة A2</span><strong>الدروس A2-19–21 · مكتملة</strong></Link><Link href="/module/a2-8" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة الثامنة A2</span><strong>الدروس A2-22–24 · مكتملة</strong></Link><Link href="/assessment/a2" className="module-review-link level-final"><span><Sparkles size={16}/> اختبار وبوابة مستوى A2</span><strong>48 سؤالًا · كتابة ومحادثة · تقرير فجوات</strong></Link></div>}
            {level === "B1" && <div className="module-links"><Link href="/module/b1-1" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة الأولى B1</span><strong>الدروس B1-01–03 · مكتملة</strong></Link><Link href="/module/b1-2" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة الثانية B1</span><strong>الدروس B1-04–06 · مكتملة</strong></Link><Link href="/module/b1-3" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة الثالثة B1</span><strong>الدروس B1-07–09 · مكتملة</strong></Link><Link href="/module/b1-4" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة الرابعة B1</span><strong>الدروس B1-10–12 · مكتملة</strong></Link><Link href="/module/b1-5" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة الخامسة B1</span><strong>الدروس B1-13–15 · مكتملة</strong></Link><Link href="/module/b1-6" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة السادسة B1</span><strong>الدروس B1-16–18 · مكتملة</strong></Link><Link href="/module/b1-7" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة السابعة B1</span><strong>الدروس B1-19–21 · مكتملة</strong></Link><Link href="/module/b1-8" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة الثامنة B1</span><strong>الدروس B1-22–24 · مكتملة</strong></Link><Link href="/assessment/b1" className="module-review-link level-final"><span><Sparkles size={16}/> اختبار وبوابة مستوى B1</span><strong>48 سؤالًا · مشروع · كتابة ومحادثة</strong></Link></div>}
            {level === "B2" && <div className="module-links"><Link href="/module/b2-1" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة الأولى B2</span><strong>الدروس B2-01–02 · مكتملة</strong></Link><Link href="/module/b2-2" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة الثانية B2</span><strong>الدروس B2-03–04 · مكتملة</strong></Link><Link href="/module/b2-3" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة الثالثة B2</span><strong>الدروس B2-05–06 · مكتملة</strong></Link><Link href="/module/b2-4" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة الرابعة B2</span><strong>الدروس B2-07–08 · مكتملة</strong></Link><Link href="/module/b2-5" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة الخامسة B2</span><strong>الدروس B2-09–10 · مكتملة</strong></Link><Link href="/module/b2-6" className="module-review-link"><span><Sparkles size={16}/> مراجعة ومشروع الوحدة السادسة B2</span><strong>الدروس B2-11–12 · مكتملة</strong></Link><Link href="/assessment/b2" className="module-review-link level-final"><span><Sparkles size={16}/> بوابة الجاهزية النهائية B2</span><strong>48 سؤالًا · 6 كتابات · 6 محادثات · ملف أدلة</strong></Link></div>}
          </section>;
        })}
      </div>
    </div>
  );
}
