"use client";
import {useState}from"react";
import{CalendarCheck2,Check}from"lucide-react";
import type{WeeklyReflectionAdjustment,WeeklyReflectionObstacle,WeeklyReflectionSuccess}from"@/types/learning";
import{saveWeeklyReflection,weeklyReflectionBounds}from"@/core/coach/weekly-reflection";
import{useLearning}from"./learning-provider";
import{StatusAnnouncement}from"./status-announcement";
const successes:Array<[WeeklyReflectionSuccess,string]>=[["consistency","العودة بانتظام"],["review","الاسترجاع"],["lesson","هدف الدرس"],["listening","الاستماع"],["writing","الكتابة"],["speaking","الكلام"]];
const obstacles:Array<[WeeklyReflectionObstacle,string]>=[["time","الوقت"],["energy","الطاقة"],["difficulty","الصعوبة"],["instructions","وضوح التعليمات"],["technology","الجهاز/الاتصال"],["none","لا عائق بارز"]];
const adjustments:Array<[WeeklyReflectionAdjustment,string]>=[["keep-plan","أبقي الخطة"],["lighter-plan","أخفف الحمل"],["more-review","أبدأ بمراجعة أكثر"],["more-production","أزيد الإنتاج"],["change-study-time","أغير وقت الدراسة"]];
export function WeeklyReflection(){const{state,update}=useLearning();const bounds=weeklyReflectionBounds();const saved=state.weeklyReflections.find((item)=>item.weekStart===bounds.weekStart);const[worked,setWorked]=useState<WeeklyReflectionSuccess[]>(saved?.whatWorked??[]);const[blocked,setBlocked]=useState<WeeklyReflectionObstacle[]>(saved?.obstacles??[]);const[adjustment,setAdjustment]=useState<WeeklyReflectionAdjustment>(saved?.oneAdjustment??"keep-plan");const[note,setNote]=useState(saved?.note??"");const[message,setMessage]=useState("");const[open,setOpen]=useState(!saved);const toggle=<T extends string>(list:T[],value:T,set:(next:T[])=>void)=>set(list.includes(value)?list.filter((item)=>item!==value):[...list,value]);function save(){update((current)=>saveWeeklyReflection(current,{whatWorked:worked,obstacles:blocked,oneAdjustment:adjustment,note}));setMessage("حُفظ تأمل هذا الأسبوع وحده؛ لم ننسخ ملاحظة الإغلاق اليومية ولم تتغير درجة أو بوابة.")}
return <details id="weekly-reflection" className="weekly-reflection-card" data-weekly-reflection-policy="independent-weekly-reflection-v1" open={open} onToggle={(event)=>setOpen(event.currentTarget.open)}><summary><CalendarCheck2 size={18}/><span><small>Wöchentlicher Rückblick · تأمل أسبوعي مستقل</small><strong>{saved?"راجع قرار أسبوعك":"ما الذي نجح وما الذي أعاقك؟"}</strong></span><b>{bounds.weekStart} → {bounds.weekEnd}</b></summary><div className="weekly-reflection-form"><fieldset><legend><span lang="de" dir="ltr">Was hat diese Woche funktioniert?</span><small>اختر ما نجح هذا الأسبوع.</small></legend><div>{successes.map(([value,label])=><label key={value}><input type="checkbox" checked={worked.includes(value)} onChange={()=>toggle(worked,value,setWorked)}/><span>{label}</span></label>)}</div></fieldset><fieldset><legend><span lang="de" dir="ltr">Was hat das Lernen erschwert?</span><small>اختر العائق كما تراه أنت؛ لا نستنتج حالة نفسية.</small></legend><div>{obstacles.map(([value,label])=><label key={value}><input type="checkbox" checked={blocked.includes(value)} onChange={()=>toggle(blocked,value,setBlocked)}/><span>{label}</span></label>)}</div></fieldset><label><span lang="de" dir="ltr">Was ändere ich nächste Woche?</span><small>تعديل واحد فقط للخطة القادمة.</small><select value={adjustment} onChange={(event)=>setAdjustment(event.target.value as WeeklyReflectionAdjustment)}>{adjustments.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label><span lang="de" dir="ltr">Notiz, optional</span><small>ملاحظة أسبوعية مستقلة · 400 حرف كحد أقصى.</small><textarea maxLength={400} value={note} onChange={(event)=>setNote(event.target.value)} placeholder="لا تُنسخ هنا ملاحظتك اليومية تلقائيًا."/></label><footer><p>المصدر: نموذج الأسبوع فقط. إعادة استعمال التأمل اليومي متوقفة ولا توجد موافقة ضمنية.</p><button type="button" onClick={save}><Check size={15}/> {saved?"حدّث تأمل الأسبوع":"احفظ تأمل الأسبوع"}</button></footer>{message&&<StatusAnnouncement message={message} channel="weekly-reflection" className="compact"/>}</div></details>}
