import type { CEFRLevel, DiagnosticResult, DiagnosticSkill, SkillDiagnosticAttempt } from "@/types/learning";
import { alternateDiagnosticForm } from "./adaptive";
import { diagnosticForms, diagnosticLevels, type DiagnosticFormId, type DiagnosticQuestion } from "@/data/diagnostic";

export const SINGLE_SKILL_DIAGNOSTIC_POLICY="single-skill-diagnostic-v1" as const;
export function formForSkillRetest(skill:DiagnosticSkill,prior:DiagnosticResult,attempts:SkillDiagnosticAttempt[]):DiagnosticFormId{const last=[...attempts].reverse().find(item=>item.skill===skill);return alternateDiagnosticForm(last?.formId??prior.formId)}
export function questionsForSkillRetest(skill:DiagnosticSkill,formId:DiagnosticFormId):DiagnosticQuestion[]{return diagnosticForms[formId].filter(question=>question.skill===skill).sort((a,b)=>diagnosticLevels.indexOf(a.level)-diagnosticLevels.indexOf(b.level))}
export function recommendedFocusLevel(correctByLevel:Record<CEFRLevel,boolean>):CEFRLevel{return diagnosticLevels.find(level=>!correctByLevel[level])??"B2"}
export function evaluateSkillRetest(input:{skill:DiagnosticSkill;formId:DiagnosticFormId;questions:DiagnosticQuestion[];answers:Record<string,number>;priorDiagnosticCompletedAt:string},now=new Date(),id=`skill-diagnostic-${crypto.randomUUID()}`):SkillDiagnosticAttempt{if(input.questions.length!==4||input.questions.some(question=>question.skill!==input.skill||question.formId!==input.formId))throw new Error("عينة إعادة المهارة يجب أن تضم سؤالًا واحدًا من كل مستوى.");const correctByLevel=Object.fromEntries(diagnosticLevels.map(level=>{const question=input.questions.find(item=>item.level===level)!;return[level,input.answers[question.id]===question.correctIndex]})) as Record<CEFRLevel,boolean>;return{id,policyVersion:SINGLE_SKILL_DIAGNOSTIC_POLICY,skill:input.skill,formId:input.formId,questionIds:input.questions.map(question=>question.id),correctByLevel,correctCount:Object.values(correctByLevel).filter(Boolean).length,attemptedCount:4,recommendedFocusLevel:recommendedFocusLevel(correctByLevel),priorDiagnosticCompletedAt:input.priorDiagnosticCompletedAt,evidenceBoundary:"skill-sample-planning-only-no-level-change",createdAt:now.toISOString()}}
