import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { academicLessonList } from "../src/data/academic-lessons";
import { curriculum } from "../src/data/curriculum";
import { buildLocalTestCatalog } from "../src/core/training/local-test-generator";

const catalog = buildLocalTestCatalog(academicLessonList, curriculum);
if (!catalog.ok) {
  console.error(`Local test template audit failed:\n${catalog.issues.map((issue) => `- ${issue}`).join("\n")}`);
  process.exit(1);
}

const outputDirectory = resolve(process.cwd(), "src/data/local-test-templates");
const write = process.argv.includes("--write");
const levels = ["A1", "A2", "B1", "B2"] as const;
let failures = 0;

for (const level of levels) {
  const constantName = `localTestTemplateBank${level}`;
  const content = `/* Generated by scripts/generate-local-test-templates.ts; do not edit. */\nimport type { LocalTestTemplateLesson } from "@/core/training/local-test-generator";\n\nexport const ${constantName} = ${JSON.stringify(catalog.banks[level], null, 2)} as const satisfies readonly LocalTestTemplateLesson[];\n`;
  const path = resolve(outputDirectory, `${level.toLowerCase()}.ts`);

  if (write) {
    mkdirSync(outputDirectory, { recursive: true });
    writeFileSync(path, content);
    console.log(`${level}: wrote ${catalog.byLevel[level].questionTemplates} question templates from ${catalog.byLevel[level].publishedLessons} published lessons`);
    continue;
  }

  let current = "";
  try {
    current = readFileSync(path, "utf8");
  } catch {
    // A missing generated bank is a failed audit, not a reason to generate during a read-only check.
  }
  if (current !== content) {
    failures += 1;
    console.error(`${level}: generated local-test bank is missing or stale; run npm run local:test:templates:write`);
  } else {
    console.log(`${level}: ${catalog.byLevel[level].questionTemplates} question templates / ${catalog.byLevel[level].publishedLessons} published lessons`);
  }
}

if (failures > 0) process.exit(1);
console.log(`local-test-generator-v1: ${catalog.totalQuestionTemplates} authored mini-test templates across ${catalog.publishedLessonCount} published lessons; no external or AI-generated content`);
