import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { buildProductionMixAudit } from "../src/core/content-validation/production-mix";

const writeMode = process.argv.includes("--write");
const audit = buildProductionMixAudit();
const payload = { format: "dwnb-production-mix-audit", version: "production-mix-audit-v1", ...audit };
const content = `${JSON.stringify(payload, null, 1)}\n`;
const contentSha256 = createHash("sha256").update(content).digest("hex");
const reportPath = "docs/generated/PRODUCTION_MIX_REPORT.md";
const rows = audit.byLevel && Object.entries(audit.byLevel).map(([level, value]) => `| ${level} | ${value.lessons} | ${value.closed} | ${value.constructed} | ${value.constructedSharePct}% |`).join("\n");
const report = `# Production Mix and Task Presence Audit

Generated by \`npm run production:mix\`. Policy \`${audit.policyVersion}\`. Content SHA-256: \`${contentSha256}\`

Boundary: ${audit.boundary}

| Metric | Value |
| --- | --- |
| Lessons | ${audit.lessons} |
| Closed practice items | ${audit.closed} |
| Constructed practice items | ${audit.constructed} |
| Constructed share | ${audit.constructedSharePct}% |
| Production blocks (writing/speaking/mediation) | ${audit.productionBlocks} |
| Lessons with a full writing task (prompt + checklist + model) | ${audit.lessonsWithFullWritingTask} |
| Lessons with a mediation task | ${audit.lessonsWithMediation} |
| Status | ${audit.ok ? "PASS" : "FAIL"} |

| Level | Lessons | Closed | Constructed | Constructed share |
| --- | --- | --- | --- | --- |
${rows}

${audit.issues.length ? `## Issues\n\n${audit.issues.map((issue) => `- ${issue}`).join("\n")}\n` : ""}
The audit counts presence and ratio only. It does not judge task quality, does not score free production, and makes no CEFR claim.
`;
const outputs = [["reports/production-mix-audit.json", content], [reportPath, report]];
if (writeMode) {
  for (const [file, text] of outputs) { await mkdir(file.includes("/") ? file.slice(0, file.lastIndexOf("/")) : ".", { recursive: true }); await writeFile(file, text); }
  console.log(`Production mix audit written: ${audit.lessons} lessons · closed ${audit.closed} · constructed ${audit.constructed} (${audit.constructedSharePct}%) · blocks ${audit.productionBlocks} · full writing task ${audit.lessonsWithFullWritingTask}/${audit.lessons} · mediation ${audit.lessonsWithMediation}/${audit.lessons} · ${audit.ok ? "PASS" : "FAIL"}`);
} else {
  const stale: string[] = [];
  for (const [file, expected] of outputs) {
    let actual = "";
    try { actual = await readFile(file, "utf8"); } catch { stale.push(`${file} (missing)`); continue; }
    if (actual !== expected) stale.push(`${file} (stale)`);
  }
  if (stale.length) throw new Error(`Production mix artifacts are not current:\n${stale.join("\n")}\nRun: npm run production:mix`);
  console.log(`Production mix verified: ${audit.constructedSharePct}% constructed · ${audit.productionBlocks} production blocks · ${audit.lessonsWithFullWritingTask}/${audit.lessons} full writing tasks`);
}
if (!audit.ok) throw new Error(`Production mix audit failed:\n${audit.issues.join("\n")}`);
