/**
 * Turns the curriculum's own authored pronunciation rows into a slim,
 * client-safe module so the phoneme reference can resolve the words a learner
 * actually practises. Importing the 84 lesson modules into a client chunk is
 * the bundle-size trap this generator exists to avoid: the emitted file holds
 * `{ de, ipa, source }` triples and nothing else.
 *
 * Run: npm run phoneme:lexicon:generate
 * Drift guard: tests/unit/german-phoneme-corpus.test.ts rebuilds the same rows
 * from the lesson data and compares them, so `npm run check` fails if the
 * curriculum changes and this file does not.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { academicLessonList } from "@/data/academic-lessons";

type Row = { de: string; ipa: string; source: string };

const rows: Row[] = [];
for (const lesson of academicLessonList as Array<{
  id: string;
  pronunciation?: { items?: Array<{ de: string; ipa: string }> };
}>) {
  for (const item of lesson.pronunciation?.items ?? []) {
    const de = String(item.de ?? "").trim();
    const ipa = String(item.ipa ?? "").trim();
    // Sentence-level rows carry an elided transcription ("[tsuˈʔeːɐ̯st …]");
    // they are teaching material, not a word lookup, so they are excluded here
    // rather than silently truncated into a single-word claim.
    if (!de || /\s/u.test(de) || !/^\[[^\]]+\]$/u.test(ipa)) continue;
    if (!/\p{L}/u.test(ipa.slice(1, -1))) continue;
    rows.push({ de, ipa, source: `lesson:${lesson.id}` });
  }
}

const literal = (value: string) => JSON.stringify(value);
const body = rows
  .map((row) => `  { de: ${literal(row.de)}, ipa: ${literal(row.ipa)}, source: ${literal(row.source)} },`)
  .join("\n");

const target = "src/config/curriculum-phoneme-reference.generated.ts";
mkdirSync(dirname(target), { recursive: true });
writeFileSync(
  target,
  `// AUTO-GENERATED by scripts/generate-phoneme-lexicon.ts — do not edit by hand.
// Authored German IPA rows from the A1-B2 curriculum, for display and word-level
// phoneme lookup only. Every row keeps its lesson id so a reviewer can reopen
// the source. No symbol is derived here: if a lesson row does not exist, nothing
// is invented for it.
// Generated from 84 academic lessons; ${rows.length} word-level rows.

export type CurriculumPhonemeRow = { readonly de: string; readonly ipa: string; readonly source: string };

export const CURRICULUM_PHONEME_REFERENCE_POLICY_VERSION = "dwnb-curriculum-phoneme-lexicon-v1" as const;

export const CURRICULUM_PHONEME_REFERENCE_ROWS: readonly CurriculumPhonemeRow[] = [
${body}
];

export const CURRICULUM_PHONEME_REFERENCE_ROW_COUNT = ${rows.length};
`,
  "utf8",
);

const words = new Set(rows.map((row) => row.de.toLowerCase()));
console.log(
  `Curriculum phoneme lexicon generated ${rows.length} word-level rows ` +
    `(${words.size} distinct spellings) from ${academicLessonList.length} lessons.`,
);
