import { strFromU8, strToU8, unzipSync, zipSync } from "fflate";
import { z } from "zod";
import type { LearningState } from "@/types/learning";
import { learningStateSchema } from "./schema";
import { listMedia } from "./db";

const MAX_ARCHIVE_BYTES = 100 * 1024 * 1024;
const MAX_UNPACKED_BYTES = 150 * 1024 * 1024;
const PBKDF2_ITERATIONS = 250_000;
const legacyManifestSchema = z.object({
  format: z.literal("dwnb"), formatVersion: z.union([z.literal(1), z.literal(2)]), appVersion: z.string(), exportedAt: z.string(), checksum: z.string().regex(/^[a-f0-9]{64}$/), includesSecrets: z.literal(false), includesMedia: z.boolean().optional().default(false), mediaCount: z.number().int().nonnegative().optional().default(0),
});
const encryptedManifestSchema = z.object({
  format: z.literal("dwnb"), formatVersion: z.literal(3), appVersion: z.string(), exportedAt: z.string(), checksum: z.string().regex(/^[a-f0-9]{64}$/), includesSecrets: z.literal(false), includesMedia: z.boolean(), mediaCount: z.number().int().nonnegative(), encrypted: z.literal(true), encryption: z.object({ algorithm: z.literal("AES-GCM"), derivation: z.literal("PBKDF2-SHA-256"), iterations: z.number().int().min(100_000), saltHex: z.string().regex(/^[a-f0-9]{32}$/), ivHex: z.string().regex(/^[a-f0-9]{24}$/) }),
});
const manifestSchema = z.union([legacyManifestSchema, encryptedManifestSchema]);
const mediaIndexSchema = z.array(z.object({ id:z.string().min(1),path:z.string().regex(/^media\/\d+\.bin$/),type:z.string(),size:z.number().int().nonnegative(),checksum:z.string().regex(/^[a-f0-9]{64}$/) }));
type MediaEntry={id:string;blob:Blob};
export type ImportedArchive={state:LearningState;media:MediaEntry[];formatVersion:1|2|3;encrypted:boolean};

function ownBytes(value:Uint8Array):Uint8Array<ArrayBuffer>{const buffer=new ArrayBuffer(value.length);const result=new Uint8Array(buffer);result.set(value);return result;}
function toHex(value:Uint8Array):string{return [...value].map(byte=>byte.toString(16).padStart(2,"0")).join("");}
function fromHex(value:string):Uint8Array<ArrayBuffer>{const result=new Uint8Array(new ArrayBuffer(value.length/2));for(let i=0;i<value.length;i+=2)result[i/2]=Number.parseInt(value.slice(i,i+2),16);return result;}
async function sha256(value:string|Uint8Array):Promise<string>{const bytes=ownBytes(typeof value==="string"?new TextEncoder().encode(value):value);return toHex(new Uint8Array(await crypto.subtle.digest("SHA-256",bytes.buffer)));}
async function deriveKey(passphrase:string,salt:Uint8Array<ArrayBuffer>,usages:KeyUsage[]):Promise<CryptoKey>{const material=await crypto.subtle.importKey("raw",ownBytes(new TextEncoder().encode(passphrase)).buffer,"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",salt:salt.buffer,iterations:PBKDF2_ITERATIONS,hash:"SHA-256"},material,{name:"AES-GCM",length:256},false,usages);}
function validateEntries(entries:Record<string,Uint8Array>){const names=Object.keys(entries);if(names.some(name=>name.includes("..")||name.startsWith("/")||name.includes("\\")))throw new Error("تحتوي النسخة على مسار غير آمن.");if(names.length>1000||Object.values(entries).reduce((sum,bytes)=>sum+bytes.length,0)>MAX_UNPACKED_BYTES)throw new Error("محتوى النسخة بعد الفك أكبر من الحد الآمن.");}
async function createPayloadFiles(state:LearningState,includeMedia:boolean){const payload=JSON.stringify({...state,lastBackupAt:new Date().toISOString()});const media=includeMedia?await listMedia():[];const files:Record<string,Uint8Array>={"progress.json":strToU8(payload)};const mediaIndex=[];for(let index=0;index<media.length;index+=1){const bytes=new Uint8Array(await media[index].blob.arrayBuffer());const path=`media/${index}.bin`;files[path]=bytes;mediaIndex.push({id:media[index].id,path,type:media[index].blob.type||"application/octet-stream",size:bytes.length,checksum:await sha256(bytes)});}if(media.length)files["media-index.json"]=strToU8(JSON.stringify(mediaIndex));return{payload,media,files};}
async function parsePayload(entries:Record<string,Uint8Array>,includesMedia:boolean,mediaCount:number){validateEntries(entries);const progressBytes=entries["progress.json"];if(!progressBytes)throw new Error("بيانات التقدم مفقودة من النسخة.");const state=learningStateSchema.parse(JSON.parse(strFromU8(progressBytes)));const media:MediaEntry[]=[];if(includesMedia){const indexBytes=entries["media-index.json"];if(!indexBytes)throw new Error("فهرس التسجيلات مفقود من النسخة.");const index=mediaIndexSchema.parse(JSON.parse(strFromU8(indexBytes)));if(index.length!==mediaCount)throw new Error("عدد التسجيلات لا يطابق Manifest النسخة.");for(const item of index){const bytes=entries[item.path];if(!bytes||bytes.length!==item.size||(await sha256(bytes))!==item.checksum)throw new Error(`فشل التحقق من التسجيل ${item.id}.`);media.push({id:item.id,blob:new Blob([ownBytes(bytes)],{type:item.type})});}}return{state,media};}

export async function exportArchive(state:LearningState,options:{includeMedia?:boolean;passphrase?:string}={}):Promise<Blob>{
 const{payload,media,files}=await createPayloadFiles(state,Boolean(options.includeMedia));const now=new Date().toISOString();const passphrase=options.passphrase?.trim();
 if(passphrase){if(passphrase.length<8)throw new Error("عبارة المرور يجب أن تتكون من 8 أحرف على الأقل.");const salt=ownBytes(crypto.getRandomValues(new Uint8Array(16)));const iv=ownBytes(crypto.getRandomValues(new Uint8Array(12)));const key=await deriveKey(passphrase,salt,["encrypt"]);const inner=ownBytes(zipSync(files,{level:6}));const encrypted=ownBytes(new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv},key,inner.buffer)));const manifest={format:"dwnb",formatVersion:3,appVersion:"0.1.0",exportedAt:now,checksum:await sha256(encrypted),includesSecrets:false,includesMedia:media.length>0,mediaCount:media.length,encrypted:true,encryption:{algorithm:"AES-GCM",derivation:"PBKDF2-SHA-256",iterations:PBKDF2_ITERATIONS,saltHex:toHex(salt),ivHex:toHex(iv)}} as const;const outer=zipSync({"manifest.json":strToU8(JSON.stringify(manifest,null,2)),"payload.enc":encrypted},{level:0});return new Blob([ownBytes(outer)],{type:"application/octet-stream"});}
 files["manifest.json"]=strToU8(JSON.stringify({format:"dwnb",formatVersion:2,appVersion:"0.1.0",exportedAt:now,checksum:await sha256(payload),includesSecrets:false,includesMedia:media.length>0,mediaCount:media.length},null,2));return new Blob([ownBytes(zipSync(files,{level:6}))],{type:"application/octet-stream"});
}

export async function importArchive(file:Blob,passphrase?:string):Promise<ImportedArchive>{
 if(file.size>MAX_ARCHIVE_BYTES)throw new Error("حجم النسخة أكبر من الحد الآمن (100MB).");let outer:Record<string,Uint8Array>;try{outer=unzipSync(new Uint8Array(await file.arrayBuffer()));}catch{throw new Error("ملف النسخة تالف أو ليس أرشيف DWNB صالحًا.");}validateEntries(outer);const manifestBytes=outer["manifest.json"];if(!manifestBytes)throw new Error("Manifest النسخة مفقود.");let manifest:z.infer<typeof manifestSchema>;try{manifest=manifestSchema.parse(JSON.parse(strFromU8(manifestBytes)));}catch{throw new Error("Manifest النسخة غير صالح أو إصدارها غير مدعوم.");}
 if(manifest.formatVersion===3){if(!passphrase?.trim())throw new Error("هذه النسخة مشفرة؛ أدخل عبارة المرور أولًا.");const encrypted=outer["payload.enc"];if(!encrypted||(await sha256(encrypted))!==manifest.checksum)throw new Error("فشل التحقق من سلامة الحمولة المشفرة.");let decrypted:Uint8Array;try{const key=await deriveKey(passphrase.trim(),fromHex(manifest.encryption.saltHex),["decrypt"]);decrypted=new Uint8Array(await crypto.subtle.decrypt({name:"AES-GCM",iv:fromHex(manifest.encryption.ivHex)},key,ownBytes(encrypted).buffer));}catch{throw new Error("عبارة المرور غير صحيحة أو النسخة المشفرة تعرضت للتعديل.");}let inner:Record<string,Uint8Array>;try{inner=unzipSync(decrypted);}catch{throw new Error("تعذر فتح الحمولة الداخلية للنسخة.");}const result=await parsePayload(inner,manifest.includesMedia,manifest.mediaCount);return{...result,formatVersion:3,encrypted:true};}
 const progressBytes=outer["progress.json"];if(!progressBytes)throw new Error("ملف النسخة لا يحتوي على بيانات تقدم.");const payload=strFromU8(progressBytes);if((await sha256(payload))!==manifest.checksum)throw new Error("فشل التحقق من سلامة بيانات التقدم.");const result=await parsePayload(outer,manifest.includesMedia,manifest.mediaCount);return{...result,formatVersion:manifest.formatVersion,encrypted:false};
}
