import type { LearningState } from "@/types/learning";
export type ImportMode="merge"|"replace"|"new-profile";
const union=<T extends string>(a:T[],b:T[])=>[...new Set([...a,...b])];
const byId=<T extends{id:string}>(a:T[],b:T[])=>[...new Map([...a,...b].map(item=>[item.id,item])).values()];
const progress=(a:Record<string,number>,b:Record<string,number>)=>Object.fromEntries([...new Set([...Object.keys(a),...Object.keys(b)])].map(key=>[key,Math.max(a[key]??0,b[key]??0)]));
const mergeExamSessions=(a:LearningState["examSessions"],b:LearningState["examSessions"])=>Object.fromEntries([...new Set([...Object.keys(a),...Object.keys(b)])].map(key=>{const left=a[key],right=b[key];if(!left)return[key,right];if(!right)return[key,left];const leftTime=Date.parse(left.completedAt??left.abandonedAt??left.startedAt),rightTime=Date.parse(right.completedAt??right.abandonedAt??right.startedAt);return[key,rightTime>leftTime?right:left]}));
const mergeDailySessions=(a:LearningState["dailySessions"],b:LearningState["dailySessions"])=>Object.fromEntries([...new Set([...Object.keys(a),...Object.keys(b)])].map(key=>{const left=a[key],right=b[key];if(!left)return[key,right];if(!right)return[key,left];const leftTime=Date.parse(left.reflectedAt??left.checkedInAt),rightTime=Date.parse(right.reflectedAt??right.checkedInAt);return[key,rightTime>leftTime?right:left]}));
export function previewImport(current:LearningState,incoming:LearningState,mediaCount:number){return{newLessons:incoming.completedLessonIds.filter(id=>!current.completedLessonIds.includes(id)).length,newExercises:incoming.exerciseAttempts.filter(x=>!current.exerciseAttempts.some(y=>y.id===x.id)).length,newWriting:incoming.writingSubmissions.filter(x=>!current.writingSubmissions.some(y=>y.id===x.id)).length,newMediation:incoming.mediationSubmissions.filter(x=>!current.mediationSubmissions.some(y=>y.id===x.id)).length,newSpeaking:incoming.speakingAttempts.filter(x=>!current.speakingAttempts.some(y=>y.id===x.id)).length,errors:incoming.errors.length,reviews:incoming.reviewItems.length,media:mediaCount,profileName:incoming.profile?.name??"—",updatedAt:incoming.updatedAt};}
export function mergeLearningStates(current:LearningState,incoming:LearningState):LearningState{
 const incomingNewer=Date.parse(incoming.updatedAt)>Date.parse(current.updatedAt);const mastery=incomingNewer?{...current.mastery,...incoming.mastery}:{...incoming.mastery,...current.mastery};const errors=byId(current.errors,incoming.errors).map(error=>{const a=current.errors.find(x=>x.id===error.id),b=incoming.errors.find(x=>x.id===error.id);if(!a||!b)return error;const eventAt=(item:typeof a)=>Date.parse(item.confirmedAt??item.lastRepairedAt??item.lastSeenAt);const latest=eventAt(b)>eventAt(a)?b:a;return{...latest,occurrences:Math.max(a.occurrences,b.occurrences),repairCount:Math.max(a.repairCount??0,b.repairCount??0),resolved:Boolean(a.resolved&&b.resolved)};});
 const history=[...new Map([...current.studyHistory,...incoming.studyHistory].map(item=>[`${item.date}:${item.minutes}:${item.evidenceCount}`,item])).values()];
 return{...current,diagnosticResult:!current.diagnosticResult?incoming.diagnosticResult:!incoming.diagnosticResult?current.diagnosticResult:Date.parse(incoming.diagnosticResult.completedAt)>Date.parse(current.diagnosticResult.completedAt)?incoming.diagnosticResult:current.diagnosticResult,completedBlockIds:union(current.completedBlockIds,incoming.completedBlockIds),completedLessonIds:union(current.completedLessonIds,incoming.completedLessonIds),currentLessonId:incomingNewer?incoming.currentLessonId:current.currentLessonId,currentStage:incomingNewer?incoming.currentStage:current.currentStage,lessonProgress:progress(current.lessonProgress,incoming.lessonProgress),exerciseAttempts:byId(current.exerciseAttempts,incoming.exerciseAttempts),dueReviews:Math.max(current.dueReviews,incoming.dueReviews),mastery,errors,errorClinicAttempts:byId(current.errorClinicAttempts,incoming.errorClinicAttempts),reviewItems:byId(current.reviewItems,incoming.reviewItems),reviewEvents:byId(current.reviewEvents,incoming.reviewEvents),writingSubmissions:byId(current.writingSubmissions,incoming.writingSubmissions),mediationSubmissions:byId(current.mediationSubmissions,incoming.mediationSubmissions),speakingAttempts:byId(current.speakingAttempts,incoming.speakingAttempts),tutorInteractions:byId(current.tutorInteractions,incoming.tutorInteractions),examSessions:mergeExamSessions(current.examSessions,incoming.examSessions),studyHistory:history,dailySessions:mergeDailySessions(current.dailySessions,incoming.dailySessions),lastBackupAt:incoming.lastBackupAt??current.lastBackupAt,updatedAt:new Date().toISOString()};
}
export function namespaceImportedProfile(state:LearningState,media:Array<{id:string;blob:Blob}>,profileId:string){
 const remap=new Map(media.map(item=>[item.id,`${profileId}:${item.id}`]));
 const examSessions=Object.fromEntries(Object.entries(state.examSessions).map(([sessionId,session])=>[sessionId,{...session,taskDrafts:Object.fromEntries(Object.entries(session.taskDrafts).map(([taskId,draft])=>{const mediaId=typeof draft.payload.mediaId==="string"?draft.payload.mediaId:undefined;return[taskId,{...draft,payload:{...draft.payload,...(mediaId?{mediaId:remap.get(mediaId)??mediaId}:{})}}]}))}]));
 return{state:{...state,examSessions,speakingAttempts:state.speakingAttempts.map(attempt=>({...attempt,mediaId:attempt.mediaId?remap.get(attempt.mediaId)??attempt.mediaId:undefined}))},media:media.map(item=>({id:remap.get(item.id)??item.id,blob:item.blob}))};
}
export function applyImportMode(current:LearningState,incoming:LearningState,mode:ImportMode){return mode==="replace"?incoming:mergeLearningStates(current,incoming);}
