import { z } from "zod";

const profileSchema = z.object({
  name: z.string().min(1),
  targetExam: z.enum(["goethe-b2", "telc-deutsch-b2"]),
  targetDate: z.string().optional(),
  dailyMinutes: z.union([z.literal(10), z.literal(20), z.literal(30), z.literal(45), z.literal(60), z.literal(90)]),
  arabicSupport: z.enum(["modern-standard-arabic", "tunisian-supported", "minimal-arabic"]),
  currentLevel: z.enum(["A1", "A2", "B1", "B2"]),
  goals: z.array(z.enum(["exam", "work", "study", "daily-life", "settlement"])).min(1).max(5).optional(),
  deviceReadiness: z.object({
    audio: z.enum(["unchecked", "ready", "unavailable", "permission-denied", "skipped"]),
    microphone: z.enum(["unchecked", "ready", "unavailable", "permission-denied", "skipped"]),
    checkedAt: z.string().optional(),
  }).optional(),
  createdAt: z.string(),
});

const diagnosticSchema = z.object({
  estimatedLevel: z.enum(["A1", "A2", "B1", "B2"]),
  score: z.number().int().nonnegative(),
  maxScore: z.number().int().positive(),
  levelScores: z.object({ A1: z.number(), A2: z.number(), B1: z.number(), B2: z.number() }),
  levelAttempted: z.object({ A1: z.number(), A2: z.number(), B1: z.number(), B2: z.number() }).optional(),
  skillScores: z.object({
    grammar: z.object({ correct: z.number().int().nonnegative(), attempted: z.number().int().nonnegative() }),
    vocabulary: z.object({ correct: z.number().int().nonnegative(), attempted: z.number().int().nonnegative() }),
    reading: z.object({ correct: z.number().int().nonnegative(), attempted: z.number().int().nonnegative() }),
    listening: z.object({ correct: z.number().int().nonnegative(), attempted: z.number().int().nonnegative() }),
  }).optional(),
  formId: z.enum(["A", "B"]).optional(),
  questionsAnswered: z.number().int().positive().optional(),
  stoppedEarly: z.boolean().optional(),
  confidence: z.enum(["low", "medium", "high"]).optional(),
  completedAt: z.string(),
});

const errorSchema = z.object({
  id: z.string(),
  type: z.enum(["article", "case", "word-order", "vocabulary", "spelling", "tense", "grammar"]),
  wrong: z.string(),
  correct: z.string(),
  explanationAr: z.string(),
  occurrences: z.number().int().positive(),
  lastSeenAt: z.string(),
  resolved: z.boolean().optional(),
  repairCount: z.number().int().nonnegative().optional(),
  lastRepairedAt: z.string().optional(),
  nextReviewAt: z.string().optional(),
  confirmedAt: z.string().optional(),
});

export const learningStateSchema = z.object({
  schemaVersion: z.literal(3),
  profile: profileSchema.nullable(),
  diagnosticResult: diagnosticSchema.nullable(),
  completedBlockIds: z.array(z.string()),
  completedLessonIds: z.array(z.string()),
  currentLessonId: z.string(),
  currentStage: z.number().int().min(0).max(13),
  lessonProgress: z.record(z.string(), z.number().int().min(0).max(13)),
  exerciseAttempts: z.array(z.object({ id:z.string(), lessonId:z.string(), exerciseId:z.string(), answer:z.string(), correct:z.boolean(), answerIndex:z.number().int().nonnegative().optional(), shuffleSeed:z.string().optional(), shuffleVersion:z.literal("lesson-shuffle-v1").optional(), createdAt:z.string() })),
  dueReviews: z.number().int().nonnegative(),
  mastery: z.record(z.string(), z.number().min(0).max(100)),
  errors: z.array(errorSchema),
  errorClinicAttempts: z.array(z.object({
    id: z.string(),
    clinicType: z.enum(["article", "case", "word-order", "vocabulary", "spelling", "tense", "grammar"]),
    sourceErrorIds: z.array(z.string()),
    answer: z.string(),
    correct: z.boolean(),
    createdAt: z.string(),
  })).default([]),
  reviewItems: z.array(z.object({
    id: z.string(), cardId: z.string(), repetitions: z.number().int().nonnegative(), interval: z.number().int().nonnegative(),
    easeFactor: z.number().min(1.3), nextReviewDate: z.string(), lastGrade: z.number().int().min(0).max(5).optional(), algorithmVersion: z.literal("sm2-v1"),
  })),
  reviewEvents: z.array(z.object({
    id: z.string(), cardId: z.string(), lessonId: z.string(), grade: z.number().int().min(0).max(5),
    evidenceKind: z.enum(["initial", "delayed"]), scheduledFor: z.string(), reviewedAt: z.string(), masteryDelta: z.number().int().nonnegative(),
  })).default([]),
  writingSubmissions: z.array(z.object({
    id: z.string(), taskId: z.string(), text: z.string(), wordCount: z.number().int().nonnegative(), version: z.number().int().positive(),
    status: z.enum(["draft", "submitted", "revised"]), feedback: z.array(z.string()),
    plan: z.object({ audience:z.string(),purpose:z.string(),points:z.array(z.string()) }).optional(),
    selfChecklist: z.array(z.string()).optional(),
    dimensions: z.array(z.object({ key:z.enum(["task-achievement","coherence","vocabulary","grammar","register"]),labelAr:z.string(),passed:z.boolean(),detailAr:z.string(),evidenceQuote:z.string().optional() })).optional(),
    sourceVersion: z.number().int().positive().optional(),
    createdAt: z.string(), updatedAt: z.string(),
  })),
  mediationSubmissions: z.array(z.object({
    id:z.string(),taskId:z.string(),audience:z.string(),purpose:z.string(),keyFacts:z.array(z.string()),transferAr:z.string(),responseDe:z.string(),version:z.number().int().positive(),status:z.enum(["draft","submitted","revised"]),selfChecklist:z.array(z.string()),
    dimensions:z.array(z.object({key:z.enum(["intent","completeness","audience","constraints","response"]),labelAr:z.string(),passed:z.boolean(),detailAr:z.string(),evidenceQuote:z.string().optional()})).optional(),
    feedback:z.array(z.string()),sourceVersion:z.number().int().positive().optional(),createdAt:z.string(),updatedAt:z.string(),
  })).default([]),
  speakingAttempts: z.array(z.object({
    id: z.string(), taskId: z.string(), mediaId: z.string().optional(), durationSeconds: z.number().nonnegative(), selfScore: z.number().min(0).max(5), reflection: z.string(),
    selfReview: z.object({ listenedBack:z.boolean(),achievedCriteria:z.array(z.string()),clarityScore:z.union([z.literal(1),z.literal(2),z.literal(3),z.literal(4),z.literal(5)]),turnTaking:z.boolean(),repairUsed:z.boolean(),preparationNotes:z.array(z.string()) }).optional(),
    targetSeconds: z.number().int().positive().optional(), preparationSeconds: z.number().int().nonnegative().optional(), retryOf: z.string().optional(), createdAt: z.string(),
  })),
  examSessions: z.record(z.string(), z.object({
    simulationId: z.string(),
    provider: z.enum(["goethe-b2", "telc-deutsch-b2"]),
    mode: z.literal("continuous-timed"),
    status: z.enum(["active", "completed", "expired", "abandoned"]),
    startedAt: z.string(),
    deadlineAt: z.string(),
    taskIds: z.array(z.string()),
    completedTaskIds: z.array(z.string()),
    currentTaskId: z.string().nullable(),
    taskDrafts: z.record(z.string(), z.object({
      taskId: z.string(),
      kind: z.enum(["matching", "choice", "listening", "writing", "speaking"]),
      payload: z.record(z.string(), z.unknown()),
      savedAt: z.string(),
    })).default({}),
    completedAt: z.string().optional(),
    abandonedAt: z.string().optional(),
  })).default({}),
  aiSettings: z.object({
    provider: z.enum(["disabled", "gemini", "openrouter", "local"]), model: z.string(), enabledFeatures: z.array(z.enum(["tutor", "writing", "speaking"])),
  }),
  tutorInteractions: z.array(z.object({
    id: z.string(),
    question: z.string(),
    answer: z.object({
      hintAr: z.string(),
      explanationAr: z.string(),
      examplesDe: z.array(z.string()),
      microExerciseAr: z.string(),
    }),
    provider: z.enum(["disabled", "gemini", "openrouter", "local"]),
    model: z.string(),
    promptVersion: z.literal("tutor-v2"),
    lessonId: z.string().optional(),
    errorIds: z.array(z.string()),
    consent: z.enum(["not-required", "explicit"]),
    createdAt: z.string(),
  })).default([]),
  studyHistory: z.array(z.object({ date: z.string(), minutes: z.number().nonnegative(), evidenceCount: z.number().int().nonnegative() })),
  dailySessions: z.record(z.string(), z.object({
    date: z.string(),
    availableMinutes: z.union([z.literal(10), z.literal(20), z.literal(30), z.literal(45), z.literal(60), z.literal(90)]),
    energyBefore: z.union([z.literal(1), z.literal(2), z.literal(3), z.literal(4), z.literal(5)]),
    checkedInAt: z.string(),
    difficultyAfter: z.union([z.literal(1), z.literal(2), z.literal(3), z.literal(4), z.literal(5)]).optional(),
    confidenceAfter: z.union([z.literal(1), z.literal(2), z.literal(3), z.literal(4), z.literal(5)]).optional(),
    reflection: z.string().max(1000).optional(),
    nextFocus: z.enum(["continue", "review", "lighter", "production"]).optional(),
    reflectedAt: z.string().optional(),
  })).default({}),
  lastBackupAt: z.string().optional(),
  updatedAt: z.string(),
});
