// @vitest-environment node
import{afterEach,describe,expect,it,vi}from"vitest";import{aiFallbackMessage,AI_RESILIENT_FALLBACK_POLICY,askSpeakingFollowUp,askTutor,type AIConfig,type TutorContext}from"@/core/ai/client";import{createSpeakingContentFollowUpEvidence}from"@/core/speaking/content-follow-up";import{learningStateSchema}from"@/core/portability/schema";import{defaultState}from"@/core/portability/db";
const context:TutorContext={lessonId:"a2-01",level:"A2",objectiveAr:"السبب",objectiveDe:"Gründe nennen",errorSummaries:[]};const payload={hintAr:"راقب الفعل.",explanationAr:"ينتقل الفعل إلى نهاية الجملة التابعة بعد weil.",examplesDe:["Ich bleibe, weil ich krank bin."],microExerciseAr:"رتب جملة جديدة."};
const providers:Array<{name:string;config:AIConfig;successBody:(content:string)=>string}>=[{name:"gemini",config:{provider:"gemini",model:"gemini-2.5-flash",key:"secret"},successBody:content=>JSON.stringify({candidates:[{content:{parts:[{text:content}]}}]})},{name:"openrouter",config:{provider:"openrouter",model:"openrouter/free",key:"secret"},successBody:content=>JSON.stringify({choices:[{message:{content}}]})},{name:"ollama",config:{provider:"local",model:"qwen2.5:3b",key:"http://localhost:11434"},successBody:content=>JSON.stringify({message:{content}})}];const failures=["rate-limit","network","timeout","malformed"]as const;
afterEach(()=>vi.unstubAllGlobals());
function mockFailure(kind:typeof failures[number],body:(content:string)=>string){if(kind==="rate-limit")return vi.fn().mockResolvedValue(new Response("limit",{status:429}));if(kind==="network")return vi.fn().mockRejectedValue(new TypeError("offline"));if(kind==="malformed")return vi.fn().mockResolvedValue(new Response(body("not-json"),{status:200,headers:{"content-type":"application/json"}}));return vi.fn((_url:string,init?:RequestInit)=>new Promise<Response>((_resolve,reject)=>init?.signal?.addEventListener("abort",()=>reject(new DOMException("Aborted","AbortError")))))}
const matrix=providers.flatMap(provider=>failures.map(failure=>({provider,failure})));
describe("resilient optional AI fallback",()=>{
it.each(matrix)("falls back once for $provider.name $failure without a second request",async({provider,failure})=>{const fetchMock=mockFailure(failure,provider.successBody);vi.stubGlobal("fetch",fetchMock);const answer=await askTutor(provider.config,"اشرح weil",{context,consentGranted:true,now:new Date("2026-09-07T12:00:00Z"),timeoutMs:5});expect(answer.provider).toBe("disabled");expect(answer.hintAr).toContain("الفعل");expect(answer.fallbackEvidence).toMatchObject({policyVersion:AI_RESILIENT_FALLBACK_POLICY,attemptedProvider:provider.config.provider,attemptedModel:provider.config.model,failureKind:failure,networkAttemptCount:1,fallbackProvider:"disabled",fallbackModel:"local-rules-v2",retryRequiresNewConsent:true});expect(fetchMock).toHaveBeenCalledTimes(1);expect(aiFallbackMessage(answer.fallbackEvidence!)).toContain("موافقة جديدة")});
it("classifies non-429 HTTP failure separately",async()=>{const fetchMock=vi.fn().mockResolvedValue(new Response("down",{status:503}));vi.stubGlobal("fetch",fetchMock);const answer=await askTutor(providers[0].config,"Warum?",{context,consentGranted:true,now:new Date("2026-09-07T12:00:00Z")});expect(answer.fallbackEvidence).toMatchObject({failureKind:"http",httpStatus:503})});
it("keeps a successful OpenRouter Free-only response remote and structured",async()=>{const provider=providers[1];const fetchMock=vi.fn().mockResolvedValue(new Response(provider.successBody(JSON.stringify(payload)),{status:200}));vi.stubGlobal("fetch",fetchMock);const answer=await askTutor(provider.config,"Warum?",{context,consentGranted:true,now:new Date("2026-09-07T12:00:00Z")});expect(answer).toMatchObject({...payload,provider:"openrouter",model:"openrouter/free"});expect(answer.fallbackEvidence).toBeUndefined()});
it("grounds speaking fallback locally after an approved 429 without sending audio",async()=>{const fetchMock=vi.fn().mockResolvedValue(new Response("limit",{status:429}));vi.stubGlobal("fetch",fetchMock);const answer=await askSpeakingFollowUp(providers[0].config,"Ich wohne in Berlin.",{context:{lessonId:"a1-01",level:"A1",taskPromptDe:"Stellen Sie sich vor."},consentGranted:true,now:new Date("2026-09-07T12:00:00Z")});expect(answer).toMatchObject({provider:"disabled",model:"local-rules-content-follow-up-v1",groundingCue:"Berlin",fallbackEvidence:{failureKind:"rate-limit",attemptedProvider:"gemini"}});expect(fetchMock).toHaveBeenCalledTimes(1);const evidence=await createSpeakingContentFollowUpEvidence({sourceText:"Ich wohne in Berlin.",questionDe:answer.questionDe,supportAr:answer.supportAr,sourceCue:answer.groundingCue,cueCategory:"keyword",provider:answer.provider,model:answer.model,consent:"not-required",fallbackEvidence:answer.fallbackEvidence});expect(evidence.fallbackEvidence?.networkAttemptCount).toBe(1)});
it("requires fresh consent before an explicit retry can issue another request",async()=>{const provider=providers[0];const fetchMock=vi.fn().mockResolvedValueOnce(new Response("limit",{status:429})).mockResolvedValueOnce(new Response(provider.successBody(JSON.stringify(payload)),{status:200}));vi.stubGlobal("fetch",fetchMock);const first=await askTutor(provider.config,"Warum?",{context,consentGranted:true,now:new Date("2026-09-07T12:00:00Z")});expect(first.fallbackEvidence).toBeDefined();await expect(askTutor(provider.config,"Warum?",{context,now:new Date("2026-09-07T12:00:00Z")})).rejects.toThrow("تأكيد الإرسال");expect(fetchMock).toHaveBeenCalledTimes(1);const retried=await askTutor(provider.config,"Warum?",{context,consentGranted:true,now:new Date("2026-09-07T12:00:00Z")});expect(retried.provider).toBe("gemini");expect(fetchMock).toHaveBeenCalledTimes(2)});
it("keeps fallback provenance schema-valid for tutor and speaking records",()=>{const fallback={policyVersion:"ai-resilient-fallback-v1"as const,attemptedProvider:"gemini"as const,attemptedModel:"gemini-2.5-flash",failureKind:"rate-limit"as const,httpStatus:429,networkAttemptCount:1 as const,fallbackProvider:"disabled"as const,fallbackModel:"local-rules-v2",retryRequiresNewConsent:true as const,failedAt:"2026-09-07T12:00:00Z"};const interaction={id:"t",question:"Warum?",answer:payload,provider:"disabled"as const,model:"local-rules-v2",promptVersion:"tutor-v2"as const,errorIds:[],consent:"explicit"as const,fallbackEvidence:fallback,createdAt:"2026-09-07T12:00:00Z"};expect(learningStateSchema.parse({...defaultState,tutorInteractions:[interaction]}).tutorInteractions[0].fallbackEvidence).toEqual(fallback)});
});
