// @vitest-environment node
import { describe,expect,it } from"vitest";
import { academicLessons } from"@/data/academic-lessons";
import { buildAssistanceSeparatedEvidence,ASSISTANCE_SEPARATION_BOUNDARY,ASSISTANCE_SEPARATION_POLICY } from"@/core/evidence/assistance-separation";
import { buildEvidenceReport } from"@/core/evidence/report";
import { defaultState } from"@/core/portability/db";
import type { ExerciseAttempt,SupportUsageEvent } from"@/types/learning";
const lesson=academicLessons["a1-01"];const guidedId=lesson.exercises[0].id;const transferId=lesson.reading.questions[0].id;
const attempt=(id:string,exerciseId:string,correct:boolean,createdAt:string):ExerciseAttempt=>({id,lessonId:lesson.id,exerciseId,answer:"private-answer-not-for-derived-record",correct,createdAt});
const support=(id:string,contentId:string,createdAt:string,afterCommit=false):SupportUsageEvent=>({id,policyVersion:"support-usage-v1",kind:"hint",surface:"lesson",contentId,lessonId:lesson.id,supportLevel:1,afterCommit,evidenceBoundary:"support-context-no-correctness-or-mastery",createdAt});
describe("P2 guided versus independent and assisted performance",()=>{
 it("separates guided practice from independent transfer using the authored item registry",()=>{const result=buildAssistanceSeparatedEvidence({...defaultState,exerciseAttempts:[attempt("g",guidedId,true,"2026-09-10T10:00:00Z"),attempt("t",transferId,false,"2026-09-10T10:01:00Z")]});expect(result).toMatchObject({policyVersion:ASSISTANCE_SEPARATION_POLICY,buckets:{guided:{attempted:1,correct:1,accuracyPercent:100},transferIndependent:{attempted:1,correct:0,accuracyPercent:0},assisted:{attempted:0}},evidenceBoundary:ASSISTANCE_SEPARATION_BOUNDARY})});
 it("marks only a direct pre-commit hint as assisted",()=>{const result=buildAssistanceSeparatedEvidence({...defaultState,supportUsageEvents:[support("h",transferId,"2026-09-10T09:59:00Z")],exerciseAttempts:[attempt("t",transferId,true,"2026-09-10T10:00:00Z")]});expect(result.records[0]).toMatchObject({supportMode:"assisted",practiceMode:"transfer",supportEventIds:["h"]});expect(result.buckets.transferAssisted).toMatchObject({attempted:1,correct:1,accuracyPercent:100})});
 it("does not retroactively mark an answer when help opens after commitment",()=>{const result=buildAssistanceSeparatedEvidence({...defaultState,supportUsageEvents:[support("late",transferId,"2026-09-10T10:01:00Z",true)],exerciseAttempts:[attempt("t",transferId,true,"2026-09-10T10:00:00Z")]});expect(result.records[0]).toMatchObject({supportMode:"independent",supportEventIds:[]})});
 it("does not let a hint on another item contaminate independent evidence",()=>{const result=buildAssistanceSeparatedEvidence({...defaultState,supportUsageEvents:[support("other",guidedId,"2026-09-10T09:59:00Z")],exerciseAttempts:[attempt("t",transferId,true,"2026-09-10T10:00:00Z")]});expect(result.buckets.transferIndependent.attempted).toBe(1);expect(result.buckets.assisted.attempted).toBe(0)});
 it("uses only the latest unique attempt and its own timing boundary",()=>{const result=buildAssistanceSeparatedEvidence({...defaultState,supportUsageEvents:[support("hint",transferId,"2026-09-10T10:01:00Z")],exerciseAttempts:[attempt("old",transferId,false,"2026-09-10T10:00:00Z"),attempt("new",transferId,true,"2026-09-10T10:02:00Z")]});expect(result.records).toHaveLength(1);expect(result.records[0]).toMatchObject({attemptId:"new",correct:true,supportMode:"assisted"})});
 it("recommends a fresh independent sample when supported transfer dominates",()=>{const second=lesson.reading.questions[1].id;const state={...defaultState,supportUsageEvents:[support("h1",transferId,"2026-09-10T09:00:00Z"),support("h2",second,"2026-09-10T09:00:00Z")],exerciseAttempts:[attempt("a1",transferId,true,"2026-09-10T10:00:00Z"),attempt("a2",second,true,"2026-09-10T10:00:00Z")]};const result=buildAssistanceSeparatedEvidence(state);expect(result.needsIndependentTransfer).toBe(true);expect(result.recommendationAr).toContain("دون تلميح")});
 it("returns process metadata without copying learner answers and integrates with the evidence report",()=>{const state={...defaultState,exerciseAttempts:[attempt("g",guidedId,true,"2026-09-10T10:00:00Z")]};const separated=buildAssistanceSeparatedEvidence(state);expect(JSON.stringify(separated)).not.toContain("private-answer-not-for-derived-record");expect(buildEvidenceReport(state).assistanceSeparation).toEqual(separated)});
});
