import { fireEvent,render,screen } from"@testing-library/react";
import { describe,expect,it,vi } from"vitest";
import { academicLessons } from"@/data/academic-lessons";
import { ExerciseCard,QuestionQuiz } from"@/components/exercise-card";
import { summarizeAttemptProcess,ATTEMPT_PROCESS_BOUNDARY,ATTEMPT_PROCESS_POLICY } from"@/core/evidence/attempt-process";
import { defaultState } from"@/core/portability/db";
import { learningStateSchema } from"@/core/portability/schema";
import type{ExerciseAttempt}from"@/types/learning";
const lesson=academicLessons["a1-01"];const mcq=lesson.exercises.find((exercise)=>exercise.type==="multiple-choice")!;
const attempt=(id:string,overrides:Partial<ExerciseAttempt>={}):ExerciseAttempt=>({id,lessonId:lesson.id,exerciseId:mcq.id,answer:"private",correct:true,createdAt:"2026-09-10T10:00:00Z",processPolicyVersion:"bounded-attempt-process-v1",responseTimeMs:1000,answerChangeCount:0,...overrides});
describe("P2 bounded attempt process evidence",()=>{
 it("summarizes bounded timing, committed changes, direct support, and explicit uncertainty",()=>{const attempts=[attempt("a",{responseTimeMs:1000,answerChangeCount:2,uncertaintyKind:"guess"}),attempt("b",{exerciseId:lesson.reading.questions[0].id,responseTimeMs:3000,uncertaintyKind:"instruction-unclear"})];const result=summarizeAttemptProcess({...defaultState,exerciseAttempts:attempts});expect(result).toMatchObject({policyVersion:ATTEMPT_PROCESS_POLICY,attemptCount:2,timedAttemptCount:2,medianResponseTimeMs:2000,answerChangeCount:2,attemptsWithChanges:1,uncertainty:{guess:1,instructionUnclear:1,knowledgeRecall:0,notRecorded:0},evidenceBoundary:ATTEMPT_PROCESS_BOUNDARY});expect(result.recommendationAr).toContain("تعليمات")});
 it("keeps old attempts valid while requiring the policy when process fields exist",()=>{expect(learningStateSchema.parse({...defaultState,exerciseAttempts:[{id:"old",lessonId:"a1-01",exerciseId:"x",answer:"x",correct:false,createdAt:"2026-09-10T10:00:00Z"}]}).exerciseAttempts).toHaveLength(1);expect(()=>learningStateSchema.parse({...defaultState,exerciseAttempts:[{id:"bad",lessonId:"a1-01",exerciseId:"x",answer:"x",correct:false,responseTimeMs:1,createdAt:"2026-09-10T10:00:00Z"}]})).toThrow("policy version")});
 it("renders German-first uncertainty choices and records discrete MCQ revisions without keystrokes",()=>{const onAttempt=vi.fn();const{container}=render(<ExerciseCard exercise={mcq} onAttempt={onAttempt}/>);const options=[...container.querySelectorAll<HTMLButtonElement>(".exercise-options button")];fireEvent.click(options[0]);fireEvent.click(options[1]);fireEvent.click(screen.getByRole("button",{name:/Ich rate/}));expect(container.textContent).toContain("لا نسجل ضغطات المفاتيح");fireEvent.click(screen.getByRole("button",{name:"تحقق"}));expect(onAttempt).toHaveBeenCalledTimes(1);expect(onAttempt.mock.calls[0][2]).toMatchObject({processPolicyVersion:"bounded-attempt-process-v1",answerChangeCount:1,uncertaintyKind:"guess",responseTimeMs:expect.any(Number)})});
 it("records QuestionQuiz uncertainty and option revision through the same metadata contract",()=>{const onAttempt=vi.fn();const question=lesson.reading.questions[0];const{container}=render(<QuestionQuiz questions={[question]} onAttempt={onAttempt}/>);const options=[...container.querySelectorAll<HTMLButtonElement>(".quiz-options button")];fireEvent.click(options[0]);fireEvent.click(options[1]);fireEvent.click(screen.getByRole("button",{name:/Die Aufgabe ist unklar/}));fireEvent.click(container.querySelector<HTMLButtonElement>(".quiz-check")!);expect(onAttempt.mock.calls[0][3]).toMatchObject({processPolicyVersion:"bounded-attempt-process-v1",answerChangeCount:1,uncertaintyKind:"instruction-unclear",responseTimeMs:expect.any(Number)})});
 it("caps persisted response time and answer-change counts through strict Zod",()=>{expect(()=>learningStateSchema.parse({...defaultState,exerciseAttempts:[attempt("long",{responseTimeMs:1_800_001})]})).toThrow();expect(()=>learningStateSchema.parse({...defaultState,exerciseAttempts:[attempt("changes",{answerChangeCount:101})]})).toThrow()});
 it("does not copy answers or intermediate text into the process summary",()=>{const result=summarizeAttemptProcess({...defaultState,exerciseAttempts:[attempt("private",{answer:"SECRET_INTERMEDIATE_TEXT",uncertaintyKind:"knowledge-recall"})]});expect(JSON.stringify(result)).not.toContain("SECRET_INTERMEDIATE_TEXT");expect(result.uncertainty.knowledgeRecall).toBe(1)});
 it("uses guess dominance only as a request for more evidence, not a cognitive diagnosis",()=>{const result=summarizeAttemptProcess({...defaultState,exerciseAttempts:[attempt("g1",{uncertaintyKind:"guess"}),attempt("g2",{exerciseId:lesson.reading.questions[0].id,uncertaintyKind:"guess"}),attempt("k",{exerciseId:lesson.listening.questions[0].id,uncertaintyKind:"knowledge-recall"})]});expect(result.recommendationAr).toContain("عينة مستقلة جديدة");expect(result.evidenceBoundary).toContain("no-keystrokes-cognitive-diagnosis")});
});
