// @vitest-environment node
import {describe,expect,it} from "vitest";
import {strFromU8,strToU8,unzipSync,zipSync} from "fflate";
import {defaultState} from "@/core/portability/db";
import {exportArchive,importArchive} from "@/core/portability/backup";
describe("portable DWNB v2/v3 archive",()=>{
 it("round-trips learning state without secrets",async()=>{const state={...defaultState,dueReviews:7,completedLessonIds:["a1-01"],dailySessions:{"2026-08-29":{date:"2026-08-29",availableMinutes:20 as const,energyBefore:2 as const,checkedInAt:"2026-08-29T08:00:00Z",difficultyAfter:4 as const,confidenceAfter:2 as const,nextFocus:"lighter" as const,reflectedAt:"2026-08-29T08:20:00Z"}},errorClinicAttempts:[{id:"clinic-1",clinicType:"word-order" as const,sourceErrorIds:["e1"],answer:"weil ich keine Zeit habe",correct:true,createdAt:"2026-08-29T08:15:00Z"}],updatedAt:"2026-08-29T00:00:00.000Z"};const blob=await exportArchive(state,{includeMedia:false});const entries=unzipSync(new Uint8Array(await blob.arrayBuffer()));const manifest=JSON.parse(strFromU8(entries["manifest.json"]));expect(manifest.formatVersion).toBe(2);expect(manifest.includesSecrets).toBe(false);expect(manifest.includesMedia).toBe(false);const imported=await importArchive(blob);expect(imported.state.dueReviews).toBe(7);expect(imported.state.completedLessonIds).toEqual(["a1-01"]);expect(imported.state.dailySessions["2026-08-29"].nextFocus).toBe("lighter");expect(imported.state.errorClinicAttempts[0].clinicType).toBe("word-order");expect(imported.media).toHaveLength(0)});
 it("rejects progress changed after checksum creation",async()=>{const blob=await exportArchive(defaultState,{includeMedia:false});const entries=unzipSync(new Uint8Array(await blob.arrayBuffer()));entries["progress.json"]=strToU8(JSON.stringify({...defaultState,dueReviews:99}));const tampered=new Blob([new Uint8Array(zipSync(entries))]);await expect(importArchive(tampered)).rejects.toThrow("سلامة بيانات التقدم")});
 it("encrypts and decrypts the complete payload with a passphrase",async()=>{const blob=await exportArchive({...defaultState,dueReviews:11},{passphrase:"Berlin-2026",includeMedia:false});const outer=unzipSync(new Uint8Array(await blob.arrayBuffer()));const manifest=JSON.parse(strFromU8(outer["manifest.json"]));expect(manifest.formatVersion).toBe(3);expect(manifest.encrypted).toBe(true);expect(outer["progress.json"]).toBeUndefined();expect(outer["payload.enc"]).toBeDefined();const imported=await importArchive(blob,"Berlin-2026");expect(imported.encrypted).toBe(true);expect(imported.state.dueReviews).toBe(11)});
 it("rejects a wrong passphrase without exposing plaintext",async()=>{const blob=await exportArchive(defaultState,{passphrase:"correct-passphrase"});await expect(importArchive(blob,"wrong-passphrase")).rejects.toThrow("عبارة المرور غير صحيحة")});
 it("round-trips structured tutor provenance without ever adding the session key",async()=>{const interaction={id:"t1",question:"Warum?",answer:{hintAr:"راقب الفعل",explanationAr:"شرح مرتبط بالدرس الحالي.",examplesDe:["weil ich lerne"],microExerciseAr:"كوّن جملة"},provider:"gemini" as const,model:"gemini-2.5-flash",promptVersion:"tutor-v2" as const,lessonId:"a2-01",errorIds:["e1"],consent:"explicit" as const,createdAt:"2026-09-01T10:00:00Z"};const blob=await exportArchive({...defaultState,tutorInteractions:[interaction]},{includeMedia:false});const imported=await importArchive(blob);expect(imported.state.tutorInteractions).toEqual([interaction]);expect(JSON.stringify(imported.state)).not.toContain("dwnb-ai-key")});
 it("round-trips delayed review events as auditable retention evidence",async()=>{const event={id:"r1",cardId:"a1-01-card",lessonId:"a1-01",grade:4,evidenceKind:"delayed" as const,scheduledFor:"2026-08-31T00:00:00Z",reviewedAt:"2026-09-01T10:00:00Z",masteryDelta:4};const blob=await exportArchive({...defaultState,reviewEvents:[event]},{includeMedia:false});const imported=await importArchive(blob);expect(imported.state.reviewEvents).toEqual([event])});
});
