// @vitest-environment node
import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";import{COLLOCATION_NETWORK_BOUNDARY,COLLOCATION_NETWORK_POLICY,collocationNetworks,collocationNetworksForLevel}from"@/data/collocation-networks";import{createCollocationNetworkAttempt,evaluateCollocationChoice}from"@/core/vocabulary/collocation-network";import{defaultState}from"@/core/portability/db";import{learningStateSchema}from"@/core/portability/schema";import{mergeLearningStates}from"@/core/portability/merge";
const levels=["A1","A2","B1","B2"]as const;
describe("P2 contextual collocation networks",()=>{
 it("provides sixteen original networks and forty-eight contextualized links balanced across A1-B2",()=>{expect(collocationNetworks).toHaveLength(16);expect(collocationNetworks.flatMap(item=>item.nodes)).toHaveLength(48);for(const level of levels)expect(collocationNetworksForLevel(level)).toHaveLength(4);expect(collocationNetworks.every(item=>item.policyVersion===COLLOCATION_NETWORK_POLICY&&item.source==="original-authored-collocation-network"&&!item.aiRequired)).toBe(true)});
 it("gives every link a distinct phrase, situation, example, Arabic meaning, contrast, and register",()=>{for(const item of collocationNetworks){expect(new Set(item.nodes.map(node=>node.id)).size).toBe(3);expect(new Set(item.nodes.map(node=>node.phraseDe)).size).toBe(3);for(const node of item.nodes){expect(node.contextDe.length).toBeGreaterThan(15);expect(node.contextAr.length).toBeGreaterThan(10);expect(node.exampleDe).toContain(item.headwordDe);expect(node.exampleAr.length).toBeGreaterThan(8);expect(node.contrastAr.length).toBeGreaterThan(15);expect(["daily","neutral","formal","academic"]).toContain(node.register)}}});
 it("matches the authored communicative context rather than treating all links as synonyms",()=>{const item=collocationNetworks[0],target=item.nodes[1];expect(evaluateCollocationChoice(item,target.id,target.id).correct).toBe(true);expect(evaluateCollocationChoice(item,target.id,item.nodes[0].id)).toEqual({targetNodeId:target.id,selectedNodeId:item.nodes[0].id,correct:false});expect(()=>evaluateCollocationChoice(item,target.id,"foreign-id")).toThrow("current network")});
 it("creates a bounded complete attempt only after all links and contexts are covered",()=>{const item=collocationNetworks[0],results=item.nodes.map(node=>evaluateCollocationChoice(item,node.id,node.id));const attempt=createCollocationNetworkAttempt({network:item,mode:"challenge",visitedNodeIds:item.nodes.map(node=>node.id),results,id:"coll-1",now:new Date("2026-09-11T21:00:00Z")});expect(attempt).toMatchObject({policyVersion:COLLOCATION_NETWORK_POLICY,level:"A1",mode:"challenge",correctCount:3,total:3,engine:"deterministic-context-match",evidenceBoundary:COLLOCATION_NETWORK_BOUNDARY});expect(attempt).not.toHaveProperty("phraseDe");expect(attempt).not.toHaveProperty("freeText")});
 it("rejects incomplete exploration, duplicate target contexts, and forged correctness",()=>{const item=collocationNetworks[0],results=item.nodes.map(node=>evaluateCollocationChoice(item,node.id,node.id));expect(()=>createCollocationNetworkAttempt({network:item,mode:"guided",visitedNodeIds:item.nodes.slice(0,2).map(node=>node.id),results})).toThrow("explored");expect(()=>createCollocationNetworkAttempt({network:item,mode:"guided",visitedNodeIds:item.nodes.map(node=>node.id),results:[results[0],results[0],results[2]]})).toThrow("every context");expect(()=>createCollocationNetworkAttempt({network:item,mode:"guided",visitedNodeIds:item.nodes.map(node=>node.id),results:[{...results[0],correct:false},results[1],results[2]]})).toThrow("correctness")});
 it("keeps strict summaries portable and mergeable without mastery",()=>{const item=collocationNetworks[0],results=item.nodes.map(node=>evaluateCollocationChoice(item,node.id,node.id));const a=createCollocationNetworkAttempt({network:item,mode:"guided",visitedNodeIds:item.nodes.map(node=>node.id),results,id:"a"}),b={...a,id:"b",mode:"challenge"as const};expect(learningStateSchema.safeParse({...defaultState,collocationNetworkAttempts:[a]}).success).toBe(true);expect(learningStateSchema.safeParse({...defaultState,collocationNetworkAttempts:[{...a,answerText:"secret"}]}).success).toBe(false);expect(learningStateSchema.safeParse({...defaultState,collocationNetworkAttempts:[{...a,correctCount:2}]}).success).toBe(false);const merged=mergeLearningStates({...defaultState,collocationNetworkAttempts:[a]},{...defaultState,collocationNetworkAttempts:[b]});expect(merged.collocationNetworkAttempts).toHaveLength(2);expect(merged.mastery).toEqual(defaultState.mastery)});
 it("renders explore-context-transfer guidance instead of a synonym list",()=>{const source=readFileSync("src/components/collocation-network-lab.tsx","utf8");for(const marker of["Netz erkunden","Kontext wählen","Übertragen","Welche Verbindung passt?","شبكة سياقية لا قائمة مرادفات","لماذا شبكة؟","لا AI، لا شبكة، لا mastery"])expect(source).toContain(marker);expect(source).not.toMatch(/fetch\(|synonymScore|officialScore/);expect(source).not.toContain("%networks.length");expect(source).toContain("إنهاء والعودة إلى المختبرات")})
});
