import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";import{defaultState}from"@/core/portability/db";import{learningStateSchema}from"@/core/portability/schema";import{mergeLearningStates}from"@/core/portability/merge";import{buildExamCountdown,buildExtraThirtyMinutesWhatIf,buildFiveMinuteQuickPractice,clearPinnedLearningTask,levelEndBackupReminder,pinLearningTask,setStudyRoutineMode}from"@/core/coach/daily-focus-tools";import type{LearningState,MissionBlock}from"@/types/learning";
const profile={name:"Nadia",targetExam:"goethe-b2"as const,targetDate:"2026-12-03",dailyMinutes:45 as const,arabicSupport:"modern-standard-arabic"as const,currentLevel:"A1"as const,createdAt:"2026-09-01T00:00:00Z"};const state:LearningState={...defaultState,profile,diagnosticResult:{estimatedLevel:"A1",score:3,maxScore:4,levelScores:{A1:3,A2:0,B1:0,B2:0},completedAt:"2026-09-01T00:00:00Z"}};const block:MissionBlock={id:"lesson",kind:"lesson",titleAr:"هدف اليوم",titleDe:"Heute lernen",minutes:10,objective:"هدف واضح",evidenceKind:"lesson-evidence",href:"/lernen/a1-01"};
describe("P2 pinned task, day modes, countdown, what-if, quick practice, and backup reminder",()=>{
 it("pins and clears one task without replacing the coach target or mastery",()=>{const pinned=pinLearningTask(state,block,new Date("2026-09-10"));expect(pinned.pinnedLearningTask).toMatchObject({blockId:"lesson",href:"/lernen/a1-01",evidenceBoundary:"learner-pin-preserves-coach-recommendation-no-completion-mastery-or-priority-override"});expect(pinned.mastery).toEqual(state.mastery);expect(clearPinnedLearningTask(pinned).pinnedLearningTask).toBeNull();expect(learningStateSchema.safeParse(pinned).success).toBe(true)});
 it("persists explicit morning/evening modes without completion or time debt",()=>{for(const mode of["morning-quick","evening-calm-review","auto"]as const){const next=setStudyRoutineMode(state,mode,new Date("2026-09-10"));expect(next.studyRoutineMode.mode).toBe(mode);expect(next.completedBlockIds).toEqual(state.completedBlockIds);expect(next.mastery).toEqual(state.mastery)}});
 it("builds exactly five minutes around the current weakest evidence",()=>{const quick=buildFiveMinuteQuickPractice({...state,errors:[{id:"e",type:"grammar",wrong:"x",correct:"y",explanationAr:"",occurrences:1,lastSeenAt:"2026-09-10"}]});expect(quick.minutes).toBe(5);expect(quick.steps.reduce((sum,step)=>sum+step.minute,0)).toBe(5);expect(quick.href).toBe("/errors");expect(quick.evidenceBoundary).toContain("no-auto-completion")});
 it("maps target dates into long-range, 12, 8, 4, and 1-week phases",()=>{const now=new Date(2026,8,10);const phase=(days:number)=>buildExamCountdown({...state,profile:{...profile,targetDate:new Date(2026,8,10+days).toISOString().slice(0,10)}},now).phase;expect([phase(100),phase(80),phase(50),phase(20),phase(5)]).toEqual(["long-range","twelve-weeks","eight-weeks","four-weeks","one-week"])});
 it("calculates the extra-thirty-minute scenario locally without changing the plan",()=>{const result=buildExtraThirtyMinutesWhatIf(state,new Date(2026,8,10));expect(result.status).toBe("calculated");expect(result.extraWeeklyMinutes).toBe(30);expect(result.extraWeeks!).toBeLessThanOrEqual(result.baselineWeeks!);expect(result.evidenceBoundary).toContain("no-behavior-change");expect(state.profile?.dailyMinutes).toBe(45)});
 it("shows a non-blocking backup reminder after a level gate and clears it after a newer export",()=>{const gate={id:"g",policyVersion:"event-derived-mastery-v1"as const,key:"level-a1-ready",operation:"set"as const,value:100,previousValue:0,resultingValue:100,source:"level-assessment"as const,evidenceRefs:["a1"],evidenceBoundary:"event-log-authoritative-for-new-mutations-legacy-snapshot-fallback-explicit"as const,createdAt:"2026-09-10T10:00:00Z"};const gated={...state,mastery:{...state.mastery,"level-a1-ready":100},masteryEvidenceEvents:[gate]};expect(levelEndBackupReminder(gated)).toMatchObject({show:true,level:"A1"});expect(levelEndBackupReminder({...gated,lastBackupAt:"2026-09-10T11:00:00Z"}).show).toBe(false);expect(readFileSync("src/components/settings-view.tsx","utf8")).toContain("lastBackupAt:new Date().toISOString()")});
 it("merges the newest pinned task and routine preference",()=>{const current={...state,updatedAt:"2026-09-10T10:00:00Z"},incoming={...pinLearningTask(state,block),studyRoutineMode:setStudyRoutineMode(state,"morning-quick").studyRoutineMode,updatedAt:"2026-09-10T11:00:00Z"};expect(mergeLearningStates(current,incoming)).toMatchObject({pinnedLearningTask:{blockId:"lesson"},studyRoutineMode:{mode:"morning-quick"}})});
});
