// @vitest-environment node
import { readFileSync } from "node:fs";
import { describe,expect,it } from "vitest";
import { buildErrorInterventionTimeline, buildWeeklyErrorTrend, ERROR_INTERVENTION_TIMELINE_POLICY, ERROR_PRINT_PRIVACY_POLICY, ERROR_TIME_PRESSURE_TAG_POLICY, ERROR_WEEKLY_TREND_POLICY, updateErrorLearnerMetadata } from "@/core/errors/insights";
import { defaultState } from "@/core/portability/db";
import { learningStateSchema } from "@/core/portability/schema";
import { mergeLearningStates } from "@/core/portability/merge";
import { exportArchive,importArchive } from "@/core/portability/backup";
import type { ErrorRecord,ExerciseAttempt } from "@/types/learning";

const error:ErrorRecord={id:"error-1",type:"word-order",wrong:"secret wrong sentence",correct:"secret correct sentence",explanationAr:"شرح حساس",occurrences:3,lastSeenAt:"2026-09-10T10:00:00Z",sourceLessonId:"a1-01",sourceExerciseId:"a1-01-e1",failedRepairCount:1,lastFailedRepairAt:"2026-09-09T09:00:00Z",repairCount:1,lastRepairedAt:"2026-09-10T11:00:00Z",nextReviewAt:"2026-09-12T11:00:00Z"};
const attempt=(id:string,date:string,correct:boolean,exerciseId=id):ExerciseAttempt=>({id,lessonId:"a1-01",exerciseId,answer:correct?"ok":"wrong",correct,createdAt:`${date}T10:00:00Z`});

describe("P2 actual error trends, learner metadata, print privacy, and intervention chronology",()=>{
  it("builds eight honest empty weeks without manufacturing a downward curve",()=>{const trend=buildWeeklyErrorTrend(defaultState,new Date("2026-09-11T12:00:00Z"));expect(trend).toMatchObject({policyVersion:ERROR_WEEKLY_TREND_POLICY,direction:"insufficient-data"});expect(trend.weeks).toHaveLength(8);expect(trend.weeks.every((week)=>week.errorRatePercent===null)).toBe(true)});
  it("derives a decreasing rate from actual dated attempts and preserves the denominator",()=>{const exerciseAttempts=[attempt("a","2026-08-24",false,"e1"),attempt("b","2026-08-25",false,"e2"),attempt("c","2026-08-26",false,"e2"),attempt("d","2026-08-27",true,"e3"),attempt("e","2026-09-07",false,"e4"),attempt("f","2026-09-08",true,"e5"),attempt("g","2026-09-09",true,"e6"),attempt("h","2026-09-10",true,"e7")];const trend=buildWeeklyErrorTrend({...defaultState,exerciseAttempts},new Date("2026-09-11T12:00:00Z"));expect(trend.direction).toBe("decreasing");expect(trend.weeks.find((week)=>week.weekStart==="2026-08-24")).toMatchObject({attemptCount:4,errorCount:3,uniqueErrorItems:2,errorRatePercent:75});expect(trend.weeks.at(-1)).toMatchObject({attemptCount:4,errorCount:1,errorRatePercent:25});expect(trend.evidenceBoundary).toContain("no-causal")});
  it("derives chronology without exposing wrong answers, corrections, or explanations",()=>{const timeline=buildErrorInterventionTimeline({...defaultState,errors:[error],errorClinicAttempts:[{id:"clinic-1",clinicType:"word-order",sourceErrorIds:[error.id],answer:"private answer",correct:false,createdAt:"2026-09-10T12:00:00Z"}]});expect(ERROR_INTERVENTION_TIMELINE_POLICY).toBe("derived-error-intervention-timeline-v1");expect(timeline.map((event)=>event.kind)).toEqual(expect.arrayContaining(["last-error-seen","repair-failed","repair-succeeded","delayed-review-scheduled","clinic-attempt"]));const serialized=JSON.stringify(timeline);expect(serialized).not.toContain(error.wrong);expect(serialized).not.toContain(error.correct);expect(serialized).not.toContain(error.explanationAr);expect(serialized).not.toContain("private answer");expect(timeline.every((event)=>event.evidenceBoundary.includes("no-answer-text"))).toBe(true)});
  it("propagates print sensitivity to every event tied to the marked error",()=>{const marked=updateErrorLearnerMetadata(error,{sensitiveInPrint:true},new Date("2026-09-11T08:00:00Z"));const timeline=buildErrorInterventionTimeline({...defaultState,errors:[marked],errorClinicAttempts:[{id:"clinic-1",clinicType:"word-order",sourceErrorIds:[marked.id],answer:"x",correct:true,createdAt:"2026-09-11T09:00:00Z"}]});expect(ERROR_PRINT_PRIVACY_POLICY).toBe("learner-sensitive-error-print-redaction-v1");expect(timeline.every((event)=>event.sensitiveInPrint)).toBe(true)});
  it("stores the time-pressure label as learner metadata without diagnosing or resolving the error",()=>{const updated=updateErrorLearnerMetadata(error,{timePressureTag:true},new Date("2026-09-11T08:00:00Z"));expect(ERROR_TIME_PRESSURE_TAG_POLICY).toBe("learner-declared-time-pressure-error-v1");expect(updated.learnerContextTags).toEqual(["knows-rule-under-time-pressure"]);expect(updated.resolved).toBe(error.resolved);expect(updated.occurrences).toBe(error.occurrences);expect(updated.learnerMetadataUpdatedAt).toBe("2026-09-11T08:00:00.000Z");expect(updateErrorLearnerMetadata(updated,{timePressureTag:false},new Date("2026-09-11T09:00:00Z")).learnerContextTags).toEqual([])});
  it("validates metadata and merges the newest learner print/tag decision",()=>{const older=updateErrorLearnerMetadata(error,{timePressureTag:true,sensitiveInPrint:false},new Date("2026-09-11T08:00:00Z"));const newer=updateErrorLearnerMetadata(error,{timePressureTag:false,sensitiveInPrint:true},new Date("2026-09-11T09:00:00Z"));expect(learningStateSchema.parse({...defaultState,errors:[newer]}).errors[0].sensitiveInPrint).toBe(true);const invalid={...newer,learnerMetadataUpdatedAt:undefined};expect(learningStateSchema.safeParse({...defaultState,errors:[invalid]}).success).toBe(false);const merged=mergeLearningStates({...defaultState,errors:[older],updatedAt:"2026-09-11T08:30:00Z"},{...defaultState,errors:[newer],updatedAt:"2026-09-11T09:30:00Z"});expect(merged.errors[0]).toMatchObject({learnerContextTags:[],sensitiveInPrint:true,learnerMetadataUpdatedAt:"2026-09-11T09:00:00.000Z"})});
  it("round-trips the learner tag and print preference through DWNB without redacting the local source of truth",async()=>{const marked=updateErrorLearnerMetadata(error,{timePressureTag:true,sensitiveInPrint:true},new Date("2026-09-11T08:00:00Z"));const archive=await exportArchive({...defaultState,errors:[marked]},{includeMedia:false});const imported=await importArchive(archive);expect(imported.state.errors[0]).toMatchObject({wrong:error.wrong,correct:error.correct,learnerContextTags:["knows-rule-under-time-pressure"],sensitiveInPrint:true})});
  it("ships print-only redaction and learner-facing controls without hiding data in the app or archive",()=>{const css=readFileSync("src/app/globals.css","utf8"),view=readFileSync("src/components/error-notebook.tsx","utf8");expect(css).toContain("@media print");expect(css).toContain(".sensitive-in-print{display:none!important}");expect(view).toContain("إخفاء هذا الخطأ من الطباعة");expect(view).toContain("يبقى داخل التطبيق وملف DWNB");expect(view).toContain("أفهم القاعدة لكن لا أطبقها تحت الوقت")});
});
