// @vitest-environment node
import { readFileSync } from"node:fs";
import { describe,expect,it } from"vitest";
import { defaultState } from"@/core/portability/db";
import { captureMasteryMutationEvents,EVENT_DERIVED_MASTERY_BOUNDARY,EVENT_DERIVED_MASTERY_POLICY,masteryDerivationSummary,recalculateMasteryFromEvidence } from"@/core/evidence/event-derived-mastery";
import { mergeLearningStates } from"@/core/portability/merge";
import { learningStateSchema } from"@/core/portability/schema";
import { exportArchive,importArchive } from"@/core/portability/backup";
import type { ReviewEvent } from"@/types/learning";

const review=(id:string):ReviewEvent=>({id,cardId:`card-${id}`,lessonId:"a1-01",grade:4,evidenceKind:"delayed",evidenceScope:"lesson-card",scheduledFor:"2026-09-09T00:00:00Z",reviewedAt:"2026-09-10T10:00:00Z",masteryDelta:4});

describe("P2 event-derived mastery and post-merge recalculation",()=>{
 it("captures a changed mastery key with evidence references and a bounded source",()=>{const candidate={...defaultState,mastery:{...defaultState.mastery,"a1-01":76},completedLessonIds:["a1-01"]};const next=captureMasteryMutationEvents(defaultState,candidate,new Date("2026-09-10T10:00:00Z"));expect(next.masteryEvidenceEvents).toHaveLength(1);expect(next.masteryEvidenceEvents[0]).toMatchObject({policyVersion:EVENT_DERIVED_MASTERY_POLICY,key:"a1-01",operation:"set",value:76,resultingValue:76,source:"lesson-evidence",evidenceRefs:["lesson-complete:a1-01"],evidenceBoundary:EVENT_DERIVED_MASTERY_BOUNDARY});expect(next.mastery["a1-01"]).toBe(76)});
 it("rebuilds event-owned keys even when the materialized mastery cache was tampered",()=>{const next=captureMasteryMutationEvents(defaultState,{...defaultState,mastery:{...defaultState.mastery,diagnostic:65},diagnosticResult:{estimatedLevel:"A1",score:13,maxScore:20,levelScores:{A1:3,A2:3,B1:3,B2:4},completedAt:"2026-09-10T10:00:00Z"}},new Date("2026-09-10T10:00:00Z"));expect(recalculateMasteryFromEvidence({...next.mastery,diagnostic:99},next.masteryEvidenceEvents).diagnostic).toBe(65)});
 it("unions concurrent delayed-review increments and recalculates 88 instead of choosing either 84 snapshot",()=>{const base={...defaultState,mastery:{...defaultState.mastery,"a1-01":80},updatedAt:"2026-09-10T09:00:00Z"};const leftReview=review("left"),rightReview=review("right");const left=captureMasteryMutationEvents(base,{...base,mastery:{...base.mastery,"a1-01":84},reviewEvents:[leftReview],updatedAt:"2026-09-10T10:00:00Z"},new Date("2026-09-10T10:00:00Z"));const right=captureMasteryMutationEvents(base,{...base,mastery:{...base.mastery,"a1-01":84},reviewEvents:[rightReview],updatedAt:"2026-09-10T10:01:00Z"},new Date("2026-09-10T10:01:00Z"));const merged=mergeLearningStates(left,right);expect(merged.masteryEvidenceEvents).toHaveLength(2);expect(merged.masteryEvidenceEvents.every((event)=>event.operation==="increment")).toBe(true);expect(merged.mastery["a1-01"]).toBe(88)});
 it("deduplicates the same evidence event by stable ID during merge",()=>{const base={...defaultState,mastery:{...defaultState.mastery,"a1-01":80}};const event=review("same");const state=captureMasteryMutationEvents(base,{...base,mastery:{...base.mastery,"a1-01":84},reviewEvents:[event]},new Date("2026-09-10T10:00:00Z"));const merged=mergeLearningStates(state,state);expect(merged.masteryEvidenceEvents).toHaveLength(1);expect(merged.mastery["a1-01"]).toBe(84)});
 it("uses the latest set event rather than the higher imported snapshot",()=>{const low=captureMasteryMutationEvents(defaultState,{...defaultState,mastery:{...defaultState.mastery,"exam-target-task":90},updatedAt:"2026-09-10T09:00:00Z"},new Date("2026-09-10T09:00:00Z"));const highBase={...defaultState,mastery:{...defaultState.mastery,"exam-target-task":90},updatedAt:"2026-09-10T09:30:00Z"};const later=captureMasteryMutationEvents(highBase,{...highBase,mastery:{...highBase.mastery,"exam-target-task":50},updatedAt:"2026-09-10T11:00:00Z"},new Date("2026-09-10T11:00:00Z"));const merged=mergeLearningStates(low,later);expect(merged.mastery["exam-target-task"]).toBe(50);expect(merged.masteryEvidenceEvents).toHaveLength(2)});
 it("records deletion and prevents an older workflow marker from reappearing after merge",()=>{const started=captureMasteryMutationEvents(defaultState,{...defaultState,mastery:{...defaultState.mastery,"full-exam-x-started":1}},new Date("2026-09-10T09:00:00Z"));const mastery={...started.mastery};delete mastery["full-exam-x-started"];const reset=captureMasteryMutationEvents(started,{...started,mastery},new Date("2026-09-10T10:00:00Z"));expect(reset.masteryEvidenceEvents.at(-1)?.operation).toBe("delete");expect(mergeLearningStates(started,reset).mastery["full-exam-x-started"]).toBeUndefined()});
 it("keeps old schema-v3 snapshots as explicit fallback instead of inventing retroactive events",()=>{const legacy={...defaultState} as Partial<typeof defaultState>;delete legacy.masteryEvidenceEvents;const parsed=learningStateSchema.parse({...legacy,mastery:{legacySkill:73}});expect(parsed.masteryEvidenceEvents).toEqual([]);expect(parsed.mastery.legacySkill).toBe(73);expect(masteryDerivationSummary(parsed)).toMatchObject({eventCount:0,eventDerivedKeys:0,legacyFallbackCount:1,legacyFallbackKeys:["legacySkill"]})});
 it("round-trips the event log and normalizes the imported cache from its events",async()=>{const state=captureMasteryMutationEvents(defaultState,{...defaultState,mastery:{...defaultState.mastery,"module-a1-1":80}},new Date("2026-09-10T10:00:00Z"));const blob=await exportArchive({...state,mastery:{...state.mastery,"module-a1-1":5}});const imported=await importArchive(blob);expect(imported.state.mastery["module-a1-1"]).toBe(80);expect(imported.state.masteryEvidenceEvents).toEqual(state.masteryEvidenceEvents)});
 it("wires automatic mutation capture into the one central LearningProvider update boundary",()=>{const source=readFileSync("src/components/learning-provider.tsx","utf8");expect(source).toContain("captureMasteryMutationEvents(current,candidate,now)");expect(source.match(/const update=/g)).toHaveLength(1)});
});
