import { describe,expect,it } from "vitest";
import { buildExamReadiness } from "@/core/exams/readiness";
import { allPublishedExamTasks } from "@/data/exam-simulation-registry";
import { defaultState } from "@/core/portability/db";

const tasks=(provider:"goethe-b2"|"telc-deutsch-b2",skill:string)=>allPublishedExamTasks.filter(task=>task.provider===provider&&task.skill===skill);

describe("P0 provider-scoped exam readiness",()=>{
  it("builds four Goethe modules and five telc modules without a fabricated average",()=>{const goethe=buildExamReadiness(defaultState,"goethe-b2"),telc=buildExamReadiness(defaultState,"telc-deutsch-b2");expect(goethe.modules.map(module=>module.moduleId)).toEqual(["lesen","hoeren","schreiben","sprechen"]);expect(telc.modules.map(module=>module.moduleId)).toEqual(["lesen","sprachbausteine","hoeren","schreiben","sprechen"]);expect(goethe.readyModuleCount).toBe(0);expect(telc.readyModuleCount).toBe(0)});
  it("keeps evidence strictly inside its provider",()=>{const task=tasks("goethe-b2","reading")[0];const state={...defaultState,mastery:{...defaultState.mastery,[`exam-target-${task.id}`]:90}};expect(buildExamReadiness(state,"goethe-b2").modules.find(module=>module.moduleId==="lesen")?.attemptedTasks).toBe(1);expect(buildExamReadiness(state,"telc-deutsch-b2").modules.every(module=>module.attemptedTasks===0)).toBe(true)});
  it("marks a sufficiently broad low receptive sample as needs-work",()=>{const reading=tasks("goethe-b2","reading").slice(0,6);const mastery=Object.fromEntries(reading.map(task=>[`exam-target-${task.id}`,50]));const readinessModule=buildExamReadiness({...defaultState,mastery},"goethe-b2").modules.find(item=>item.moduleId==="lesen")!;expect(readinessModule.requiredSamples).toBe(5);expect(readinessModule.accuracyPercent).toBe(50);expect(readinessModule.status).toBe("needs-work")});
  it("marks a broad high receptive sample as strong internal evidence",()=>{const listening=tasks("goethe-b2","listening").slice(0,4);const mastery=Object.fromEntries(listening.map(task=>[`exam-target-${task.id}`,90]));const readinessModule=buildExamReadiness({...defaultState,mastery},"goethe-b2").modules.find(item=>item.moduleId==="hoeren")!;expect(readinessModule.requiredSamples).toBe(4);expect(readinessModule.status).toBe("strong-evidence");expect(readinessModule.accuracyPercent).toBe(90)});
  it("uses revisions rather than a fake accuracy score for writing",()=>{const writing=tasks("telc-deutsch-b2","writing").slice(0,3);const submissions=writing.map((task,index)=>({id:`w${index}`,taskId:task.id,text:"Text",wordCount:1,version:1,status:(index===0?"revised":"submitted") as "revised"|"submitted",feedback:[],createdAt:"2026-08-31T10:00:00Z",updatedAt:"2026-08-31T10:00:00Z"}));const readinessModule=buildExamReadiness({...defaultState,writingSubmissions:submissions},"telc-deutsch-b2").modules.find(item=>item.moduleId==="schreiben")!;expect(readinessModule.accuracyPercent).toBeNull();expect(readinessModule.revisionOrRetryCount).toBe(1);expect(readinessModule.status).toBe("strong-evidence")});
  it("requires repeated productive evidence before speaking becomes strong",()=>{const speaking=tasks("goethe-b2","speaking").slice(0,3);const attempts=[...speaking.map((task,index)=>({id:`s${index}`,taskId:task.id,durationSeconds:60,selfScore:3,reflection:"",createdAt:"2026-08-31T10:00:00Z"})),{id:"s-retry",taskId:speaking[0].id,durationSeconds:70,selfScore:4,reflection:"إعادة",createdAt:"2026-08-31T11:00:00Z"}];const readinessModule=buildExamReadiness({...defaultState,speakingAttempts:attempts},"goethe-b2").modules.find(item=>item.moduleId==="sprechen")!;expect(readinessModule.attemptedTasks).toBe(3);expect(readinessModule.revisionOrRetryCount).toBe(1);expect(readinessModule.status).toBe("strong-evidence")});
  it("chooses the weakest module separately and links an unattempted task",()=>{const report=buildExamReadiness(defaultState,"telc-deutsch-b2");expect(report.weakestModule.status).toBe("no-evidence");expect(report.weakestModule.nextHref).toMatch(/^\/exams\/telc-deutsch-b2\//);expect(report.boundaryAr).toContain("لا تجمع نقاطًا رسمية")});
});
