// @vitest-environment node
import{describe,expect,it}from"vitest";import{DEFAULT_PLANNING_INTENSITY,minutesForIntensity,planningPresetMinutes,selectPlanningIntensity}from"@/core/coach/intensity-presets";import{effectiveSessionMinutes}from"@/core/coach/session-signals";import{buildWeeklyPlan}from"@/core/coach/weekly-plan";import{defaultState}from"@/core/portability/db";import{learningStateSchema}from"@/core/portability/schema";import{mergeLearningStates}from"@/core/portability/merge";import{exportArchive,importArchive}from"@/core/portability/backup";
const profile={name:"N",targetExam:"goethe-b2"as const,dailyMinutes:45 as const,arabicSupport:"modern-standard-arabic"as const,currentLevel:"A1"as const,createdAt:"2026-09-01T00:00:00Z"};const state={...defaultState,profile};
describe("P2 learner-selected intensity presets",()=>{
 it("keeps balanced equal to the contract/profile base and never increases by default",()=>{expect(DEFAULT_PLANNING_INTENSITY.preset).toBe("balanced");expect(planningPresetMinutes(state)).toEqual({base:45,preset:"balanced",minutes:45})});
 it("maps light to at most twenty minutes without increasing a ten-minute base",()=>{expect(minutesForIntensity(90,"light")).toBe(20);expect(minutesForIntensity(45,"light")).toBe(20);expect(minutesForIntensity(10,"light")).toBe(10)});
 it("raises intensive by exactly one valid step only after explicit selection",()=>{expect(minutesForIntensity(10,"intensive")).toBe(20);expect(minutesForIntensity(45,"intensive")).toBe(60);expect(minutesForIntensity(90,"intensive")).toBe(90);const selected=selectPlanningIntensity(state,"intensive",new Date("2026-09-10T10:00:00Z"));expect(selected.planningIntensity).toMatchObject({preset:"intensive",selectedAt:"2026-09-10T10:00:00.000Z",evidenceBoundary:"learner-selected-session-budget-no-automatic-increase-mastery-or-penalty"});expect(selected.mastery).toEqual(state.mastery)});
 it("uses the latest learning contract as the base without rewriting it",()=>{const contract={id:"c",policyVersion:"fourteen-day-learning-contract-v1"as const,revision:1,startsOn:"2026-09-10",endsOn:"2026-09-23",goal:"work"as const,dailyMinutes:30 as const,studyWeekdays:[1,2,3]as Array<1|2|3|4|5|6|7>,evidenceBoundary:"planning-commitment-no-mastery-or-gate"as const,createdAt:"2026-09-10T08:00:00Z"};expect(planningPresetMinutes({...state,learningContracts:[contract],planningIntensity:{...state.planningIntensity,preset:"intensive"}})).toEqual({base:30,preset:"intensive",minutes:45})});
 it("lets explicit check-in and low energy override even an intensive preset",()=>{const intensive={...state,planningIntensity:{...state.planningIntensity,preset:"intensive"as const,selectedAt:"2026-09-10T08:00:00Z"}};expect(effectiveSessionMinutes(intensive,new Date(2026,8,10,9))).toBe(60);const date="2026-09-10";const checked={...intensive,dailySessions:{[date]:{date,availableMinutes:30 as const,energyBefore:1 as const,checkedInAt:"2026-09-10T09:00:00Z"}}};expect(effectiveSessionMinutes(checked,new Date(2026,8,10,10))).toBe(20)});
 it("applies the preset to future weekly budgets while preserving Sunday rest",()=>{const light={...state,planningIntensity:{...state.planningIntensity,preset:"light"as const}};const plan=buildWeeklyPlan(light,new Date(2026,8,7,9));expect(plan.days.slice(0,6).every(day=>day.budgetMinutes===20)).toBe(true);expect(plan.days[6].budgetMinutes).toBe(0);expect(plan.plannedMinutes).toBe(120)});
 it("defaults old states and round-trips the newest selected preference through Merge and DWNB",async()=>{const old={...defaultState}as Partial<typeof defaultState>;delete old.planningIntensity;expect(learningStateSchema.parse(old).planningIntensity).toEqual(DEFAULT_PLANNING_INTENSITY);const selected=selectPlanningIntensity(state,"light",new Date("2026-09-10T10:00:00Z"));const merged=mergeLearningStates({...state,updatedAt:"2026-09-09T00:00:00Z"},{...selected,updatedAt:"2026-09-10T00:00:00Z"});expect(merged.planningIntensity.preset).toBe("light");expect((await importArchive(await exportArchive(selected))).state.planningIntensity.preset).toBe("light")});
});
