// @vitest-environment node
import{describe,expect,it}from"vitest";import{contractEndDate,createLearningContract,DEFAULT_QUIET_HOURS,isQuietHoursActive,latestLearningContract,shouldSuppressInAppReminder}from"@/core/coach/learning-agreement";import{evaluateSkillRetest,formForSkillRetest,questionsForSkillRetest}from"@/core/diagnostic/single-skill";import{defaultState}from"@/core/portability/db";import{learningStateSchema}from"@/core/portability/schema";import{mergeLearningStates}from"@/core/portability/merge";import{exportArchive,importArchive}from"@/core/portability/backup";import type{DiagnosticResult,SkillDiagnosticAttempt}from"@/types/learning";
const prior:DiagnosticResult={estimatedLevel:"A1",score:3,maxScore:4,levelScores:{A1:3,A2:0,B1:0,B2:0},formId:"A",completedAt:"2026-09-01T10:00:00Z"};
describe("fourteen-day agreement, quiet hours, and single-skill diagnostic",()=>{
it("calculates a local inclusive fourteen-day contract across month boundaries",()=>{expect(contractEndDate("2026-09-25")).toBe("2026-10-08");const contract=createLearningContract({startsOn:"2026-09-25",goal:"work",dailyMinutes:30,studyWeekdays:[1,3,5]},undefined,new Date("2026-09-07T10:00:00Z"),"c1");expect(contract).toMatchObject({revision:1,endsOn:"2026-10-08",evidenceBoundary:"planning-commitment-no-mastery-or-gate"})});
it("appends a linked revision instead of overwriting the earlier contract",()=>{const first=createLearningContract({startsOn:"2026-09-07",goal:"exam",dailyMinutes:45,studyWeekdays:[1,2]},undefined,new Date("2026-09-07T10:00:00Z"),"c1");const second=createLearningContract({startsOn:"2026-09-10",goal:"work",dailyMinutes:20,studyWeekdays:[2,4]},first,new Date("2026-09-08T10:00:00Z"),"c2");expect(second).toMatchObject({revision:2,previousContractId:"c1"});expect(latestLearningContract([first,second])?.id).toBe("c2")});
it("rejects invalid dates and contracts without study days",()=>{expect(()=>contractEndDate("2026-02-30")).toThrow("غير صالح");expect(()=>createLearningContract({startsOn:"2026-09-07",goal:"exam",dailyMinutes:20,studyWeekdays:[]},undefined,new Date(),"x")).toThrow("يوم دراسة")});
it("handles overnight and daytime quiet windows without requesting notifications",()=>{const overnight={...DEFAULT_QUIET_HOURS,enabled:true,startLocal:"22:00",endLocal:"07:00"};expect(isQuietHoursActive(overnight,new Date(2026,8,7,23,0))).toBe(true);expect(isQuietHoursActive(overnight,new Date(2026,8,7,12,0))).toBe(false);const daytime={...overnight,startLocal:"13:00",endLocal:"15:00"};expect(isQuietHoursActive(daytime,new Date(2026,8,7,14,0))).toBe(true);expect(isQuietHoursActive({...daytime,startLocal:"13:00",endLocal:"13:00"},new Date(2026,8,7,14,0))).toBe(false)});
it("suppresses only noncritical nudges while preserving active deadline safety",()=>{const quiet={...DEFAULT_QUIET_HOURS,enabled:true,startLocal:"22:00",endLocal:"07:00"};const night=new Date(2026,8,7,23,0);expect(shouldSuppressInAppReminder(quiet,"study-nudge",night)).toBe(true);expect(shouldSuppressInAppReminder(quiet,"review-nudge",night)).toBe(true);expect(shouldSuppressInAppReminder(quiet,"deadline-safety",night)).toBe(false)});
it("selects the alternate form and one question from every level for one skill",()=>{const form=formForSkillRetest("grammar",prior,[]);const questions=questionsForSkillRetest("grammar",form);expect(form).toBe("B");expect(questions.map(question=>question.level)).toEqual(["A1","A2","B1","B2"]);expect(questions.every(question=>question.skill==="grammar")).toBe(true)});
it("alternates against the latest attempt of that skill only",()=>{const attempt={id:"s",policyVersion:"single-skill-diagnostic-v1",skill:"grammar",formId:"B",questionIds:["1","2","3","4"],correctByLevel:{A1:true,A2:true,B1:false,B2:false},correctCount:2,attemptedCount:4,recommendedFocusLevel:"B1",priorDiagnosticCompletedAt:prior.completedAt,evidenceBoundary:"skill-sample-planning-only-no-level-change",createdAt:"2026-09-02T00:00:00Z"}satisfies SkillDiagnosticAttempt;expect(formForSkillRetest("grammar",prior,[attempt])).toBe("A");expect(formForSkillRetest("reading",prior,[attempt])).toBe("B")});
it("evaluates the skill sample without producing a new overall diagnostic",()=>{const questions=questionsForSkillRetest("reading","B");const answers=Object.fromEntries(questions.map((question,index)=>[question.id,index<2?question.correctIndex:(question.correctIndex+1)%4]));const attempt=evaluateSkillRetest({skill:"reading",formId:"B",questions,answers,priorDiagnosticCompletedAt:prior.completedAt},new Date("2026-09-07T12:00:00Z"),"skill-1");expect(attempt).toMatchObject({correctCount:2,attemptedCount:4,recommendedFocusLevel:"B1",evidenceBoundary:"skill-sample-planning-only-no-level-change"});expect(attempt).not.toHaveProperty("estimatedLevel")});
it("defaults old schema-v3 records to empty contracts/retests and disabled quiet hours",()=>{const old:Record<string,unknown>={...defaultState};delete old.learningContracts;delete old.skillDiagnosticAttempts;delete old.quietHours;const parsed=learningStateSchema.parse(old);expect(parsed.learningContracts).toEqual([]);expect(parsed.skillDiagnosticAttempts).toEqual([]);expect(parsed.quietHours.enabled).toBe(false)});
it("merges contract/retest provenance and takes newer quiet settings without mastery changes",()=>{const contract=createLearningContract({startsOn:"2026-09-07",goal:"exam",dailyMinutes:20,studyWeekdays:[1]},undefined,new Date(),"c1");const questions=questionsForSkillRetest("grammar","B");const answers=Object.fromEntries(questions.map(q=>[q.id,q.correctIndex]));const attempt=evaluateSkillRetest({skill:"grammar",formId:"B",questions,answers,priorDiagnosticCompletedAt:prior.completedAt},new Date(),"s1");const current={...defaultState,learningContracts:[contract],updatedAt:"2026-09-07T08:00:00Z"};const incoming={...defaultState,skillDiagnosticAttempts:[attempt],quietHours:{...DEFAULT_QUIET_HOURS,enabled:true},updatedAt:"2026-09-07T09:00:00Z"};const merged=mergeLearningStates(current,incoming);expect(merged.learningContracts).toHaveLength(1);expect(merged.skillDiagnosticAttempts).toHaveLength(1);expect(merged.quietHours.enabled).toBe(true);expect(merged.mastery).toEqual(defaultState.mastery)});
it("round-trips all planning records through DWNB",async()=>{const contract=createLearningContract({startsOn:"2026-09-07",goal:"study",dailyMinutes:30,studyWeekdays:[1,3]},undefined,new Date(),"c1");const questions=questionsForSkillRetest("vocabulary","B");const answers=Object.fromEntries(questions.map(q=>[q.id,q.correctIndex]));const attempt=evaluateSkillRetest({skill:"vocabulary",formId:"B",questions,answers,priorDiagnosticCompletedAt:prior.completedAt},new Date(),"s1");const state={...defaultState,diagnosticResult:prior,learningContracts:[contract],skillDiagnosticAttempts:[attempt],quietHours:{...DEFAULT_QUIET_HOURS,enabled:true,timeZone:"Africa/Tunis"}};const imported=await importArchive(await exportArchive(state,{includeMedia:false}));expect(imported.state.learningContracts).toEqual([contract]);expect(imported.state.skillDiagnosticAttempts).toEqual([attempt]);expect(imported.state.quietHours.timeZone).toBe("Africa/Tunis")});
});
