import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe,expect,it } from "vitest";
import { academicLessons } from "@/data/academic-lessons";
import { grammarNodeById, grammarProgressionNodes } from "@/data/grammar-progression-registry";
import { buildLearningArchitectureAudit, grammarProgressionNodeSchema, questionTaxonomyRecordSchema } from "@/core/content-validation/learning-architecture";
import { questionTaxonomyByQuestionId, questionTaxonomyForLesson, questionTaxonomyRecords } from "@/core/comprehension/question-taxonomy";
import { GrammarProgressionMap } from "@/components/grammar-progression-map";
import { RuleProgressionPanel } from "@/components/rule-progression-panel";
import { QuestionQuiz } from "@/components/exercise-card";

describe("P1 progressive grammar and comprehension taxonomy",()=>{
  it("registers 24 strict canonical grammar nodes balanced six per level",()=>{expect(grammarProgressionNodes).toHaveLength(24);for(const level of ["A1","A2","B1","B2"])expect(grammarProgressionNodes.filter((node)=>node.level===level)).toHaveLength(6);expect(grammarProgressionNodes.every((node)=>grammarProgressionNodeSchema.safeParse(node).success)).toBe(true)});
  it("rejects unknown grammar fields and incomplete progressive boundaries",()=>{const node=grammarProgressionNodes[0];expect(grammarProgressionNodeSchema.safeParse({...node,automaticException:"must fail"}).success).toBe(false);expect(grammarProgressionNodeSchema.safeParse({...node,boundariesAr:[node.boundariesAr[0]],exceptionsAr:[]}).success).toBe(false)});
  it("keeps the prerequisite graph acyclic and strictly earlier",()=>{for(const node of grammarProgressionNodes)for(const parentId of node.prerequisiteIds){const parent=grammarNodeById[parentId];expect(parent,node.id).toBeDefined();expect(parent.order,node.id).toBeLessThan(node.order)}const audit=buildLearningArchitectureAudit();expect(audit.issues.filter((issue)=>issue.includes("cycle"))).toEqual([])});
  it("maps every canonical rule to real theory, controlled practice, and one lesson-owned productive task",()=>{for(const node of grammarProgressionNodes){const lesson=academicLessons[node.lessonId];expect(lesson.theory.some((item)=>item.id===node.theoryId)).toBe(true);expect(node.controlledExerciseIds.every((id)=>lesson.exercises.some((item)=>item.id===id))).toBe(true);expect(node.production.ref).toBe(`${node.lessonId}:${node.production.stage}`);expect(node.semanticAlignmentAr.length).toBeGreaterThan(24)}});
  it("stores progressive now, common-limit, deferred, boundary, and exception layers on every rule",()=>{for(const node of grammarProgressionNodes){expect(node.progression.introducedAr.length).toBeGreaterThan(19);expect(node.progression.commonLimitAr.length).toBeGreaterThan(19);expect(node.progression.deferredAr.length).toBeGreaterThan(19);expect(node.boundariesAr.length).toBeGreaterThanOrEqual(2);expect(node.exceptionsAr.length).toBeGreaterThanOrEqual(1)}});
  it("classifies all 504 reading/listening questions exactly once with strict provenance",()=>{expect(questionTaxonomyRecords).toHaveLength(504);expect(new Set(questionTaxonomyRecords.map((item)=>item.questionId)).size).toBe(504);expect(questionTaxonomyRecords.filter((item)=>item.surface==="reading")).toHaveLength(252);expect(questionTaxonomyRecords.filter((item)=>item.surface==="listening")).toHaveLength(252);expect(questionTaxonomyRecords.every((item)=>questionTaxonomyRecordSchema.safeParse(item).success)).toBe(true)});
  it("represents all five functions in every level under the audited balance envelope",()=>{for(const level of ["A1","A2","B1","B2"]){const rows=questionTaxonomyRecords.filter((item)=>item.level===level);for(const category of ["gist","detail","stance","inference","structure"])expect(rows.some((item)=>item.category===category),`${level}:${category}`).toBe(true);expect(rows.filter((item)=>item.category==="detail").length/rows.length).toBeLessThanOrEqual(.72);expect(rows.filter((item)=>item.category==="gist").length/rows.length).toBeGreaterThanOrEqual(.12)}});
  it("preserves the existing first-listening gist contract in all 84 lessons",()=>{const rows=questionTaxonomyRecords.filter((item)=>item.classificationBasis==="listening-sequence-gist-contract");expect(rows).toHaveLength(84);expect(rows.every((item)=>item.category==="gist"&&item.surface==="listening")).toBe(true)});
  it("rejects unknown taxonomy fields instead of turning labels into scores",()=>{const row=questionTaxonomyRecords[0];expect(questionTaxonomyRecordSchema.safeParse({...row,masteryDelta:10}).success).toBe(false);expect(row.evidenceBoundary).toBe("question-function-label-no-score-mastery-or-cefr")});
  it("passes the combined graph, semantic-link, provenance, and balance audit",()=>{expect(buildLearningArchitectureAudit()).toMatchObject({ok:true,counts:{grammarNodes:24,controlledMappings:24,productiveMappings:24,questionTaxonomyRows:504,readingQuestions:252,listeningQuestions:252},issues:[]})});
  it("renders the visible map and lesson rule panel without learner-facing exercise IDs",()=>{const map=renderToStaticMarkup(createElement(GrammarProgressionMap));expect(map).toContain('data-grammar-map-policy="grammar-progression-map-v1"');expect(map).toContain("Grammatik-Landkarte");expect(map).toContain("24 قاعدة محورية");const panel=renderToStaticMarkup(createElement(RuleProgressionPanel,{lessonId:"b2-04"}));expect(panel).toContain("Grenzen und Transfer");expect(panel).toContain("أين تتوقف القاعدة؟");expect(panel).toContain("تدريب مضبوط");expect(panel).not.toMatch(/b2-04-e\d/)});
  it("renders the German question before Arabic support with a strategy label",()=>{const lesson=academicLessons["b2-08"];const question=lesson.reading.questions[0];const taxonomy=questionTaxonomyForLesson(lesson);const html=renderToStaticMarkup(createElement(QuestionQuiz,{questions:[question],taxonomyByQuestionId:taxonomy,onAttempt:()=>{}}));expect(html).toContain(`data-question-category="${questionTaxonomyByQuestionId[question.id].category}"`);expect(html.indexOf(question.promptDe)).toBeLessThan(html.indexOf(question.promptAr));expect(html).toContain("Wie sicher sind Sie?")});
});
