// @vitest-environment node
import{describe,expect,it}from"vitest";import{buildPlanChangeTimeline,PLAN_CHANGE_TIMELINE_BOUNDARY,PLAN_CHANGE_TIMELINE_POLICY}from"@/core/coach/plan-change-timeline";import{defaultState}from"@/core/portability/db";
const date="2026-09-10";const session={date,availableMinutes:45 as const,energyBefore:4 as const,checkedInAt:"2026-09-10T08:00:00Z"};
describe("P2 explainable plan-change timeline",()=>{
 it("returns an honest empty state without manufacturing a change",()=>{expect(buildPlanChangeTimeline(defaultState)).toMatchObject({policyVersion:PLAN_CHANGE_TIMELINE_POLICY,entries:[],evidenceBoundary:PLAN_CHANGE_TIMELINE_BOUNDARY})});
 it("explains a low-energy or changed-time check-in with before and after minutes",()=>{const result=buildPlanChangeTimeline({...defaultState,profile:{name:"N",targetExam:"goethe-b2",dailyMinutes:45,arabicSupport:"modern-standard-arabic",currentLevel:"A1",createdAt:"2026-09-01T00:00:00Z"},dailySessions:{[date]:{...session,availableMinutes:60,energyBefore:1}}});expect(result.entries[0]).toMatchObject({kind:"check-in-adjustment",beforeMinutes:45,afterMinutes:20});expect(result.entries[0].reasonAr).toContain("1/5")});
 it("maps every immediate adaptation reason to simple non-punitive Arabic",()=>{const reasons=["less-time","too-easy","too-hard","load-suggestion"]as const;const adaptations=reasons.map((reason,index)=>({id:`a${index}`,policyVersion:"session-adaptation-v1"as const,reason,beforeMinutes:45-index*5,afterMinutes:40-index*5,completedBlockIdsBefore:[],evidenceBoundary:"planning-signal-no-mastery-or-correctness"as const,createdAt:`2026-09-10T0${index+9}:00:00Z`}));const rows=buildPlanChangeTimeline({...defaultState,dailySessions:{[date]:{...session,adaptations}}}).entries;expect(rows).toHaveLength(4);expect(rows.every((row)=>row.kind==="session-adaptation"&&row.reasonAr.length>30)).toBe(true);expect(rows.map((row)=>row.reasonAr).join(" ")).not.toMatch(/mastery|correctness/)});
 it("explains an equivalent alternative without claiming the original complete",()=>{const alternative={id:"alt",policyVersion:"equivalent-mission-alternative-v1"as const,date,originalBlockId:"practice",alternativeBlockId:"alternative-practice",originalKind:"practice"as const,alternativeTitleAr:"بديل",alternativeTitleDe:"Alternative",objectiveSnapshot:"هدف",evidenceKind:"controlled-practice"as const,minutes:8,href:"/practice",reason:"learner-declined-now"as const,originalCompletedAtSelection:false as const,evidenceBoundary:"planning-substitution-no-completion-mastery-or-correctness"as const,createdAt:"2026-09-10T09:00:00Z"};const row=buildPlanChangeTimeline({...defaultState,dailySessions:{[date]:{...session,missionAlternatives:[alternative]}}}).entries[0];expect(row).toMatchObject({kind:"mission-alternative",beforeMinutes:8,afterMinutes:8});expect(row.reasonAr).toContain("لم يكتمل الأصل")});
 it("records accepted and declined load decisions as learner choices without blame",()=>{const base={id:"offer",policyVersion:"automatic-load-reduction-offer-v1"as const,trigger:"consecutive-errors"as const,consecutiveErrorCount:3,activeSeconds:300,plannedSeconds:2700,offeredOnce:true as const,evidenceBoundary:"learner-controlled-planning-offer-no-penalty-mastery-or-deletion"as const,offeredAt:"2026-09-10T09:00:00Z",decidedAt:"2026-09-10T09:01:00Z"};for(const status of["accepted","declined"]as const){const row=buildPlanChangeTimeline({...defaultState,dailySessions:{[date]:{...session,loadReductionOffer:{...base,status}}}}).entries[0];expect(row.kind).toBe("load-offer-decision");expect(row.reasonAr).not.toMatch(/فشل|كسل|ذنب/)}});
 it("uses next-focus metadata but never copies free reflection text",()=>{const state={...defaultState,dailySessions:{[date]:{...session,nextFocus:"review"as const,reflection:"PRIVATE FREE TEXT",reflectedAt:"2026-09-10T10:00:00Z"}}};const result=buildPlanChangeTimeline(state);expect(result.entries[0]).toMatchObject({kind:"next-focus",titleAr:"قرار الجلسة التالية"});expect(JSON.stringify(result)).not.toContain("PRIVATE FREE TEXT")});
 it("shows linked contract revisions and sorts all changes newest first",()=>{const first={id:"c1",policyVersion:"fourteen-day-learning-contract-v1"as const,revision:1,startsOn:"2026-09-01",endsOn:"2026-09-14",goal:"work"as const,dailyMinutes:30 as const,studyWeekdays:[1,2,3]as Array<1|2|3|4|5|6|7>,evidenceBoundary:"planning-commitment-no-mastery-or-gate"as const,createdAt:"2026-09-01T08:00:00Z"};const second={...first,id:"c2",revision:2,previousContractId:"c1",dailyMinutes:45 as const,createdAt:"2026-09-10T12:00:00Z"};const result=buildPlanChangeTimeline({...defaultState,learningContracts:[first,second],dailySessions:{[date]:session}});expect(result.entries[0]).toMatchObject({kind:"learning-contract-revision",afterMinutes:45});expect(result.entries[0].reasonAr).toContain("بقيت الأدلة السابقة")});
});
