// @vitest-environment node
import { describe, expect, it } from "vitest";
import { serializeCsv } from "@/core/content-validation/safe-csv";
import { assertReviewPacketSafeToReplace } from "@/core/content-validation/review-packet-safety";

const generatedReadme = "# حزمة المراجعة البشرية المستقلة — Der Weg nach Berlin\nGenerated by scripts/generate-human-review-packet.ts\n";
const signatureHeaders = ["decision", "reviewerName", "reviewDate", "note"];

function b2Checklist(decisionAt?: number) {
  const rows = Array.from({ length: 24 }, (_, index) => {
    const lessonId = `b2-${String(index + 1).padStart(2, "0")}`;
    const decision = decisionAt === index ? "accept" : "";
    return `| \`${lessonId}\` | 40 ✓ | — | 90 | 1 | 12 | ${decision} |`;
  });
  return [
    "# قائمة فحص دروس B2 — يملؤها مراجع بشري مسمّى (لا يملؤها السكربت)",
    "",
    "| lesson | words | objective | listening | pronunciation | phrases | decision |",
    "|---|---|---|---:|---:|---:|---|",
    ...rows,
    "",
  ].join("\n");
}

function blankReviewSheet() {
  return serializeCsv(signatureHeaders, [["", "", "", ""]]);
}

describe("review packet regeneration protection", () => {
  it("allows recognized generated files while all review fields remain blank", () => {
    expect(() => assertReviewPacketSafeToReplace([
      { name: "README.md", isFile: true, content: generatedReadme },
      { name: "review-sheet-01.csv", isFile: true, content: blankReviewSheet() },
      { name: "b2-lesson-checklist.md", isFile: true, content: b2Checklist() },
    ])).not.toThrow();
  });

  it("refuses to overwrite a CSV containing any signed review field", () => {
    const signedSheet = serializeCsv(signatureHeaders, [["", "Reviewer Name", "", ""]]);
    expect(() => assertReviewPacketSafeToReplace([
      { name: "review-sheet-01.csv", isFile: true, content: signedSheet },
    ])).toThrow("contains a decision, reviewer identity, date, or note");
  });

  it("refuses to overwrite a filled B2 decision checklist", () => {
    expect(() => assertReviewPacketSafeToReplace([
      { name: "b2-lesson-checklist.md", isFile: true, content: b2Checklist(4) },
    ])).toThrow("contains a reviewer decision");
  });

  it("fails closed on unknown files, directories, or an incomplete checklist", () => {
    expect(() => assertReviewPacketSafeToReplace([
      { name: "reviewer-copy.csv", isFile: true, content: "" },
    ])).toThrow("unrecognized file");
    expect(() => assertReviewPacketSafeToReplace([
      { name: "review-sheet-01.csv", isFile: false, content: "" },
    ])).toThrow("non-file entry");
    expect(() => assertReviewPacketSafeToReplace([
      { name: "b2-lesson-checklist.md", isFile: true, content: b2Checklist().split("\n").slice(0, 8).join("\n") },
    ])).toThrow("expected 24 B2 checklist rows");
  });
});
