import{createElement}from"react";import{renderToStaticMarkup}from"react-dom/server";import{describe,expect,it}from"vitest";import{readFileSync}from"node:fs";import{defaultState}from"@/core/portability/db";import{learningStateSchema}from"@/core/portability/schema";import{appendListeningUsageEvent,LISTENING_USAGE_BOUNDARY}from"@/core/listening/usage-evidence";import{mergeLearningStates}from"@/core/portability/merge";import{readingLibrary}from"@/data/library-registry";import{splitKnownCompound,unknownWordChallenge}from"@/core/reading/unknown-word";import{prosodyProgression}from"@/data/prosody-progression";import{prosodyItemSchema,buildStudyModesAudit}from"@/core/content-validation/study-modes";import{summarizeRmsSamples}from"@/core/speaking/pause-analysis";import{registerExamples}from"@/data/lexical-strategy-registry";import{RedemittelBank}from"@/components/redemittel-bank";import{ProsodyProgressionPanel}from"@/components/prosody-progression-panel";import{LibraryView}from"@/components/library-view";import{LearningProvider}from"@/components/learning-provider";
describe("P1 reading modes, listening process evidence, and prosody",()=>{
it("stores playback ordinal and transcript timing without a comprehension score",()=>{let events=appendListeningUsageEvent([], {surface:"library",contentId:"lib-l-a1-01",event:"playback",playbackSource:"mp3"},new Date("2026-09-08T10:00:00Z"),"u1");events=appendListeningUsageEvent(events,{surface:"library",contentId:"lib-l-a1-01",event:"playback",playbackSource:"browser-tts"},new Date("2026-09-08T10:00:30Z"),"u2");events=appendListeningUsageEvent(events,{surface:"library",contentId:"lib-l-a1-01",event:"transcript-revealed",revealAfterAnswerCommit:true},new Date("2026-09-08T10:01:00Z"),"u3");expect(events.map(x=>x.playOrdinal)).toEqual([1,2,2]);expect(events[2]).toMatchObject({secondsSinceFirstPlayback:60,revealAfterAnswerCommit:true,evidenceBoundary:LISTENING_USAGE_BOUNDARY});expect(events[2]).not.toHaveProperty("score");expect(events[2]).not.toHaveProperty("mastery")});
it("keeps the listening event schema strict",()=>{const event=appendListeningUsageEvent([], {surface:"lesson",contentId:"a1-01",event:"playback",playbackSource:"mp3"},new Date(),"u1")[0];expect(learningStateSchema.safeParse({...defaultState,listeningUsageEvents:[event]}).success).toBe(true);expect(learningStateSchema.safeParse({...defaultState,listeningUsageEvents:[{...event,officialScore:10}]}).success).toBe(false)});
it("merges unique listening process evidence",()=>{const a=appendListeningUsageEvent([], {surface:"lesson",contentId:"a1-01",event:"playback",playbackSource:"mp3"},new Date(),"u1")[0];const b={...a,id:"u2",playOrdinal:2};const merged=mergeLearningStates({...defaultState,listeningUsageEvents:[a]},{...defaultState,listeningUsageEvents:[b]});expect(merged.listeningUsageEvents.map(x=>x.id).sort()).toEqual(["u1","u2"]);expect(merged.mastery).toEqual(defaultState.mastery)});
it("splits only known compounds and never invents an unknown meaning",()=>{expect(splitKnownCompound("Reiseplanung")).toEqual(["reise","planung"]);expect(splitKnownCompound("Unbekanntesphantasiewort")).toEqual([]);const challenge=unknownWordChallenge(readingLibrary.find(x=>x.textDe.includes("Reiseplanung"))??readingLibrary[0]);if(challenge)expect(challenge.boundary).toBe("hypothesis-before-authored-gloss-no-inferred-meaning-or-mastery")});
it("provides authored unknown-word practice across all levels",()=>{const covered=readingLibrary.map(x=>unknownWordChallenge(x)).filter(Boolean);expect(covered.length).toBeGreaterThanOrEqual(60);for(const level of["A1","A2","B1","B2"])expect(readingLibrary.filter(x=>x.level===level&&unknownWordChallenge(x)).length).toBeGreaterThanOrEqual(4)});
it("provides four progressive prosody functions at every level",()=>{expect(prosodyProgression).toHaveLength(16);for(const level of["A1","A2","B1","B2"]){const rows=prosodyProgression.filter(x=>x.level===level);expect(rows).toHaveLength(4);expect(new Set(rows.map(x=>x.focus)).size).toBe(4)}expect(prosodyProgression.every(x=>prosodyItemSchema.safeParse(x).success)).toBe(true)});
it("renders synthetic prosody limits and separate Easy/Exam reading controls",()=>{const prosody=renderToStaticMarkup(createElement(LearningProvider,null,createElement(ProsodyProgressionPanel,{level:"B2"})));expect(prosody).toContain('data-prosody-policy="prosody-rhythm-progression-v1"');expect(prosody).toContain("Hörprobe");expect(prosody).toContain("لا يستمع التطبيق");const library=renderToStaticMarkup(createElement(LearningProvider,null,createElement(LibraryView)));expect(library).toContain('data-reading-mode="easy"');expect(library).toContain("Einfach lesen");expect(library).toContain("Prüfungslesen")});
it("instruments every authored listening surface family",()=>{const files=["resilient-audio-player.tsx","lesson-listening-player.tsx","library-audio-player.tsx","shadowing-studio.tsx","targeted-listening-simulation.tsx"].map(f=>readFileSync(`src/components/${f}`,"utf8")).join("\n");for(const surface of["onboarding","diagnostic","lesson","library","shadowing","exam-guided","exam-continuous"])expect(files).toContain(surface);expect(files).toContain("emitListeningUsage");expect(readFileSync("src/components/learning-provider.tsx","utf8")).toContain("dwnb:listening-usage")});
it("passes the static study-mode audit",()=>{expect(buildStudyModesAudit()).toMatchObject({ok:true,counts:{readingItems:80,unknownWordChallenges:63,prosodyItems:16,prosodyLevels:4},issues:[]})});
it("estimates pauses from local RMS energy without speech recognition",()=>{const metrics=summarizeRmsSamples([.03,.04,.001,.001,.001,.001,.04,.001,.001,.001,.03]);expect(metrics).toMatchObject({estimatedVoicedSeconds:.4,estimatedSilenceSeconds:.7,pauseCount:2,longestPauseMs:400,evidenceBoundary:"energy-only-no-word-phoneme-pronunciation-or-fluency-score"})});
it("keeps pause and learner-attribution contracts strict and score-free",()=>{const pause=summarizeRmsSamples([.03,.001]);const condition={policyVersion:"learner-attributed-language-vs-device-v1" as const,category:"both" as const,factors:["vocabulary" as const,"noise" as const],attribution:"learner-reported-not-automatically-diagnosed" as const,evidenceBoundary:"planning-context-no-score-mastery-or-device-diagnosis" as const};const attempt={id:"s",taskId:"a1-01",durationSeconds:1,selfScore:3,reflection:"retry",pauseMetrics:pause,conditionAttribution:condition,createdAt:new Date().toISOString()};expect(learningStateSchema.safeParse({...defaultState,speakingAttempts:[attempt]}).success).toBe(true);expect(learningStateSchema.safeParse({...defaultState,speakingAttempts:[{...attempt,pauseMetrics:{...pause,fluencyScore:90}}]}).success).toBe(false)});
it("exposes a central Redemittel bank by function, register, and level",()=>{expect(registerExamples).toHaveLength(32);expect(new Set(registerExamples.map(x=>x.function)).size).toBe(8);expect(new Set(registerExamples.map(x=>x.register)).size).toBe(4);const html=renderToStaticMarkup(createElement(RedemittelBank,{initialLevel:"B1"}));expect(html).toContain('data-redemittel-policy="central-redemittel-function-register-v1"');expect(html).toContain("Redemittel-Bank");expect(html).toContain("الوظيفة");expect(html).toContain("السجل")});
it("records preparation, voiced/silent estimates, and learner attribution without diagnosing the device",()=>{const source=readFileSync("src/components/speaking-lab.tsx","utf8");for(const token of["preparationSeconds","pauseMetrics","conditionAttribution","learner-reported-not-automatically-diagnosed","RedemittelBank"])expect(source).toContain(token)});
});
