// @vitest-environment node
import {describe,expect,it} from "vitest";
import {defaultState} from "@/core/portability/db";
import {buildAnkiTsv,buildJpegPdf,buildStudyExportSnapshot,buildWeeklyPlanIcs,weeklyReportModel,ANKI_EXPORT_COLUMNS,STUDY_EXPORT_POLICY} from "@/core/exports/study-exports";
import type {ErrorRecord,LearningState} from "@/types/learning";

const now=new Date(2026,8,7,10,0,0);
const profile={name:"Nadia",targetExam:"goethe-b2" as const,dailyMinutes:45 as const,arabicSupport:"modern-standard-arabic" as const,currentLevel:"A1" as const,createdAt:"2026-08-01T00:00:00Z"};
const base:LearningState={...defaultState,profile,diagnosticResult:{estimatedLevel:"A1",score:3,maxScore:4,levelScores:{A1:3,A2:0,B1:0,B2:0},completedAt:"2026-08-01T00:10:00Z"},completedLessonIds:["a1-01"],studyHistory:[{date:"2026-09-07",minutes:30,evidenceCount:4}]};

describe("zero-server local study exports",()=>{
 it("builds a privacy-minimized weekly preview from actual state",()=>{const snapshot=buildStudyExportSnapshot(base,now);expect(snapshot).toMatchObject({policyVersion:STUDY_EXPORT_POLICY,ready:true,profileName:"Nadia",actualMinutes:30,evidenceCount:4,completedLessons:1});expect(snapshot.plan.days).toHaveLength(7);expect(snapshot.cardCount).toBeGreaterThan(0)});
 it("exports stable UTF-8 ICS events with IANA timezone and CRLF",()=>{const file=buildWeeklyPlanIcs(base,now,"Africa/Tunis");expect(file.mime).toBe("text/calendar;charset=utf-8");expect(file.filename).toBe(`dwnb-plan-${file.content.match(/DTSTART[^:]*:(\d{8})/)?.[1].replace(/(\d{4})(\d{2})(\d{2})/,"$1-$2-$3")}.ics`);expect(file.content).toContain("BEGIN:VCALENDAR\r\nVERSION:2.0");expect(file.content).toContain("DTSTART;TZID=Africa/Tunis:");expect(file.content).toContain(`X-DWNB-POLICY:${STUDY_EXPORT_POLICY}`);expect((file.content.match(/BEGIN:VEVENT/g)??[])).toHaveLength(file.eventCount);expect(file.content).not.toContain("Nadia")});
 it("falls back to UTC for an invalid timezone",()=>{expect(buildWeeklyPlanIcs(base,now,"Not/AZone").timeZone).toBe("UTC")});
 it("rejects calendar/report export before onboarding",()=>{expect(()=>buildWeeklyPlanIcs(defaultState,now,"UTC")).toThrow("أكمل التهيئة");expect(()=>weeklyReportModel(defaultState,{plan:true,evidence:true,profileName:false},now)).toThrow("أكمل التهيئة")});
 it("exports eligible lesson cards through a stable BOM-prefixed TSV contract",()=>{const file=buildAnkiTsv(base,now);expect(file.mime).toBe("text/tab-separated-values;charset=utf-8");expect(file.content.startsWith(`\uFEFF${ANKI_EXPORT_COLUMNS.join("\t")}`)).toBe(true);expect(file.content.split("\r\n")).toHaveLength(file.rowCount+2);expect(file.content).not.toContain("Nadia")});
 it("includes confirmed-error cards and blocks spreadsheet formulas",()=>{const error:ErrorRecord={id:"formula",type:"grammar",wrong:"@falsch",correct:"=2+2",explanationAr:"=خطر",occurrences:2,lastSeenAt:"2026-09-01T00:00:00Z",sourceLessonId:"a1-01",resolved:true,repairCount:2,confirmedAt:"2026-09-02T00:00:00Z"};const file=buildAnkiTsv({...base,errors:[error]},now);expect(file.content).toContain("personal-error-card:formula");expect(file.content).not.toContain("' =");expect(file.content).toContain("'=2+2")});
 it("rejects an empty Anki export",()=>{expect(()=>buildAnkiTsv({...defaultState,profile},now)).toThrow("لا توجد بطاقات")});
 it("keeps profile name optional and excludes free learner text",()=>{const sensitive={...base,writingSubmissions:[{id:"w",taskId:"a1-01",text:"SECRET FREE TEXT",wordCount:3,version:1,status:"submitted" as const,feedback:[],createdAt:"x",updatedAt:"x"}]};const hidden=weeklyReportModel(sensitive,{plan:true,evidence:true,profileName:false},now);const named=weeklyReportModel(sensitive,{plan:true,evidence:false,profileName:true},now);expect(hidden.displayName).toBe("غير مضمّن");expect(named.displayName).toBe("Nadia");expect(JSON.stringify(hidden)).not.toContain("SECRET FREE TEXT")});
 it("requires at least one printable report section",()=>{expect(()=>weeklyReportModel(base,{plan:false,evidence:false,profileName:false},now)).toThrow("اختر قسم")});
 it("builds a self-contained single-image PDF and rejects empty image data",()=>{const jpeg=new Uint8Array([0xff,0xd8,0xff,0xd9]);const pdf=buildJpegPdf(jpeg,1240,1754);const text=new TextDecoder().decode(pdf);expect(text.startsWith("%PDF-1.4")).toBe(true);expect(text).toContain("/Subtype /Image");expect(text).toContain("/DCTDecode");expect(text).toContain("xref");expect(text.trimEnd().endsWith("%%EOF")).toBe(true);expect(()=>buildJpegPdf(new Uint8Array(),1,1)).toThrow("صورة التقرير")});
});
