import{describe,expect,it}from"vitest";
import{defaultState}from"@/core/portability/db";
import{learningStateSchema}from"@/core/portability/schema";
import{mergeLearningStates}from"@/core/portability/merge";
import{saveWeeklyReflection,weeklyReflectionBounds}from"@/core/coach/weekly-reflection";
import{buildExamTargetForecast}from"@/core/coach/exam-target-forecast";
import{buildStartingGoalReport}from"@/core/coach/starting-goal-report";
import{composeTodayMission}from"@/core/coach/coach";
import{startTenMinuteRescueMode}from"@/core/coach/session-signals";
import type{LearningState}from"@/types/learning";

const state:LearningState={...defaultState,profile:{name:"Nadia",targetExam:"goethe-b2",targetDate:"2027-09-10",dailyMinutes:45,arabicSupport:"modern-standard-arabic",currentLevel:"A1",priorExperience:"none",createdAt:"2026-09-01T00:00:00Z"},diagnosticResult:{estimatedLevel:"A1",score:2,maxScore:4,levelScores:{A1:2,A2:0,B1:0,B2:0},questionsAnswered:4,confidence:"low",completedAt:"2026-09-01T01:00:00Z"}};

describe("P2 bounded weekly reflection and target planning",()=>{
 it("uses local Monday through Sunday bounds and never copies daily reflection text",()=>{const now=new Date(2026,8,10,12);expect(weeklyReflectionBounds(now)).toEqual({weekStart:"2026-09-07",weekEnd:"2026-09-13"});const withDaily={...state,dailySessions:{"2026-09-10":{date:"2026-09-10",availableMinutes:45 as const,energyBefore:3 as const,checkedInAt:"2026-09-10T08:00:00Z",reflection:"PRIVATE DAILY TEXT"}}};const saved=saveWeeklyReflection(withDaily,{whatWorked:["review","review"],obstacles:["time"],oneAdjustment:"lighter-plan",note:`  ${"x".repeat(450)} `},now);const record=saved.weeklyReflections[0];expect(record).toMatchObject({id:"weekly-reflection-2026-09-07",whatWorked:["review"],obstacles:["time"],source:"weekly-form-only",dailyReflectionReuseConsent:false});expect(record.note).toHaveLength(400);expect(JSON.stringify(record)).not.toContain("PRIVATE DAILY TEXT");expect(saved.mastery).toEqual(state.mastery);expect(learningStateSchema.safeParse(saved).success).toBe(true)});
 it("updates one weekly record and Merge retains the newest revision",()=>{const early=saveWeeklyReflection(state,{whatWorked:["lesson"],obstacles:[],oneAdjustment:"keep-plan",note:"old"},new Date(2026,8,8,10));const late=saveWeeklyReflection(state,{whatWorked:["speaking"],obstacles:["energy"],oneAdjustment:"more-production",note:"new"},new Date(2026,8,9,10));expect(saveWeeklyReflection(early,{whatWorked:[],obstacles:[],oneAdjustment:"keep-plan",note:"updated"},new Date(2026,8,10)).weeklyReflections).toHaveLength(1);expect(mergeLearningStates(late,early).weeklyReflections[0].note).toBe("new")});
 it("creates an explicit ten-minute rescue plan without completion or mastery",()=>{const rescued=startTenMinuteRescueMode(state,new Date(2026,8,10,12));expect(rescued.dailySessions["2026-09-10"]).toMatchObject({availableMinutes:10,rescueMode:{policyVersion:"save-my-day-ten-minute-v1"}});expect(composeTodayMission(rescued,new Date(2026,8,10,12)).reduce((sum,item)=>sum+item.minutes,0)).toBe(10);expect(rescued.completedBlockIds).toEqual(state.completedBlockIds);expect(rescued.mastery).toEqual(state.mastery)});
 it("lets either ritual disappear independently while preserving the chosen session budget",()=>{for(const [startEnabled,endEnabled] of [[false,true],[true,false],[false,false]] as const){const custom={...state,sessionRitualPreferences:{...state.sessionRitualPreferences,startEnabled,endEnabled}};const mission=composeTodayMission(custom,new Date(2026,8,10,12));expect(mission.some((item)=>item.kind==="check-in")).toBe(startEnabled);expect(mission.some((item)=>item.kind==="reflection")).toBe(endEnabled);expect(mission.reduce((sum,item)=>sum+item.minutes,0)).toBe(45)}});
 it("produces a reviewable evidence-linked starting-goal report without a CEFR certificate",()=>{const report=buildStartingGoalReport(state);expect(report.rows.length).toBeGreaterThanOrEqual(2);expect(report.rows.every((row)=>row.evidenceRef&&row.boundaryAr)).toBe(true);expect(JSON.stringify(report)).not.toMatch(/شهادة.*ممنوحة|إتقان مؤكد/)});
 it("calculates target-date weekly load and a practical non-threatening gap",()=>{const forecast=buildExamTargetForecast(state,new Date(2026,8,10));expect(forecast.targetDate).toBe("2027-09-10");expect(forecast.remainingStudyMinutes).toBeGreaterThan(0);expect(forecast.requiredWeeklyMinutes).toBeGreaterThan(0);expect(forecast.solutionsAr.length).toBeGreaterThan(0);expect(forecast.evidenceBoundary).toContain("no-official-readiness")});
 it("handles missing and past dates without manufacturing pass probability",()=>{const none=buildExamTargetForecast({...state,profile:{...state.profile!,targetDate:undefined}},new Date(2026,8,10));expect(none.status).toBe("no-date");const past=buildExamTargetForecast({...state,profile:{...state.profile!,targetDate:"2026-01-01"}},new Date(2026,8,10));expect(past.status).toBe("past-date");expect(past).not.toHaveProperty("passProbability");expect(past.solutionsAr.join(" ")).not.toMatch(/احتمال نجاح/)});
});
