import { describe, expect, it } from "vitest";
import { analyzeWriting } from "@/core/writing/analyze";
import { defaultState } from "@/core/portability/db";
import { learningStateSchema } from "@/core/portability/schema";

describe("P0 evidence-bound writing workflow",()=>{
  it("reports five separate deterministic dimensions without an official score",()=>{const analysis=analyzeWriting("Hallo! Ich heiße Nadia und lerne Deutsch, weil ich in Berlin arbeiten möchte. Ich brauche deshalb einen neuen Termin. Können Sie mir bitte antworten? Viele Grüße",{minWords:20,taskPointsCompleted:3,taskPointsTotal:3});expect(analysis.dimensions.map(item=>item.key)).toEqual(["task-achievement","coherence","vocabulary","grammar","register"]);expect(analysis.dimensions.every(item=>typeof item.passed==="boolean")).toBe(true)});
  it("quotes the learner's own sentence in priority feedback",()=>{const analysis=analyzeWriting("ich brauche termin",{minWords:30,taskPointsCompleted:0,taskPointsTotal:3});expect(analysis.feedback.length).toBeGreaterThan(0);expect(analysis.feedback.every(item=>item.includes("ich brauche termin"))).toBe(true)});
  it("does not pass task achievement until all self-check points are confirmed",()=>{const text="Hallo! Ich schreibe Ihnen heute, weil ich einen Termin brauche. Der alte Termin passt leider nicht. Können wir einen neuen Termin finden? Viele Grüße";const incomplete=analyzeWriting(text,{minWords:15,taskPointsCompleted:2,taskPointsTotal:3});const complete=analyzeWriting(text,{minWords:15,taskPointsCompleted:3,taskPointsTotal:3});expect(incomplete.dimensions.find(item=>item.key==="task-achievement")?.passed).toBe(false);expect(complete.dimensions.find(item=>item.key==="task-achievement")?.passed).toBe(true)});
  it("checks message register through greeting and closing rather than length alone",()=>{const body="Ich schreibe Ihnen, weil ich einen Termin brauche. Der alte Termin passt nicht. Können Sie mir helfen?";expect(analyzeWriting(body,{minWords:10,requireGreeting:true}).dimensions.find(item=>item.key==="register")?.passed).toBe(false);expect(analyzeWriting(`Guten Tag! ${body} Mit freundlichen Grüßen`,{minWords:10,requireGreeting:true}).dimensions.find(item=>item.key==="register")?.passed).toBe(true)});
  it("allows an argumentative register path for non-message tasks",()=>{const text="Meiner Meinung nach sollte die Stadt das Angebot verlängern. Allerdings müssen die Kosten transparent bleiben. Deshalb schlage ich einen begrenzten Pilotversuch vor. Danach können die Ergebnisse verglichen werden.";expect(analyzeWriting(text,{minWords:20,requireGreeting:false}).dimensions.find(item=>item.key==="register")?.passed).toBe(true)});
  it("validates persisted plan, checklist, dimensions, and revision provenance",()=>{const analysis=analyzeWriting("Hallo! Ich brauche einen neuen Termin, weil ich am Montag arbeite. Können Sie mir helfen? Viele Grüße",{minWords:10,taskPointsCompleted:2,taskPointsTotal:2});const parsed=learningStateSchema.parse({...defaultState,writingSubmissions:[{id:"w2",taskId:"a1-01",text:"Hallo! Ich brauche einen neuen Termin, weil ich am Montag arbeite. Können Sie mir helfen? Viele Grüße",wordCount:analysis.wordCount,version:2,status:"revised",feedback:analysis.feedback,plan:{audience:"Kursbüro",purpose:"Termin ändern",points:["Grund","Alternative"]},selfChecklist:["Grund","Alternative"],dimensions:analysis.dimensions,sourceVersion:1,createdAt:"2026-08-31T10:00:00Z",updatedAt:"2026-08-31T10:10:00Z"}]});expect(parsed.writingSubmissions[0].sourceVersion).toBe(1);expect(parsed.writingSubmissions[0].dimensions).toHaveLength(5)});
});
